package aberdeen;

import java.io.File;
import java.io.FileInputStream;

import org.htmlparser.Node;
import org.htmlparser.Parser;
import org.htmlparser.filters.AndFilter;
import org.htmlparser.filters.HasAttributeFilter;
import org.htmlparser.filters.TagNameFilter;
import org.htmlparser.tags.LinkTag;
import org.htmlparser.util.NodeList;

public class getURL {

	/**
	 * @param args
	 */
	public static void main(String[] args) throws Exception{
		// TODO Auto-generated method stub
		
FileInputStream fis=new FileInputStream(new File("./aberdeenPost.html"));//鏂板缓涓�涓狥ileInputStream瀵硅薄
        
        byte[] b=new byte[fis.available()];//鏂板缓涓�涓瓧鑺傛暟缁�
        fis.read(b);//灏嗘枃浠朵腑鐨勫唴瀹硅鍙栧埌瀛楄妭鏁扮粍涓�
       fis.close();
        String htmls=new String(b);//鍐嶅皢瀛楄妭鏁扮粍涓殑鍐呭杞寲鎴愬瓧绗︿覆褰㈠紡杈撳嚭
       //System.out.println(htmls);
        int count=290;
	    Parser	parser=Parser.createParser(htmls, "utf-8");
	   /* AndFilter ListFilter=new AndFilter(new TagNameFilter("div"),
                new HasAttributeFilter("class","advanced-search-name-award"));*/
	    TagNameFilter ListFilter=new TagNameFilter("li");
	    NodeList nodes0=parser.extractAllNodesThatMatch(ListFilter);
	    System.out.println(nodes0.size());
	    for(int i=0;i<nodes0.size();i++)
   	    {
	    	parser=Parser.createParser(nodes0.elementAt(i).toHtml(), "utf-8");
	    	AndFilter ProfessionNameFilter=new AndFilter(new TagNameFilter("a"),
	                   new HasAttributeFilter("href"));
	   	    NodeList nodes4=parser.extractAllNodesThatMatch(ProfessionNameFilter);
	   	 
	   	    for(int j=0;j<nodes4.size();j++)
	   	    {
	   	    	LinkTag link=(LinkTag)nodes4.elementAt(j);
	   	    	String get1=link.getAttribute("href");
	   	    	if(get1.contains("postgraduatee/research"))
	   	    	{
	   	    		System.out.println("{\""+count+"\",\""+get1+"\",\""+HTMLFilter(html2Str(link.toHtml()))+"\",\"0\"},");
	   	    	    count++;
	   	    	}
	   	    	System.out.println(get1);
	   	    	
	   	    	break;
	   	    }
	   	    
   	    }
   	    
	    
	}
	public static String[][] UnData={
		{"1","http://www.abdn.ac.uk/study/courses/undergraduate/arts/accountancy/","Accountancy","0"},
		{"2","http://www.abdn.ac.uk/study/courses/undergraduate/science/animalbehaviour/","Animal Behaviour","0"},
		{"3","http://www.abdn.ac.uk/study/courses/undergraduate/arts/anthropology/","Anthropology","0"},
		{"4","http://www.abdn.ac.uk/study/courses/undergraduate/arts/archaeology/","Archaeology","0"},
		{"5","http://www.abdn.ac.uk/study/courses/undergraduate/science/archaeology/","Archaeology","0"},
		{"6","http://www.abdn.ac.uk/study/courses/undergraduate/science/behaviouralbiology/","Behavioural Biology","0"},
		{"7","http://www.abdn.ac.uk/study/courses/undergraduate/arts/behavioural_studies/","Behavioural Studies","0"},
		{"8","http://www.abdn.ac.uk/study/courses/undergraduate/science/behavioural_studies/","Behavioural Studies","0"},
		{"9","http://www.abdn.ac.uk/study/courses/undergraduate/science/biobusiness/","Biobusiness Options","0"},
		{"10","http://www.abdn.ac.uk/study/courses/undergraduate/science/biochemistry/","Biochemistry","0"},
		{"11","http://www.abdn.ac.uk/study/courses/undergraduate/science/biological_sciences/","Biological Sciences (MSci)","0"},
		{"12","http://www.abdn.ac.uk/study/courses/undergraduate/science/biology/","Biology","0"},
		{"13","http://www.abdn.ac.uk/study/courses/undergraduate/science/biomedical_science/","Biomedical Science","0"},
		{"14","http://www.abdn.ac.uk/study/courses/undergraduate/science/biotechnology/","Biotechnology","0"},
		{"15","http://www.abdn.ac.uk/study/courses/undergraduate/arts/management_studies/","Business Management","0"},
		{"16","http://www.abdn.ac.uk/study/courses/undergraduate/arts/information_systems/","Business Management and Information Systems","0"},
		{"17","http://www.abdn.ac.uk/study/courses/undergraduate/arts/celtic_anglo/","Celtic and Anglo-Saxon Studies","0"},
		{"18","http://www.abdn.ac.uk/study/courses/undergraduate/engineering/chemical_engineering/","Chemical Engineering","0"},
		{"19","http://www.abdn.ac.uk/study/courses/undergraduate/science/chemistry/","Chemistry","0"},
		{"20","http://www.abdn.ac.uk/study/courses/undergraduate/science/chemistry_mchem/","Chemistry (MChem)","0"},
		{"21","http://www.abdn.ac.uk/study/courses/undergraduate/engineering/civil_structural_engineering/","Civil (and Structural) Engineering","0"},
		{"22","http://www.abdn.ac.uk/study/courses/undergraduate/arts/computing/","Computing","0"},
		{"23","http://www.abdn.ac.uk/study/courses/undergraduate/science/computing_science/","Computing Science","0"},
		{"24","http://www.abdn.ac.uk/study/courses/undergraduate/science/conservation_biology/","Conservation Biology","0"},
		{"25","http://www.abdn.ac.uk/study/courses/undergraduate/medicine/dentistry/","Dentistry","0"},
		{"26","http://www.abdn.ac.uk/study/courses/undergraduate/arts/divinity/","Divinity","0"},
		{"27","http://www.abdn.ac.uk/study/courses/undergraduate/divinity/divinity/","Divinity","0"},
		{"28","http://www.abdn.ac.uk/study/courses/undergraduate/science/ecology/","Ecology","0"},
		{"29","http://www.abdn.ac.uk/study/courses/undergraduate/arts/economics/","Economics","0"},
		{"30","http://www.abdn.ac.uk/study/courses/undergraduate/education/primary/","Education","0"},
		{"31","http://www.abdn.ac.uk/study/courses/undergraduate/engineering/electrical_electronic_engineering/","Electrical and Electronic Engineering","0"},
		{"32","http://www.abdn.ac.uk/study/courses/undergraduate/engineering/engineering/","Engineering","0"},
		{"33","http://www.abdn.ac.uk/study/courses/undergraduate/arts/english/","English","0"},
		{"34","http://www.abdn.ac.uk/study/courses/undergraduate/science/environmental_science/","Environmental Science","0"},
		{"35","http://www.abdn.ac.uk/study/courses/undergraduate/science/sports_studies/","Exercise and Health Science","0"},
		{"36","http://www.abdn.ac.uk/study/courses/undergraduate/arts/film_studies/","Film and Visual Culture","0"},
		{"37","http://www.abdn.ac.uk/study/courses/undergraduate/arts/finance/","Finance","0"},
		{"38","http://www.abdn.ac.uk/study/courses/undergraduate/science/forest_sciences/","Forest Sciences","0"},
		{"39","http://www.abdn.ac.uk/study/courses/undergraduate/science/forestry/","Forestry","0"},
		{"40","http://www.abdn.ac.uk/study/courses/undergraduate/arts/french/","French","0"},
		{"41","http://www.abdn.ac.uk/study/courses/undergraduate/arts/gaelic/","Gaelic Studies","0"},
		{"42","http://www.abdn.ac.uk/study/courses/undergraduate/science/genetics/","Genetics","0"},
		{"43","http://www.abdn.ac.uk/study/courses/undergraduate/arts/geography/","Geography","0"},
		{"44","http://www.abdn.ac.uk/study/courses/undergraduate/science/geography/","Geography","0"},
		{"45","http://www.abdn.ac.uk/study/courses/undergraduate/science/geology/","Geology & Petroleum Geology","0"},
		{"46","http://www.abdn.ac.uk/study/courses/undergraduate/arts/german/","German","0"},
		{"47","http://www.abdn.ac.uk/study/courses/undergraduate/arts/hispanic_studies/","Hispanic Studies","0"},
		{"48","http://www.abdn.ac.uk/study/courses/undergraduate/arts/history/","History","0"},
		{"49","http://www.abdn.ac.uk/study/courses/undergraduate/arts/history_of_art/","History of Art","0"},
		{"50","http://www.abdn.ac.uk/study/courses/undergraduate/science/developmental_biology/","Human Embryology and Developmental Biology","0"},
		{"51","http://www.abdn.ac.uk/study/courses/undergraduate/science/immunology/","Immunology","0"},
		{"52","http://www.abdn.ac.uk/study/courses/undergraduate/science/industrial_academic_placements/","Industrial Placements - Five Year MSci Degrees","0"},
		{"53","http://www.abdn.ac.uk/study/courses/undergraduate/arts/language_linguistics/","Language & Linguistics","0"},
		{"54","http://www.abdn.ac.uk/study/courses/undergraduate/arts/lang_literature_scotland/","Languages and Literature of Scotland","0"},
		{"55","http://www.abdn.ac.uk/study/courses/undergraduate/law/law/","Law","0"},
		{"56","http://www.abdn.ac.uk/study/courses/undergraduate/arts/legal_studies/","Legal Studies","0"},
		{"57","http://www.abdn.ac.uk/study/courses/undergraduate/science/marine_biology/","Marine Biology","0"},
		{"58","http://www.abdn.ac.uk/study/courses/undergraduate/arts/mathematics/","Mathematics","0"},
		{"59","http://www.abdn.ac.uk/study/courses/undergraduate/science/mathematics/","Mathematics","0"},
		{"60","http://www.abdn.ac.uk/study/courses/undergraduate/engineering/mechanical_engineering/","Mechanical Engineering","0"},
		{"61","http://www.abdn.ac.uk/study/courses/undergraduate/medicine/medicine/","Medicine","0"},
		{"62","http://www.abdn.ac.uk/study/courses/undergraduate/science/microbiology/","Microbiology","0"},
		{"63","http://www.abdn.ac.uk/study/courses/undergraduate/science/molecular_biology/","Molecular Biology","0"},
		{"64","http://www.abdn.ac.uk/study/courses/undergraduate/education/music/","Music","0"},
		{"65","http://www.abdn.ac.uk/study/courses/undergraduate/arts/music_studies/","Music Studies","0"},
		{"66","http://www.abdn.ac.uk/study/courses/undergraduate/arts/natural_philosophy/","Natural Philosophy (Physics)","0"},
		{"67","http://www.abdn.ac.uk/study/courses/undergraduate/science/neuroscience_psychology/","Neuroscience with Psychology","0"},
		{"68","http://www.abdn.ac.uk/study/courses/undergraduate/engineering/petroleum_engineering/","Petroleum Engineering","0"},
		{"69","http://www.abdn.ac.uk/study/courses/undergraduate/science/pharmacology/","Pharmacology","0"},
		{"70","http://www.abdn.ac.uk/study/courses/undergraduate/arts/philosophy/","Philosophy","0"},
		{"71","http://www.abdn.ac.uk/study/courses/undergraduate/science/physics/","Physics","0"},
		{"72","http://www.abdn.ac.uk/study/courses/undergraduate/science/physiology/","Physiology","0"},
		{"73","http://www.abdn.ac.uk/study/courses/undergraduate/science/plant_soil/","Plant & Soil Science","0"},
		{"74","http://www.abdn.ac.uk/study/courses/undergraduate/arts/politics/","Politics & International Relations","0"},
		{"75","http://www.abdn.ac.uk/study/courses/undergraduate/arts/psychology/","Psychology","0"},
		{"76","http://www.abdn.ac.uk/study/courses/undergraduate/science/psychology/","Psychology","0"},
		{"77","http://www.abdn.ac.uk/study/courses/undergraduate/arts/property/","Real Estate","0"},
		{"78","http://www.abdn.ac.uk/study/courses/undergraduate/arts/religious_studies/","Religious Studies","0"},
		{"79","http://www.abdn.ac.uk/study/courses/undergraduate/arts/scottish_studies/","Scottish Studies","0"},
		{"80","http://www.abdn.ac.uk/study/courses/undergraduate/arts/sociology/","Sociology","0"},
		{"81","http://www.abdn.ac.uk/study/courses/undergraduate/science/sports_exercise/","Sports & Exercise Science","0"},
		{"82","http://www.abdn.ac.uk/study/courses/undergraduate/divinity/theology/","Theology","0"},
		{"83","http://www.abdn.ac.uk/study/courses/undergraduate/science/zoology/","Zoology","0"}
	};
	public static String[][] PostData1={
		{"1","http://www.abdn.ac.uk/study/courses/postgraduate/taught/finance_accounting/","Accounting and Finance","0"},
		{"2","http://www.abdn.ac.uk/study/courses/postgraduate/taught/finance/","Finance (MRes)","0"},
		{"3","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fin_man/","Finance & Investment Management","0"},
		{"4","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_business_energy/","Petroleum, Energy Economics and Finance","0"},
		{"5","http://www.abdn.ac.uk/study/courses/postgraduate/taught/archaeology/","Archaeology","0"},
		{"6","http://www.abdn.ac.uk/study/courses/postgraduate/taught/archaeology_north/","Archaeology of the North","0"},
		{"7","http://www.abdn.ac.uk/study/courses/postgraduate/taught/museum_studies/","Museum Studies","0"},
		{"8","http://www.abdn.ac.uk/study/courses/postgraduate/taught/people_environment/","People and Environment","0"},
		{"9","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_anthro/","Social Anthropology","0"},
		{"10","http://www.abdn.ac.uk/study/courses/postgraduate/taught/global_health_man/","Global Health and Management","0"},
		{"11","http://www.abdn.ac.uk/study/courses/postgraduate/taught/health_econ/","Health Economics","0"},
		{"12","http://www.abdn.ac.uk/study/courses/postgraduate/taught/healthpsy/","Health Psychology","0"},
		{"13","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_ed/","Medical Education","0"},
		{"14","http://www.abdn.ac.uk/study/courses/postgraduate/taught/research-methods-health/","Research Methods for Health","0"},
		{"15","http://www.abdn.ac.uk/study/courses/postgraduate/taught/archaeology/","Archaeology","0"},
		{"16","http://www.abdn.ac.uk/study/courses/postgraduate/taught/archaeology_north/","Archaeology of the North","0"},
		{"17","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fish/","Applied Marine and Fisheries Ecology","0"},
		{"18","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ecology/","Ecology and Conservation","0"},
		{"19","http://www.abdn.ac.uk/study/courses/postgraduate/taught/env_sci/","Environmental Science","0"},
		{"20","http://www.abdn.ac.uk/study/courses/postgraduate/taught/forestry/","Forestry","0"},
		{"21","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soil_sci/","Soil Science","0"},
		{"22","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_imag/","Medical Imaging","0"},
		{"23","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_phys/","Medical Physics","0"},
		{"24","http://www.abdn.ac.uk/study/courses/postgraduate/taught/biobusiness_medical/","Bio-Business and Medical Sciences","0"},
		{"25","http://www.abdn.ac.uk/study/courses/postgraduate/taught/stratified_med/","Stratified Medicine and Pharmacological Innovation","0"},
		{"26","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_man/","International Business Management","0"},
		{"27","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_admin/","MBA Business Administration","0"},
		{"28","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_admin_jan/","MBA Business Administration (January Entry)","0"},
		{"29","http://www.abdn.ac.uk/study/courses/postgraduate/taught/mba_energy/","MBA Energy Management","0"},
		{"30","http://www.abdn.ac.uk/study/courses/postgraduate/taught/celtic_studies/","Celtic and Anglo Saxon Studies","0"},
		{"31","http://www.abdn.ac.uk/study/courses/postgraduate/taught/analytical_chemistry/","Analytical Chemistry","0"},
		{"32","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oil_gas_chemistry/","Oil & Gas Chemistry","0"},
		{"33","http://www.abdn.ac.uk/study/courses/postgraduate/taught/data_analysis/","Data Analysis, Visualisation and Communication","0"},
		{"34","http://www.abdn.ac.uk/study/courses/postgraduate/taught/information_systems/","Information Systems & Data Management","0"},
		{"35","http://www.abdn.ac.uk/study/courses/postgraduate/taught/infotech/","Information Technology","0"},
		{"36","http://www.abdn.ac.uk/study/courses/postgraduate/taught/og_computing/","Oil and Gas Computing","0"},
		{"37","http://www.abdn.ac.uk/study/courses/postgraduate/taught/consultancy/","Management Consultancy","0"},
		{"38","http://www.abdn.ac.uk/study/courses/postgraduate/taught/counsel/","Person-Centred Counselling","0"},
		{"39","http://www.abdn.ac.uk/study/courses/postgraduate/taught/peace_processes/","Global Conflict and Peace Processes","0"},
		{"40","http://www.abdn.ac.uk/study/courses/postgraduate/taught/museum_studies/","Museum Studies","0"},
		{"41","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_anthro/","Social Anthropology","0"},
		{"42","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_res/","Social Research","0"},
		{"43","http://www.abdn.ac.uk/study/courses/postgraduate/taught/sociology/","Sociology","0"},
		{"44","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bib_theol/","Biblical Studies","0"},
		{"45","http://www.abdn.ac.uk/study/courses/postgraduate/taught/church_hist/","Church History","0"},
		{"46","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ministry-studies/","Ministry Studies","0"},
		{"47","http://www.abdn.ac.uk/study/courses/postgraduate/taught/past_studs/","Pastoral Studies","0"},
		{"48","http://www.abdn.ac.uk/study/courses/postgraduate/taught/religious_studies/","Religious Studies","0"},
		{"49","http://www.abdn.ac.uk/study/courses/postgraduate/taught/systematic_theology/","Systematic Theology","0"},
		{"50","http://www.abdn.ac.uk/study/courses/postgraduate/taught/theological_ethics/","Theological Ethics","0"},
		{"51","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fish/","Applied Marine and Fisheries Ecology","0"},
		{"52","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ecology/","Ecology and Conservation","0"},
		{"53","http://www.abdn.ac.uk/study/courses/postgraduate/taught/appliedeconomics/","Applied Economics","0"},
		{"54","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_business_energy/","Petroleum, Energy Economics and Finance","0"},
		{"55","http://www.abdn.ac.uk/study/courses/postgraduate/taught/autism_learning/","Autism and Learning","0"},
		{"56","http://www.abdn.ac.uk/study/courses/postgraduate/taught/community_development/","Community Learning and Development","0"},
		{"57","http://www.abdn.ac.uk/study/courses/postgraduate/taught/early_years/","Early Years","0"},
		{"58","http://www.abdn.ac.uk/study/courses/postgraduate/taught/gaelic_medium_education/","Gaelic Medium Education","0"},
		{"59","http://www.abdn.ac.uk/study/courses/postgraduate/taught/inc_pract/","Inclusive Practice","0"},
		{"60","http://www.abdn.ac.uk/study/courses/postgraduate/taught/leadership_settings/","Leadership in Professional Contexts","0"},
		{"61","http://www.abdn.ac.uk/study/courses/postgraduate/taught/leadership_settings_headship/","Leadership in Professional Contexts: Incorporating the Standard for Headship (SQH)","0"},
		{"62","http://www.abdn.ac.uk/study/courses/postgraduate/taught/guidance/","Pastoral Care, Guidance and Pupil Support","0"},
		{"63","http://www.abdn.ac.uk/study/courses/postgraduate/taught/counsel/","Person-Centred Counselling","0"},
		{"64","http://www.abdn.ac.uk/study/courses/postgraduate/taught/plurilingual_education/","Plurilingual Education","0"},
		{"65","http://www.abdn.ac.uk/study/courses/postgraduate/taught/primary/","Primary Education","0"},
		{"66","http://www.abdn.ac.uk/study/courses/postgraduate/taught/professional_learning_development/","Professional Learning and Development (Primary)","0"},
		{"67","http://www.abdn.ac.uk/study/courses/postgraduate/taught/secondary/","Secondary Education","0"},
		{"68","http://www.abdn.ac.uk/study/courses/postgraduate/taught/advanced_educational/","Studies in Education","0"},
		{"69","http://www.abdn.ac.uk/study/courses/postgraduate/taught/studies_in_mindfulness/","Studies in Mindfulness","0"},
		{"70","http://www.abdn.ac.uk/study/courses/postgraduate/taught/teaching_qualification_education/","Teaching Qualification in Further Education","0"},
		{"71","http://www.abdn.ac.uk/study/courses/postgraduate/taught/analytical_chemistry/","Analytical Chemistry","0"},
		{"72","http://www.abdn.ac.uk/study/courses/postgraduate/taught/law_susdev/","Energy and Environmental Law (LLM)","0"},
		{"73","http://www.abdn.ac.uk/study/courses/postgraduate/taught/eng_law/","Energy Law (LLM)","0"},
		{"74","http://www.abdn.ac.uk/study/courses/postgraduate/taught/energypoliticslaw/","Energy Politics and Law","0"},
		{"75","http://www.abdn.ac.uk/study/courses/postgraduate/taught/env_sci/","Environmental Science","0"},
		{"76","http://www.abdn.ac.uk/study/courses/postgraduate/taught/gis/","Geographical Information Systems","0"},
		{"77","http://www.abdn.ac.uk/study/courses/postgraduate/taught/geophysics/","Geophysics","0"},
		{"78","http://www.abdn.ac.uk/study/courses/postgraduate/taught/petrol/","Integrated Petroleum Geoscience","0"},
		{"79","http://www.abdn.ac.uk/study/courses/postgraduate/taught/mba_energy/","MBA Energy Management","0"},
		{"80","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oil_gas_chemistry/","Oil & Gas Chemistry","0"},
		{"81","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oglps/","Oil & Gas Law with Professional Skills (LLM)","0"},
		{"82","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oil_gas_structural/","Oil & Gas Structural Engineering","0"},
		{"83","http://www.abdn.ac.uk/study/courses/postgraduate/taught/og_computing/","Oil and Gas Computing","0"},
		{"84","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oilgas/","Oil and Gas Engineering","0"},
		{"85","http://www.abdn.ac.uk/study/courses/postgraduate/taught/hydrocarbon/","Oil and Gas Enterprise Management","0"},
		{"86","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oil_gas_law/","Oil and Gas Law with Dissertation (LLM)","0"},
		{"87","http://www.abdn.ac.uk/study/courses/postgraduate/taught/peteng/","Petroleum Engineering","0"},
		{"88","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_business_energy/","Petroleum, Energy Economics and Finance","0"},
		{"89","http://www.abdn.ac.uk/study/courses/postgraduate/taught/petrophysics/","Petrophysics and Formation Evaluation","0"},
		{"90","http://www.abdn.ac.uk/study/courses/postgraduate/taught/process_safety/","Process Safety","0"},
		{"91","http://www.abdn.ac.uk/study/courses/postgraduate/taught/proj_man/","Project Management (campus based or distance learning)","0"},
		{"92","http://www.abdn.ac.uk/study/courses/postgraduate/taught/renewables/","Renewable Energy Engineering","0"},
		{"93","http://www.abdn.ac.uk/study/courses/postgraduate/taught/reservoir_engineering/","Reservoir Engineering","0"},
		{"94","http://www.abdn.ac.uk/study/courses/postgraduate/taught/safety/","Safety & Reliability Engineering for Oil & Gas","0"},
		{"95","http://www.abdn.ac.uk/study/courses/postgraduate/taught/subsea_engineering/","Subsea Engineering","0"},
		{"96","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oil_gas_structural/","Oil & Gas Structural Engineering","0"},
		{"97","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oilgas/","Oil and Gas Engineering","0"},
		{"98","http://www.abdn.ac.uk/study/courses/postgraduate/taught/peteng/","Petroleum Engineering","0"},
		{"99","http://www.abdn.ac.uk/study/courses/postgraduate/taught/process_safety/","Process Safety","0"},
		{"100","http://www.abdn.ac.uk/study/courses/postgraduate/taught/proj_man/","Project Management (campus based or distance learning)","0"},
		{"101","http://www.abdn.ac.uk/study/courses/postgraduate/taught/renewables/","Renewable Energy Engineering","0"},
		{"102","http://www.abdn.ac.uk/study/courses/postgraduate/taught/reservoir_engineering/","Reservoir Engineering","0"},
		{"103","http://www.abdn.ac.uk/study/courses/postgraduate/taught/safety/","Safety & Reliability Engineering for Oil & Gas","0"},
		{"104","http://www.abdn.ac.uk/study/courses/postgraduate/taught/subsea_engineering/","Subsea Engineering","0"},
		{"105","http://www.abdn.ac.uk/study/courses/postgraduate/taught/creative_writing/","Creative Writing","0"},
		{"106","http://www.abdn.ac.uk/study/courses/postgraduate/taught/eng_lit/","English Literary  Studies","0"},
		{"107","http://www.abdn.ac.uk/study/courses/postgraduate/taught/irish_scottish/","Irish and Scottish Literature","0"},
		{"108","http://www.abdn.ac.uk/study/courses/postgraduate/taught/procom/","Professional Communication","0"},
		{"109","http://www.abdn.ac.uk/study/courses/postgraduate/taught/translation_studies/","Translation Studies, MSc","0"},
		{"110","http://www.abdn.ac.uk/study/courses/postgraduate/taught/visual_cult/","Visual Culture","0"},
		{"111","http://www.abdn.ac.uk/study/courses/postgraduate/taught/analytical_chemistry/","Analytical Chemistry","0"},
		{"112","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ecology/","Ecology and Conservation","0"},
		{"113","http://www.abdn.ac.uk/study/courses/postgraduate/taught/enviro_partnership_management/","Environmental Partnership Management","0"},
		{"114","http://www.abdn.ac.uk/study/courses/postgraduate/taught/env_sci/","Environmental Science","0"},
		{"115","http://www.abdn.ac.uk/study/courses/postgraduate/taught/gis/","Geographical Information Systems","0"},
		{"116","http://www.abdn.ac.uk/study/courses/postgraduate/taught/land_econ/","Land Economy (Rural Surveying, RICS accredited)","0"},
		{"117","http://www.abdn.ac.uk/study/courses/postgraduate/taught/analytical_chemistry/","Analytical Chemistry","0"},
		{"118","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ecology/","Ecology and Conservation","0"},
		{"119","http://www.abdn.ac.uk/study/courses/postgraduate/taught/enviro_partnership_management/","Environmental Partnership Management","0"},
		{"120","http://www.abdn.ac.uk/study/courses/postgraduate/taught/env_sci/","Environmental Science","0"},
		{"121","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ethno_folk/","Ethnology & Folklore","0"},
		{"122","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_anthro/","Social Anthropology","0"},
		{"123","http://www.abdn.ac.uk/study/courses/postgraduate/taught/visual_cult/","Visual Culture","0"},
		{"124","http://www.abdn.ac.uk/study/courses/postgraduate/taught/finance_accounting/","Accounting and Finance","0"},
		{"125","http://www.abdn.ac.uk/study/courses/postgraduate/taught/finance/","Finance (MRes)","0"},
		{"126","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fin_man/","Finance & Investment Management","0"},
		{"127","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fin-realestate/","Finance and Real Estate","0"},
		{"128","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_business_energy/","Petroleum, Energy Economics and Finance","0"},
		{"129","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ethno_folk/","Ethnology & Folklore","0"},
		{"130","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_anthro/","Social Anthropology","0"},
		{"131","http://www.abdn.ac.uk/study/courses/postgraduate/taught/forestry/","Forestry","0"},
		{"132","http://www.abdn.ac.uk/study/courses/postgraduate/taught/visual_cult/","Visual Culture","0"},
		{"133","http://www.abdn.ac.uk/study/courses/postgraduate/taught/sex_gender_violence/","Sex, Gender, Violence: Contemporary Critical Approaches","0"},
		{"134","http://www.abdn.ac.uk/study/courses/postgraduate/taught/genetics/","Genetics","0"},
		{"135","http://www.abdn.ac.uk/study/courses/postgraduate/taught/data_analysis/","Data Analysis, Visualisation and Communication","0"},
		{"136","http://www.abdn.ac.uk/study/courses/postgraduate/taught/enviro_partnership_management/","Environmental Partnership Management","0"},
		{"137","http://www.abdn.ac.uk/study/courses/postgraduate/taught/gis/","Geographical Information Systems","0"},
		{"138","http://www.abdn.ac.uk/study/courses/postgraduate/taught/land_econ/","Land Economy (Rural Surveying, RICS accredited)","0"},
		{"139","http://www.abdn.ac.uk/study/courses/postgraduate/taught/geophysics/","Geophysics","0"},
		{"140","http://www.abdn.ac.uk/study/courses/postgraduate/taught/petrol/","Integrated Petroleum Geoscience","0"},
		{"141","http://www.abdn.ac.uk/study/courses/postgraduate/taught/hydrocarbon/","Oil and Gas Enterprise Management","0"},
		{"142","http://www.abdn.ac.uk/study/courses/postgraduate/taught/petrophysics/","Petrophysics and Formation Evaluation","0"},
		{"143","http://www.abdn.ac.uk/study/courses/postgraduate/taught/reservoir_engineering/","Reservoir Engineering","0"},
		{"144","http://www.abdn.ac.uk/study/courses/postgraduate/taught/visual_cult/","Visual Culture","0"},
		{"145","http://www.abdn.ac.uk/study/courses/postgraduate/taught/health_econ/","Health Economics","0"},
		{"146","http://www.abdn.ac.uk/study/courses/postgraduate/taught/physician_assistant/","Physician Associate Studies","0"},
		{"147","http://www.abdn.ac.uk/study/courses/postgraduate/taught/research-methods-health/","Research Methods for Health","0"},
		{"148","http://www.abdn.ac.uk/study/courses/postgraduate/taught/latin_american/","Latin American Studies","0"},
		{"149","http://www.abdn.ac.uk/study/courses/postgraduate/taught/visual_cult/","Visual Culture","0"},
		{"150","http://www.abdn.ac.uk/study/courses/postgraduate/taught/church_hist/","Church History","0"},
		{"151","http://www.abdn.ac.uk/study/courses/postgraduate/taught/irish_and_scottish/","Irish and Scottish History","0"},
		{"152","http://www.abdn.ac.uk/study/courses/postgraduate/taught/medieval-early-mod/","Medieval and Early Modern Studies","0"},
		{"153","http://www.abdn.ac.uk/study/courses/postgraduate/taught/modern_history/","Modern History","0"},
		{"154","http://www.abdn.ac.uk/study/courses/postgraduate/taught/art_business/","Art and Business","0"},
		{"155","http://www.abdn.ac.uk/study/courses/postgraduate/taught/immunology/","Immunology","0"},
		{"156","http://www.abdn.ac.uk/study/courses/postgraduate/taught/european_politics/","European Politics and Society","0"},
		{"157","http://www.abdn.ac.uk/study/courses/postgraduate/taught/globalization/","Globalization","0"},
		{"158","http://www.abdn.ac.uk/study/courses/postgraduate/taught/intlaw_ir/","International Law and International Relations (LLM)","0"},
		{"159","http://www.abdn.ac.uk/study/courses/postgraduate/taught/international_relations/","International Relations","0"},
		{"160","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ir_law/","International Relations and International Law","0"},
		{"161","http://www.abdn.ac.uk/study/courses/postgraduate/taught/latin_american/","Latin American Studies","0"},
		{"162","http://www.abdn.ac.uk/study/courses/postgraduate/taught/pol_res/","Political Research","0"},
		{"163","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strat_studs/","Strategic Studies","0"},
		{"164","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_studies/","Strategic Studies and International Law","0"},
		{"165","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_management/","Strategic Studies and Management","0"},
		{"166","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fin_man/","Finance & Investment Management","0"},
		{"167","http://www.abdn.ac.uk/study/courses/postgraduate/taught/medieval-early-mod/","Medieval and Early Modern Studies","0"},
		{"168","http://www.abdn.ac.uk/study/courses/postgraduate/taught/land_econ/","Land Economy (Rural Surveying, RICS accredited)","0"},
		{"169","http://www.abdn.ac.uk/study/courses/postgraduate/taught/crim_just/","Criminal Justice (LLM)","0"},
		{"170","http://www.abdn.ac.uk/study/courses/postgraduate/taught/crim_rights/","Criminal Justice & Human Rights (LLM)","0"},
		{"171","http://www.abdn.ac.uk/study/courses/postgraduate/taught/law_susdev/","Energy and Environmental Law (LLM)","0"},
		{"172","http://www.abdn.ac.uk/study/courses/postgraduate/taught/eng_law/","Energy Law (LLM)","0"},
		{"173","http://www.abdn.ac.uk/study/courses/postgraduate/taught/energypoliticslaw/","Energy Politics and Law","0"},
		{"174","http://www.abdn.ac.uk/study/courses/postgraduate/taught/gen_law/","General Law (LLM)","0"},
		{"175","http://www.abdn.ac.uk/study/courses/postgraduate/taught/human_right/","Human Rights (LLM)","0"},
		{"176","http://www.abdn.ac.uk/study/courses/postgraduate/taught/human_crim/","Human Rights and Criminal Justice (LLM)","0"},
		{"177","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_arbitration/","International Arbitration (PgDip)","0"},
		{"178","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_comlaw/","International Commercial Law with Dissertation (LLM)","0"},
		{"179","http://www.abdn.ac.uk/study/courses/postgraduate/taught/iclps/","International Commercial Law with Professional Skills (LLM)","0"},
		{"180","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_law/","International Law (LLM)","0"},
		{"181","http://www.abdn.ac.uk/study/courses/postgraduate/taught/intlaw_ir/","International Law and International Relations (LLM)","0"},
		{"182","http://www.abdn.ac.uk/study/courses/postgraduate/taught/intlaw_str/","International Law and Strategic Studies (LLM)","0"},
		{"183","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ir_law/","International Relations and International Law","0"},
		{"184","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oglps/","Oil & Gas Law with Professional Skills (LLM)","0"},
		{"185","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oil_gas_law/","Oil and Gas Law with Dissertation (LLM)","0"},
		{"186","http://www.abdn.ac.uk/study/courses/postgraduate/taught/private_international_law/","Private International Law (LLM)","0"},
		{"187","http://www.abdn.ac.uk/study/courses/postgraduate/taught/legal_pract/","Professional Legal Practice","0"},
		{"188","http://www.abdn.ac.uk/study/courses/postgraduate/taught/public_international_law/","Public International Law (LLM)","0"},
		{"189","http://www.abdn.ac.uk/study/courses/postgraduate/taught/procom/","Professional Communication","0"},
		{"190","http://www.abdn.ac.uk/study/courses/postgraduate/taught/tesol_linguistics/","TESOL, MSc","0"},
		{"191","http://www.abdn.ac.uk/study/courses/postgraduate/taught/creative_writing/","Creative Writing","0"},
		{"192","http://www.abdn.ac.uk/study/courses/postgraduate/taught/eng_lit/","English Literary  Studies","0"},
		{"193","http://www.abdn.ac.uk/study/courses/postgraduate/taught/literature_science_medicine/","Literature, Science and Medicine","0"},
		{"194","http://www.abdn.ac.uk/study/courses/postgraduate/taught/novel_the/","Novel, The","0"},
		{"195","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_admin/","MBA Business Administration","0"},
		{"196","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_admin_jan/","MBA Business Administration (January Entry)","0"},
		{"197","http://www.abdn.ac.uk/study/courses/postgraduate/taught/mba_energy/","MBA Energy Management","0"},
		{"198","http://www.abdn.ac.uk/study/courses/postgraduate/taught/business_research/","Business Research","0"},
		{"199","http://www.abdn.ac.uk/study/courses/postgraduate/taught/enviro_partnership_management/","Environmental Partnership Management","0"},
		{"200","http://www.abdn.ac.uk/study/courses/postgraduate/taught/finance/","Finance (MRes)","0"},
		{"201","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fin_man/","Finance & Investment Management","0"},
		{"202","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_man/","International Business Management","0"},
		{"203","http://www.abdn.ac.uk/study/courses/postgraduate/taught/consultancy/","Management Consultancy","0"},
		{"204","http://www.abdn.ac.uk/study/courses/postgraduate/taught/marketing_management/","Marketing Management","0"},
		{"205","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_admin/","MBA Business Administration","0"},
		{"206","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_admin_jan/","MBA Business Administration (January Entry)","0"},
		{"207","http://www.abdn.ac.uk/study/courses/postgraduate/taught/mba_energy/","MBA Energy Management","0"},
		{"208","http://www.abdn.ac.uk/study/courses/postgraduate/taught/hydrocarbon/","Oil and Gas Enterprise Management","0"},
		{"209","http://www.abdn.ac.uk/study/courses/postgraduate/taught/proj_man/","Project Management (campus based or distance learning)","0"},
		{"210","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_management/","Strategic Studies and Management","0"},
		{"211","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fish/","Applied Marine and Fisheries Ecology","0"},
		{"212","http://www.abdn.ac.uk/study/courses/postgraduate/taught/env_sci/","Environmental Science","0"},
		{"213","http://www.abdn.ac.uk/study/courses/postgraduate/taught/digital_marketing/","Digital Marketing Leadership  (Online MSc degree)","0"},
		{"214","http://www.abdn.ac.uk/study/courses/postgraduate/taught/marketing_management/","Marketing Management","0"},
		{"215","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_imag/","Medical Imaging","0"},
		{"216","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_phys/","Medical Physics","0"},
		{"217","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_imag/","Medical Imaging","0"},
		{"218","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_phys/","Medical Physics","0"},
		{"219","http://www.abdn.ac.uk/study/courses/postgraduate/taught/biobusiness_medical/","Bio-Business and Medical Sciences","0"},
		{"220","http://www.abdn.ac.uk/study/courses/postgraduate/taught/clin_pharm/","Clinical Pharmacology","0"},
		{"221","http://www.abdn.ac.uk/study/courses/postgraduate/taught/drug_discovery/","Drug Discovery (MRes)","0"},
		{"222","http://www.abdn.ac.uk/study/courses/postgraduate/taught/drug_disc_dev/","Drug Discovery and Development","0"},
		{"223","http://www.abdn.ac.uk/study/courses/postgraduate/taught/immunology/","Immunology","0"},
		{"224","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_imag/","Medical Imaging","0"},
		{"225","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_phys/","Medical Physics","0"},
		{"226","http://www.abdn.ac.uk/study/courses/postgraduate/taught/medical-research-skills/","Medical Research Skills","0"},
		{"227","http://www.abdn.ac.uk/study/courses/postgraduate/taught/stratified_med/","Stratified Medicine and Pharmacological Innovation","0"},
		{"228","http://www.abdn.ac.uk/study/courses/postgraduate/taught/microbiology/","Microbiology","0"},
		{"229","http://www.abdn.ac.uk/study/courses/postgraduate/taught/master_music/","Music","0"},
		{"230","http://www.abdn.ac.uk/study/courses/postgraduate/taught/sonic_arts/","Sonic Arts","0"},
		{"231","http://www.abdn.ac.uk/study/courses/postgraduate/taught/vocal/","Vocal Music","0"},
		{"232","http://www.abdn.ac.uk/study/courses/postgraduate/taught/human_nutrition/","Human Nutrition","0"},
		{"233","http://www.abdn.ac.uk/study/courses/postgraduate/taught/geophysics/","Geophysics","0"},
		{"234","http://www.abdn.ac.uk/study/courses/postgraduate/taught/petrol/","Integrated Petroleum Geoscience","0"},
		{"235","http://www.abdn.ac.uk/study/courses/postgraduate/taught/hydrocarbon/","Oil and Gas Enterprise Management","0"},
		{"236","http://www.abdn.ac.uk/study/courses/postgraduate/taught/petrophysics/","Petrophysics and Formation Evaluation","0"},
		{"237","http://www.abdn.ac.uk/study/courses/postgraduate/taught/reservoir_engineering/","Reservoir Engineering","0"},
		{"238","http://www.abdn.ac.uk/study/courses/postgraduate/taught/geophysics/","Geophysics","0"},
		{"239","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_imag/","Medical Imaging","0"},
		{"240","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_phys/","Medical Physics","0"},
		{"241","http://www.abdn.ac.uk/study/courses/postgraduate/taught/env_sci/","Environmental Science","0"},
		{"242","http://www.abdn.ac.uk/study/courses/postgraduate/taught/forestry/","Forestry","0"},
		{"243","http://www.abdn.ac.uk/study/courses/postgraduate/taught/energypoliticslaw/","Energy Politics and Law","0"},
		{"244","http://www.abdn.ac.uk/study/courses/postgraduate/taught/european_politics/","European Politics and Society","0"},
		{"245","http://www.abdn.ac.uk/study/courses/postgraduate/taught/globalization/","Globalization","0"},
		{"246","http://www.abdn.ac.uk/study/courses/postgraduate/taught/international_relations/","International Relations","0"},
		{"247","http://www.abdn.ac.uk/study/courses/postgraduate/taught/latin_american/","Latin American Studies","0"},
		{"248","http://www.abdn.ac.uk/study/courses/postgraduate/taught/pol_res/","Political Research","0"},
		{"249","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strat_studs/","Strategic Studies","0"},
		{"250","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_studies/","Strategic Studies and International Law","0"},
		{"251","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_management/","Strategic Studies and Management","0"},
		{"252","http://www.abdn.ac.uk/study/courses/postgraduate/taught/proj_man/","Project Management (campus based or distance learning)","0"},
		{"253","http://www.abdn.ac.uk/study/courses/postgraduate/taught/healthpsy/","Health Psychology","0"},
		{"254","http://www.abdn.ac.uk/study/courses/postgraduate/taught/psychstuds/","Psychological Studies (MSc)","0"},
		{"255","http://www.abdn.ac.uk/study/courses/postgraduate/taught/psych/","Psychology","0"},
		{"256","http://www.abdn.ac.uk/study/courses/postgraduate/taught/health_econ/","Health Economics","0"},
		{"257","http://www.abdn.ac.uk/study/courses/postgraduate/taught/real_estate2/","Real Estate","0"},
		{"258","http://www.abdn.ac.uk/study/courses/postgraduate/taught/religion_society/","Religion and Society","0"},
		{"259","http://www.abdn.ac.uk/study/courses/postgraduate/taught/islamic_studies/","Islamic Studies","0"},
		{"260","http://www.abdn.ac.uk/study/courses/postgraduate/taught/religious_studies/","Religious Studies","0"},
		{"261","http://www.abdn.ac.uk/study/courses/postgraduate/taught/medical-research-skills/","Medical Research Skills","0"},
		{"262","http://www.abdn.ac.uk/study/courses/postgraduate/taught/pol_res/","Political Research","0"},
		{"263","http://www.abdn.ac.uk/study/courses/postgraduate/taught/research-methods-health/","Research Methods for Health","0"},
		{"264","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_res/","Social Research","0"},
		{"265","http://www.abdn.ac.uk/study/courses/postgraduate/taught/medieval-early-mod/","Medieval and Early Modern Studies","0"},
		{"266","http://www.abdn.ac.uk/study/courses/postgraduate/taught/scandinavian_studies/","Scandinavian Studies","0"},
		{"267","http://www.abdn.ac.uk/study/courses/postgraduate/taught/irish_and_scottish/","Irish and Scottish History","0"},
		{"268","http://www.abdn.ac.uk/study/courses/postgraduate/taught/irish_scottish/","Irish and Scottish Literature","0"},
		{"269","http://www.abdn.ac.uk/study/courses/postgraduate/taught/celtic_studies/","Celtic and Anglo Saxon Studies","0"},
		{"270","http://www.abdn.ac.uk/study/courses/postgraduate/taught/medieval-early-mod/","Medieval and Early Modern Studies","0"},
		{"271","http://www.abdn.ac.uk/study/courses/postgraduate/taught/european_politics/","European Politics and Society","0"},
		{"272","http://www.abdn.ac.uk/study/courses/postgraduate/taught/peace_processes/","Global Conflict and Peace Processes","0"},
		{"273","http://www.abdn.ac.uk/study/courses/postgraduate/taught/globalization/","Globalization","0"},
		{"274","http://www.abdn.ac.uk/study/courses/postgraduate/taught/justice_peacebuilding/","Post-Conflict Justice and Peacebuilding","0"},
		{"275","http://www.abdn.ac.uk/study/courses/postgraduate/taught/radicalization_resistance/","Radicalization and Resistance","0"},
		{"276","http://www.abdn.ac.uk/study/courses/postgraduate/taught/refugee_displacement/","Refugee and Displacement Studies","0"},
		{"277","http://www.abdn.ac.uk/study/courses/postgraduate/taught/religion_society/","Religion and Society","0"},
		{"278","http://www.abdn.ac.uk/study/courses/postgraduate/taught/sex_gender_violence/","Sex, Gender, Violence: Contemporary Critical Approaches","0"},
		{"279","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_res/","Social Research","0"},
		{"280","http://www.abdn.ac.uk/study/courses/postgraduate/taught/sociology/","Sociology","0"},
		{"281","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strat_studs/","Strategic Studies","0"},
		{"282","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_studies/","Strategic Studies and International Law","0"},
		{"283","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_management/","Strategic Studies and Management","0"},
		{"284","http://www.abdn.ac.uk/study/courses/postgraduate/taught/land_econ/","Land Economy (Rural Surveying, RICS accredited)","0"},
		{"285","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bib_theol/","Biblical Studies","0"},
		{"286","http://www.abdn.ac.uk/study/courses/postgraduate/taught/church_hist/","Church History","0"},
		{"287","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ministry-studies/","Ministry Studies","0"},
		{"288","http://www.abdn.ac.uk/study/courses/postgraduate/taught/systematic_theology/","Systematic Theology","0"},
		{"289","http://www.abdn.ac.uk/study/courses/postgraduate/taught/theological_ethics/","Theological Ethics","0"}
	};
	
	public static String[][] PostData={
		
		{"1","http://www.abdn.ac.uk/study/courses/postgraduate/taught/finance_accounting/","Accounting and Finance","0"},
		{"2","http://www.abdn.ac.uk/study/courses/postgraduate/taught/finance/","Finance (MRes)","0"},
		{"3","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fin_man/","Finance & Investment Management","0"},
		{"4","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_business_energy/","Petroleum, Energy Economics and Finance","0"},
		{"5","http://www.abdn.ac.uk/study/courses/postgraduate/taught/archaeology/","Archaeology","0"},
		{"6","http://www.abdn.ac.uk/study/courses/postgraduate/taught/archaeology_north/","Archaeology of the North","0"},
		{"7","http://www.abdn.ac.uk/study/courses/postgraduate/taught/museum_studies/","Museum Studies","0"},
		{"8","http://www.abdn.ac.uk/study/courses/postgraduate/taught/people_environment/","People and Environment","0"},
		{"9","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_anthro/","Social Anthropology","0"},
		{"10","http://www.abdn.ac.uk/study/courses/postgraduate/taught/global_health_man/","Global Health and Management","0"},
		{"11","http://www.abdn.ac.uk/study/courses/postgraduate/taught/health_econ/","Health Economics","0"},
		{"12","http://www.abdn.ac.uk/study/courses/postgraduate/taught/healthpsy/","Health Psychology","0"},
		{"13","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_ed/","Medical Education","0"},
		{"14","http://www.abdn.ac.uk/study/courses/postgraduate/taught/research-methods-health/","Research Methods for Health","0"},
		{"15","http://www.abdn.ac.uk/study/courses/postgraduate/taught/archaeology/","Archaeology","0"},
		{"16","http://www.abdn.ac.uk/study/courses/postgraduate/taught/archaeology_north/","Archaeology of the North","0"},
		{"17","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fish/","Applied Marine and Fisheries Ecology","0"},
		{"18","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ecology/","Ecology and Conservation","0"},
		{"19","http://www.abdn.ac.uk/study/courses/postgraduate/taught/env_sci/","Environmental Science","0"},
		{"20","http://www.abdn.ac.uk/study/courses/postgraduate/taught/forestry/","Forestry","0"},
		{"21","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soil_sci/","Soil Science","0"},
		{"22","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_imag/","Medical Imaging","0"},
		{"23","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_phys/","Medical Physics","0"},
		{"24","http://www.abdn.ac.uk/study/courses/postgraduate/taught/biobusiness_medical/","Bio-Business and Medical Sciences","0"},
		{"25","http://www.abdn.ac.uk/study/courses/postgraduate/taught/stratified_med/","Stratified Medicine and Pharmacological Innovation","0"},
		{"26","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_man/","International Business Management","0"},
		{"27","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_admin/","MBA Business Administration","0"},
		{"28","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_admin_jan/","MBA Business Administration (January Entry)","0"},
		{"29","http://www.abdn.ac.uk/study/courses/postgraduate/taught/mba_energy/","MBA Energy Management","0"},
		{"30","http://www.abdn.ac.uk/study/courses/postgraduate/taught/celtic_studies/","Celtic and Anglo Saxon Studies","0"},
		{"31","http://www.abdn.ac.uk/study/courses/postgraduate/taught/analytical_chemistry/","Analytical Chemistry","0"},
		{"32","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oil_gas_chemistry/","Oil & Gas Chemistry","0"},
		{"33","http://www.abdn.ac.uk/study/courses/postgraduate/taught/data_analysis/","Data Analysis, Visualisation and Communication","0"},
		{"34","http://www.abdn.ac.uk/study/courses/postgraduate/taught/information_systems/","Information Systems & Data Management","0"},
		{"35","http://www.abdn.ac.uk/study/courses/postgraduate/taught/infotech/","Information Technology","0"},
		{"36","http://www.abdn.ac.uk/study/courses/postgraduate/taught/og_computing/","Oil and Gas Computing","0"},
		{"37","http://www.abdn.ac.uk/study/courses/postgraduate/taught/consultancy/","Management Consultancy","0"},
		{"38","http://www.abdn.ac.uk/study/courses/postgraduate/taught/counsel/","Person-Centred Counselling","0"},
		{"39","http://www.abdn.ac.uk/study/courses/postgraduate/taught/peace_processes/","Global Conflict and Peace Processes","0"},
		{"40","http://www.abdn.ac.uk/study/courses/postgraduate/taught/museum_studies/","Museum Studies","0"},
		{"41","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_anthro/","Social Anthropology","0"},
		{"42","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_res/","Social Research","0"},
		{"43","http://www.abdn.ac.uk/study/courses/postgraduate/taught/sociology/","Sociology","0"},
		{"44","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bib_theol/","Biblical Studies","0"},
		{"45","http://www.abdn.ac.uk/study/courses/postgraduate/taught/church_hist/","Church History","0"},
		{"46","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ministry-studies/","Ministry Studies","0"},
		{"47","http://www.abdn.ac.uk/study/courses/postgraduate/taught/past_studs/","Pastoral Studies","0"},
		{"48","http://www.abdn.ac.uk/study/courses/postgraduate/taught/religious_studies/","Religious Studies","0"},
		{"49","http://www.abdn.ac.uk/study/courses/postgraduate/taught/systematic_theology/","Systematic Theology","0"},
		{"50","http://www.abdn.ac.uk/study/courses/postgraduate/taught/theological_ethics/","Theological Ethics","0"},
		{"51","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fish/","Applied Marine and Fisheries Ecology","0"},
		{"52","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ecology/","Ecology and Conservation","0"},
		{"53","http://www.abdn.ac.uk/study/courses/postgraduate/taught/appliedeconomics/","Applied Economics","0"},
		{"54","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_business_energy/","Petroleum, Energy Economics and Finance","0"},
		{"55","http://www.abdn.ac.uk/study/courses/postgraduate/taught/autism_learning/","Autism and Learning","0"},
		{"56","http://www.abdn.ac.uk/study/courses/postgraduate/taught/community_development/","Community Learning and Development","0"},
		{"57","http://www.abdn.ac.uk/study/courses/postgraduate/taught/early_years/","Early Years","0"},
		{"58","http://www.abdn.ac.uk/study/courses/postgraduate/taught/gaelic_medium_education/","Gaelic Medium Education","0"},
		{"59","http://www.abdn.ac.uk/study/courses/postgraduate/taught/inc_pract/","Inclusive Practice","0"},
		{"60","http://www.abdn.ac.uk/study/courses/postgraduate/taught/leadership_settings/","Leadership in Professional Contexts","0"},
		{"61","http://www.abdn.ac.uk/study/courses/postgraduate/taught/leadership_settings_headship/","Leadership in Professional Contexts: Incorporating the Standard for Headship (SQH)","0"},
		{"62","http://www.abdn.ac.uk/study/courses/postgraduate/taught/guidance/","Pastoral Care, Guidance and Pupil Support","0"},
		{"63","http://www.abdn.ac.uk/study/courses/postgraduate/taught/counsel/","Person-Centred Counselling","0"},
		{"64","http://www.abdn.ac.uk/study/courses/postgraduate/taught/plurilingual_education/","Plurilingual Education","0"},
		{"65","http://www.abdn.ac.uk/study/courses/postgraduate/taught/primary/","Primary Education","0"},
		{"66","http://www.abdn.ac.uk/study/courses/postgraduate/taught/professional_learning_development/","Professional Learning and Development (Primary)","0"},
		{"67","http://www.abdn.ac.uk/study/courses/postgraduate/taught/secondary/","Secondary Education","0"},
		{"68","http://www.abdn.ac.uk/study/courses/postgraduate/taught/advanced_educational/","Studies in Education","0"},
		{"69","http://www.abdn.ac.uk/study/courses/postgraduate/taught/studies_in_mindfulness/","Studies in Mindfulness","0"},
		{"70","http://www.abdn.ac.uk/study/courses/postgraduate/taught/teaching_qualification_education/","Teaching Qualification in Further Education","0"},
		{"71","http://www.abdn.ac.uk/study/courses/postgraduate/taught/analytical_chemistry/","Analytical Chemistry","0"},
		{"72","http://www.abdn.ac.uk/study/courses/postgraduate/taught/law_susdev/","Energy and Environmental Law (LLM)","0"},
		{"73","http://www.abdn.ac.uk/study/courses/postgraduate/taught/eng_law/","Energy Law (LLM)","0"},
		{"74","http://www.abdn.ac.uk/study/courses/postgraduate/taught/energypoliticslaw/","Energy Politics and Law","0"},
		{"75","http://www.abdn.ac.uk/study/courses/postgraduate/taught/env_sci/","Environmental Science","0"},
		{"76","http://www.abdn.ac.uk/study/courses/postgraduate/taught/gis/","Geographical Information Systems","0"},
		{"77","http://www.abdn.ac.uk/study/courses/postgraduate/taught/geophysics/","Geophysics","0"},
		{"78","http://www.abdn.ac.uk/study/courses/postgraduate/taught/petrol/","Integrated Petroleum Geoscience","0"},
		{"79","http://www.abdn.ac.uk/study/courses/postgraduate/taught/mba_energy/","MBA Energy Management","0"},
		{"80","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oil_gas_chemistry/","Oil & Gas Chemistry","0"},
		{"81","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oglps/","Oil & Gas Law with Professional Skills (LLM)","0"},
		{"82","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oil_gas_structural/","Oil & Gas Structural Engineering","0"},
		{"83","http://www.abdn.ac.uk/study/courses/postgraduate/taught/og_computing/","Oil and Gas Computing","0"},
		{"84","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oilgas/","Oil and Gas Engineering","0"},
		{"85","http://www.abdn.ac.uk/study/courses/postgraduate/taught/hydrocarbon/","Oil and Gas Enterprise Management","0"},
		{"86","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oil_gas_law/","Oil and Gas Law with Dissertation (LLM)","0"},
		{"87","http://www.abdn.ac.uk/study/courses/postgraduate/taught/peteng/","Petroleum Engineering","0"},
		{"88","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_business_energy/","Petroleum, Energy Economics and Finance","0"},
		{"89","http://www.abdn.ac.uk/study/courses/postgraduate/taught/petrophysics/","Petrophysics and Formation Evaluation","0"},
		{"90","http://www.abdn.ac.uk/study/courses/postgraduate/taught/process_safety/","Process Safety","0"},
		{"91","http://www.abdn.ac.uk/study/courses/postgraduate/taught/proj_man/","Project Management (campus based or distance learning)","0"},
		{"92","http://www.abdn.ac.uk/study/courses/postgraduate/taught/renewables/","Renewable Energy Engineering","0"},
		{"93","http://www.abdn.ac.uk/study/courses/postgraduate/taught/reservoir_engineering/","Reservoir Engineering","0"},
		{"94","http://www.abdn.ac.uk/study/courses/postgraduate/taught/safety/","Safety & Reliability Engineering for Oil & Gas","0"},
		{"95","http://www.abdn.ac.uk/study/courses/postgraduate/taught/subsea_engineering/","Subsea Engineering","0"},
		{"96","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oil_gas_structural/","Oil & Gas Structural Engineering","0"},
		{"97","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oilgas/","Oil and Gas Engineering","0"},
		{"98","http://www.abdn.ac.uk/study/courses/postgraduate/taught/peteng/","Petroleum Engineering","0"},
		{"99","http://www.abdn.ac.uk/study/courses/postgraduate/taught/process_safety/","Process Safety","0"},
		{"100","http://www.abdn.ac.uk/study/courses/postgraduate/taught/proj_man/","Project Management (campus based or distance learning)","0"},
		{"101","http://www.abdn.ac.uk/study/courses/postgraduate/taught/renewables/","Renewable Energy Engineering","0"},
		{"102","http://www.abdn.ac.uk/study/courses/postgraduate/taught/reservoir_engineering/","Reservoir Engineering","0"},
		{"103","http://www.abdn.ac.uk/study/courses/postgraduate/taught/safety/","Safety & Reliability Engineering for Oil & Gas","0"},
		{"104","http://www.abdn.ac.uk/study/courses/postgraduate/taught/subsea_engineering/","Subsea Engineering","0"},
		{"105","http://www.abdn.ac.uk/study/courses/postgraduate/taught/creative_writing/","Creative Writing","0"},
		{"106","http://www.abdn.ac.uk/study/courses/postgraduate/taught/eng_lit/","English Literary  Studies","0"},
		{"107","http://www.abdn.ac.uk/study/courses/postgraduate/taught/irish_scottish/","Irish and Scottish Literature","0"},
		{"108","http://www.abdn.ac.uk/study/courses/postgraduate/taught/procom/","Professional Communication","0"},
		{"109","http://www.abdn.ac.uk/study/courses/postgraduate/taught/translation_studies/","Translation Studies, MSc","0"},
		{"110","http://www.abdn.ac.uk/study/courses/postgraduate/taught/visual_cult/","Visual Culture","0"},
		{"111","http://www.abdn.ac.uk/study/courses/postgraduate/taught/analytical_chemistry/","Analytical Chemistry","0"},
		{"112","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ecology/","Ecology and Conservation","0"},
		{"113","http://www.abdn.ac.uk/study/courses/postgraduate/taught/enviro_partnership_management/","Environmental Partnership Management","0"},
		{"114","http://www.abdn.ac.uk/study/courses/postgraduate/taught/env_sci/","Environmental Science","0"},
		{"115","http://www.abdn.ac.uk/study/courses/postgraduate/taught/gis/","Geographical Information Systems","0"},
		{"116","http://www.abdn.ac.uk/study/courses/postgraduate/taught/land_econ/","Land Economy (Rural Surveying, RICS accredited)","0"},
		{"117","http://www.abdn.ac.uk/study/courses/postgraduate/taught/analytical_chemistry/","Analytical Chemistry","0"},
		{"118","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ecology/","Ecology and Conservation","0"},
		{"119","http://www.abdn.ac.uk/study/courses/postgraduate/taught/enviro_partnership_management/","Environmental Partnership Management","0"},
		{"120","http://www.abdn.ac.uk/study/courses/postgraduate/taught/env_sci/","Environmental Science","0"},
		{"121","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ethno_folk/","Ethnology & Folklore","0"},
		{"122","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_anthro/","Social Anthropology","0"},
		{"123","http://www.abdn.ac.uk/study/courses/postgraduate/taught/visual_cult/","Visual Culture","0"},
		{"124","http://www.abdn.ac.uk/study/courses/postgraduate/taught/finance_accounting/","Accounting and Finance","0"},
		{"125","http://www.abdn.ac.uk/study/courses/postgraduate/taught/finance/","Finance (MRes)","0"},
		{"126","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fin_man/","Finance & Investment Management","0"},
		{"127","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fin-realestate/","Finance and Real Estate","0"},
		{"128","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_business_energy/","Petroleum, Energy Economics and Finance","0"},
		{"129","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ethno_folk/","Ethnology & Folklore","0"},
		{"130","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_anthro/","Social Anthropology","0"},
		{"131","http://www.abdn.ac.uk/study/courses/postgraduate/taught/forestry/","Forestry","0"},
		{"132","http://www.abdn.ac.uk/study/courses/postgraduate/taught/visual_cult/","Visual Culture","0"},
		{"133","http://www.abdn.ac.uk/study/courses/postgraduate/taught/sex_gender_violence/","Sex, Gender, Violence: Contemporary Critical Approaches","0"},
		{"134","http://www.abdn.ac.uk/study/courses/postgraduate/taught/genetics/","Genetics","0"},
		{"135","http://www.abdn.ac.uk/study/courses/postgraduate/taught/data_analysis/","Data Analysis, Visualisation and Communication","0"},
		{"136","http://www.abdn.ac.uk/study/courses/postgraduate/taught/enviro_partnership_management/","Environmental Partnership Management","0"},
		{"137","http://www.abdn.ac.uk/study/courses/postgraduate/taught/gis/","Geographical Information Systems","0"},
		{"138","http://www.abdn.ac.uk/study/courses/postgraduate/taught/land_econ/","Land Economy (Rural Surveying, RICS accredited)","0"},
		{"139","http://www.abdn.ac.uk/study/courses/postgraduate/taught/geophysics/","Geophysics","0"},
		{"140","http://www.abdn.ac.uk/study/courses/postgraduate/taught/petrol/","Integrated Petroleum Geoscience","0"},
		{"141","http://www.abdn.ac.uk/study/courses/postgraduate/taught/hydrocarbon/","Oil and Gas Enterprise Management","0"},
		{"142","http://www.abdn.ac.uk/study/courses/postgraduate/taught/petrophysics/","Petrophysics and Formation Evaluation","0"},
		{"143","http://www.abdn.ac.uk/study/courses/postgraduate/taught/reservoir_engineering/","Reservoir Engineering","0"},
		{"144","http://www.abdn.ac.uk/study/courses/postgraduate/taught/visual_cult/","Visual Culture","0"},
		{"145","http://www.abdn.ac.uk/study/courses/postgraduate/taught/health_econ/","Health Economics","0"},
		{"146","http://www.abdn.ac.uk/study/courses/postgraduate/taught/physician_assistant/","Physician Associate Studies","0"},
		{"147","http://www.abdn.ac.uk/study/courses/postgraduate/taught/research-methods-health/","Research Methods for Health","0"},
		{"148","http://www.abdn.ac.uk/study/courses/postgraduate/taught/latin_american/","Latin American Studies","0"},
		{"149","http://www.abdn.ac.uk/study/courses/postgraduate/taught/visual_cult/","Visual Culture","0"},
		{"150","http://www.abdn.ac.uk/study/courses/postgraduate/taught/church_hist/","Church History","0"},
		{"151","http://www.abdn.ac.uk/study/courses/postgraduate/taught/irish_and_scottish/","Irish and Scottish History","0"},
		{"152","http://www.abdn.ac.uk/study/courses/postgraduate/taught/medieval-early-mod/","Medieval and Early Modern Studies","0"},
		{"153","http://www.abdn.ac.uk/study/courses/postgraduate/taught/modern_history/","Modern History","0"},
		{"154","http://www.abdn.ac.uk/study/courses/postgraduate/taught/art_business/","Art and Business","0"},
		{"155","http://www.abdn.ac.uk/study/courses/postgraduate/taught/immunology/","Immunology","0"},
		{"156","http://www.abdn.ac.uk/study/courses/postgraduate/taught/european_politics/","European Politics and Society","0"},
		{"157","http://www.abdn.ac.uk/study/courses/postgraduate/taught/globalization/","Globalization","0"},
		{"158","http://www.abdn.ac.uk/study/courses/postgraduate/taught/intlaw_ir/","International Law and International Relations (LLM)","0"},
		{"159","http://www.abdn.ac.uk/study/courses/postgraduate/taught/international_relations/","International Relations","0"},
		{"160","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ir_law/","International Relations and International Law","0"},
		{"161","http://www.abdn.ac.uk/study/courses/postgraduate/taught/latin_american/","Latin American Studies","0"},
		{"162","http://www.abdn.ac.uk/study/courses/postgraduate/taught/pol_res/","Political Research","0"},
		{"163","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strat_studs/","Strategic Studies","0"},
		{"164","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_studies/","Strategic Studies and International Law","0"},
		{"165","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_management/","Strategic Studies and Management","0"},
		{"166","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fin_man/","Finance & Investment Management","0"},
		{"167","http://www.abdn.ac.uk/study/courses/postgraduate/taught/medieval-early-mod/","Medieval and Early Modern Studies","0"},
		{"168","http://www.abdn.ac.uk/study/courses/postgraduate/taught/land_econ/","Land Economy (Rural Surveying, RICS accredited)","0"},
		{"169","http://www.abdn.ac.uk/study/courses/postgraduate/taught/crim_just/","Criminal Justice (LLM)","0"},
		{"170","http://www.abdn.ac.uk/study/courses/postgraduate/taught/crim_rights/","Criminal Justice & Human Rights (LLM)","0"},
		{"171","http://www.abdn.ac.uk/study/courses/postgraduate/taught/law_susdev/","Energy and Environmental Law (LLM)","0"},
		{"172","http://www.abdn.ac.uk/study/courses/postgraduate/taught/eng_law/","Energy Law (LLM)","0"},
		{"173","http://www.abdn.ac.uk/study/courses/postgraduate/taught/energypoliticslaw/","Energy Politics and Law","0"},
		{"174","http://www.abdn.ac.uk/study/courses/postgraduate/taught/gen_law/","General Law (LLM)","0"},
		{"175","http://www.abdn.ac.uk/study/courses/postgraduate/taught/human_right/","Human Rights (LLM)","0"},
		{"176","http://www.abdn.ac.uk/study/courses/postgraduate/taught/human_crim/","Human Rights and Criminal Justice (LLM)","0"},
		{"177","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_arbitration/","International Arbitration (PgDip)","0"},
		{"178","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_comlaw/","International Commercial Law with Dissertation (LLM)","0"},
		{"179","http://www.abdn.ac.uk/study/courses/postgraduate/taught/iclps/","International Commercial Law with Professional Skills (LLM)","0"},
		{"180","http://www.abdn.ac.uk/study/courses/postgraduate/taught/int_law/","International Law (LLM)","0"},
		{"181","http://www.abdn.ac.uk/study/courses/postgraduate/taught/intlaw_ir/","International Law and International Relations (LLM)","0"},
		{"182","http://www.abdn.ac.uk/study/courses/postgraduate/taught/intlaw_str/","International Law and Strategic Studies (LLM)","0"},
		{"183","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ir_law/","International Relations and International Law","0"},
		{"184","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oglps/","Oil & Gas Law with Professional Skills (LLM)","0"},
		{"185","http://www.abdn.ac.uk/study/courses/postgraduate/taught/oil_gas_law/","Oil and Gas Law with Dissertation (LLM)","0"},
		{"186","http://www.abdn.ac.uk/study/courses/postgraduate/taught/private_international_law/","Private International Law (LLM)","0"},
		{"187","http://www.abdn.ac.uk/study/courses/postgraduate/taught/legal_pract/","Professional Legal Practice","0"},
		{"188","http://www.abdn.ac.uk/study/courses/postgraduate/taught/public_international_law/","Public International Law (LLM)","0"},
		{"189","http://www.abdn.ac.uk/study/courses/postgraduate/taught/procom/","Professional Communication","0"},
		{"190","http://www.abdn.ac.uk/study/courses/postgraduate/taught/tesol_linguistics/","TESOL, MSc","0"},
		{"191","http://www.abdn.ac.uk/study/courses/postgraduate/taught/creative_writing/","Creative Writing","0"},
		{"192","http://www.abdn.ac.uk/study/courses/postgraduate/taught/eng_lit/","English Literary  Studies","0"},
		{"193","http://www.abdn.ac.uk/study/courses/postgraduate/taught/literature_science_medicine/","Literature, Science and Medicine","0"},
		{"194","http://www.abdn.ac.uk/study/courses/postgraduate/taught/novel_the/","Novel, The","0"},
		{"195","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_admin/","MBA Business Administration","0"},
		{"196","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_admin_jan/","MBA Business Administration (January Entry)","0"},
		{"197","http://www.abdn.ac.uk/study/courses/postgraduate/taught/mba_energy/","MBA Energy Management","0"},
		{"198","http://www.abdn.ac.uk/study/courses/postgraduate/taught/business_research/","Business Research","0"},
		{"199","http://www.abdn.ac.uk/study/courses/postgraduate/taught/enviro_partnership_management/","Environmental Partnership Management","0"},
		{"200","http://www.abdn.ac.uk/study/courses/postgraduate/taught/finance/","Finance (MRes)","0"},
		{"201","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fin_man/","Finance & Investment Management","0"},
		{"202","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_man/","International Business Management","0"},
		{"203","http://www.abdn.ac.uk/study/courses/postgraduate/taught/consultancy/","Management Consultancy","0"},
		{"204","http://www.abdn.ac.uk/study/courses/postgraduate/taught/marketing_management/","Marketing Management","0"},
		{"205","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_admin/","MBA Business Administration","0"},
		{"206","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bus_admin_jan/","MBA Business Administration (January Entry)","0"},
		{"207","http://www.abdn.ac.uk/study/courses/postgraduate/taught/mba_energy/","MBA Energy Management","0"},
		{"208","http://www.abdn.ac.uk/study/courses/postgraduate/taught/hydrocarbon/","Oil and Gas Enterprise Management","0"},
		{"209","http://www.abdn.ac.uk/study/courses/postgraduate/taught/proj_man/","Project Management (campus based or distance learning)","0"},
		{"210","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_management/","Strategic Studies and Management","0"},
		{"211","http://www.abdn.ac.uk/study/courses/postgraduate/taught/fish/","Applied Marine and Fisheries Ecology","0"},
		{"212","http://www.abdn.ac.uk/study/courses/postgraduate/taught/env_sci/","Environmental Science","0"},
		{"213","http://www.abdn.ac.uk/study/courses/postgraduate/taught/digital_marketing/","Digital Marketing Leadership  (Online MSc degree)","0"},
		{"214","http://www.abdn.ac.uk/study/courses/postgraduate/taught/marketing_management/","Marketing Management","0"},
		{"215","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_imag/","Medical Imaging","0"},
		{"216","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_phys/","Medical Physics","0"},
		{"217","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_imag/","Medical Imaging","0"},
		{"218","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_phys/","Medical Physics","0"},
		{"219","http://www.abdn.ac.uk/study/courses/postgraduate/taught/biobusiness_medical/","Bio-Business and Medical Sciences","0"},
		{"220","http://www.abdn.ac.uk/study/courses/postgraduate/taught/clin_pharm/","Clinical Pharmacology","0"},
		{"221","http://www.abdn.ac.uk/study/courses/postgraduate/taught/drug_discovery/","Drug Discovery (MRes)","0"},
		{"222","http://www.abdn.ac.uk/study/courses/postgraduate/taught/drug_disc_dev/","Drug Discovery and Development","0"},
		{"223","http://www.abdn.ac.uk/study/courses/postgraduate/taught/immunology/","Immunology","0"},
		{"224","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_imag/","Medical Imaging","0"},
		{"225","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_phys/","Medical Physics","0"},
		{"226","http://www.abdn.ac.uk/study/courses/postgraduate/taught/medical-research-skills/","Medical Research Skills","0"},
		{"227","http://www.abdn.ac.uk/study/courses/postgraduate/taught/stratified_med/","Stratified Medicine and Pharmacological Innovation","0"},
		{"228","http://www.abdn.ac.uk/study/courses/postgraduate/taught/microbiology/","Microbiology","0"},
		{"229","http://www.abdn.ac.uk/study/courses/postgraduate/taught/master_music/","Music","0"},
		{"230","http://www.abdn.ac.uk/study/courses/postgraduate/taught/sonic_arts/","Sonic Arts","0"},
		{"231","http://www.abdn.ac.uk/study/courses/postgraduate/taught/vocal/","Vocal Music","0"},
		{"232","http://www.abdn.ac.uk/study/courses/postgraduate/taught/human_nutrition/","Human Nutrition","0"},
		{"233","http://www.abdn.ac.uk/study/courses/postgraduate/taught/geophysics/","Geophysics","0"},
		{"234","http://www.abdn.ac.uk/study/courses/postgraduate/taught/petrol/","Integrated Petroleum Geoscience","0"},
		{"235","http://www.abdn.ac.uk/study/courses/postgraduate/taught/hydrocarbon/","Oil and Gas Enterprise Management","0"},
		{"236","http://www.abdn.ac.uk/study/courses/postgraduate/taught/petrophysics/","Petrophysics and Formation Evaluation","0"},
		{"237","http://www.abdn.ac.uk/study/courses/postgraduate/taught/reservoir_engineering/","Reservoir Engineering","0"},
		{"238","http://www.abdn.ac.uk/study/courses/postgraduate/taught/geophysics/","Geophysics","0"},
		{"239","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_imag/","Medical Imaging","0"},
		{"240","http://www.abdn.ac.uk/study/courses/postgraduate/taught/med_phys/","Medical Physics","0"},
		{"241","http://www.abdn.ac.uk/study/courses/postgraduate/taught/env_sci/","Environmental Science","0"},
		{"242","http://www.abdn.ac.uk/study/courses/postgraduate/taught/forestry/","Forestry","0"},
		{"243","http://www.abdn.ac.uk/study/courses/postgraduate/taught/energypoliticslaw/","Energy Politics and Law","0"},
		{"244","http://www.abdn.ac.uk/study/courses/postgraduate/taught/european_politics/","European Politics and Society","0"},
		{"245","http://www.abdn.ac.uk/study/courses/postgraduate/taught/globalization/","Globalization","0"},
		{"246","http://www.abdn.ac.uk/study/courses/postgraduate/taught/international_relations/","International Relations","0"},
		{"247","http://www.abdn.ac.uk/study/courses/postgraduate/taught/latin_american/","Latin American Studies","0"},
		{"248","http://www.abdn.ac.uk/study/courses/postgraduate/taught/pol_res/","Political Research","0"},
		{"249","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strat_studs/","Strategic Studies","0"},
		{"250","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_studies/","Strategic Studies and International Law","0"},
		{"251","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_management/","Strategic Studies and Management","0"},
		{"252","http://www.abdn.ac.uk/study/courses/postgraduate/taught/proj_man/","Project Management (campus based or distance learning)","0"},
		{"253","http://www.abdn.ac.uk/study/courses/postgraduate/taught/healthpsy/","Health Psychology","0"},
		{"254","http://www.abdn.ac.uk/study/courses/postgraduate/taught/psychstuds/","Psychological Studies (MSc)","0"},
		{"255","http://www.abdn.ac.uk/study/courses/postgraduate/taught/psych/","Psychology","0"},
		{"256","http://www.abdn.ac.uk/study/courses/postgraduate/taught/health_econ/","Health Economics","0"},
		{"257","http://www.abdn.ac.uk/study/courses/postgraduate/taught/real_estate2/","Real Estate","0"},
		{"258","http://www.abdn.ac.uk/study/courses/postgraduate/taught/religion_society/","Religion and Society","0"},
		{"259","http://www.abdn.ac.uk/study/courses/postgraduate/taught/islamic_studies/","Islamic Studies","0"},
		{"260","http://www.abdn.ac.uk/study/courses/postgraduate/taught/religious_studies/","Religious Studies","0"},
		{"261","http://www.abdn.ac.uk/study/courses/postgraduate/taught/medical-research-skills/","Medical Research Skills","0"},
		{"262","http://www.abdn.ac.uk/study/courses/postgraduate/taught/pol_res/","Political Research","0"},
		{"263","http://www.abdn.ac.uk/study/courses/postgraduate/taught/research-methods-health/","Research Methods for Health","0"},
		{"264","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_res/","Social Research","0"},
		{"265","http://www.abdn.ac.uk/study/courses/postgraduate/taught/medieval-early-mod/","Medieval and Early Modern Studies","0"},
		{"266","http://www.abdn.ac.uk/study/courses/postgraduate/taught/scandinavian_studies/","Scandinavian Studies","0"},
		{"267","http://www.abdn.ac.uk/study/courses/postgraduate/taught/irish_and_scottish/","Irish and Scottish History","0"},
		{"268","http://www.abdn.ac.uk/study/courses/postgraduate/taught/irish_scottish/","Irish and Scottish Literature","0"},
		{"269","http://www.abdn.ac.uk/study/courses/postgraduate/taught/celtic_studies/","Celtic and Anglo Saxon Studies","0"},
		{"270","http://www.abdn.ac.uk/study/courses/postgraduate/taught/medieval-early-mod/","Medieval and Early Modern Studies","0"},
		{"271","http://www.abdn.ac.uk/study/courses/postgraduate/taught/european_politics/","European Politics and Society","0"},
		{"272","http://www.abdn.ac.uk/study/courses/postgraduate/taught/peace_processes/","Global Conflict and Peace Processes","0"},
		{"273","http://www.abdn.ac.uk/study/courses/postgraduate/taught/globalization/","Globalization","0"},
		{"274","http://www.abdn.ac.uk/study/courses/postgraduate/taught/justice_peacebuilding/","Post-Conflict Justice and Peacebuilding","0"},
		{"275","http://www.abdn.ac.uk/study/courses/postgraduate/taught/radicalization_resistance/","Radicalization and Resistance","0"},
		{"276","http://www.abdn.ac.uk/study/courses/postgraduate/taught/refugee_displacement/","Refugee and Displacement Studies","0"},
		{"277","http://www.abdn.ac.uk/study/courses/postgraduate/taught/religion_society/","Religion and Society","0"},
		{"278","http://www.abdn.ac.uk/study/courses/postgraduate/taught/sex_gender_violence/","Sex, Gender, Violence: Contemporary Critical Approaches","0"},
		{"279","http://www.abdn.ac.uk/study/courses/postgraduate/taught/soc_res/","Social Research","0"},
		{"280","http://www.abdn.ac.uk/study/courses/postgraduate/taught/sociology/","Sociology","0"},
		{"281","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strat_studs/","Strategic Studies","0"},
		{"282","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_studies/","Strategic Studies and International Law","0"},
		{"283","http://www.abdn.ac.uk/study/courses/postgraduate/taught/strategic_management/","Strategic Studies and Management","0"},
		{"284","http://www.abdn.ac.uk/study/courses/postgraduate/taught/land_econ/","Land Economy (Rural Surveying, RICS accredited)","0"},
		{"285","http://www.abdn.ac.uk/study/courses/postgraduate/taught/bib_theol/","Biblical Studies","0"},
		{"286","http://www.abdn.ac.uk/study/courses/postgraduate/taught/church_hist/","Church History","0"},
		{"287","http://www.abdn.ac.uk/study/courses/postgraduate/taught/ministry-studies/","Ministry Studies","0"},
		{"288","http://www.abdn.ac.uk/study/courses/postgraduate/taught/systematic_theology/","Systematic Theology","0"},
		{"289","http://www.abdn.ac.uk/study/courses/postgraduate/taught/theological_ethics/","Theological Ethics","0"},
		{"290","http://www.abdn.ac.uk/study/courses/postgraduate/research/accountancy/","Accountancy (MPhil, PhD)","0"},
		{"291","http://www.abdn.ac.uk/study/courses/postgraduate/research/economics/","Economics (MPhil, PhD)","0"},
		{"292","http://www.abdn.ac.uk/study/courses/postgraduate/research/finance/","Finance (MPhil, PhD)","0"},
		{"293","http://www.abdn.ac.uk/study/courses/postgraduate/research/anthropology/","Anthropology (MPhil, PhD)","0"},
		{"294","http://www.abdn.ac.uk/study/courses/postgraduate/research/centre_for_citizenship/","Citizenship, Civil Society and Rule of Law, Centre for","0"},
		{"295","http://www.abdn.ac.uk/study/courses/postgraduate/research/elph_int/","The Elphinstone Institute (MLitt Res, MPhil, PhD)","0"},
		{"296","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"297","http://www.abdn.ac.uk/study/courses/postgraduate/research/archaeology/","Archaeology (MSc, PhD)","0"},
		{"298","http://www.abdn.ac.uk/study/courses/postgraduate/research/biological_sciences/","Biological & Environmental Sciences","0"},
		{"299","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"300","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"301","http://www.abdn.ac.uk/study/courses/postgraduate/research/accountancy/","Accountancy (MPhil, PhD)","0"},
		{"302","http://www.abdn.ac.uk/study/courses/postgraduate/research/economics/","Economics (MPhil, PhD)","0"},
		{"303","http://www.abdn.ac.uk/study/courses/postgraduate/research/finance/","Finance (MPhil, PhD)","0"},
		{"304","http://www.abdn.ac.uk/study/courses/postgraduate/research/man_studs/","Management Studies (MRes Business Management, MPhil, PhD in Management)","0"},
		{"305","http://www.abdn.ac.uk/study/courses/postgraduate/research/real_estate/","Real Estate (MRes, MPhil, PhD)","0"},
		{"306","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"307","http://www.abdn.ac.uk/study/courses/postgraduate/research/celtic_anglo%20saxon/","Celtic & Anglo-Saxon Studies (MLitt, PhD)","0"},
		{"308","http://www.abdn.ac.uk/study/courses/postgraduate/research/chemistry/","Chemistry (MSc, PhD)","0"},
		{"309","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"310","http://www.abdn.ac.uk/study/courses/postgraduate/research/comp_sci/","Computing Science (MSc, MPhil, PhD)","0"},
		{"311","http://www.abdn.ac.uk/study/courses/postgraduate/research/elph_int/","The Elphinstone Institute (MLitt Res, MPhil, PhD)","0"},
		{"312","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"313","http://www.abdn.ac.uk/study/courses/postgraduate/research/spirit_health/","Spirituality, Health and Disability, Centre for (PhD)","0"},
		{"314","http://www.abdn.ac.uk/study/courses/postgraduate/research/divinity/","Divinity (Ph D)","0"},
		{"315","http://www.abdn.ac.uk/study/courses/postgraduate/research/biological_sciences/","Biological & Environmental Sciences","0"},
		{"316","http://www.abdn.ac.uk/study/courses/postgraduate/research/economics/","Economics (MPhil, PhD)","0"},
		{"317","http://www.abdn.ac.uk/study/courses/postgraduate/research/euro_market/","European Labour Market Research, Centre for (MPhil, PhD)","0"},
		{"318","http://www.abdn.ac.uk/study/courses/postgraduate/research/education/","Education (PhD)","0"},
		{"319","http://www.abdn.ac.uk/study/courses/postgraduate/research/energy_law/","Energy Law, Centre for (PhD, MPhil, LLM)","0"},
		{"320","http://www.abdn.ac.uk/study/courses/postgraduate/research/engineering/","Engineering (MSc, PhD, EngD)","0"},
		{"321","http://www.abdn.ac.uk/study/courses/postgraduate/research/geology/","Geology & Petroleum Geology (MSc, PhD)","0"},
		{"322","http://www.abdn.ac.uk/study/courses/postgraduate/research/doc_engineering/","Doctor of Engineering Programme (EngD)","0"},
		{"323","http://www.abdn.ac.uk/study/courses/postgraduate/research/engineering/","Engineering (MSc, PhD, EngD)","0"},
		{"324","http://www.abdn.ac.uk/study/courses/postgraduate/research/english/","English, Film & Visual Culture and Linguistics (Language & Literature) (MLitt, MPhil, PhD)","0"},
		{"325","http://www.abdn.ac.uk/study/courses/postgraduate/research/novel/","Novel, Centre for the (PhD, MLitt by Research)","0"},
		{"326","http://www.abdn.ac.uk/study/courses/postgraduate/research/biological_sciences/","Biological & Environmental Sciences","0"},
		{"327","http://www.abdn.ac.uk/study/courses/postgraduate/research/env_health/","Environmental Health (MSc, PhD (occupational hygiene, occupational/environmental medicine))","0"},
		{"328","http://www.abdn.ac.uk/study/courses/postgraduate/research/environmental_science/","Environmental Science","0"},
		{"329","http://www.abdn.ac.uk/study/courses/postgraduate/research/geography/","Geography & Environment (MRes, MSc by research, PhD)","0"},
		{"330","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"331","http://www.abdn.ac.uk/study/courses/postgraduate/research/biological_sciences/","Biological & Environmental Sciences","0"},
		{"332","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"333","http://www.abdn.ac.uk/study/courses/postgraduate/research/elph_int/","The Elphinstone Institute (MLitt Res, MPhil, PhD)","0"},
		{"334","http://www.abdn.ac.uk/study/courses/postgraduate/research/english/","English, Film & Visual Culture and Linguistics (Language & Literature) (MLitt, MPhil, PhD)","0"},
		{"335","http://www.abdn.ac.uk/study/courses/postgraduate/research/finance/","Finance (MPhil, PhD)","0"},
		{"336","http://www.abdn.ac.uk/study/courses/postgraduate/research/elph_int/","The Elphinstone Institute (MLitt Res, MPhil, PhD)","0"},
		{"337","http://www.abdn.ac.uk/study/courses/postgraduate/research/french/","French (MLitt, PhD)","0"},
		{"338","http://www.abdn.ac.uk/study/courses/postgraduate/research/gender_studies/","Gender Studies, Centre for (MPhil, PhD)","0"},
		{"339","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"340","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"341","http://www.abdn.ac.uk/study/courses/postgraduate/research/geography/","Geography & Environment (MRes, MSc by research, PhD)","0"},
		{"342","http://www.abdn.ac.uk/study/courses/postgraduate/research/geology/","Geology & Petroleum Geology (MSc, PhD)","0"},
		{"343","http://www.abdn.ac.uk/study/courses/postgraduate/research/german/","German (MLitt, MPhil, PhD)","0"},
		{"344","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"345","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"346","http://www.abdn.ac.uk/study/courses/postgraduate/research/rowett/","Nutrition and Health","0"},
		{"347","http://www.abdn.ac.uk/study/courses/postgraduate/research/spirit_health/","Spirituality, Health and Disability, Centre for (PhD)","0"},
		{"348","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"349","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"350","http://www.abdn.ac.uk/study/courses/postgraduate/research/psychology/","Psychology","0"},
		{"351","http://www.abdn.ac.uk/study/courses/postgraduate/research/hisp_studs/","Hispanic Studies (PhD)","0"},
		{"352","http://www.abdn.ac.uk/study/courses/postgraduate/research/history/","History (Ph D)","0"},
		{"353","http://www.abdn.ac.uk/study/courses/postgraduate/research/hist_art/","History of Art (PhD)","0"},
		{"354","http://www.abdn.ac.uk/study/courses/postgraduate/research/euro_market/","European Labour Market Research, Centre for (MPhil, PhD)","0"},
		{"355","http://www.abdn.ac.uk/study/courses/postgraduate/research/man_studs/","Management Studies (MRes Business Management, MPhil, PhD in Management)","0"},
		{"356","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"357","http://www.abdn.ac.uk/study/courses/postgraduate/research/economics/","Economics (MPhil, PhD)","0"},
		{"358","http://www.abdn.ac.uk/study/courses/postgraduate/research/finance/","Finance (MPhil, PhD)","0"},
		{"359","http://www.abdn.ac.uk/study/courses/postgraduate/research/geography/","Geography & Environment (MRes, MSc by research, PhD)","0"},
		{"360","http://www.abdn.ac.uk/study/courses/postgraduate/research/energy_law/","Energy Law, Centre for (PhD, MPhil, LLM)","0"},
		{"361","http://www.abdn.ac.uk/study/courses/postgraduate/research/law/","Law (LLM, MPhil, PhD)","0"},
		{"362","http://www.abdn.ac.uk/study/courses/postgraduate/research/property_law/","Property Law, Centre for (PhD, MPhil)","0"},
		{"363","http://www.abdn.ac.uk/study/courses/postgraduate/research/english/","English, Film & Visual Culture and Linguistics (Language & Literature) (MLitt, MPhil, PhD)","0"},
		{"364","http://www.abdn.ac.uk/study/courses/postgraduate/research/english/","English, Film & Visual Culture and Linguistics (Language & Literature) (MLitt, MPhil, PhD)","0"},
		{"365","http://www.abdn.ac.uk/study/courses/postgraduate/research/novel/","Novel, Centre for the (PhD, MLitt by Research)","0"},
		{"366","http://www.abdn.ac.uk/study/courses/postgraduate/research/accountancy/","Accountancy (MPhil, PhD)","0"},
		{"367","http://www.abdn.ac.uk/study/courses/postgraduate/research/economics/","Economics (MPhil, PhD)","0"},
		{"368","http://www.abdn.ac.uk/study/courses/postgraduate/research/euro_market/","European Labour Market Research, Centre for (MPhil, PhD)","0"},
		{"369","http://www.abdn.ac.uk/study/courses/postgraduate/research/finance/","Finance (MPhil, PhD)","0"},
		{"370","http://www.abdn.ac.uk/study/courses/postgraduate/research/man_studs/","Management Studies (MRes Business Management, MPhil, PhD in Management)","0"},
		{"371","http://www.abdn.ac.uk/study/courses/postgraduate/research/real_estate/","Real Estate (MRes, MPhil, PhD)","0"},
		{"372","http://www.abdn.ac.uk/study/courses/postgraduate/research/biological_sciences/","Biological & Environmental Sciences","0"},
		{"373","http://www.abdn.ac.uk/study/courses/postgraduate/research/man_studs/","Management Studies (MRes Business Management, MPhil, PhD in Management)","0"},
		{"374","http://www.abdn.ac.uk/study/courses/postgraduate/research/maths/","Mathematical Sciences (PhD)","0"},
		{"375","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"376","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"377","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"378","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"379","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"380","http://www.abdn.ac.uk/study/courses/postgraduate/research/mod_thought/","Modern Thought, Centre for (MLitt by Research, PhD)","0"},
		{"381","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"382","http://www.abdn.ac.uk/study/courses/postgraduate/research/music/","Music (MPhil, PhD)","0"},
		{"383","http://www.abdn.ac.uk/study/courses/postgraduate/research/psychology/","Psychology","0"},
		{"384","http://www.abdn.ac.uk/study/courses/postgraduate/research/rowett/","Nutrition and Health","0"},
		{"385","http://www.abdn.ac.uk/study/courses/postgraduate/research/rowett/","Nutrition and Health","0"},
		{"386","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"387","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"388","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"389","http://www.abdn.ac.uk/study/courses/postgraduate/research/geology/","Geology & Petroleum Geology (MSc, PhD)","0"},
		{"390","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"391","http://www.abdn.ac.uk/study/courses/postgraduate/research/philos/","Philosophy (Ph D)","0"},
		{"392","http://www.abdn.ac.uk/study/courses/postgraduate/research/physics/","Physics (MSc, PhD)","0"},
		{"393","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"394","http://www.abdn.ac.uk/study/courses/postgraduate/research/biological_sciences/","Biological & Environmental Sciences","0"},
		{"395","http://www.abdn.ac.uk/study/courses/postgraduate/research/politics/","Politics & International Relations (PhD, MRes)","0"},
		{"396","http://www.abdn.ac.uk/study/courses/postgraduate/research/psychology/","Psychology","0"},
		{"397","http://www.abdn.ac.uk/study/courses/postgraduate/research/applied_health_sciences/","Applied Health Sciences","0"},
		{"398","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"399","http://www.abdn.ac.uk/study/courses/postgraduate/research/real_estate/","Real Estate (MRes, MPhil, PhD)","0"},
		{"400","http://www.abdn.ac.uk/study/courses/postgraduate/research/religious_studies/","Religious Studies (Ph D)","0"},
		{"401","http://www.abdn.ac.uk/study/courses/postgraduate/research/religious_studies/","Religious Studies (Ph D)","0"},
		{"402","http://www.abdn.ac.uk/study/courses/postgraduate/research/scandinavian_studies/","Scandinavian Studies, Centre for (MLitt by Research, MPhil, PhD)","0"},
		{"403","http://www.abdn.ac.uk/study/courses/postgraduate/research/celtic_anglo%20saxon/","Celtic & Anglo-Saxon Studies (MLitt, PhD)","0"},
		{"404","http://www.abdn.ac.uk/study/courses/postgraduate/research/sociology/","Sociology (MRes, MPhil, PhD)","0"},
		{"405","http://www.abdn.ac.uk/study/courses/postgraduate/research/spirit_health/","Spirituality, Health and Disability, Centre for (PhD)","0"},
		{"406","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"407","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"408","http://www.abdn.ac.uk/study/courses/postgraduate/research/geography/","Geography & Environment (MRes, MSc by research, PhD)","0"},
		{"409","http://www.abdn.ac.uk/study/courses/postgraduate/research/divinity/","Divinity (Ph D)","0"},
		{"410","http://www.abdn.ac.uk/study/courses/postgraduate/research/medical_sciences/","Medical Sciences","0"},
		{"411","http://www.abdn.ac.uk/study/courses/postgraduate/research/rowett/","Nutrition and Health","0"},
		{"412","http://www.abdn.ac.uk/study/courses/postgraduate/research/biological_sciences/","Biological & Environmental Sciences","0"}
	
	};
	
	public static String html2Str(String html) { 
		return html.replaceAll("<[^>]+>", "");
	}
	public static String HTMLFilter(String input) {
	    if (input == null) {
	        input = "";
	        return input;
	    }
	    input = input.trim().replaceAll("&amp;", "&");
	    input = input.trim().replaceAll("&lt;", "<");
	    input = input.trim().replaceAll("&gt;", ">");
	    input = input.trim().replaceAll("    ", " ");
	    input = input.trim().replaceAll("<br>", "\n");
	    input = input.trim().replaceAll("&nbsp;", "  ");
	    input = input.trim().replaceAll("&quot;", "\"");
	    input = input.trim().replaceAll("&#39;", "'");
	    input = input.trim().replaceAll("&#92;", "\\\\");
	    input = input.trim().replaceAll("&#...;", "");
	    input = input.trim().replaceAll("&#....;", "");
	    input = input.trim().replaceAll("&....;", "");
	    input = input.trim().replaceAll("&.....;", "");
	    return input;
	}
	
}
