package no6.ulster;

import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.config.CookieSpecs;
import org.apache.http.client.config.RequestConfig;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;
import org.htmlparser.Node;
import org.htmlparser.Parser;
import org.htmlparser.filters.AndFilter;
import org.htmlparser.filters.HasAttributeFilter;
import org.htmlparser.filters.TagNameFilter;
import org.htmlparser.tags.LinkTag;
import org.htmlparser.util.NodeList;

//http://www.ulster.ac.uk/courses/course-finder?query=&f.Level|Y=Undergraduate&start_rank=161
public class getURL {

	public static String url="http://www.ulster.ac.uk/courses/course-finder?query=&f.Level&Y=Undergraduate&start_rank=";
	public static void main(String[] args) throws Exception{
		RequestConfig requestConfig = RequestConfig.custom().setCookieSpec(CookieSpecs.STANDARD_STRICT).build();  
		CloseableHttpClient httpclient = HttpClients.custom().setDefaultRequestConfig(requestConfig).build();  
		int count=1;
		for(int i=0;i<=11;i++)
		{
			int index=1+i*40;
			//System.out.println(index);
			HttpGet httpGet = new HttpGet(url+index);
			HttpResponse response = httpclient.execute(httpGet);  
			HttpEntity entity = response.getEntity();
			String htmls=null;
			if (entity != null) { 
			    htmls=EntityUtils.toString(entity).replace("\t", " ");
			}
			Parser	parser=Parser.createParser(htmls, "utf-8");
	   	    AndFilter dFilter=new AndFilter(new TagNameFilter("div"),
	                   new HasAttributeFilter("id","course_list"));
	   	    NodeList nodes3=parser.extractAllNodesThatMatch(dFilter);
	   	    if(nodes3.size()>0)
	   	    {
	   	    	htmls=nodes3.elementAt(0).toHtml();
	   	    	parser=Parser.createParser(htmls, "utf-8");
		   	    AndFilter ProfessionNameFilter=new AndFilter(new TagNameFilter("a"),
		                   new HasAttributeFilter("href"));
		   	    NodeList nodes4=parser.extractAllNodesThatMatch(ProfessionNameFilter);
		   	    for(int j=0;j<nodes4.size();j++)
		   	    {
		   	    	LinkTag link=(LinkTag)nodes4.elementAt(j);
		   	    	if(link.getAttribute("href").contains("http://www.ulster.ac.uk/"))
		   	    	{//.replaceAll("<span[\\s\\S]*/span>","")
		   	    		String temp=link.toHtml();
		   	    		String type="";
		   	    		String level="";
		   	    		if(temp.contains("Undergraduate"))
		   	    		{
		   	    			level="Undergraduate";
		   	    		}
		   	    		else if(temp.contains("Postgraduate"))
		   	    		{
		   	    			level="Postgraduate";
		   	    		}
		   	    		System.out.println("{\""+count+"\",\""+link.getAttribute("href")+"\",\""+html2Str(temp.replaceAll("<span[\\s\\S]*/span>","")).replace("\r\n", "").trim()+"\",\""+level+"\",\"0\"},");
		                count++;
		   	    	}
		   	    	
		   	    }
	   	    }
	   	    	
	   	    
		    
		}
		//System.out.println("DONE.");
	}
	
	public static String[][] AllData={
		{"1","http://www.ulster.ac.uk/courses/course-finder/201617/accounting-8905","Accounting","Postgraduate","0"},
		{"2","http://www.ulster.ac.uk/courses/course-finder/201516/accounting-12334","Accounting","Postgraduate","0"},
		{"3","http://www.ulster.ac.uk/courses/course-finder/201617/accounting-pathways-9265","Accounting (Pathways)","Undergraduate","0"},
		{"4","http://www.ulster.ac.uk/courses/course-finder/201617/accounting-and-advertising-9516","Accounting and Advertising","Undergraduate","0"},
		{"5","http://www.ulster.ac.uk/courses/course-finder/201617/accounting-and-human-resource-management-9515","Accounting and Human Resource Management","Undergraduate","0"},
		{"6","http://www.ulster.ac.uk/courses/course-finder/201617/accounting-and-law-9266","Accounting and Law","Undergraduate","0"},
		{"7","http://www.ulster.ac.uk/courses/course-finder/201617/accounting-and-management-8904","Accounting and Management","Undergraduate","0"},
		{"8","http://www.ulster.ac.uk/courses/course-finder/201617/accounting-and-marketing-9514","Accounting and Marketing","Undergraduate","0"},
		{"9","http://www.ulster.ac.uk/courses/course-finder/201617/accounting-with-specialisms-9279","Accounting with Specialisms","Undergraduate","0"},
		{"10","http://www.ulster.ac.uk/courses/course-finder/201617/accounting-with-specialisms-12859","Accounting with Specialisms","Undergraduate","0"},
		{"11","http://www.ulster.ac.uk/courses/course-finder/201617/advanced-accounting-8986","Advanced Accounting","Postgraduate","0"},
		{"12","http://www.ulster.ac.uk/courses/course-finder/201617/advanced-composites-and-polymers-8857","Advanced Composites and Polymers","Postgraduate","0"},
		{"13","http://www.ulster.ac.uk/courses/course-finder/201617/advanced-composites-and-polymers-8872","Advanced Composites and Polymers","Postgraduate","0"},
		{"14","http://www.ulster.ac.uk/courses/course-finder/201617/advanced-composites-and-polymers-8873","Advanced Composites and Polymers","Postgraduate","0"},
		{"15","http://www.ulster.ac.uk/courses/course-finder/201617/advanced-composites-and-polymers-8858","Advanced Composites and Polymers","Postgraduate","0"},
		{"16","http://www.ulster.ac.uk/courses/course-finder/201617/advancing-practice-8832","Advancing Practice","Postgraduate","0"},
		{"17","http://www.ulster.ac.uk/courses/course-finder/201617/advertising-and-human-resource-management-9513","Advertising and Human Resource Management","Undergraduate","0"},
		{"18","http://www.ulster.ac.uk/courses/course-finder/201617/advertising-with-computing-9512","Advertising with Computing","Undergraduate","0"},
		{"19","http://www.ulster.ac.uk/courses/course-finder/201617/advertising-with-drama-9511","Advertising with Drama","Undergraduate","0"},
		{"20","http://www.ulster.ac.uk/courses/course-finder/201617/advertising-with-human-resource-management-9510","Advertising with Human Resource Management","Undergraduate","0"},
		{"21","http://www.ulster.ac.uk/courses/course-finder/201617/animation-9371","Animation","Undergraduate","0"},
		{"22","http://www.ulster.ac.uk/courses/course-finder/201617/applied-behaviour-analysis-9008","Applied Behaviour Analysis","Postgraduate","0"},
		{"23","http://www.ulster.ac.uk/courses/course-finder/201617/applied-biosciences-8907","Applied Biosciences","Undergraduate","0"},
		{"24","http://www.ulster.ac.uk/courses/course-finder/201617/applied-finance-8987","Applied Finance","Postgraduate","0"},
		{"25","http://www.ulster.ac.uk/courses/course-finder/201516/applied-finance-12417","Applied Finance","Postgraduate","0"},
		{"26","http://www.ulster.ac.uk/courses/course-finder/201617/applied-health-studies-12750","Applied Health Studies","Postgraduate","0"},
		{"27","http://www.ulster.ac.uk/courses/course-finder/201617/applied-health-studies-12751","Applied Health Studies","Undergraduate","0"},
		{"28","http://www.ulster.ac.uk/courses/course-finder/201617/applied-psychology-mental-health-and-psychological-therapies-8896","Applied Psychology (Mental Health and Psychological Therapies)","Postgraduate","0"},
		{"29","http://www.ulster.ac.uk/courses/course-finder/201617/applied-psychology-mental-health-and-psychological-therapies-8897","Applied Psychology (Mental Health and Psychological Therapies)","Postgraduate","0"},
		{"30","http://www.ulster.ac.uk/courses/course-finder/201617/architectural-engineering-12729","Architectural Engineering","Undergraduate","0"},
		{"31","http://www.ulster.ac.uk/courses/course-finder/201617/architectural-engineering-12731","Architectural Engineering","Undergraduate","0"},
		{"32","http://www.ulster.ac.uk/courses/course-finder/201617/architectural-technology-and-management-9369","Architectural Technology and Management","Undergraduate","0"},
		{"33","http://www.ulster.ac.uk/courses/course-finder/201617/architecture-9368","Architecture","Undergraduate","0"},
		{"34","http://www.ulster.ac.uk/courses/course-finder/201617/architecture-9367","Architecture","Undergraduate","0"},
		{"35","http://www.ulster.ac.uk/courses/course-finder/201617/art-and-design-12962","Art and Design","Postgraduate","0"},
		{"36","http://www.ulster.ac.uk/courses/course-finder/201516/art-and-design-12706","Art and Design","Postgraduate","0"},
		{"37","http://www.ulster.ac.uk/courses/course-finder/201516/bidding-for-success-12915","Bidding for Success","Postgraduate","0"},
		{"38","http://www.ulster.ac.uk/courses/course-finder/201516/biodiversity-management-12935","Biodiversity Management","Postgraduate","0"},
		{"39","http://www.ulster.ac.uk/courses/course-finder/201617/biology-9263","Biology","Undergraduate","0"},
		{"40","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-and-bio-industrial-sciences-12780","Biomedical and Bio-industrial Sciences (Subject to Approval)","Undergraduate","0"},
		{"41","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-and-healthcare-sciences-12779","Biomedical and Healthcare Sciences (Subject to Approval)","Undergraduate","0"},
		{"42","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-engineering-8861","Biomedical Engineering","Postgraduate","0"},
		{"43","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-engineering-8869","Biomedical Engineering","Postgraduate","0"},
		{"44","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-engineering-9311","Biomedical Engineering","Undergraduate","0"},
		{"45","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-engineering-8868","Biomedical Engineering","Postgraduate","0"},
		{"46","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-engineering-8862","Biomedical Engineering","Postgraduate","0"},
		{"47","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-professional-practice-9059","Biomedical Professional Practice","Postgraduate","0"},
		{"48","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-professional-practice-9058","Biomedical Professional Practice","Postgraduate","0"},
		{"49","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-science-9158","Biomedical Science","Postgraduate","0"},
		{"50","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-science-9159","Biomedical Science","Postgraduate","0"},
		{"51","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-science-12814","Biomedical Science","Undergraduate","0"},
		{"52","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-science-12894","Biomedical Science","Undergraduate","0"},
		{"53","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-science-with-dpp-pathology-9319","Biomedical Science with DPP (Pathology)","Undergraduate","0"},
		{"54","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-science-with-dpp-dias-12860","Biomedical Science with DPP/DIAS","Undergraduate","0"},
		{"55","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-sciences-12954","Biomedical Sciences","Postgraduate","0"},
		{"56","http://www.ulster.ac.uk/courses/course-finder/201516/biomedical-sciences-12696","Biomedical Sciences","Postgraduate","0"},
		{"57","http://www.ulster.ac.uk/courses/course-finder/201617/biomedical-sciences-12794","Biomedical Sciences (Subject to Approval)","Undergraduate","0"},
		{"58","http://www.ulster.ac.uk/courses/course-finder/201617/biotechnology-9267","Biotechnology","Undergraduate","0"},
		{"59","http://www.ulster.ac.uk/courses/course-finder/201617/bsc-hons-customer-contact-management-8882","BSc Hons Customer Contact Management","Undergraduate","0"},
		{"60","http://www.ulster.ac.uk/courses/course-finder/201516/bsc-hons-customer-contact-management-12311","BSc Hons Customer Contact Management","Undergraduate","0"},
		{"61","http://www.ulster.ac.uk/courses/course-finder/201516/building-information-modelling-12803","Building Information Modelling","Postgraduate","0"},
		{"62","http://www.ulster.ac.uk/courses/course-finder/201617/building-surveying-9057","Building Surveying","Undergraduate","0"},
		{"63","http://www.ulster.ac.uk/courses/course-finder/201617/building-surveying-9343","Building Surveying","Undergraduate","0"},
		{"64","http://www.ulster.ac.uk/courses/course-finder/201617/built-environment-12946","Built Environment","Postgraduate","0"},
		{"65","http://www.ulster.ac.uk/courses/course-finder/201516/built-environment-12680","Built Environment","Postgraduate","0"},
		{"66","http://www.ulster.ac.uk/courses/course-finder/201617/business-administration-8947","Business Administration","Undergraduate","0"},
		{"67","http://www.ulster.ac.uk/courses/course-finder/201617/business-administration-8998","Business Administration","Postgraduate","0"},
		{"68","http://www.ulster.ac.uk/courses/course-finder/201617/business-administration-8997","Business Administration","Postgraduate","0"},
		{"69","http://www.ulster.ac.uk/courses/course-finder/201617/business-administration-12895","Business Administration","Postgraduate","0"},
		{"70","http://www.ulster.ac.uk/courses/course-finder/201516/business-and-management-12646","Business and Management","Postgraduate","0"},
		{"71","http://www.ulster.ac.uk/courses/course-finder/201617/business-and-management-12942","Business and Management","Postgraduate","0"},
		{"72","http://www.ulster.ac.uk/courses/course-finder/201617/business-development-and-innovation-8894","Business Development and Innovation","Postgraduate","0"},
		{"73","http://www.ulster.ac.uk/courses/course-finder/201617/business-development-and-innovation-8895","Business Development and Innovation","Postgraduate","0"},
		{"74","http://www.ulster.ac.uk/courses/course-finder/201617/business-economics-9258","Business Economics","Undergraduate","0"},
		{"75","http://www.ulster.ac.uk/courses/course-finder/201617/business-economics-with-accounting-9404","Business Economics with Accounting","Undergraduate","0"},
		{"76","http://www.ulster.ac.uk/courses/course-finder/201617/business-economics-with-marketing-9405","Business Economics with Marketing","Undergraduate","0"},
		{"77","http://www.ulster.ac.uk/courses/course-finder/201617/business-improvement-8999","Business Improvement","Postgraduate","0"},
		{"78","http://www.ulster.ac.uk/courses/course-finder/201617/business-improvement-12717","Business Improvement","Postgraduate","0"},
		{"79","http://www.ulster.ac.uk/courses/course-finder/201516/business-improvement-12429","Business Improvement","Postgraduate","0"},
		{"80","http://www.ulster.ac.uk/courses/course-finder/201617/business-information-systems-9299","Business Information Systems","Undergraduate","0"},
		{"81","http://www.ulster.ac.uk/courses/course-finder/201617/business-studies-12801","Business Studies","Undergraduate","0"},
		{"82","http://www.ulster.ac.uk/courses/course-finder/201617/business-studies-12797","Business Studies","Undergraduate","0"},
		{"83","http://www.ulster.ac.uk/courses/course-finder/201617/business-studies-with-advertising-9508","Business Studies with Advertising","Undergraduate","0"},
		{"84","http://www.ulster.ac.uk/courses/course-finder/201617/business-studies-with-computing-9507","Business Studies with Computing","Undergraduate","0"},
		{"85","http://www.ulster.ac.uk/courses/course-finder/201617/business-studies-with-drama-9505","Business Studies with Drama","Undergraduate","0"},
		{"86","http://www.ulster.ac.uk/courses/course-finder/201617/business-studies-with-irish-9506","Business Studies with Irish","Undergraduate","0"},
		{"87","http://www.ulster.ac.uk/courses/course-finder/201617/celtic-studies-12958","Celtic Studies","Postgraduate","0"},
		{"88","http://www.ulster.ac.uk/courses/course-finder/201516/celtic-studies-12702","Celtic Studies","Postgraduate","0"},
		{"89","http://www.ulster.ac.uk/courses/course-finder/201516/ceramics-evening-class-wednesday-12920","Ceramics Evening Class Wednesday","","0"},
		{"90","http://www.ulster.ac.uk/courses/course-finder/201617/civic-leadership-and-community-planning-8981","Civic Leadership and Community Planning","Undergraduate","0"},
		{"91","http://www.ulster.ac.uk/courses/course-finder/201516/civic-leadership-and-community-planning-12411","Civic Leadership and Community Planning","Undergraduate","0"},
		{"92","http://www.ulster.ac.uk/courses/course-finder/201617/civil-engineering-9056","Civil Engineering","Undergraduate","0"},
		{"93","http://www.ulster.ac.uk/courses/course-finder/201617/civil-engineering-9303","Civil Engineering","Undergraduate","0"},
		{"94","http://www.ulster.ac.uk/courses/course-finder/201617/civil-engineering-9342","Civil Engineering","Undergraduate","0"},
		{"95","http://www.ulster.ac.uk/courses/course-finder/201617/civil-engineering-8982","Civil Engineering","Undergraduate","0"},
		{"96","http://www.ulster.ac.uk/courses/course-finder/201617/civil-engineering-geoinformatics-9341","Civil Engineering (Geoinformatics)","Undergraduate","0"},
		{"97","http://www.ulster.ac.uk/courses/course-finder/201617/clean-technology-9381","Clean Technology","Undergraduate","0"},
		{"98","http://www.ulster.ac.uk/courses/course-finder/201617/clinical-legal-education-9087","Clinical Legal Education","Postgraduate","0"},
		{"99","http://www.ulster.ac.uk/courses/course-finder/201617/clinical-legal-education-9088","Clinical Legal Education","Postgraduate","0"},
		{"100","http://www.ulster.ac.uk/courses/course-finder/201617/clinical-visual-science-8888","Clinical Visual Science","Postgraduate","0"},
		{"101","http://www.ulster.ac.uk/courses/course-finder/201617/coastal-zone-management-9045","Coastal Zone Management","Postgraduate","0"},
		{"102","http://www.ulster.ac.uk/courses/course-finder/201617/commercial-management-in-construction-9047","Commercial Management in Construction","Postgraduate","0"},
		{"103","http://www.ulster.ac.uk/courses/course-finder/201617/commercial-management-in-construction-9046","Commercial Management in Construction","Postgraduate","0"},
		{"104","http://www.ulster.ac.uk/courses/course-finder/201516/communication-12671","Communication","Postgraduate","0"},
		{"105","http://www.ulster.ac.uk/courses/course-finder/201617/communication-12945","Communication","Postgraduate","0"},
		{"106","http://www.ulster.ac.uk/courses/course-finder/201617/communication-and-public-relations-12889","Communication and Public Relations","Postgraduate","0"},
		{"107","http://www.ulster.ac.uk/courses/course-finder/201617/communication-and-public-relations-12888","Communication and Public Relations","Postgraduate","0"},
		{"108","http://www.ulster.ac.uk/courses/course-finder/201617/communication-management-and-public-relations-9219","Communication Management and Public Relations","Undergraduate","0"},
		{"109","http://www.ulster.ac.uk/courses/course-finder/201617/communication-management-and-public-relations-12627","Communication Management and Public Relations","Undergraduate","0"},
		{"110","http://www.ulster.ac.uk/courses/course-finder/201617/communication-management-in-healthcare-12873","Communication Management in Healthcare","Postgraduate","0"},
		{"111","http://www.ulster.ac.uk/courses/course-finder/201617/communication-advertising-and-marketing-9324","Communication, Advertising and Marketing","Undergraduate","0"},
		{"112","http://www.ulster.ac.uk/courses/course-finder/201617/community-development-8955","Community Development","Undergraduate","0"},
		{"113","http://www.ulster.ac.uk/courses/course-finder/201617/community-planning-and-governance-12823","Community Planning and Governance","Postgraduate","0"},
		{"114","http://www.ulster.ac.uk/courses/course-finder/201617/community-planning-and-governance-12822","Community Planning and Governance","Postgraduate","0"},
		{"115","http://www.ulster.ac.uk/courses/course-finder/201617/community-youth-work-9291","Community Youth Work","Undergraduate","0"},
		{"116","http://www.ulster.ac.uk/courses/course-finder/201617/community-youth-work-8943","Community Youth Work","Postgraduate","0"},
		{"117","http://www.ulster.ac.uk/courses/course-finder/201617/community-youth-work-8934","Community Youth Work","Undergraduate","0"},
		{"118","http://www.ulster.ac.uk/courses/course-finder/201617/computer-engineering-9221","Computer Engineering","Undergraduate","0"},
		{"119","http://www.ulster.ac.uk/courses/course-finder/201617/computer-engineering-12629","Computer Engineering","Undergraduate","0"},
		{"120","http://www.ulster.ac.uk/courses/course-finder/201617/computer-games-development-9222","Computer Games Development","Undergraduate","0"},
		{"121","http://www.ulster.ac.uk/courses/course-finder/201617/computer-games-development-12630","Computer Games Development","Undergraduate","0"},
		{"122","http://www.ulster.ac.uk/courses/course-finder/201617/computer-science-8826","Computer Science","Undergraduate","0"},
		{"123","http://www.ulster.ac.uk/courses/course-finder/201617/computer-science-9225","Computer Science","Undergraduate","0"},
		{"124","http://www.ulster.ac.uk/courses/course-finder/201617/computer-science-12948","Computer Science","Postgraduate","0"},
		{"125","http://www.ulster.ac.uk/courses/course-finder/201516/computer-science-12690","Computer Science","Postgraduate","0"},
		{"126","http://www.ulster.ac.uk/courses/course-finder/201617/computer-science-software-systems-development-8825","Computer Science (Software Systems Development)","Undergraduate","0"},
		{"127","http://www.ulster.ac.uk/courses/course-finder/201617/computer-science-software-systems-development-9224","Computer Science (Software Systems Development)","Undergraduate","0"},
		{"128","http://www.ulster.ac.uk/courses/course-finder/201617/computing-science-9254","Computing Science","Undergraduate","0"},
		{"129","http://www.ulster.ac.uk/courses/course-finder/201617/computing-systems-8920","Computing Systems","Undergraduate","0"},
		{"130","http://www.ulster.ac.uk/courses/course-finder/201617/computing-technologies-9253","Computing Technologies","Undergraduate","0"},
		{"131","http://www.ulster.ac.uk/courses/course-finder/201516/conflict-analysis-12876","Conflict Analysis","Postgraduate","0"},
		{"132","http://www.ulster.ac.uk/courses/course-finder/201617/construction-business-and-project-management-9055","Construction Business and Project Management","Postgraduate","0"},
		{"133","http://www.ulster.ac.uk/courses/course-finder/201617/construction-business-and-project-management-9054","Construction Business and Project Management","Postgraduate","0"},
		{"134","http://www.ulster.ac.uk/courses/course-finder/201617/construction-engineering-and-management-9322","Construction Engineering and Management","Undergraduate","0"},
		{"135","http://www.ulster.ac.uk/courses/course-finder/201617/construction-engineering-and-management-9006","Construction Engineering and Management","Undergraduate","0"},
		{"136","http://www.ulster.ac.uk/courses/course-finder/201617/consumer-management-and-food-innovation-12718","Consumer Management and Food Innovation","Undergraduate","0"},
		{"137","http://www.ulster.ac.uk/courses/course-finder/201617/consumer-management-and-food-innovation-12716","Consumer Management and Food Innovation","Undergraduate","0"},
		{"138","http://www.ulster.ac.uk/courses/course-finder/201617/contemporary-applied-art-9372","Contemporary Applied Art","Undergraduate","0"},
		{"139","http://www.ulster.ac.uk/courses/course-finder/201617/counselling-and-therapeutic-communication-with-professional-practice-8848","Counselling and Therapeutic Communication with Professional Practice","Postgraduate","0"},
		{"140","http://www.ulster.ac.uk/courses/course-finder/201617/counselling-and-therapeutic-communication-with-professional-practice-8850","Counselling and Therapeutic Communication with Professional Practice","Postgraduate","0"},
		{"141","http://www.ulster.ac.uk/courses/course-finder/201617/counselling-studies-and-therapeutic-communication-8846","Counselling Studies and Therapeutic Communication","Postgraduate","0"},
		{"142","http://www.ulster.ac.uk/courses/course-finder/201617/counselling-studies-and-therapeutic-communication-8845","Counselling Studies and Therapeutic Communication","Postgraduate","0"},
		{"143","http://www.ulster.ac.uk/courses/course-finder/201516/counsellor-self-care-and-transformative-practice-12968","Counsellor Self-care and Transformative Practice","","0"},
		{"144","http://www.ulster.ac.uk/courses/course-finder/201617/creative-technologies-12976","Creative Technologies","Postgraduate","0"},
		{"145","http://www.ulster.ac.uk/courses/course-finder/201617/criminology-and-criminal-justice-8893","Criminology and Criminal Justice","Undergraduate","0"},
		{"146","http://www.ulster.ac.uk/courses/course-finder/201617/criminology-and-criminal-justice-9257","Criminology and Criminal Justice","Undergraduate","0"},
		{"147","http://www.ulster.ac.uk/courses/course-finder/201617/culinary-arts-management-9294","Culinary Arts Management","Undergraduate","0"},
		{"148","http://www.ulster.ac.uk/courses/course-finder/201617/culinary-arts-management-8942","Culinary Arts Management","Undergraduate","0"},
		{"149","http://www.ulster.ac.uk/courses/course-finder/201516/customising-gis-applications-12928","Customising GIS Applications","Postgraduate","0"},
		{"150","http://www.ulster.ac.uk/courses/course-finder/201617/diabetes-12855","Diabetes","Postgraduate","0"},
		{"151","http://www.ulster.ac.uk/courses/course-finder/201617/diagnostic-radiography-imaging-9239","Diagnostic Radiography & Imaging","Undergraduate","0"},
		{"152","http://www.ulster.ac.uk/courses/course-finder/201617/dietetics-9153","Dietetics","Postgraduate","0"},
		{"153","http://www.ulster.ac.uk/courses/course-finder/201617/dietetics-9328","Dietetics","Undergraduate","0"},
		{"154","http://www.ulster.ac.uk/courses/course-finder/201617/digital-media-communication-12684","Digital Media Communication","Postgraduate","0"},
		{"155","http://www.ulster.ac.uk/courses/course-finder/201617/digital-media-communication-12685","Digital Media Communication","Postgraduate","0"},
		{"156","http://www.ulster.ac.uk/courses/course-finder/201516/doctor-of-medicine-12923","Doctor of Medicine","Postgraduate","0"},
		{"157","http://www.ulster.ac.uk/courses/course-finder/201617/doctor-of-medicine-12966","Doctor of Medicine","Postgraduate","0"},
		{"158","http://www.ulster.ac.uk/courses/course-finder/201516/drama-12707","Drama","Postgraduate","0"},
		{"159","http://www.ulster.ac.uk/courses/course-finder/201617/drama-12963","Drama","Postgraduate","0"},
		{"160","http://www.ulster.ac.uk/courses/course-finder/201617/economics-9259","Economics","Undergraduate","0"},
		{"161","http://www.ulster.ac.uk/courses/course-finder/201617/economics-with-finance-12726","Economics with Finance","Undergraduate","0"},
		{"162","http://www.ulster.ac.uk/courses/course-finder/201617/education-9095","Education","Postgraduate","0"},
		{"163","http://www.ulster.ac.uk/courses/course-finder/201617/education-12953","Education","Postgraduate","0"},
		{"164","http://www.ulster.ac.uk/courses/course-finder/201516/education-12695","Education","Postgraduate","0"},
		{"165","http://www.ulster.ac.uk/courses/course-finder/201617/education-for-nurses-and-midwives-9131","Education for Nurses and Midwives","Postgraduate","0"},
		{"166","http://www.ulster.ac.uk/courses/course-finder/201617/education-with-specialisms-9009","Education with Specialisms","Postgraduate","0"},
		{"167","http://www.ulster.ac.uk/courses/course-finder/201617/education-with-specialisms-9010","Education with Specialisms","Postgraduate","0"},
		{"168","http://www.ulster.ac.uk/courses/course-finder/201617/education-with-specialisms-9012","Education with Specialisms","Postgraduate","0"},
		{"169","http://www.ulster.ac.uk/courses/course-finder/201617/education-with-specialisms-9011","Education with Specialisms","Postgraduate","0"},
		{"170","http://www.ulster.ac.uk/courses/course-finder/201617/electrical-and-electronic-engineering-12812","Electrical and Electronic Engineering (Subject to Approval)","Undergraduate","0"},
		{"171","http://www.ulster.ac.uk/courses/course-finder/201617/electrical-and-electronic-engineering-12808","Electrical and Electronic Engineering (Subject to Approval)","Undergraduate","0"},
		{"172","http://www.ulster.ac.uk/courses/course-finder/201617/electronic-engineering-9380","Electronic Engineering","Undergraduate","0"},
		{"173","http://www.ulster.ac.uk/courses/course-finder/201516/employment-law-and-practice-12936","Employment Law and Practice","Postgraduate","0"},
		{"174","http://www.ulster.ac.uk/courses/course-finder/201617/energy-12730","Energy","Undergraduate","0"},
		{"175","http://www.ulster.ac.uk/courses/course-finder/201617/engineering-management-9333","Engineering Management","Undergraduate","0"},
		{"176","http://www.ulster.ac.uk/courses/course-finder/201617/engineering-management-9378","Engineering Management","Undergraduate","0"},
		{"177","http://www.ulster.ac.uk/courses/course-finder/201617/engineering-science-9270","Engineering Science","Undergraduate","0"},
		{"178","http://www.ulster.ac.uk/courses/course-finder/201617/english-12947","English","Postgraduate","0"},
		{"179","http://www.ulster.ac.uk/courses/course-finder/201516/english-12689","English","Postgraduate","0"},
		{"180","http://www.ulster.ac.uk/courses/course-finder/201617/english-language-and-linguistics-8990","English Language and Linguistics","Postgraduate","0"},
		{"181","http://www.ulster.ac.uk/courses/course-finder/201617/english-language-and-linguistics-8989","English Language and Linguistics","Postgraduate","0"},
		{"182","http://www.ulster.ac.uk/courses/course-finder/201617/environmental-health-9242","Environmental Health","Undergraduate","0"},
		{"183","http://www.ulster.ac.uk/courses/course-finder/201617/environmental-management-9147","Environmental Management","Postgraduate","0"},
		{"184","http://www.ulster.ac.uk/courses/course-finder/201617/environmental-management-with-geographic-information-systems-12835","Environmental Management with Geographic Information Systems","Postgraduate","0"},
		{"185","http://www.ulster.ac.uk/courses/course-finder/201617/environmental-science-12861","Environmental Science","Undergraduate","0"},
		{"186","http://www.ulster.ac.uk/courses/course-finder/201617/environmental-sciences-12961","Environmental Sciences","Postgraduate","0"},
		{"187","http://www.ulster.ac.uk/courses/course-finder/201516/environmental-sciences-12705","Environmental Sciences","Postgraduate","0"},
		{"188","http://www.ulster.ac.uk/courses/course-finder/201516/environmental-toxicology-12938","Environmental Toxicology","Postgraduate","0"},
		{"189","http://www.ulster.ac.uk/courses/course-finder/201617/environmental-toxicology-and-pollution-monitoring-9145","Environmental Toxicology and Pollution Monitoring","Postgraduate","0"},
		{"190","http://www.ulster.ac.uk/courses/course-finder/201516/etutor-training-12917","eTutor Training","","0"},
		{"191","http://www.ulster.ac.uk/courses/course-finder/201617/executive-leadership-8979","Executive Leadership","Postgraduate","0"},
		{"192","http://www.ulster.ac.uk/courses/course-finder/201617/family-therapy-and-systemic-practice-12747","Family Therapy and Systemic Practice","Postgraduate","0"},
		{"193","http://www.ulster.ac.uk/courses/course-finder/201617/finance-and-investment-management-9264","Finance and Investment Management","Undergraduate","0"},
		{"194","http://www.ulster.ac.uk/courses/course-finder/201617/fine-art-9040","Fine Art","Undergraduate","0"},
		{"195","http://www.ulster.ac.uk/courses/course-finder/201617/fine-art-9168","Fine Art","Postgraduate","0"},
		{"196","http://www.ulster.ac.uk/courses/course-finder/201617/fine-art-9335","Fine Art","Undergraduate","0"},
		{"197","http://www.ulster.ac.uk/courses/course-finder/201617/fine-art-9167","Fine Art","Postgraduate","0"},
		{"198","http://www.ulster.ac.uk/courses/course-finder/201617/fire-safety-engineering-9053","Fire Safety Engineering","Postgraduate","0"},
		{"199","http://www.ulster.ac.uk/courses/course-finder/201617/fire-safety-engineering-9052","Fire Safety Engineering","Postgraduate","0"},
		{"200","http://www.ulster.ac.uk/courses/course-finder/201617/food-and-nutrition-9062","Food and Nutrition","Postgraduate","0"},
		{"201","http://www.ulster.ac.uk/courses/course-finder/201617/food-and-nutrition-9061","Food and Nutrition","Postgraduate","0"},
		{"202","http://www.ulster.ac.uk/courses/course-finder/201617/food-and-nutrition-9325","Food and Nutrition","Undergraduate","0"},
		{"203","http://www.ulster.ac.uk/courses/course-finder/201617/food-regulatory-affairs-9020","Food Regulatory Affairs","Postgraduate","0"},
		{"204","http://www.ulster.ac.uk/courses/course-finder/201617/food-regulatory-affairs-12782","Food Regulatory Affairs","Postgraduate","0"},
		{"205","http://www.ulster.ac.uk/courses/course-finder/201617/food-regulatory-affairs-veterinary-public-health-9022","Food Regulatory Affairs (Veterinary Public Health)","Postgraduate","0"},
		{"206","http://www.ulster.ac.uk/courses/course-finder/201516/gender-and-transition-12871","Gender and Transition","Postgraduate","0"},
		{"207","http://www.ulster.ac.uk/courses/course-finder/201617/gender-conflict-and-human-rights-9079","Gender, Conflict and Human Rights","Postgraduate","0"},
		{"208","http://www.ulster.ac.uk/courses/course-finder/201617/gender-conflict-and-human-rights-9080","Gender, Conflict and Human Rights","Postgraduate","0"},
		{"209","http://www.ulster.ac.uk/courses/course-finder/201617/geographic-information-systems-9143","Geographic Information Systems","Postgraduate","0"},
		{"210","http://www.ulster.ac.uk/courses/course-finder/201617/geographic-information-systems-9141","Geographic Information Systems","Postgraduate","0"},
		{"211","http://www.ulster.ac.uk/courses/course-finder/201617/geographic-information-systems-9142","Geographic Information Systems","Postgraduate","0"},
		{"212","http://www.ulster.ac.uk/courses/course-finder/201617/geographic-information-systems-9144","Geographic Information Systems","Postgraduate","0"},
		{"213","http://www.ulster.ac.uk/courses/course-finder/201617/geography-12862","Geography","Undergraduate","0"},
		{"214","http://www.ulster.ac.uk/courses/course-finder/201516/gis-in-business-and-society-12926","GIS in Business and Society","Postgraduate","0"},
		{"215","http://www.ulster.ac.uk/courses/course-finder/201516/global-marketing-and-competitiveness-12925","Global Marketing and Competitiveness","Postgraduate","0"},
		{"216","http://www.ulster.ac.uk/courses/course-finder/201617/graphic-design-and-illustration-9334","Graphic Design and Illustration","Undergraduate","0"},
		{"217","http://www.ulster.ac.uk/courses/course-finder/201617/graphic-design-and-illustration-9039","Graphic Design and Illustration","Undergraduate","0"},
		{"218","http://www.ulster.ac.uk/courses/course-finder/201617/headship-12934","Headship","Postgraduate","0"},
		{"219","http://www.ulster.ac.uk/courses/course-finder/201617/headship-12933","Headship","Postgraduate","0"},
		{"220","http://www.ulster.ac.uk/courses/course-finder/201617/headship-12932","Headship","Postgraduate","0"},
		{"221","http://www.ulster.ac.uk/courses/course-finder/201617/health-and-social-care-policy-8885","Health and Social Care Policy","Undergraduate","0"},
		{"222","http://www.ulster.ac.uk/courses/course-finder/201617/health-and-social-care-policy-9245","Health and Social Care Policy","Undergraduate","0"},
		{"223","http://www.ulster.ac.uk/courses/course-finder/201617/health-and-wellbeing-9130","Health and Wellbeing (Subject to Approval)","Postgraduate","0"},
		{"224","http://www.ulster.ac.uk/courses/course-finder/201617/health-and-wellbeing-9127","Health and Wellbeing (Subject to Approval)","Postgraduate","0"},
		{"225","http://www.ulster.ac.uk/courses/course-finder/201617/health-and-wellbeing-9123","Health and Wellbeing (Subject to Approval)","Undergraduate","0"},
		{"226","http://www.ulster.ac.uk/courses/course-finder/201617/health-and-wellbeing-9129","Health and Wellbeing (Subject to Approval)","Postgraduate","0"},
		{"227","http://www.ulster.ac.uk/courses/course-finder/201617/health-and-wellbeing-9356","Health and Wellbeing (Subject to Approval)","Undergraduate","0"},
		{"228","http://www.ulster.ac.uk/courses/course-finder/201617/health-and-wellbeing-9122","Health and Wellbeing (Subject to Approval)","Undergraduate","0"},
		{"229","http://www.ulster.ac.uk/courses/course-finder/201617/health-and-wellbeing-9128","Health and Wellbeing (Subject to Approval)","Postgraduate","0"},
		{"230","http://www.ulster.ac.uk/courses/course-finder/201617/health-physiology-9236","Health Physiology","Undergraduate","0"},
		{"231","http://www.ulster.ac.uk/courses/course-finder/201617/health-promotion-and-public-health-9118","Health Promotion and Public Health","Postgraduate","0"},
		{"232","http://www.ulster.ac.uk/courses/course-finder/201617/health-promotion-and-public-health-9119","Health Promotion and Public Health","Postgraduate","0"},
		{"233","http://www.ulster.ac.uk/courses/course-finder/201617/health-psychology-8900","Health Psychology","Postgraduate","0"},
		{"234","http://www.ulster.ac.uk/courses/course-finder/201617/health-psychology-8899","Health Psychology","Postgraduate","0"},
		{"235","http://www.ulster.ac.uk/courses/course-finder/201617/healthcare-science-cardiac-physiology-9361","Healthcare Science (Cardiac Physiology)","Undergraduate","0"},
		{"236","http://www.ulster.ac.uk/courses/course-finder/201617/healthcare-science-respiratory-and-sleep-physiology-9360","Healthcare Science (Respiratory and Sleep Physiology)","Undergraduate","0"},
		{"237","http://www.ulster.ac.uk/courses/course-finder/201617/history-12955","History","Postgraduate","0"},
		{"238","http://www.ulster.ac.uk/courses/course-finder/201516/history-12697","History","Postgraduate","0"},
		{"239","http://www.ulster.ac.uk/courses/course-finder/201617/human-nutrition-9329","Human Nutrition","Undergraduate","0"},
		{"240","http://www.ulster.ac.uk/courses/course-finder/201617/human-nutrition-9152","Human Nutrition","Postgraduate","0"},
		{"241","http://www.ulster.ac.uk/courses/course-finder/201617/human-nutrition-9151","Human Nutrition","Postgraduate","0"},
		{"242","http://www.ulster.ac.uk/courses/course-finder/201617/human-resource-management-9251","Human Resource Management","Undergraduate","0"},
		{"243","http://www.ulster.ac.uk/courses/course-finder/201617/human-resource-management-8864","Human Resource Management","Postgraduate","0"},
		{"244","http://www.ulster.ac.uk/courses/course-finder/201617/human-resource-management-and-marketing-9502","Human Resource Management and Marketing","Undergraduate","0"},
		{"245","http://www.ulster.ac.uk/courses/course-finder/201617/human-rights-law-and-transitional-justice-9082","Human Rights Law and Transitional Justice","Postgraduate","0"},
		{"246","http://www.ulster.ac.uk/courses/course-finder/201617/human-rights-law-and-transitional-justice-9081","Human Rights Law and Transitional Justice","Postgraduate","0"},
		{"247","http://www.ulster.ac.uk/courses/course-finder/201516/humanistic-counselling-12825","Humanistic Counselling","Postgraduate","0"},
		{"248","http://www.ulster.ac.uk/courses/course-finder/201617/information-technologies-9223","Information Technologies","Undergraduate","0"},
		{"249","http://www.ulster.ac.uk/courses/course-finder/201617/information-technologies-12631","Information Technologies","Undergraduate","0"},
		{"250","http://www.ulster.ac.uk/courses/course-finder/201617/infrastructure-engineering-8828","Infrastructure Engineering","Postgraduate","0"},
		{"251","http://www.ulster.ac.uk/courses/course-finder/201617/infrastructure-engineering-8827","Infrastructure Engineering","Postgraduate","0"},
		{"252","http://www.ulster.ac.uk/courses/course-finder/201617/interaction-design-12719","Interaction Design","Undergraduate","0"},
		{"253","http://www.ulster.ac.uk/courses/course-finder/201617/interactive-multimedia-design-9255","Interactive Multimedia Design","Undergraduate","0"},
		{"254","http://www.ulster.ac.uk/courses/course-finder/201617/international-business-8836","International Business","Postgraduate","0"},
		{"255","http://www.ulster.ac.uk/courses/course-finder/201617/international-business-8834","International Business","Postgraduate","0"},
		{"256","http://www.ulster.ac.uk/courses/course-finder/201617/international-business-8835","International Business","Postgraduate","0"},
		{"257","http://www.ulster.ac.uk/courses/course-finder/201617/international-business-8833","International Business","Postgraduate","0"},
		{"258","http://www.ulster.ac.uk/courses/course-finder/201617/international-event-management-8939","International Event Management","Postgraduate","0"},
		{"259","http://www.ulster.ac.uk/courses/course-finder/201617/international-event-management-8938","International Event Management","Postgraduate","0"},
		{"260","http://www.ulster.ac.uk/courses/course-finder/201617/international-hospitality-management-8941","International Hospitality Management","Undergraduate","0"},
		{"261","http://www.ulster.ac.uk/courses/course-finder/201617/international-hospitality-management-9293","International Hospitality Management","Undergraduate","0"},
		{"262","http://www.ulster.ac.uk/courses/course-finder/201617/international-hospitality-management-12677","International Hospitality Management","Postgraduate","0"},
		{"263","http://www.ulster.ac.uk/courses/course-finder/201617/international-hospitality-management-12676","International Hospitality Management","Postgraduate","0"},
		{"264","http://www.ulster.ac.uk/courses/course-finder/201617/international-tourism-management-12678","International Tourism Management","Postgraduate","0"},
		{"265","http://www.ulster.ac.uk/courses/course-finder/201617/international-tourism-management-12679","International Tourism Management","Postgraduate","0"},
		{"266","http://www.ulster.ac.uk/courses/course-finder/201617/international-travel-and-tourism-management-12664","International Travel and Tourism Management","Undergraduate","0"},
		{"267","http://www.ulster.ac.uk/courses/course-finder/201617/international-travel-and-tourism-management-12665","International Travel and Tourism Management","Undergraduate","0"},
		{"268","http://www.ulster.ac.uk/courses/course-finder/201516/l2-fitness-instructing-gym-fri-jordanstown-12970","L2 Fitness Instructing GYM: Fri Jordanstown","","0"},
		{"269","http://www.ulster.ac.uk/courses/course-finder/201516/l2-fitness-instructing-gym-fri-magee-12969","L2 Fitness Instructing GYM: Fri Magee","","0"},
		{"270","http://www.ulster.ac.uk/courses/course-finder/201617/language-and-linguistics-12686","Language and Linguistics","Undergraduate","0"},
		{"271","http://www.ulster.ac.uk/courses/course-finder/201617/language-and-linguistics-12687","Language and Linguistics","Undergraduate","0"},
		{"272","http://www.ulster.ac.uk/courses/course-finder/201617/law-9234","Law","Undergraduate","0"},
		{"273","http://www.ulster.ac.uk/courses/course-finder/201617/law-9235","Law","Undergraduate","0"},
		{"274","http://www.ulster.ac.uk/courses/course-finder/201617/law-8855","Law","Undergraduate","0"},
		{"275","http://www.ulster.ac.uk/courses/course-finder/201617/law-8856","Law","Undergraduate","0"},
		{"276","http://www.ulster.ac.uk/courses/course-finder/201516/law-12693","Law","Postgraduate","0"},
		{"277","http://www.ulster.ac.uk/courses/course-finder/201617/law-12951","Law","Postgraduate","0"},
		{"278","http://www.ulster.ac.uk/courses/course-finder/201617/law-with-accounting-9203","Law with Accounting","Undergraduate","0"},
		{"279","http://www.ulster.ac.uk/courses/course-finder/201617/law-with-accounting-9396","Law with Accounting","Undergraduate","0"},
		{"280","http://www.ulster.ac.uk/courses/course-finder/201617/law-with-criminology-9395","Law with Criminology","Undergraduate","0"},
		{"281","http://www.ulster.ac.uk/courses/course-finder/201617/law-with-criminology-9202","Law with Criminology","Undergraduate","0"},
		{"282","http://www.ulster.ac.uk/courses/course-finder/201617/law-with-human-resource-management-9211","Law with Human Resource Management","Undergraduate","0"},
		{"283","http://www.ulster.ac.uk/courses/course-finder/201617/law-with-human-resource-management-9456","Law with Human Resource Management","Undergraduate","0"},
		{"284","http://www.ulster.ac.uk/courses/course-finder/201617/law-with-irish-9454","Law with Irish","Undergraduate","0"},
		{"285","http://www.ulster.ac.uk/courses/course-finder/201617/law-with-marketing-9453","Law with Marketing","Undergraduate","0"},
		{"286","http://www.ulster.ac.uk/courses/course-finder/201617/law-with-marketing-9209","Law with Marketing","Undergraduate","0"},
		{"287","http://www.ulster.ac.uk/courses/course-finder/201617/law-with-politics-9201","Law with Politics","Undergraduate","0"},
		{"288","http://www.ulster.ac.uk/courses/course-finder/201617/law-with-politics-9394","Law with Politics","Undergraduate","0"},
		{"289","http://www.ulster.ac.uk/courses/course-finder/201617/leisure-and-events-management-8940","Leisure and Events Management","Undergraduate","0"},
		{"290","http://www.ulster.ac.uk/courses/course-finder/201617/leisure-and-events-management-9292","Leisure and Events Management","Undergraduate","0"},
		{"291","http://www.ulster.ac.uk/courses/course-finder/201617/library-and-information-management-9093","Library and Information Management","Postgraduate","0"},
		{"292","http://www.ulster.ac.uk/courses/course-finder/201617/library-and-information-management-9092","Library and Information Management","Postgraduate","0"},
		{"293","http://www.ulster.ac.uk/courses/course-finder/201617/library-and-information-management-9094","Library and Information Management","Postgraduate","0"},
		{"294","http://www.ulster.ac.uk/courses/course-finder/201617/linguistics-12949","Linguistics","Postgraduate","0"},
		{"295","http://www.ulster.ac.uk/courses/course-finder/201516/linguistics-12691","Linguistics","Postgraduate","0"},
		{"296","http://www.ulster.ac.uk/courses/course-finder/201617/llm-commercial-law-8891","LLM Commercial Law","Postgraduate","0"},
		{"297","http://www.ulster.ac.uk/courses/course-finder/201617/llm-commercial-law-8892","LLM Commercial Law","Postgraduate","0"},
		{"298","http://www.ulster.ac.uk/courses/course-finder/201617/lower-limb-preservation-in-diabetes-12856","Lower Limb Preservation in Diabetes","Postgraduate","0"},
		{"299","http://www.ulster.ac.uk/courses/course-finder/201617/-ma-teaching-of-english-to-speakers-of-other-languages-8915","MA Teaching of English to Speakers of Other Languages","Postgraduate","0"},
		{"300","http://www.ulster.ac.uk/courses/course-finder/201617/-ma-teaching-of-english-to-speakers-of-other-languages-8914","MA Teaching of English to Speakers of Other Languages","Postgraduate","0"},
		{"301","http://www.ulster.ac.uk/courses/course-finder/201617/management-8921","Management","Postgraduate","0"},
		{"302","http://www.ulster.ac.uk/courses/course-finder/201617/management-8922","Management","Postgraduate","0"},
		{"303","http://www.ulster.ac.uk/courses/course-finder/201617/management-12833","Management","Postgraduate","0"},
		{"304","http://www.ulster.ac.uk/courses/course-finder/201617/management-12834","Management","Postgraduate","0"},
		{"305","http://www.ulster.ac.uk/courses/course-finder/201617/management-and-corporate-governance-8903","Management and Corporate Governance","Postgraduate","0"},
		{"306","http://www.ulster.ac.uk/courses/course-finder/201617/management-and-corporate-governance-8902","Management and Corporate Governance","Postgraduate","0"},
		{"307","http://www.ulster.ac.uk/courses/course-finder/201617/management-and-corporate-governance-8901","Management and Corporate Governance","Postgraduate","0"},
		{"308","http://www.ulster.ac.uk/courses/course-finder/201617/management-and-leadership-development-12877","Management and Leadership Development","Undergraduate","0"},
		{"309","http://www.ulster.ac.uk/courses/course-finder/201516/management-of-coastal-water-resources-12937","Management of Coastal Water Resources","Postgraduate","0"},
		{"310","http://www.ulster.ac.uk/courses/course-finder/201617/management-practice-8959","Management Practice","Undergraduate","0"},
		{"311","http://www.ulster.ac.uk/courses/course-finder/201617/management-practice-8965","Management Practice","Undergraduate","0"},
		{"312","http://www.ulster.ac.uk/courses/course-finder/201516/management-practice-12395","Management Practice","Undergraduate","0"},
		{"313","http://www.ulster.ac.uk/courses/course-finder/201617/manufacturing-management-8867","Manufacturing Management","Postgraduate","0"},
		{"314","http://www.ulster.ac.uk/courses/course-finder/201617/manufacturing-management-8860","Manufacturing Management","Postgraduate","0"},
		{"315","http://www.ulster.ac.uk/courses/course-finder/201617/manufacturing-management-8866","Manufacturing Management","Postgraduate","0"},
		{"316","http://www.ulster.ac.uk/courses/course-finder/201617/manufacturing-management-8859","Manufacturing Management","Postgraduate","0"},
		{"317","http://www.ulster.ac.uk/courses/course-finder/201617/marine-spatial-planning-9140","Marine Spatial Planning","Postgraduate","0"},
		{"318","http://www.ulster.ac.uk/courses/course-finder/201617/marketing-8881","Marketing","Postgraduate","0"},
		{"319","http://www.ulster.ac.uk/courses/course-finder/201617/marketing-8880","Marketing","Postgraduate","0"},
		{"320","http://www.ulster.ac.uk/courses/course-finder/201617/marketing-12849","Marketing","Undergraduate","0"},
		{"321","http://www.ulster.ac.uk/courses/course-finder/201617/mechanical-and-manufacturing-engineering-12811","Mechanical and Manufacturing Engineering (Subject to Approval)","Undergraduate","0"},
		{"322","http://www.ulster.ac.uk/courses/course-finder/201617/mechanical-and-manufacturing-engineering-12815","Mechanical and Manufacturing Engineering (Subject to Approval)","Undergraduate","0"},
		{"323","http://www.ulster.ac.uk/courses/course-finder/201617/mechanical-engineering-9377","Mechanical Engineering","Undergraduate","0"},
		{"324","http://www.ulster.ac.uk/courses/course-finder/201617/mechanical-engineering-12735","Mechanical Engineering","Undergraduate","0"},
		{"325","http://www.ulster.ac.uk/courses/course-finder/201617/mechatronic-engineering-9186","Mechatronic Engineering","Undergraduate","0"},
		{"326","http://www.ulster.ac.uk/courses/course-finder/201617/mechatronic-engineering-9376","Mechatronic Engineering","Undergraduate","0"},
		{"327","http://www.ulster.ac.uk/courses/course-finder/201516/media-and-entertainment-law-substance-and-practice-12870","Media and Entertainment Law: Substance and Practice","Postgraduate","0"},
		{"328","http://www.ulster.ac.uk/courses/course-finder/201516/media-studies-12709","Media Studies","Postgraduate","0"},
		{"329","http://www.ulster.ac.uk/courses/course-finder/201617/media-studies-12965","Media Studies","Postgraduate","0"},
		{"330","http://www.ulster.ac.uk/courses/course-finder/201617/medical-and-healthcare-biotechnology-12742","Medical and Healthcare Biotechnology","Postgraduate","0"},
		{"331","http://www.ulster.ac.uk/courses/course-finder/201617/medicines-management-9139","Medicines Management","Postgraduate","0"},
		{"332","http://www.ulster.ac.uk/courses/course-finder/201617/middle-leadership-12907","Middle Leadership","Postgraduate","0"},
		{"333","http://www.ulster.ac.uk/courses/course-finder/201617/middle-leadership-12906","Middle Leadership","Postgraduate","0"},
		{"334","http://www.ulster.ac.uk/courses/course-finder/201617/middle-leadership-12905","Middle Leadership","Postgraduate","0"},
		{"335","http://www.ulster.ac.uk/courses/course-finder/201516/mres-in-arts-12703","MRes in Arts","Postgraduate","0"},
		{"336","http://www.ulster.ac.uk/courses/course-finder/201617/mres-in-arts-12959","MRes in Arts","Postgraduate","0"},
		{"337","http://www.ulster.ac.uk/courses/course-finder/201617/mres-in-life-and-health-sciences-12967","MRes in Life and Health Sciences","Postgraduate","0"},
		{"338","http://www.ulster.ac.uk/courses/course-finder/201516/mres-in-life-and-health-sciences-12924","MRes in Life and Health Sciences","Postgraduate","0"},
		{"339","http://www.ulster.ac.uk/courses/course-finder/201516/music-12708","Music","Postgraduate","0"},
		{"340","http://www.ulster.ac.uk/courses/course-finder/201617/music-12964","Music","Postgraduate","0"},
		{"341","http://www.ulster.ac.uk/courses/course-finder/201516/nanotechnology-advanced-materials-and-bioengineering-12704","Nanotechnology, Advanced Materials and Bioengineering","Postgraduate","0"},
		{"342","http://www.ulster.ac.uk/courses/course-finder/201617/nanotechnology-advanced-materials-and-bioengineering-12960","Nanotechnology, Advanced Materials and Bioengineering","Postgraduate","0"},
		{"343","http://www.ulster.ac.uk/courses/course-finder/201617/non-medical-prescribing-9116","Non Medical Prescribing","Undergraduate","0"},
		{"344","http://www.ulster.ac.uk/courses/course-finder/201617/non-medical-prescribing-12841","Non Medical Prescribing","Postgraduate","0"},
		{"345","http://www.ulster.ac.uk/courses/course-finder/201617/nursing-9115","Nursing","Postgraduate","0"},
		{"346","http://www.ulster.ac.uk/courses/course-finder/201617/nursing-9114","Nursing","Postgraduate","0"},
		{"347","http://www.ulster.ac.uk/courses/course-finder/201617/nursing-adult-9283","Nursing (Adult)","Undergraduate","0"},
		{"348","http://www.ulster.ac.uk/courses/course-finder/201617/nursing-mental-health-9282","Nursing (Mental Health)","Undergraduate","0"},
		{"349","http://www.ulster.ac.uk/courses/course-finder/201617/nursing-and-health-research-12952","Nursing and Health Research","Postgraduate","0"},
		{"350","http://www.ulster.ac.uk/courses/course-finder/201516/nursing-and-health-research-12694","Nursing and Health Research","Postgraduate","0"},
		{"351","http://www.ulster.ac.uk/courses/course-finder/201617/nutraceuticals-functional-foods-and-supplements-9060","Nutraceuticals, Functional Foods and Supplements","Postgraduate","0"},
		{"352","http://www.ulster.ac.uk/courses/course-finder/201617/nutraceuticals-functional-foods-and-supplements-12832","Nutraceuticals, Functional Foods and Supplements","Postgraduate","0"},
		{"353","http://www.ulster.ac.uk/courses/course-finder/201617/occupational-therapy-9295","Occupational Therapy","Undergraduate","0"},
		{"354","http://www.ulster.ac.uk/courses/course-finder/201617/optometry-12764","Optometry (Subject to Approval)","Undergraduate","0"},
		{"355","http://www.ulster.ac.uk/courses/course-finder/201617/palliative-care-8870","Palliative Care","Postgraduate","0"},
		{"356","http://www.ulster.ac.uk/courses/course-finder/201516/peace-and-conflict-research-in-divided-societies-12913","Peace and Conflict Research in Divided Societies","Postgraduate","0"},
		{"357","http://www.ulster.ac.uk/courses/course-finder/201617/peace-and-conflict-studies-9075","Peace and Conflict Studies","Postgraduate","0"},
		{"358","http://www.ulster.ac.uk/courses/course-finder/201617/peace-and-conflict-studies-with-early-years-9073","Peace and Conflict Studies with Early Years","Postgraduate","0"},
		{"359","http://www.ulster.ac.uk/courses/course-finder/201617/pg-cert-education-further-education-8924","PG Cert Education (Further Education)","Postgraduate","0"},
		{"360","http://www.ulster.ac.uk/courses/course-finder/201617/pg-cert-education-further-education-8925","PG Cert Education (Further Education)","Postgraduate","0"},
		{"361","http://www.ulster.ac.uk/courses/course-finder/201617/pharmacy-9326","Pharmacy","Undergraduate","0"},
		{"362","http://www.ulster.ac.uk/courses/course-finder/201617/pharmacy-management-9107","Pharmacy Management","Postgraduate","0"},
		{"363","http://www.ulster.ac.uk/courses/course-finder/201617/photography-9164","Photography","Postgraduate","0"},
		{"364","http://www.ulster.ac.uk/courses/course-finder/201617/photography-9370","Photography","Undergraduate","0"},
		{"365","http://www.ulster.ac.uk/courses/course-finder/201617/physical-activity-and-public-health-9043","Physical Activity and Public Health","Postgraduate","0"},
		{"366","http://www.ulster.ac.uk/courses/course-finder/201617/physical-activity-and-public-health-9042","Physical Activity and Public Health","Postgraduate","0"},
		{"367","http://www.ulster.ac.uk/courses/course-finder/201617/physical-activity-exercise-and-health-9273","Physical Activity, Exercise and Health","Undergraduate","0"},
		{"368","http://www.ulster.ac.uk/courses/course-finder/201617/physiotherapy-9323","Physiotherapy","Undergraduate","0"},
		{"369","http://www.ulster.ac.uk/courses/course-finder/201617/podiatry-9289","Podiatry","Undergraduate","0"},
		{"370","http://www.ulster.ac.uk/courses/course-finder/201617/politics-9232","Politics","Undergraduate","0"},
		{"371","http://www.ulster.ac.uk/courses/course-finder/201617/politics-8847","Politics","Undergraduate","0"},
		{"372","http://www.ulster.ac.uk/courses/course-finder/201617/politics-and-international-studies-12956","Politics and International Studies","Postgraduate","0"},
		{"373","http://www.ulster.ac.uk/courses/course-finder/201516/politics-and-international-studies-12698","Politics and International Studies","Postgraduate","0"},
		{"374","http://www.ulster.ac.uk/courses/course-finder/201617/politics-with-criminology-9416","Politics with Criminology","Undergraduate","0"},
		{"375","http://www.ulster.ac.uk/courses/course-finder/201617/product-and-furniture-design-9365","Product and Furniture Design","Undergraduate","0"},
		{"376","http://www.ulster.ac.uk/courses/course-finder/201516/professional-decision-making-in-social-work-12912","Professional Decision Making in Social Work","Postgraduate","0"},
		{"377","http://www.ulster.ac.uk/courses/course-finder/201617/professional-development-in-counselling-8944","Professional Development in Counselling","Undergraduate","0"},
		{"378","http://www.ulster.ac.uk/courses/course-finder/201617/professional-development-in-occupational-therapy-12760","Professional Development in Occupational Therapy (Subject to Approval)","Postgraduate","0"},
		{"379","http://www.ulster.ac.uk/courses/course-finder/201617/professional-development-in-occupational-therapy-12759","Professional Development in Occupational Therapy (Subject to Approval)","Postgraduate","0"},
		{"380","http://www.ulster.ac.uk/courses/course-finder/201617/professional-development-in-physiotherapy-12762","Professional Development in Physiotherapy (Subject to Approval)","Postgraduate","0"},
		{"381","http://www.ulster.ac.uk/courses/course-finder/201617/professional-development-in-physiotherapy-12761","Professional Development in Physiotherapy (Subject to Approval)","Postgraduate","0"},
		{"382","http://www.ulster.ac.uk/courses/course-finder/201617/professional-software-development-9004","Professional Software Development","Postgraduate","0"},
		{"383","http://www.ulster.ac.uk/courses/course-finder/201516/psychodynamic-approaches-12826","Psychodynamic Approaches","Postgraduate","0"},
		{"384","http://www.ulster.ac.uk/courses/course-finder/201617/psychology-9244","Psychology","Undergraduate","0"},
		{"385","http://www.ulster.ac.uk/courses/course-finder/201617/psychology-8875","Psychology","Undergraduate","0"},
		{"386","http://www.ulster.ac.uk/courses/course-finder/201617/psychology-12957","Psychology","Postgraduate","0"},
		{"387","http://www.ulster.ac.uk/courses/course-finder/201516/psychology-12699","Psychology","Postgraduate","0"},
		{"388","http://www.ulster.ac.uk/courses/course-finder/201617/public-administration-8844","Public Administration","Postgraduate","0"},
		{"389","http://www.ulster.ac.uk/courses/course-finder/201516/qualitative-research-methods-12838","Qualitative Research Methods","Postgraduate","0"},
		{"390","http://www.ulster.ac.uk/courses/course-finder/201617/quantity-surveying-and-commercial-management-8841","Quantity Surveying and Commercial Management","Undergraduate","0"},
		{"391","http://www.ulster.ac.uk/courses/course-finder/201617/quantity-surveying-and-commercial-management-9229","Quantity Surveying and Commercial Management","Undergraduate","0"},
		{"392","http://www.ulster.ac.uk/courses/course-finder/201617/radiotherapy-and-oncology-9317","Radiotherapy and Oncology","Undergraduate","0"},
		{"393","http://www.ulster.ac.uk/courses/course-finder/201617/real-estate-9227","Real Estate","Undergraduate","0"},
		{"394","http://www.ulster.ac.uk/courses/course-finder/201617/real-estate-8839","Real Estate","Undergraduate","0"},
		{"395","http://www.ulster.ac.uk/courses/course-finder/201617/real-estate-12625","Real Estate","Postgraduate","0"},
		{"396","http://www.ulster.ac.uk/courses/course-finder/201617/real-estate-12626","Real Estate","Postgraduate","0"},
		{"397","http://www.ulster.ac.uk/courses/course-finder/201617/renewable-energy-and-energy-management-9049","Renewable Energy and Energy Management","Postgraduate","0"},
		{"398","http://www.ulster.ac.uk/courses/course-finder/201617/renewable-energy-engineering-12813","Renewable Energy Engineering (Subject to Approval)","Undergraduate","0"},
		{"399","http://www.ulster.ac.uk/courses/course-finder/201617/renewable-energy-engineering-12809","Renewable Energy Engineering (Subject to Approval)","Undergraduate","0"},
		{"400","http://www.ulster.ac.uk/courses/course-finder/201617/restorative-practices-8884","Restorative Practices","Undergraduate","0"},
		{"401","http://www.ulster.ac.uk/courses/course-finder/201617/restorative-practices-8883","Restorative Practices","Postgraduate","0"},
		{"402","http://www.ulster.ac.uk/courses/course-finder/201516/return-to-practice-nursing-12874","Return to Practice Nursing","","0"},
		{"403","http://www.ulster.ac.uk/courses/course-finder/201617/safety-engineering-and-disaster-management-12766","Safety Engineering and Disaster Management","Undergraduate","0"},
		{"404","http://www.ulster.ac.uk/courses/course-finder/201617/sensory-integration-9137","Sensory Integration","Postgraduate","0"},
		{"405","http://www.ulster.ac.uk/courses/course-finder/201516/silver-jewellery-make-a-necklace-or-earrings-in-a-day-12921","Silver Jewellery: Make a Necklace or Earrings in a Day","","0"},
		{"406","http://www.ulster.ac.uk/courses/course-finder/201617/social-enterprise-8966","Social Enterprise","Undergraduate","0"},
		{"407","http://www.ulster.ac.uk/courses/course-finder/201516/social-enterprise-12396","Social Enterprise","Undergraduate","0"},
		{"408","http://www.ulster.ac.uk/courses/course-finder/201617/social-policy-12784","Social Policy","Undergraduate","0"},
		{"409","http://www.ulster.ac.uk/courses/course-finder/201617/social-policy-12785","Social Policy","Undergraduate","0"},
		{"410","http://www.ulster.ac.uk/courses/course-finder/201617/social-policy-with-criminology-9208","Social Policy with Criminology","Undergraduate","0"},
		{"411","http://www.ulster.ac.uk/courses/course-finder/201617/social-policy-with-criminology-9412","Social Policy with Criminology","Undergraduate","0"},
		{"412","http://www.ulster.ac.uk/courses/course-finder/201617/social-policy-with-sociology-12843","Social Policy with Sociology","Undergraduate","0"},
		{"413","http://www.ulster.ac.uk/courses/course-finder/201617/social-policy-with-sociology-12842","Social Policy with Sociology","Undergraduate","0"},
		{"414","http://www.ulster.ac.uk/courses/course-finder/201516/social-policy-criminology-public-policy-and-social-work-12647","Social Policy, Criminology, Public Policy and Social Work","Postgraduate","0"},
		{"415","http://www.ulster.ac.uk/courses/course-finder/201617/social-policy-criminology-public-policy-and-social-work-12943","Social Policy, Criminology, Public Policy and Social Work","Postgraduate","0"},
		{"416","http://www.ulster.ac.uk/courses/course-finder/201617/social-psychology-8863","Social Psychology","Undergraduate","0"},
		{"417","http://www.ulster.ac.uk/courses/course-finder/201617/social-psychology-9237","Social Psychology","Undergraduate","0"},
		{"418","http://www.ulster.ac.uk/courses/course-finder/201617/social-research-skills-9096","Social Research Skills","Postgraduate","0"},
		{"419","http://www.ulster.ac.uk/courses/course-finder/201617/sociology-with-criminology-9207","Sociology with Criminology","Undergraduate","0"},
		{"420","http://www.ulster.ac.uk/courses/course-finder/201617/sociology-with-criminology-9411","Sociology with Criminology","Undergraduate","0"},
		{"421","http://www.ulster.ac.uk/courses/course-finder/201617/sociology-with-politics-9407","Sociology with Politics","Undergraduate","0"},
		{"422","http://www.ulster.ac.uk/courses/course-finder/201617/software-engineering-9252","Software Engineering","Undergraduate","0"},
		{"423","http://www.ulster.ac.uk/courses/course-finder/201617/specialist-community-public-health-nursing-9110","Specialist Community Public Health Nursing","Postgraduate","0"},
		{"424","http://www.ulster.ac.uk/courses/course-finder/201617/specialist-community-public-health-nursing-9281","Specialist Community Public Health Nursing","Undergraduate","0"},
		{"425","http://www.ulster.ac.uk/courses/course-finder/201617/specialist-nursing-with-pathways-9226","Specialist Nursing (with pathways)","Undergraduate","0"},
		{"426","http://www.ulster.ac.uk/courses/course-finder/201617/specialist-nursing-with-pathways-8829","Specialist Nursing (with pathways)","Undergraduate","0"},
		{"427","http://www.ulster.ac.uk/courses/course-finder/201617/specialist-nursing-with-pathways-8831","Specialist Nursing (with pathways)","Postgraduate","0"},
		{"428","http://www.ulster.ac.uk/courses/course-finder/201617/specialist-nursing-with-pathways-8830","Specialist Nursing (with pathways)","Postgraduate","0"},
		{"429","http://www.ulster.ac.uk/courses/course-finder/201617/sport-and-exercise-medicine-9097","Sport and Exercise Medicine","Postgraduate","0"},
		{"430","http://www.ulster.ac.uk/courses/course-finder/201617/sport-and-exercise-medicine-9098","Sport and Exercise Medicine","Postgraduate","0"},
		{"431","http://www.ulster.ac.uk/courses/course-finder/201617/sport-and-exercise-nutrition-9102","Sport and Exercise Nutrition","Postgraduate","0"},
		{"432","http://www.ulster.ac.uk/courses/course-finder/201617/sport-and-exercise-nutrition-9101","Sport and Exercise Nutrition","Postgraduate","0"},
		{"433","http://www.ulster.ac.uk/courses/course-finder/201617/sport-and-exercise-psychology-9104","Sport and Exercise Psychology","Postgraduate","0"},
		{"434","http://www.ulster.ac.uk/courses/course-finder/201617/sport-and-exercise-psychology-9103","Sport and Exercise Psychology","Postgraduate","0"},
		{"435","http://www.ulster.ac.uk/courses/course-finder/201617/sport-and-exercise-sciences-9241","Sport and Exercise Sciences","Undergraduate","0"},
		{"436","http://www.ulster.ac.uk/courses/course-finder/201617/sport-management-8995","Sport Management","Postgraduate","0"},
		{"437","http://www.ulster.ac.uk/courses/course-finder/201617/sport-management-8996","Sport Management","Postgraduate","0"},
		{"438","http://www.ulster.ac.uk/courses/course-finder/201617/sport-studies-9217","Sport Studies","Undergraduate","0"},
		{"439","http://www.ulster.ac.uk/courses/course-finder/201617/sport-physical-activity-and-health-12944","Sport, Physical Activity and Health","Postgraduate","0"},
		{"440","http://www.ulster.ac.uk/courses/course-finder/201516/sport-physical-activity-and-health-12662","Sport, Physical Activity and Health","Postgraduate","0"},
		{"441","http://www.ulster.ac.uk/courses/course-finder/201617/sports-coaching-9247","Sports Coaching","Undergraduate","0"},
		{"442","http://www.ulster.ac.uk/courses/course-finder/201617/sports-coaching-8889","Sports Coaching","Undergraduate","0"},
		{"443","http://www.ulster.ac.uk/courses/course-finder/201516/strategic-management-12916","Strategic Management","Postgraduate","0"},
		{"444","http://www.ulster.ac.uk/courses/course-finder/201516/strategic-marketing-12975","Strategic Marketing","Postgraduate","0"},
		{"445","http://www.ulster.ac.uk/courses/course-finder/201516/strategic-sports-marketing-12824","Strategic Sports Marketing","Postgraduate","0"},
		{"446","http://www.ulster.ac.uk/courses/course-finder/201617/stratified-medicine-9218","Stratified Medicine","Undergraduate","0"},
		{"447","http://www.ulster.ac.uk/courses/course-finder/201617/stratified-medicine-12654","Stratified Medicine","Postgraduate","0"},
		{"448","http://www.ulster.ac.uk/courses/course-finder/201617/stratified-medicine-12655","Stratified Medicine","Postgraduate","0"},
		{"449","http://www.ulster.ac.uk/courses/course-finder/201617/teaching-9089","Teaching","Undergraduate","0"},
		{"450","http://www.ulster.ac.uk/courses/course-finder/201617/teaching-9090","Teaching","Undergraduate","0"},
		{"451","http://www.ulster.ac.uk/courses/course-finder/201617/technology-with-design-9375","Technology with Design","Undergraduate","0"},
		{"452","http://www.ulster.ac.uk/courses/course-finder/201617/textile-art-design-and-fashion-9269","Textile Art, Design and Fashion","Undergraduate","0"},
		{"453","http://www.ulster.ac.uk/courses/course-finder/201617/textile-art-design-and-fashion-8908","Textile Art, Design and Fashion","Undergraduate","0"},
		{"454","http://www.ulster.ac.uk/courses/course-finder/201516/the-wine-spirits-education-trust-course-level-2-12919","The Wine & Spirits Education Trust Course - Level 2","","0"},
		{"455","http://www.ulster.ac.uk/courses/course-finder/201617/theory-of-independent-prescribing-for-optometrists-12763","Theory of Independent Prescribing for Optometrists","Postgraduate","0"},
		{"456","http://www.ulster.ac.uk/courses/course-finder/201617/-therapeutic-communication-and-counselling-studies-9228","Therapeutic Communication and Counselling Studies","Undergraduate","0"},
		{"457","http://www.ulster.ac.uk/courses/course-finder/201617/-therapeutic-communication-and-counselling-studies-8840","Therapeutic Communication and Counselling Studies","Undergraduate","0"},
		{"458","http://www.ulster.ac.uk/courses/course-finder/201516/transitional-justice-institute-12692","Transitional Justice Institute","Postgraduate","0"},
		{"459","http://www.ulster.ac.uk/courses/course-finder/201617/transitional-justice-institute-12950","Transitional Justice Institute","Postgraduate","0"},
		{"460","http://www.ulster.ac.uk/courses/course-finder/201617/urban-planning-and-property-development-9340","Urban Planning and Property Development","Undergraduate","0"},
		{"461","http://www.ulster.ac.uk/courses/course-finder/201617/urban-planning-and-property-development-9050","Urban Planning and Property Development","Undergraduate","0"},
		{"462","http://www.ulster.ac.uk/courses/course-finder/201617/veterinary-public-health-9019","Veterinary Public Health","Postgraduate","0"},
		{"463","http://www.ulster.ac.uk/courses/course-finder/201516/visitor-attractions-events-12914","Visitor Attractions & Events","Postgraduate","0"},
		{"464","http://www.ulster.ac.uk/courses/course-finder/201516/web-based-gis-12927","Web-based GIS","Postgraduate","0"}
	};
	
	public static String html2Str(String html) { 
		return html.replaceAll("<[^>]+>", "");
	}
	
	
		public static String HTMLFilter(String input) {
		    if (input == null) {
		        input = "";
		        return input;
		    }
		    input = input.trim().replaceAll("&amp;", "&");
		    input = input.trim().replaceAll("&lt;", "<");
		    input = input.trim().replaceAll("&gt;", ">");
		    input = input.trim().replaceAll("    ", " ");
		    input = input.trim().replaceAll("<br>", "\n");
		    input = input.trim().replaceAll("&nbsp;", "  ");
		    input = input.trim().replaceAll("&quot;", "\"");
		    input = input.trim().replaceAll("&#39;", "'");
		    input = input.trim().replaceAll("&#92;", "\\\\");
		    input = input.trim().replaceAll("&#...;", "");
		    input = input.trim().replaceAll("&#....;", "");
		    return input;
		}

}
