package bristol;

import java.io.File;
import java.io.FileInputStream;

import org.htmlparser.Parser;
import org.htmlparser.filters.AndFilter;
import org.htmlparser.filters.HasAttributeFilter;
import org.htmlparser.filters.TagNameFilter;
import org.htmlparser.tags.LinkTag;
import org.htmlparser.util.NodeList;

public class getURL {

	/**
	 * @param args
	 */
	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub
		FileInputStream fis=new FileInputStream(new File("./bristolPost.html"));
        
        byte[] b=new byte[fis.available()];//鏂板缓涓�涓瓧鑺傛暟缁�
        fis.read(b);//灏嗘枃浠朵腑鐨勫唴瀹硅鍙栧埌瀛楄妭鏁扮粍涓�
       fis.close();
        String htmls=new String(b);//鍐嶅皢瀛楄妭鏁扮粍涓殑鍐呭杞寲鎴愬瓧绗︿覆褰㈠紡杈撳嚭
       //System.out.println(htmls);
        //System.out.println("{\"");
       Parser parser=Parser.createParser(htmls, "utf-8");
       TagNameFilter ProfessionNameFilter=new TagNameFilter("li");
       NodeList nodes2 = parser.extractAllNodesThatMatch(ProfessionNameFilter);
       for(int i=0;i<nodes2.size();i++)
	    {
    	   System.out.print("{\"");
    	   String Duration=html2Str(nodes2.elementAt(i).toHtml());
           if(Duration.contains("1 year"))
   		{
   			System.out.print(12);
   		}
   		else if(Duration.contains("2 year"))
   		{
   			System.out.print(24);
   		}
   		else if(Duration.contains("3 year"))
   		{
   			System.out.print(36);
   		}
   		else if(Duration.contains("4 year"))
   		{
   			System.out.print(48);
   		}
   		else if(Duration.contains("1")&&Duration.contains("year"))
   		{
   			System.out.print(12);
   		}
   		else if(Duration.contains("2")&&Duration.contains("year"))
   		{
   			System.out.print(24);
   		}
   		else if(Duration.contains("3")&&Duration.contains("year"))
   		{
   			System.out.print(36);
   		}
   		else if(Duration.contains("4")&&Duration.contains("year"))
   		{
   			System.out.print(48);
   		}
          // System.out.println("\",\"");
	    	parser=Parser.createParser(nodes2.elementAt(i).toHtml(), "utf-8");
   	    AndFilter ProfessionNameFilter2=new AndFilter(new TagNameFilter("a"),
                   new HasAttributeFilter("href"));
   	    NodeList nodes4=parser.extractAllNodesThatMatch(ProfessionNameFilter2);
   	    for(int j=0;j<nodes4.size();j++)
   	    {
   	    	LinkTag link=(LinkTag)nodes4.elementAt(j);
   	    	String get1=link.getAttribute("href");
   	    	if(html2Str(link.toHtml()).split(",").length==2)
   	    	System.out.println("\",\"http://www.bristol.ac.uk"+get1+"\",\""+html2Str(link.toHtml()).split(",")[0].trim()+"\",\""+html2Str(link.toHtml()).split(",")[1].trim()+"\"},");
   	    	else
   	    	{
   	    		System.out.println("\",\"http://www.bristol.ac.uk"+get1+"\",\""+html2Str(link.toHtml()).split(",")[0].trim()+"\",\"\"},");
   	    	}
   	    }
   	    	
	    }

	}
	public static String html2Str(String html) { 
		return html.replaceAll("<[^>]+>", "");
	}
	String[][] UnData={
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/accounting-finance/bsc-accounting-finance/","Accounting and Finance","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/accounting-finance/bsc-accounting-and-finance-with-study-abroad/","Accounting and Finance with Study Abroad","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/accounting-finance/bsc-accounting-finance-europe/","Accounting and Finance with Study in Continental Europe","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/management/bsc-accounting-management/","Accounting and Management","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/aerospace/beng-aerospace-engineering/","Aerospace Engineering","BEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/aerospace/meng-aerospace/","Aerospace Engineering","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/aerospace/meng-aerospace-study-abroad/","Aerospace Engineering with Study Abroad","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/aerospace/meng-aerospace-europe/","Aerospace Engineering with Study in Continental Europe","MEng"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/ancient-history/ba-ancient-history/","Ancient History","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/animal-behaviour-welfare/bsc-animal-behaviour-welfare/","Animal Behaviour and Welfare Science","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/anthropology/ba-anthropology/","Anthropology","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/innovation/marts-anthropology-with-innovation/","Anthropology with Innovation","MArts"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/archaeology/ba-archaeology/","Archaeology","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/archaeology/ba-arch-anth/","Archaeology and Anthropology","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/biochemistry/bsc-biochem/","Biochemistry","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/biochemistry/bsc-biochem-medical-biochem/","Biochemistry with Medical Biochemistry","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/biochemistry/bsc-biochem-molecular-biology-biotech/","Biochemistry with Molecular Biology and Biotechnology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/biochemistry/bsc-biochem-industry/","Biochemistry with Study in Industry","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/biological-sciences/bsc-biology/","Biology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/biological-sciences/msci-biology/","Biology","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/geology/bsc-geology-biology/","Geology and Biology","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/cellular-molecular/bsc-cancer-biology-immunology/","Cancer Biology and Immunology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/cellular-molecular/bsc-cancer-biology-and-immunology-with-study-in-i/","Cancer Biology and Immunology with Study in Industry","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/cellular-molecular/bsc-cellular-molecular/","Cellular and Molecular Medicine","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/cellular-molecular/bsc-cellular-and-molecular-medicine-with-study-in/","Cellular and Molecular Medicine with Study in Industry","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/chemical-physics/bsc-chemical-physics/","Chemical Physics","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/chemical-physics/msci-chemical-physics/","Chemical Physics","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/chemical-physics/msci-chemical-physics-industry/","Chemical Physics with Industrial Experience","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/chemistry/bsc-chemistry/","Chemistry","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/chemistry/msci-chemistry/","Chemistry","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/chemistry/msci-chemistry-industry/","Chemistry with Industrial Experience","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/chemistry/msci-chemistry-study-abroad/","Chemistry with Study Abroad","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/chemistry/msci-chemistry-europe/","Chemistry with Study in Continental Europe","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/chemistry/bsc-chemistry-preliminary-study/","Chemistry with a Preliminary Year of Study","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/childhood-studies/bsc-childhood/","Childhood Studies","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/childhood-studies/bsc-childhood-management/","Childhood Studies with Management","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/quantitative-research-methods/bsc-childhood-quantitative-research/","Childhood Studies with Quantitative Research Methods","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/quantitative-research-methods/msci-childhood-quantitative-research/","Childhood Studies with Quantitative Research Methods","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/civil-engineering/beng-civil-eng/","Civil Engineering","BEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/civil-engineering/meng-civil-eng/","Civil Engineering","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/civil-engineering/meng-civil-eng-study-abroad/","Civil Engineering with Study Abroad","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/civil-engineering/meng-civil-eng-europe/","Civil Engineering with Study in Continental Europe","MEng"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/classical-studies/ba-classical-studies/","Classical Studies","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/classics/ba-classics/","Classics","BA"},
			{"24","http://www.bristol.ac.uk/study/undergraduate/2016/companion-animal-welfare-behavioural-rehab/certificate/","Companion Animal Welfare and Behavioural Rehabilitation","Cert"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/computer-science/bsc-comp-sci/","Computer Science","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/computer-science/meng-comp-sci/","Computer Science","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/electrical-electronic-eng/meng-comp-sci-electronics/","Computer Science and Electronics","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/electrical-electronic-eng/meng-comp-sci-electronics-study-abroad/","Computer Science and Electronics with Study Abroad","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/innovation/meng-computer-science-with-innovation/","Computer Science with Innovation","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/computer-science/meng-comp-sci-study-abroad/","Computer Science with Study Abroad","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/computer-science/meng-comp-sci-europe/","Computer Science with Study in Continental Europe","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/czech/ba-czech-french/","Czech and French","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/czech/ba-czech-german/","Czech and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/czech/ba-czech-italian/","Czech and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/czech/ba-czech-portuguese/","Czech and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/czech/ba-czech-russian/","Czech and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/czech/ba-czech-spanish/","Czech and Spanish","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/english/ba-english-classical-studies/","English and Classical Studies","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/computer-science/bsc-maths-comp-sci/","Mathematics and Computer Science","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/computer-science/meng-maths-comp-sci/","Mathematics and Computer Science","MEng"},
			{"24","http://www.bristol.ac.uk/study/undergraduate/2016/dental-hygiene/dip-dental-hygiene/","Dental Hygiene","Dip"},
			{"24","http://www.bristol.ac.uk/study/undergraduate/2016/dental-therapy/dip-dental-therapy/","Dental Therapy","Dip"},
			{"24","http://www.bristol.ac.uk/study/undergraduate/2016/dentistry/bds-dentistry/","Dentistry","BDS"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/electrical-electronic-eng/meng-comp-sci-electronics/","Computer Science and Electronics","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/electrical-electronic-eng/meng-comp-sci-electronics-study-abroad/","Computer Science and Electronics with Study Abroad","MEng"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/economics/bsc-econ/","Economics","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/accounting-finance/bsc-econ-accounting/","Economics and Accounting","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/economics/bsc-econ-econometrics/","Economics and Econometrics","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/economics/bsc-econ-finance/","Economics and Finance","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/management/bsc-econ-management/","Economics and Management","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/economics/bsc-econ-maths/","Economics and Mathematics","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/economics/bsc-econ-politics/","Economics and Politics","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/economics/bsc-economics-with-study-abroad/","Economics with Study Abroad","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/economics/bsc-econ-europe/","Economics with Study in Continental Europe","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/electrical-electronic-eng/beng-elec-electronic/","Electrical and Electronic Engineering","BEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/electrical-electronic-eng/meng-elec-electronic/","Electrical and Electronic Engineering","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/innovation/meng-electrical-and-electronic-engineering-with-i/","Electrical and Electronic Engineering with Innovation","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/electrical-electronic-eng/meng-elec-electronic-study-abroad/","Electrical and Electronic Engineering with Study Abroad","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/electrical-electronic-eng/meng-elec-electronic-europe/","Electrical and Electronic Engineering with Study in Continental Europe","MEng"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/electrical-electronic-eng/beng-electronic-communications/","Electronic and Communications Engineering","BEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/electrical-electronic-eng/meng-electronic-communications-eng/","Electronic and Communications Engineering","MEng"},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/engineering-design/meng-eng-design-industry/","Engineering Design with Study in Industry","MEng"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/engineering-maths/beng-eng-maths/","Engineering Mathematics","BEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/engineering-maths/meng-eng-maths/","Engineering Mathematics","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/engineering-maths/meng-maths-study-abroad/","Engineering Mathematics with Study Abroad","MEng"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/english/ba-english/","English","BA"},
			{"","http://www.bristol.ac.uk/study/undergraduate/2016/english/ba-english-lit-community-engagement/","English Literature and Community Engagement","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/english/ba-english-classical-studies/","English and Classical Studies","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/english/ba-english-philosophy/","English and Philosophy","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/geoscience/bsc-environmental-geoscience/","Environmental Geoscience","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/geoscience/msci-environmental-geoscience/","Environmental Geoscience","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/geoscience/msci-environmental-geoscience-study-abroad/","Environmental Geoscience with Study Abroad","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/film-television/ba-film-english/","Film and English","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/geology/msci-palaentology-evolution/","Palaeontology and Evolution","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/bsc-philosophy-econ/","Philosophy and Economics","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-english/","Theatre and English","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/czech/ba-czech-french/","Czech and French","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/film-television/ba-film-english/","Film and English","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/film-television/ba-film-french/","Film and French","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/film-television/ba-film-german/","Film and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/film-television/ba-film-italian/","Film and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/film-television/ba-film-portuguese/","Film and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/film-television/ba-film-spanish/","Film and Spanish","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/film-television/ba-film-television/","Film and Television","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/innovation/marts-film-and-television-with-innovation/","Film and Television with Innovation","MArts"},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/foundation/english-arts/","Foundation Programme (English with Arts and Humanities)","Cert"},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/foundation/english-chemistry/","Foundation Programme (English with Chemistry and Mathematics)","Cert"},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/foundation/english-econ/","Foundation Programme (English with Economics",""},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/foundation/cert-foundation-programme-english-with-law/","Foundation Programme (English with Law)","Cert"},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/foundation/english-maths/","Foundation Programme (English with Mathematics)","Cert"},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/foundation/english-physics/","Foundation Programme (English with Physics and Mathematics)","Cert"},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/foundation-arts-humanities/certificate/","Foundation Year in Arts and Humanities","Cert"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/french/ba-french/","French","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/french/ba-french-german/","French and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/french/ba-french-italian/","French and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/french/ba-french-portuguese/","French and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/french/ba-french-russian/","French and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/french/ba-french-spanish/","French and Spanish","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art-french/","History of Art and French","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/law/llb-law-french/","Law and French","LLB"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/music/ba-music-french/","Music and French","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-french/","Philosophy and French","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/ba-politics-french/","Politics and French","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-film/","Theatre and Film","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-french/","Theatre and French","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/czech/ba-czech-german/","Czech and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/film-television/ba-film-german/","Film and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/french/ba-french-german/","French and German","BA"},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/dentistry/bds-gateway-to-dentistry/","Gateway to Dentistry","BDS"},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/medicine/mb-chb-gateway-to-medicine/","Gateway to Medicine","MB ChB"},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/vet-science/bvsc-gateway-to-veterinary-science/","Gateway to Veterinary Science","BVSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/geography/bsc-geography/","Geography","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/geography/msci-geography/","Geography","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/innovation/msci-geography-with-innovation/","Geography with Innovation","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/quantitative-research-methods/bsc-geography-quantitative-research/","Geography with Quantitative Research Methods","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/quantitative-research-methods/msci-geography-quantitative-research/","Geography with Quantitative Research Methods","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/geography/bsc-study-abroad/","Geography with Study Abroad","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/geography/bsc-geography-study-europe/","Geography with Study in Continental Europe","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/geology/bsc-geology/","Geology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/geology/msci-geology/","Geology","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/geology/bsc-geology-biology/","Geology and Biology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/geology/msci-geology-study-abroad/","Geology with Study Abroad","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/geophysics/bsc-geophysics/","Geophysics","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/geophysics/msci-geophysics/","Geophysics","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/german/ba-german/","German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/german/ba-german-italian/","German and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/german/ba-german-portuguese/","German and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/german/ba-german-russian/","German and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/german/ba-german-spanish/","German and Spanish","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art-german/","History of Art and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/law/llb-law-german/","Law and German","LLB"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/music/ba-music-german/","Music and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-german/","Philosophy and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/ba-politics-german/","Politics and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-german/","Theatre and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/spanish/ba-hispanic-studies/","Hispanic Studies","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/history/ba-history/","History","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art/","History of Art","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art-french/","History of Art and French","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art-german/","History of Art and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art-italian/","History of Art and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art-portuguese/","History of Art and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art-russian/","History of Art and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art-spanish/","History of Art and Spanish","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/innovation/marts-history-with-innovation/","History with Innovation","MArts"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/czech/ba-czech-italian/","Czech and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/film-television/ba-film-italian/","Film and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/french/ba-french-italian/","French and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/german/ba-german-italian/","German and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art-italian/","History of Art and Italian","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/management/bsc-international-business-management/","International Business Management","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/italian/ba-italian/","Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/italian/ba-italian-portuguese/","Italian and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/italian/ba-italian-russian/","Italian and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/italian/ba-italian-spanish/","Italian and Spanish","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/music/ba-music-italian/","Music and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-italian/","Philosophy and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/ba-politics-italian/","Politics and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-italian/","Theatre and Italian","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/law/llb-law/","Law","LLB"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/law/llb-law-french/","Law and French","LLB"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/law/llb-law-german/","Law and German","LLB"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/law/llb-law-study-abroad/","Law with Study Abroad","LLB"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/law/llb-law-europe/","Law with Study in Continental Europe","LLB"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/liberal-arts/ba-liberal-arts/","Liberal Arts","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/liberal-arts/mlibarts-liberal-arts-study-abroad/","Liberal Arts with Study Abroad","MLibArts"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/economics/bsc-econ-maths/","Economics and Mathematics","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/management/bsc-management/","Management","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/innovation/msci-management-with-innovation/","Management with Innovation","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/management/bsc-management-with-study-abroad/","Management with Study Abroad","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/management/bsc-management-europe/","Management with Study in Continental Europe","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/maths/bsc-maths/","Mathematics","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/maths/msci-maths/","Mathematics","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/computer-science/bsc-maths-comp-sci/","Mathematics and Computer Science","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/computer-science/meng-maths-comp-sci/","Mathematics and Computer Science","MEng"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/maths/bsc-maths-philosophy/","Mathematics and Philosophy","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/maths/msci-maths-philosophy/","Mathematics and Philosophy","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/maths/bsc-maths-physics/","Mathematics and Physics","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/maths/msci-maths-physics/","Mathematics and Physics","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/maths/bsc-maths-statistics/","Mathematics with Statistics","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/maths/msci-maths-statistics/","Mathematics with Statistics","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/maths/bsc-maths-europe/","Mathematics with Study in Continental Europe","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/maths/msci-maths-europe/","Mathematics with Study in Continental Europe","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/mechanical-engineering/beng-mech-eng/","Mechanical Engineering","BEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/mechanical-engineering/meng-mech-eng/","Mechanical Engineering","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/mechanical-engineering/meng-mech-eng-study-abroad/","Mechanical Engineering with Study Abroad","MEng"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/mechanical-engineering/meng-mech-eng-europe/","Mechanical Engineering with Study in Continental Europe","MEng"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/cellular-molecular/bsc-medical-microbiology/","Medical Microbiology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/cellular-molecular/bsc-medical-microbiology-with-study-in-industry/","Medical Microbiology with Study in Industry","BSc"},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/medicine/mb-medicine/","Medicine","MB ChB"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/medicine/mb-medicine-grad-entry/","Medicine (graduate entry)","MB ChB"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/modern-languages/ba-modern-languages/","Modern Languages","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/music/ba-music/","Music","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/music/ba-music-french/","Music and French","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/music/ba-music-german/","Music and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/music/ba-music-italian/","Music and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/innovation/marts-music-with-innovation/","Music with Innovation","MArts"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/neuroscience/bsc-neuroscience/","Neuroscience","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/neuroscience/msci-neuroscience-industry/","Neuroscience with Study in Industry","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/czech/ba-czech-portuguese/","Czech and Portuguese","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/economics/bsc-econ-politics/","Economics and Politics","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/english/ba-english-philosophy/","English and Philosophy","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/film-television/ba-film-portuguese/","Film and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/french/ba-french-portuguese/","French and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/german/ba-german-portuguese/","German and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art-portuguese/","History of Art and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/italian/ba-italian-portuguese/","Italian and Portuguese","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/maths/bsc-maths-philosophy/","Mathematics and Philosophy","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/maths/msci-maths-philosophy/","Mathematics and Philosophy","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/maths/bsc-maths-physics/","Mathematics and Physics","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/maths/msci-maths-physics/","Mathematics and Physics","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/geology/msci-palaentology-evolution/","Palaeontology and Evolution","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/cellular-molecular/bsc-pathology-microbiology/","Pathology and Microbiology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/cellular-molecular/bsc-pathology-and-microbiology-with-study-in-indu/","Pathology and Microbiology with Study in Industry","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/pharmacology/bsc-pharmacology/","Pharmacology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/pharmacology/msci-pharmacology-industry/","Pharmacology with Study in Industry","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy/","Philosophy","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/bsc-philosophy-econ/","Philosophy and Economics","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-french/","Philosophy and French","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-german/","Philosophy and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-italian/","Philosophy and Italian","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/bsc-philosophy-politics/","Philosophy and Politics","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-portuguese/","Philosophy and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-russian/","Philosophy and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-spanish/","Philosophy and Spanish","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-theology/","Philosophy and Theology","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/physics/bsc-physics/","Physics","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/physics/msci-physics/","Physics","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/physics/bsc-physics-philosophy/","Physics and Philosophy","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/physics/msci-physics-philosophy/","Physics and Philosophy","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/physics/bsc-physics-astrophysics/","Physics with Astrophysics","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/physics/msci-physics-astrophysics/","Physics with Astrophysics","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/physics/msci-physics-industry/","Physics with Industrial Experience","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/innovation/msci-physics-with-innovation/","Physics with Innovation","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/physics/msci-physics-europe/","Physics with Study in Continental Europe","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/physics/bsc-physics-preliminary-study/","Physics with a Preliminary Year of Study","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/physiology/bsc-physiology-science/","Physiological Science","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/physiology/msci-physiological-science-industry/","Physiological Science with Study in Industry","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/ba-politics-french/","Politics and French","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/ba-politics-german/","Politics and German","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/bsc-politics-international-relations/","Politics and International Relations","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/bsc-politics-and-international-relations-with-stu/","Politics and International Relations with Study Abroad","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/ba-politics-italian/","Politics and Italian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/ba-politics-portuguese/","Politics and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/ba-politics-russian/","Politics and Russian","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/bsc-politics-sociology/","Politics and Sociology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/ba-politics-spanish/","Politics and Spanish","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/quantitative-research-methods/bsc-politics-quantitative-research/","Politics with Quantitative Research Methods","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/quantitative-research-methods/msci-politics-quantitative-research/","Politics with Quantitative Research Methods","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/psychology/bsc-psychology/","Psychology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/psychology/msci-psychology/","Psychology","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/innovation/msci-psychology-with-innovation/","Psychology with Innovation","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/russian/ba-russian-portuguese/","Russian and Portuguese","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/social-policy/bsc-social-policy-politics/","Social Policy and Politics","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/sociology/bsc-sociology-philosophy/","Sociology and Philosophy","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/spanish/ba-spanish-portuguese/","Spanish and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-portuguese/","Theatre and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/czech/ba-czech-russian/","Czech and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/french/ba-french-russian/","French and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/german/ba-german-russian/","German and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art-russian/","History of Art and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/italian/ba-italian-russian/","Italian and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-russian/","Philosophy and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/ba-politics-russian/","Politics and Russian","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/religion-theology/ba-religion-theology/","Religion and Theology","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/russian/ba-russian/","Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/russian/ba-russian-portuguese/","Russian and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/spanish/ba-spanish-russian/","Spanish and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/czech/ba-czech-spanish/","Czech and Spanish","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/film-television/ba-film-spanish/","Film and Spanish","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/french/ba-french-spanish/","French and Spanish","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/german/ba-german-spanish/","German and Spanish","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/history-art/ba-history-art-spanish/","History of Art and Spanish","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/italian/ba-italian-spanish/","Italian and Spanish","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-spanish/","Philosophy and Spanish","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/bsc-politics-sociology/","Politics and Sociology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/politics-international-relations/ba-politics-spanish/","Politics and Spanish","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/social-policy/bsc-social-policy/","Social Policy","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/social-policy/bsc-social-policy-politics/","Social Policy and Politics","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/social-policy/bsc-social-policy-sociology/","Social Policy and Sociology","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/social-policy/bsc-social-policy-with-criminology/","Social Policy with Criminology","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/social-policy/bsc-social-policy-management/","Social Policy with Management","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/quantitative-research-methods/bsc-social-policy-quantitative-research/","Social Policy with Quantitative Research Methods","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/quantitative-research-methods/msci-social-policy-quantitative-research/","Social Policy with Quantitative Research Methods","MSci"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/sociology/bsc-sociology/","Sociology","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/sociology/bsc-sociology-philosophy/","Sociology and Philosophy","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/quantitative-research-methods/bsc-sociology-quantitative-research/","Sociology with Quantitative Research Methods","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/quantitative-research-methods/msci-sociology-quantitative-research/","Sociology with Quantitative Research Methods","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/sociology/bsc-sociology-study-abroad/","Sociology with Study Abroad","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/spanish/ba-spanish/","Spanish","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/spanish/ba-spanish-portuguese/","Spanish and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/spanish/ba-spanish-russian/","Spanish and Russian","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-spanish/","Theatre and Spanish","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/religion-theology/ba-theology-sociology/","Theology and Sociology","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/philosophy/ba-philosophy-theology/","Philosophy and Theology","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-english/","Theatre and English","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-film/","Theatre and Film","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-french/","Theatre and French","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-german/","Theatre and German","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-italian/","Theatre and Italian","BA"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-performance/","Theatre and Performance Studies","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-portuguese/","Theatre and Portuguese","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/theatre/ba-theatre-spanish/","Theatre and Spanish","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/innovation/marts-theatre-with-innovation/","Theatre with Innovation","MArts"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/religion-theology/ba-theology-sociology/","Theology and Sociology","BA"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/physics/msci-theoretical-physics/","Theoretical Physics","MSci"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/vet-nursing-biovet-science/bsc-vet-nursing/","Veterinary Nursing and Bioveterinary Science","BSc"},
			{"12","http://www.bristol.ac.uk/study/undergraduate/2016/vet-science/bvsc-veterinary-science/","Veterinary Science","BVSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/cellular-molecular/bsc-virology-immunology/","Virology and Immunology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/cellular-molecular/bsc-virology-and-immunology-with-study-in-industry/","Virology and Immunology with Study in Industry","BSc"},
			{"36","http://www.bristol.ac.uk/study/undergraduate/2016/biological-sciences/bsc-zoology/","Zoology","BSc"},
			{"48","http://www.bristol.ac.uk/study/undergraduate/2016/biological-sciences/msci-zoology/","Zoology","MSci"}	
	};
	String[][] PostData={
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-accounting-finance/","Accounting and Finance","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-accounting-finance-management/","Accounting",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-adv-composites/","Advanced Composites","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-advanced-composites/","Advanced Composites","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-adv-computing/","Advanced Computing","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-adv-computing-creative-tech/","Advanced Computing - Creative Technology","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-adv-computing-machine-learning/","Advanced Computing - Machine Learning",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-adv-mech-eng/","Advanced Mechanical Engineering","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-adv-microelectronic-systems-eng/","Advanced Microelectronic Systems Engineering","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-adv-qualitative-methods/","Advanced Quantitative Methods","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-adv-social-work-children-family/","Advanced Social Work with Children and Families","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/phd-aero-eng/","Aerospace Engineering","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/msc-applied-neuropsychology/","Applied Neuropsychology","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/pg-dip-applied-neuropsychology/","Applied Neuropsychology","PG Diploma (Postgraduate Diploma)"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-archaeology/","Archaeology","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-arch-anth/","Archaeology and Anthropology","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/biomedical-sciences/phd-biochemistry/","Biochemistry","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/phd-biological-sciences/","Biological Sciences","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-biomedical-eng/","Biomedical Engineering","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/biomedical-sciences/msc-biomedical-sciences-research/","Biomedical Sciences Research","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/biomedical-sciences/msc-biophysics-molecular-life-sciences/","Biophysics and Molecular Life Sciences","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/biomedical-sciences/phd-cellular-molecular-medicine/","Cellular and Molecular Medicine","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-epsrc-bristol-chemical-synthesis/","Chemical Synthesis (EPSRC Centre for Doctoral Training)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/phd-chemistry/","Chemistry","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-chinese-eng-translation/","Chinese-English Translation","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/phd-civil-eng/","Civil Engineering","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-classical-reception/","Classical Reception","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-classics-ancient-history/","Classics and Ancient History","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-classics-ancient-history/","Classics and Ancient History","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/msc-climate-change-science-policy/","Climate Change Science and Policy","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/msc-clinical-neuropsychology/","Clinical Neuropsychology","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/pg-diploma-clinical-neuropsychology/","Clinical Neuropsychology","PG Diploma (Postgraduate Diploma)"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/phd-clinical-sciences/","Clinical Sciences","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-comms-networks-signal-processing/","Communication Networks and Signal Processing","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-communications/","Communications","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-comparative-literatures-and-cultures/","Comparative Literatures and Cultures","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/phd-comparative-clinical-anatomy/","Comparative and Clinical Anatomy","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-complexity-sciences/","Complexity Sciences","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/engd-composites-manufacture/","Composites Manufacture","EngD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-composition-music-film-tv/","Composition of Music for Film and Television","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/phd-computer-science/","Computer Science","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-computer-science/","Computer Science (conversion)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-condensed-matter-physics-/","Condensed Matter Physics","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-contemporary-identities/","Contemporary Identities","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/msc-dental-implantology/","Dental Implantology","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/dpds-dental-postgraduate-studies/","Dental Postgraduate Studies","DPDS"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-development-security/","Development and Security","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-epsrc-cdt-diamond-science/","Diamond Science and Technology (EPSRC Centre for  Doctoral Training)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-disability-studies/","Disability Studies","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-disability-studies/","Disability Studies: Inclusive Theory and Research","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-dynamic-cell-biology-wellcome-trust/","Dynamic Cell Biology (Wellcome Trust)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/phd-earth-sciences/","Earth Sciences","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-east-asian-dev-global-economy/","East Asian Development and the Global Economy","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/graduate-diploma-economics/","Economics","Graduate Diploma"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/mres-economics/","Economics","MRes"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-economics/","Economics","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-economics/","Economics","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-economics-econometrics/","Economics and Econometrics","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-economics-finance/","Economics and Finance","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-economics-public-policy/","Economics and Public Policy","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-economics-accounting-finance/","Economics",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-economics-finance-management/","Economics",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-education/","Education","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-education/","Education","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/edd-education-management/","Education (Hong Kong)","EdD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-education-leadership--policy/","Education (Leadership &amp; Policy)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/edd-education-learning-leadership--policy/","Education (Learning",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-education-learning-technology-and-society/","Education (Learning",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-education-mathematics-education/","Education (Mathematics Education)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-education-neuroscience--education/","Education (Neuroscience &amp; Education)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-education-policy--international-development/","Education (Policy &amp; International Development)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-education-psychology-of-education/","Education (Psychology of Education)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-education-science-education/","Education (Science Education)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/pgce-education/","Education (Secondary)","PGCE"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-education-special-and-inclusive-education/","Education (Special and Inclusive Education)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-education-teaching--learning/","Education (Teaching &amp; Learning)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-education-teaching-english/","Education - Teaching English to Speakers of Other Languages (TESOL)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/med-education-management/","Education Management (Hong Kong)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-educational-leadership-teach-first/","Educational Leadership (Teach First)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/dedpsy-educational-psychology/","Educational Psychology","DEdPsy"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-educational-research/","Educational Research","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/phd-elec-electronic-eng/","Electrical and Electronic Engineering","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/phd-eng-maths/","Engineering Mathematics","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-english-literature/","English Literature","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-english-literature/","English Literature","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/mres-environment-energy-resilience/","Environment",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-environment-energy-resilience/","Environment",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-environmental-policy-management/","Environmental Policy and Management","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-ethnicity-multiculturalism/","Ethnicity and Multiculturalism","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-european-and-global-governance/","European and Global Governance","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-exercise-nutrition-health/","Exercise",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-film-tv/","Film and Television","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-film-tv-production/","Film and Television Production","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-film-television/","Film and Television Studies","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-finance-investment/","Finance and Investment","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-french/","French","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-epsrc-bristol-centre-functional-nanomater/","Functional Nanomaterials (EPSRC Centre for Doctoral Training)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-epsrc-centre-doctoral-training/","Future Autonomous Robotic Systems - FARSCOPE (EPSRC Centre for Doctoral Training)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-gender-international-relations/","Gender and International Relations","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-geographical-sciences/","Geographical Sciences (Human Geography)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/phd-geographical-sciences/","Geographical Sciences (Physical Geography)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-german/","German","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/mres-global-political-economy/","Global Political Economy: Transformations and Policy Analysis","MRes"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-global-political-economy-transformations/","Global Political Economy: Transformations and Policy Analysis","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/msc-global-wildlife-health-conservation/","Global Wildlife Health and Conservation","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-great-western-four-dtp/","Great Western Four+ Doctoral Training Partnership (NERC)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/mres-health-sciences-research/","Health Sciences Research","MRes"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/mres-health-wellbeing/","Health and Wellbeing","MRes"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-health-wellbeing/","Health and Wellbeing","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/p-hispanic-portuguese-latin-american/","Hispanic",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-history/","History","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-history/","History","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-history-art/","History of Art","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-history-art/","History of Art","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-human-geography-society-space/","Human Geography: Society and Space","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-img-video-comms-signal-processing/","Image and Video Communications and Signal Processing","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-international-development/","International Development","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/path-pre-masters/","International Graduate Programme in English for Academic Purposes","Pathway Certificate"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-international-relations/","International Relations","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-international-security/","International Security","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-italian/","Italian","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/ma-law/","Law","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-law/","Law","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/llm-law---commercial-law/","Law - Commercial Law","LLM"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/llm-law---european-legal-studies/","Law - European Legal Studies","LLM"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/llm-general-legal-studies/","Law - General Legal Studies","LLM"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/llm-human-rights-law/","Law - Human Rights Law","LLM"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/llm-law---international-commercial-law/","Law - International Commercial Law","LLM"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/llm-international-law/","Law - International Law","LLM"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/llm-labour-law-corporate-governance/","Law - Labour Law and Corporate Governance","LLM"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/llm-law-globalisation/","Law - Law and Globalisation","LLM"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/llm-public-law/","Law - Public Law","LLM"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-logic-philosophy-maths/","Logic and Philosophy of Mathematics","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-management/","Management","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-management/","Management","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/msc-mathematical-sciences/","Mathematical Sciences","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/phd-mathematics/","Mathematics","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/phd-mech-eng/","Mechanical Engineering","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-medieval-studies/","Medieval Studies","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/msc-molecular-neuroscience/","Molecular Neuroscience","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-wellcome-trust-phd-molecular-genetic/","Molecular",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-music/","Music","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-music/","Music","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/msc-nanoscience-functional-nanomaterials/","Nanoscience and Functional Nanomaterials","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-neural-dynamics-wellcome-trust/","Neural Dynamics (Wellcome Trust)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/msc-neuropsychology/","Neuropsychology","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/msc-nuclear-science-and-engineering/","Nuclear Science and Engineering","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-nutrition-physical-activity-public-health/","Nutrition",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-optical-comms-signal-processing/","Optical Communications and Signal Processing","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/phd-oral-dental-sciences/","Oral and Dental Sciences","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/dds-orthodontics/","Orthodontics (Doctorate in Dental Surgery)","DDS"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/msc-palaeobiology/","Palaeobiology","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-philosophy/","Philosophy","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/grad-dip-philosophy/","Philosophy","PG Diploma (Postgraduate Diploma)"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-philosophy/","Philosophy","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-phil-history-science/","Philosophy and History of Science","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-philosophy-law/","Philosophy and Law","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-phil-biol-cognitive-sciences/","Philosophy of Biological and Cognitive Sciences","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/phd-physics/","Physics","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/biomedical-sciences/phd-physiology-pharmacology/","Physiology and Pharmacology","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-policy-research/","Policy Research","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/phd-experimental-psychology/","Psychology (Experimental)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/med-education-psychology-education/","Psychology of Education (BPS)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-public-policy/","Public Policy","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-epsrc-centre-doctoral-training-quantum/","Quantum Engineering (EPSRC Centre for Doctoral Training)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-religion/","Religion","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-religion-theology/","Religion and Theology","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/msc-reproduction-development/","Reproduction and Development","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/msc-research-methods-psychology/","Research Methods in Psychology","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-robotics/","Robotics","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-russian-czech/","Russian and Czech","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/mres-security-conflict-justice/","Security",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-security-conflict-justice/","Security",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-social-policy/","Social Policy","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-soc-sci-research-methods/","Social Science Research Methods (Politics / International Relations)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-research-methods-sociology/","Social Science Research Methods (Sociology)","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-social-work/","Social Work","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-social-work/","Social Work","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-social-work-research/","Social Work Research","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/phd-social-community-medicine/","Social and Community Medicine","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-social-cultural-theory/","Social and Cultural Theory","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-socio-legal-studies/","Socio-Legal Studies","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-sociology/","Sociology","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/phd-sociology-politics-international-studies/","Sociology",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-esrc-south-west-dtc/","South West Doctoral Training Centre (ESRC)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/msc-statistics/","Statistics","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/msc-stem-cells-regeneration/","Stem Cells and Regeneration","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/ssl/msc-strategy-change-leadership/","Strategy",""},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/doctoral/phd-epsrc-cdt-synthetic-biology/","Synthetic Biology (EPSRC and BBSRC Centre for Doctoral Training)","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/biomedical-sciences/mres-systems-neuroscience/","Systems Neuroscience","MRes"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/msc-teaching-learning-health-professionals/","Teaching and Learning for Health Professionals","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-theatre-performance/","Theatre and Performance","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/biomedical-sciences/msc-transfusion-transplantation-sciences/","Transfusion and Transplantation Sciences","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/ma-translation/","Translation","MA"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/arts/phd-translation/","Translation","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/msc-translational-cardiovascular-medicine/","Translational Cardiovascular Medicine","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/health-sciences/phd-veterinary-science/","Veterinary Science","PhD"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/sci/msc-volcanology/","Volcanology","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-water-environmental-management/","Water and Environmental Management","MSc"},
			{"http://www.bristol.ac.uk/study/postgraduate/2016/eng/msc-wireless-comms-signal-processing/","Wireless Communications and Signal Processing","MSc"}	
	};

}
