package newcastle;

import java.io.File;
import java.io.FileInputStream;

import org.htmlparser.Parser;
import org.htmlparser.filters.AndFilter;
import org.htmlparser.filters.HasAttributeFilter;
import org.htmlparser.filters.TagNameFilter;
import org.htmlparser.tags.LinkTag;
import org.htmlparser.util.NodeList;

public class getURL {

	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub

FileInputStream fis=new FileInputStream(new File("./newcatslePost.html"));//鏂板缓涓�涓狥ileInputStream瀵硅薄
        
        byte[] b=new byte[fis.available()];//鏂板缓涓�涓瓧鑺傛暟缁�
        fis.read(b);//灏嗘枃浠朵腑鐨勫唴瀹硅鍙栧埌瀛楄妭鏁扮粍涓�
       fis.close();
        String htmls=new String(b);//鍐嶅皢瀛楄妭鏁扮粍涓殑鍐呭杞寲鎴愬瓧绗︿覆褰㈠紡杈撳嚭
       //System.out.println(htmls);
       
	    Parser	parser=Parser.createParser(htmls, "utf-8");
   	    AndFilter ProfessionNameFilter=new AndFilter(new TagNameFilter("a"),
                   new HasAttributeFilter("href"));
   	    NodeList nodes4=parser.extractAllNodesThatMatch(ProfessionNameFilter);
   	    for(int i=0;i<nodes4.size();i++)
   	    {
   	    	LinkTag link=(LinkTag)nodes4.elementAt(i);
   	    	String get1=link.getAttribute("href");
   	    	if(get1.startsWith("/postgraduate"))
   	    	{

   	   	        System.out.println("{\"http://www.ncl.ac.uk"+get1.replace("courseoverview/", "modules/")+"\",\""+html2Str(link.toHtml())+"\"},");
   	    	}
   	    }
   	    	
   	    
	    
	}
	public static String html2Str(String html) { 
		return html.replaceAll("<[^>]+>", "");
	}
	public static String[][] UnData={
		{"http://www.ncl.ac.uk/undergraduate/degrees/n400/modules/","Accounting and Finance BA Honours (N400)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/n402/modules/","Accounting and Finance BSc Honours (N402) - London campus"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/ng41/modules/","Accounting and Mathematics BSc Honours (NG41)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/nn14/modules/","Business Accounting and Finance BA Honours (NN14)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/n280/modules/","Agri-Business Management BSc Honours (N280)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/n280/modules/","Agri-Business Management BSc Honours (N280)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/d400/modules/#d.en.64510","Agriculture BSc Honours (D400)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/d444/modules/#d.en.64534","Agriculture with Agronomy BSc Honours (D444)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/d422/modules/#d.en.64557","Agriculture with Animal Production Science BSc Honours (D422)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/d402/modules/#d.en.64580","Agriculture with Farm Business Management BSc Honours (D402)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/v110/modules/","Ancient History BA Honours (V110)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/vv14/modules/","Ancient History and Archaeology BA Honours (VV14)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c305/modules/","Animal Science BSc Honours (C305)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/vv14/modules/","Ancient History and Archaeology BA Honours (VV14)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/v400/modules/","Archaeology BA Honours (V400)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/vv41/modules/","History and Archaeology BA Honours (VV41)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/k100/modules/","Architecture BA Honours (K100)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/k190/modules/","Architecture and Urban Planning BA Honours (K190)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c700/modules/","Biochemistry BSc Honours (C700)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c701/modules/#d.en.228031","Biochemistry (Integrated Master's) MSci Honours (C701)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c100/modules/","Biology BSc Honours (C100)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c103/modules/#d.en.228022","Biology MBiol Honours (C103)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c1c7/modules/","Biology (Cellular and Molecular Biology) BSc Honours (C1C7)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c7c1/modules/#d.en.228024","Biology (Cellular and Molecular Biology) MBiol Honours (C7C1)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c180/modules/","Biology (Ecology and Environmental Biology) BSc Honours (C180)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c181/modules/#d.en.228025","Biology (Ecology and Environmental Biology) MBiol Honours (C181)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/cc18/modules/","Biology and Psychology BSc Honours (CC18)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c300/modules/","Zoology BSc Honours (C300)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c301/modules/#d.en.228027","Zoology MBiol Honours (C301)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c700/modules/","Biochemistry BSc Honours (C700)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c701/modules/#d.en.228031","Biochemistry (Integrated Master's) MSci Honours (C701)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b901/modules/","Biomedical Genetics BSc Honours (B901)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b903/modules/#d.en.228053","Biomedical Genetics (Integrated Master's) MSci Honours (B903)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b940/modules/","Biomedical Sciences BSc Honours (B940)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b900/modules/","Biomedical Sciences (Integrated Master's) MSci Honours (B900)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b942/modules/#d.en.147021","Biomedical Sciences with Industrial Placement Year BSc Honours (B942)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b9c6/modules/#d.en.147018","Exercise Biomedicine BSc Honours (B9C6)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b902/modules/","Medical Science (Deferred Choice) BSc Honours (B902)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b210/modules/","Pharmacology BSc Honours (B210)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b100/modules/","Physiological Sciences BSc Honours (B100)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/n280/modules/","Agri-Business Management BSc Honours (N280)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/n200/modules/","Business Management BA Honours (N200)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/ln12/modules/","Economics and Business Management BA Honours (LN12)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/n120/modules/","International Business Management BSc Honours (N120/N121)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/n122/modules/","International Business Management BSc Honours (N122) - London campus"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/n5n2/modules/","International Marketing and Management BSc Honours (N5N2) - London campus"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/nn52/modules/","Marketing and Management BA Honours (NN52)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h810/modules/","Chemical Engineering BEng Honours (H810) "},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h813/modules/","Chemical Engineering MEng Honours (H813) "},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h831/modules/","Chemical Engineering with Bioprocess Engineering MEng Honours (H831) "},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h814/modules/","Chemical Engineering with Foundation Year BEng Honours (H814) "},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h816/modules/","Chemical Engineering with Foundation Year MEng Honours (H816) "},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h815/modules/","Chemical Engineering with Industry MEng Honours (H815)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h830/modules/","Chemical Engineering with Process Control MEng Honours (H830) "},
		{"http://www.ncl.ac.uk/undergraduate/degrees/hh82/modules/","Chemical Engineering with Sustainable Engineering MEng Honours (HH82) "},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f100/modules/","Chemistry BSc Honours (F100)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f103/modules/","Chemistry MChem Honours (F103)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f102/modules/","Chemistry (with Industrial Training Year) BSc Honours (F102)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f106/modules/","Chemistry (with Industrial Training Year) MChem Honours (F106)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f151/modules/","Chemistry with Medicinal Chemistry BSc Honours (F151)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f123/modules/","Chemistry with Medicinal Chemistry MChem Honours (F123)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f122/modules/","Chemistry with Medicinal Chemistry (with Industrial Training Year) BSc Honours (F122)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f124/modules/","Chemistry with Medicinal Chemistry (with Industrial Training Year) MChem Honours (F124)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f107/modules/","Chemistry with Study Abroad MChem Honours (F107)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h210/modules/","Civil and Structural Engineering BEng Honours (H210)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h242/modules/","Civil and Structural Engineering MEng Honours (H242)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h202/modules/","Civil and Surveying Engineering BEng Honours (H202)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h292/modules/#d.en.121505","Civil and Surveying Engineering MEng Honours (H292)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h200/modules/","Civil Engineering BEng Honours (H200)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h290/modules/","Civil Engineering MEng Honours (H290)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h201/modules/","Civil Engineering with Foundation Year BEng Honours (H201)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h291/modules/","Civil Engineering with Foundation Year MEng Honours (H291)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/v110/modules/","Ancient History BA Honours (V110)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/vv14/modules/","Ancient History and Archaeology BA Honours (VV14)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q810/modules/","Classical Studies BA Honours (Q810)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/qq83/modules/","Classical Studies and English BA Honours (QQ83)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q800/modules/","Classics BA Honours (Q800)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g400/modules/","Computer Science BSc Honours (G400)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g405/modules/","Computer Science MComp Honours (G405)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g406/modules/","Computer Science (Study Abroad) MComp Honours (G406)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g401/modules/","Computer Science with Industrial Placement BSc Honours (G401)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i100/modules/#d.en.132956","Computer Science with Industrial Placement MComp Honours (I100)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i520/modules/","Computer Science (Bio-Computing) BSc Honours (I520)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i522/modules/","Computer Science (Bio-Computing) MComp Honours (I522)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i521/modules/","Computer Science with Industrial Placement (Bio-Computing) BSc Honours (I521)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i524/modules/#d.en.132961","Computer Science with Industrial Placement (Bio-Computing) MComp Honours (I524)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g450/modules/","Computer Science (Game Engineering) BSc Honours (G450)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i610/modules/","Computer Science (Game Engineering) MComp Honours (I610)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g451/modules/","Computer Science with Industrial Placement (Game Engineering) BSc Honours (G451)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i612/modules/#d.en.132964","Computer Science with Industrial Placement (Game Engineering) MComp Honours (I612)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i140/modules/#d.en.133000","Computer Science (Human-Computer Interaction) BSc Honours (I140)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i141/modules/#d.en.133008","Computer Science with Industrial Placement (Human-Computer Interaction) BSc Honours (I141)&nbsp;"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g420/modules/","Computer Science (Mobile and Distributed Systems) BSc Honours (G420)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i120/modules/","Computer Science (Mobile and Distributed Systems) MComp Honours (I120)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g421/modules/","Computer Science with Industrial Placement (Mobile and Distributed Systems) BSc Honours (G421)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i122/modules/#d.en.132966","Computer Science with Industrial Placement (Mobile and Distributed Systems) MComp Honours (I122)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i190/modules/","Computer Science (Security and Resilience) BSc Honours (I190)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i192/modules/","Computer Science (Security and Resilience) MComp Honours (I192)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i191/modules/","Computer Science with Industrial Placement (Security and Resilience) BSc Honours (I191)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/i194/modules/#d.en.132967","Computer Science with Industrial Placement (Security and Resilience) MComp Honours (I194)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g600/modules/","Computer Science (Software Engineering) BSc Honours (G600)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g603/modules/","Computer Science with Industrial Placement (Software Engineering) BSc Honours (G603)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/a206/modules/","Dental Surgery BDS Honours (A206)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/a207/","Oral and Dental Health Sciences BSc Honours (A207)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f641/modules/#d.en.143078","Earth Science BSc Honours (F641)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f640/modules/#d.en.146172","Earth Science MEarthSci Honours (F640)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/l100/modules/","Economics BSc Honours (L100)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/ln12/modules/","Economics and Business Management BA Honours (LN12)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/l161/modules/","Economics and Finance BSc Honours (L161)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/gl11/modules/","Economics and Mathematics BSc Honours (GL11)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/ll21/modules/","Politics and Economics BA Honours (LL21)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/x390/modules/#d.en.139623","Education BA Honours (X390)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h660/modules/#d.en.121508","Automation and Control BEng Honours (H660)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h661/modules/#d.en.121513","Automation and Control with Industrial Project MEng Honours (H661)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h990/modules/#d.en.121543","Digital Electronics BEng Honours (H990)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h991/modules/#d.en.121548","Digital Electronics with Industrial Project MEng Honours (H991)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h607/modules/","Electrical and Electronic Engineering BEng Honours (H607)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h604/modules/","Electrical and Electronic Engineering with Foundation Year BEng Honours (H604)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h606/modules/","Electrical and Electronic Engineering with Foundation Year MEng Honours (H606)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h605/modules/","Electrical and Electronic Engineering with Industrial Project MEng Honours (H605)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h623/modules/","Electrical Power Engineering BEng Honours (H623)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h622/modules/#d.en.121560","Electrical Power Engineering with Industrial Project MEng Honours (H622)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h640/modules/","Electronic Communications BEng Honours (H640)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h621/modules/","Electronic Communications with Industrial Project MEng Honours (H621)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h652/modules/","Electronics and Computer Engineering BEng Honours (H652)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h654/modules/","Electronics and Computer Engineering with Industrial Project MEng Honours (H654)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h611/modules/","Microelectronic Engineering BEng Honours (H611)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h612/modules/","Microelectronic Engineering with Industrial Project MEng Honours (H612)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/qq83/modules/","Classical Studies and English BA Honours (QQ83)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/qv31/modules/#d.en.122797","English Literature and History BA Honours (QV31)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q302/modules/","English Language BA Honours (Q302)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q300/modules/","English Language and Literature BA Honours (Q300)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q306/modules/","English Literature BA Honours (Q306)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/qw38/modules/","English Literature with Creative Writing BA Honours (QW38)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q100/modules/","Linguistics BA Honours (Q100)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q1t4/modules/","Linguistics with Chinese or Japanese BA Honours (Q1T4)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q1r1/modules/","Linguistics with French BA Honours (Q1R1)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q1r2/modules/","Linguistics with German BA Honours (Q1R2)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q1r4/modules/","Linguistics with Spanish BA Honours (Q1R4)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/qt19/modules/","Modern Languages and Linguistics BA Honours (QT19)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/d455/modules/","Countryside Management BSc Honours (D455)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f850/modules/","Environmental Science BSc Honours (F850)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f8d4/modules/","Environmental Sciences (Agricultural and Environmental Science) MEnv Honours (F8D4)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f8h8/modules/","Environmental Sciences (Clean Technology) MEnv Honours (F8H8)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f8c1/modules/","Environmental Sciences (Ecosystem Management) MEnv Honours (F8C1)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f8f6/modules/","Environmental Sciences (Environmental Geochemistry) MEnv Honours (F8F6)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/d452/modules/","Rural Studies BSc Honours (D452)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b9c6/modules/#d.en.147018","Exercise Biomedicine BSc Honours (B9C6)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/p303/modules/#d.en.147064","Film and Media BA Honours (P303)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/p313/modules/#d.en.284890","Film Practices (P313)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/w150/modules/","Fine Art BA Honours (W150)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h814/modules/","Chemical Engineering with Foundation Year BEng Honours (H814)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h816/modules/","Chemical Engineering with Foundation Year MEng Honours (H816)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h201/modules/","Civil Engineering with Foundation Year BEng Honours (H201)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h291/modules/","Civil Engineering with Foundation Year MEng Honours (H291)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h604/modules/","Electrical and Electronic Engineering with Foundation Year BEng Honours (H604)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h606/modules/","Electrical and Electronic Engineering with Foundation Year MEng Honours (H606)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h101/modules/","Engineering with Foundation Year BEng Honours (H101)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h103/modules/","Engineering with Foundation Year MEng Honours (H103)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/j615/modules/","Marine Technology with Foundation Year BEng Honours (J615)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/j616/modules/","Marine Technology with Foundation Year MEng Honours (J616)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g101/modules/","Mathematical Sciences with Foundation Year BSc Honours (G101)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h304/modules/","Mechanical Engineering with Foundation Year BEng Honours (H304)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h305/modules/","Mechanical Engineering with Foundation Year MEng Honours (H305)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b901/modules/","Biomedical Genetics BSc Honours (B901)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b903/modules/#d.en.228053","Biomedical Genetics (Integrated Master's) MSci Honours (B903)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f862/modules/","Geographic Information Science BSc Honours (F862)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f800/modules/","Geography BSc Honours (F800)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/l701/modules/","Geography BA Honours (L701)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/lk74/modules/","Geography and Planning BA Honours (LK74)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/fh82/modules/","Physical Geography BSc Honours (FH82)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h244/modules/","Surveying and Mapping Science BSc Honours (H244)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/qv31/modules/#d.en.122797","English Literature and History BA Honours (QV31)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/v100/modules/","History BA Honours (V100)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/vv41/modules/","History and Archaeology BA Honours (VV41)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/vl12/modules/","Politics and History BA Honours (VL12)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/w150/modules/","Fine Art BA Honours (W150)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/ng41/modules/","Accounting and Mathematics BSc Honours (NG41)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/cc18/modules/","Biology and Psychology BSc Honours (CC18)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/gl11/modules/","Economics and Mathematics BSc Honours (GL11)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/cg81/modules/","Mathematics and Psychology BSc Honours (CG81)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/bc48/modules/","Nutrition and Psychology BSc Honours (BC48)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/p500/modules/#d.en.147065","Journalism, Media and Culture BA Honours (P500)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/m101/modules/","Law LLB Honours (M101)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q100/modules/","Linguistics BA Honours (Q100)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q1t4/modules/","Linguistics with Chinese or Japanese BA Honours (Q1T4)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q1r1/modules/","Linguistics with French BA Honours (Q1R1)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q1r2/modules/","Linguistics with German BA Honours (Q1R2)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/q1r4/","Linguistics with Spanish BA Honours (Q1R4)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/qt19/modules/","Modern Languages and Linguistics BA Honours (QT19)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c161/modules/","Marine Biology BSc Honours (C161)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/cf17/modules/","Marine Biology and Oceanography BSc Honours (CF17)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c350/modules/","Marine Zoology BSc Honours (C350)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/j615/modules/","Marine Technology with Foundation Year BEng Honours (J615)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/j616/modules/","Marine Technology with Foundation Year MEng Honours (J616)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h504/modules/","Marine Technology with Marine Engineering BEng Honours (H504)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h501/modules/","Marine Technology with Marine Engineering MEng Honours (H501)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h502/modules/","Marine Technology with Naval Architecture BEng Honours (H502)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h503/modules/","Marine Technology with Naval Architecture MEng Honours (H503)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h355/modules/","Marine Technology with Offshore Engineering BEng Honours (H355)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h356/modules/","Marine Technology with Offshore Engineering MEng Honours (H356)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h520/modules/","Marine Technology with Small Craft Technology BEng Honours (H520)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h524/modules/","Marine Technology with Small Craft Technology MEng Honours (H524)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/db64/modules/","Food Marketing and Nutrition BSc Honours (DB64)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/n5n2/modules/","International Marketing and Management BSc Honours (N5N2) - London campus"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/n500/modules/","Marketing BSc Honours (N500)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/nn52/modules/","Marketing and Management BA Honours (NN52)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/ng41/modules/","Accounting and Mathematics BSc Honours (NG41)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/gl11/modules/","Economics and Mathematics BSc Honours (GL11)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g101/modules/","Mathematical Sciences with Foundation Year BSc Honours (G101)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g100/modules/","Mathematics BSc Honours (G100)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g103/modules/","Mathematics MMath Honours (G103)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/cg81/modules/","Mathematics and Psychology BSc Honours (CG81)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/gg13/modules/","Mathematics and Statistics BSc Honours (GG13)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/ggc3/modules/","Mathematics and Statistics MMathStat Honours (GGC3)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g1n3/modules/","Mathematics with Finance BSc Honours (G1N3)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g1n2/modules/","Mathematics with Management BSc Honours (G1N2)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/g300/modules/","Statistics BSc Honours (G300)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h390/modules/","Mechanical and Low Carbon Transport Engineering MEng Honours (H390)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/hh73/modules/","Mechanical Design and Manufacturing Engineering BEng Honours (HH73)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/hh37/modules/","Mechanical Design and Manufacturing Engineering MEng Honours (HH37)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h300/modules/","Mechanical Engineering BEng Honours (H300)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h301/modules/","Mechanical Engineering MEng Honours (H301)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h3h8/modules/","Mechanical Engineering with Biomedical Engineering MEng Honours (H3H8)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h304/modules/","Mechanical Engineering with Foundation Year BEng Honours (H304)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h305/modules/","Mechanical Engineering with Foundation Year MEng Honours (H305)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h3h6/modules/","Mechanical Engineering with Mechatronics MEng Honours (H3H6)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h3h9/modules/","Mechanical Engineering with Microsystems MEng Honours (H3H9)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/p303/modules/#d.en.147064","Film and Media BA Honours (P303)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/p500/modules/#d.en.147065","Journalism, Media and Culture BA Honours (P500)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/pql0/modules/","Media, Communication and Cultural Studies BA Honours (PQL0)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/a100/modules/","Medicine and Surgery MB BS Honours (A100)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/a101/modules/","Medicine and Surgery (Accelerated Programme) MB BS Honours (A101)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/tt12/modules/","Chinese Studies OR Japanese Studies BA Honours (TT12)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/t901/modules/","Modern Languages BA Honours (T901)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/tn92/modules/","Modern Languages and Business Studies BA Honours (TN92)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/qt19/modules/","Modern Languages and Linguistics BA Honours (QT19)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/r9q9/modules/#d.en.132937","Modern Languages, Translation and Interpreting (R9Q9)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/rt47/modules/","Spanish, Portuguese and Latin American Studies BA Honours (RT47)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/w301/modules/","Contemporary and Popular Music BA Honours (W301)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/w344/modules/#d.en.63245","Folk and Traditional Music BA Honours (W344)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/w304/modules/","Music BMus Honours (W304)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/w300/modules/","Music BA Honours (W300)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b4d6/modules/","Food and Human Nutrition BSc Honours (B4D6)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/db64/modules/","Food Marketing and Nutrition BSc Honours (DB64)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/bc48/modules/","Nutrition and Psychology BSc Honours (BC48)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b210/modules/","Pharmacology BSc Honours (B210)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/v500/modules/","Philosophy BA Honours (V500)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f300/modules/#d.en.139167","Physics BSc Honours (F300)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/f303/modules/#d.en.146200","Physics MPhys Honours (F303)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/l241/modules/","Government and European Union Studies BA Honours (L241)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/l200/modules/","Politics BA Honours (L200)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/ll21/modules/","Politics and Economics BA Honours (LL21)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/vl12/modules/","Politics and History BA Honours (VL12)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/ll32/modules/","Politics and Sociology BA Honours (LL32)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/cc18/modules/","Biology and Psychology BSc Honours (CC18)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/cg81/modules/","Mathematics and Psychology BSc Honours (CG81)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/bc48/modules/","Nutrition and Psychology BSc Honours (BC48)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c800/modules/","Psychology BSc Honours (C800)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/y001/modules/","Combined Honours BA Honours (Y001)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/ll32/modules/","Politics and Sociology BA Honours (LL32)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/l300/modules/","Sociology BA Honours (L300)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/b620/modules/","Speech and Language Sciences BSc Honours (B620)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/h244/modules/","Surveying and Mapping Science BSc Honours (H244)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/k190/modules/","Architecture and Urban Planning BA Honours (K190)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/lk74/modules/","Geography and Planning BA Honours (LK74)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/k400/modules/","Master of Planning MPlan Honours (K400)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/k421/modules/","Urban Planning BA Honours (K421)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c350/modules/","Marine Zoology BSc Honours (C350)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c300/modules/","Zoology BSc Honours (C300)"},
		{"http://www.ncl.ac.uk/undergraduate/degrees/c301/modules/#d.en.228027","Zoology MBiol Honours (C301)"},

	};
    public static String[][] PostData={
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/advanced-computer-science-msc/","Advanced Computer Science MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/advanced-electrical-power-engineering-msc/","Advanced Electrical Power Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/advanced-international-business-management-ma-msc/","Advanced International Business Management (Dual Award) MA, MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/advanced-int-bus-mgt-marketing-msc-msc/","Advanced International Business Management and Marketing MSc, MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/ageing-health-mres/","Ageing and Health MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/ageing-mphil-phd-md/","Ageing MPhil, PhD, MD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/agricultural-environmental-science-msc/","Agricultural and Environmental Science MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/agriculture-mphil-phd/","Agriculture MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/animal-behaviour-mres/","Animal Behaviour MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/applied-animal-behaviour-welfare-msc-pgdip/","Applied Animal Behaviour and Welfare MSc, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/applied-educational-psychology-doctor-of-dappedpsy/","Applied Educational Psychology Doctor of (DAppEdPsy)"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/applied-linguistics-tesol-ma/","Applied Linguistics and TESOL MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/applied-linguistics-research-ma/","Applied Linguistics Research MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/applied-process-control-msc-pgdip/","Applied Process Control MSc, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/archaeology-ma/","Archaeology MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/archaeology-mlitt/","Archaeology MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/archaeology-mphil-phd/","Archaeology MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/architectural-design-research-ma/","Architectural Design Research MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/architectural-practice-management-pgdip/","Architectural Practice and Management PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/architecture-master-of-march/","Architecture, Master of (MArch)"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/architecture-planning-landscape-design-ma/","Architecture, Planning and Landscape (Design) MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/architecture-planning-landscape-ma/","Architecture, Planning and Landscape MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/architecture-planning-landscape-mphil-phd/","Architecture, Planning and Landscape MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/art-museum-gallery-practice-mprac/","Art Museum and Gallery Practice MPrac"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/art-museum-gallery-studies-ma-pgdip/","Art Museum and Gallery Studies MA, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/arts-business-creativity-ma/","Arts, Business and Creativity MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/automation-control-msc/","Automation and Control MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/banking-finance-msc/","Banking and Finance MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/banking-finance-london-msc/","Banking and Finance MSc (London campus)"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/biodiversity-conservation-ecosystem-management-msc/","Biodiversity Conservation and Ecosystem Management MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/bioinformatics-msc/","Bioinformatics MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/biological-sciences-mphil-phd/","Biological Sciences MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/biomedical-engineering-msc/","Biomedical Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/biomedicine-mphil-phd-md/","Biomedicine MPhil, PhD, MD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/biosciences-mphil-phd-md/","Biosciences MPhil, PhD, MD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/biosciences-mres/","Biosciences MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/biotechnology-business-enterprise-mres/","Biotechnology and Business Enterprise MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/biotechnology-mphil-phd/","Biotechnology MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/british-history-ma/","British History MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/business-management-mphil-phd/","Business and Management MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/cancer-mphil-phd-md/","Cancer MPhil, PhD, MD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/cancer-mres/","Cancer MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/cancer-studies-pgcert/","Cancer Studies PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/cardiovascular-science-in-health-disease-mres/","Cardiovascular Science in Health and Disease MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/chemical-engineering-mphil-phd/","Chemical Engineering MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/chemistry-mphil-phd/","Chemistry MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/chinese-studies-mlitt/","Chinese Studies MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/civil-engineering-environmental-mphil-phd/","Civil Engineering (Environmental) MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/civ-eng-geotechnical-engineering-geology-mphil-phd/","Civil Engineering (Geotechnical and Engineering Geology) MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/civil-engineering-structural-mphil-phd/","Civil Engineering (Structural) MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/civil-engineering-transport-mphil-phd/","Civil Engineering (Transport) MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/civil-engineering-water-resources-mphil-phd/","Civil Engineering (Water Resources) MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/classics-ancient-history-ma/","Classics and Ancient History MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/classics-ancient-history-mphil-phd/","Classics and Ancient History MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/classics-mlitt/","Classics MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clean-technology-msc-pgdip/","Clean Technology MSc, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clinical-health-sciences-msc-pgdip-pgcert/","Clinical and Health Sciences MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clinical-health-sciences-ageing-msc-pgdip-pgcert/","Clinical and Health Sciences with Ageing MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clinical-health-sciences-allergy-pgcert/","Clinical and Health Sciences with Allergy PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clin-healthsciences-clinresearch-msc-pgdip-pgcert/","Clinical and Health Sciences with Clinical Research MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clinical-health-sciences-surgery-pgcert/","Clinical and Health Sciences with Surgery PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clin-health-sci-therapeutics-msc-pgdip-pgcert/","Clinical and Health Sciences with Therapeutics MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clinical-implant-dentistry-pgdip/","Clinical Implant Dentistry PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clinical-leadership-pgcert/","Clinical Leadership PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clinical-linguistics-evi-based-prac-research-msc/","Clinical Linguistics and Evidence Based Practice (Research) MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clinical-psychology-doctor-of-dclinpsychol/","Clinical Psychology Doctor of (DClinPsychol)"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clinical-research-age-mclinres-pgdip-pgcert/","Clinical Research/Clinical Research (Ageing) MClinRes, PGDip, PGCert (E-learning)"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clinical-research-leader-mclinres-pgdip-pgcert/","Clinical Research/Clinical Research (Leadership) MClinRes, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/clinical-science-msc/","Clinical Science (pathways in Medical Physics and Physiological Sciences) MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/cloud-computing-msc/","Cloud Computing MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/coaching-mentoring-for-teacher-development-pgcert/","Coaching and Mentoring for Teacher Development PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/cognitive-behav-therapy-anxiety-disorders-pgcert/","Cognitive Behavioural Therapy for Anxiety Disorders PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/cognitive-behavioural-therapy-pgdip/","Cognitive Behavioural Therapy PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/communications-signal-processing-msc/","Communications and Signal Processing MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/computational-neuroscience-neuroinformatics-msc/","Computational Neuroscience and Neuroinformatics MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/computational-systems-biology-msc/","Computational Systems Biology MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/computer-game-engineering-msc/","Computer Game Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/computer-science-integrated-phd/","Computer Science Integrated PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/computer-science-mphil-phd/","Computer Science MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/computer-science-msc/","Computer Science MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/computer-security-resilience-msc/","Computer Security and Resilience MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/conscious-sedation-in-dentistry-pgdip/","Conscious Sedation in Dentistry PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/creative-arts-practice-ma/","Creative Arts Practice MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/creative-writing-ma-pgcert/","Creative Writing MA, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/creative-writing-mphil-phd/","Creative Writing MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/cross-cultural-communication-ma/","Cross Cultural Communication MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/ccc-applied-linguistics-ma/","Cross-Cultural Communication and Applied Linguistics MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/cross-cultural-communication-education-ma/","Cross-Cultural Communication and Education MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/ccc-international-management-ma/","Cross-Cultural Communication and International Management MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/ccc-int-marketing-ma/","Cross-Cultural Communication and International Marketing MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/ccc-int-relations-ma/","Cross-Cultural Communication and International Relations MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/cross-cultural-communication-media-studies-ma/","Cross-Cultural Communication and Media Studies MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/dentistry-dental-sciences-mphil-phd/","Dentistry and Dental Sciences MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/design-manufacturing-engineering-msc/","Design and Manufacturing Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/diabetes-mres/","Diabetes MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/digital-civics-mres/","Digital Civics MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/digital-media-phd/","Digital Media PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/drug-chemistry-msc/","Drug Chemistry MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/e-business-e-marketing-msc/","E-Business (E-Marketing) MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/e-business-information-systems-msc/","E-Business (Information Systems) MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/e-business-msc/","E-Business MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/ecological-consultancy-msc/","Ecological Consultancy MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/economics-mphil-phd/","Economics MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/education-clinical-mphil-phd/","Education (Clinical) MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/education-communication-integrated-phd/","Education and Communication Integrated PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/education-doctor-of-edd/","Education Doctor of (EdD)"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/education-mphil-phd/","Education MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/education-research-ma/","Education Research MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/edu-int-perspectives-dev-education-ma/","Education: International Perspectives (Development and Education) MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/edu-int-perspectives-leadership-management-ma/","Education: International Perspectives (Leadership and Management) MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/edu-int-perspectives-teaching-learning-ma/","Education: International Perspectives (Teaching and Learning) MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/edu-int-perspectives-technology-education-ma/","Education: International Perspectives (Technology in Education) MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/educational-applied-linguistics-integrated-phd/","Educational and Applied Linguistics Integrated PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/educational-leadership-pgcert/","Educational Leadership PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/educational-research-innovation-pgcert/","Educational Research and Innovation PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/electrical-electronic-engineering-phd/","Electrical and Electronic Engineering PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/electrical-power-msc/","Electrical Power MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/employee-relations-ma-pgdip-pgcert/","Employee Relations MA, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/energy-mphil-phd/","Energy MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/engineering-science-marine-environment-iphd/","Engineering and Science in the Marine Environment Integrated PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/engineering-geology-msc/","Engineering Geology MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/english-language-linguistics-mlitt/","English Language and/or Linguistics MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/english-literature-1500-1900-ma/","English Literature 1500-1900 MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/english-literature-mlitt/","English Literature MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/english-literature-mphil-phd/","English Literature MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/environmental-petroleum-geochemistry-msc/","Environmental and Petroleum Geochemistry MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/environmental-consultancy-msc/","Environmental Consultancy MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/environmental-engineering-msc/","Environmental Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/environmental-law-policy-research-llm/","Environmental Law and Policy (Research) LLM"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/environ-regulation-sustainable-development-llm/","Environmental Regulation and Sustainable Development LLM"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/environmental-resource-assessment-msc/","Environmental Resource Assessment MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/environmental-science-mphil-phd/","Environmental Science MPhil PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/epidemiology-mres/","Epidemiology MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/european-history-ma/","European History MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/european-union-studies-ma/","European Union Studies MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/evolution-human-behaviour-mres/","Evolution and Human Behaviour MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/experimental-architecture-msc/","Experimental Architecture MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/film-studies-mlitt/","Film Studies MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/film-studies-mphil-phd/","Film Studies, MPhil PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/film-theory-practice-ma/","Film: Theory and Practice MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/finance-accounting-mphil-phd/","Finance and Accounting MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/finance-economics-research-ma/","Finance and Economics (Research) MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/finance-msc/","Finance MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/finance-accounting-business-graduate-diploma/","Finance, Accounting and Business Graduate Diploma"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/fine-art-mfa/","Fine Art MFA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/fine-art-mphil-phd/","Fine Art MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/flood-risk-management-msc/","Flood Risk Management MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/food-human-nutrition-mphil-phd/","Food and Human Nutrition MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/food-rural-development-research-msc/","Food and Rural Development Research MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/forensic-psychology-msc/","Forensic Psychology MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/french-mlitt/","French MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/genetics-mphil-phd-md/","Genetics MPhil, PhD, MD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/genomic-medicine-msc-pgdip-pgcert/","Genomic Medicine MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/geochemistry-mphil-phd/","Geochemistry MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/geography-mphil-phd/","Geography MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/geomatics-mphil-phd/","Geomatics MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/geotechnical-engineering-msc/","Geotechnical Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/german-mlitt/","German MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/global-master-of-business-administration-mba/","Global Master of Business Administration MBA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/health-services-research-msc/","Health Services Research MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/heritage-practice-mprac/","Heritage Practice MPrac"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/heritage-studies-ma-pgdip/","Heritage Studies MA, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/heritage-gallery-museum-studies-pgcert/","Heritage, Gallery and Museum Studies PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/heritage-museums-galleries-mlitt/","Heritage, Museums and Galleries MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/history-ma/","History MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/history-mlitt/","History MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/history-mphil-phd/","History MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/history-of-medicine-ma/","History of Medicine MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/human-geography-research-ma/","Human Geography Research MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/human-resource-management-ma/","Human Resource Management MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/hydrogeology-water-management-msc/","Hydrogeology and Water Management MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/hydroinformatics-water-management-euro-aquae-msc/","Hydroinformatics and Water Management (Euro Aquae) MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/hydroinformatics-msc/","Hydroinformatics MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/hydrology-climate-change-msc/","Hydrology and Climate Change MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/immunobiology-mres/","Immunobiology MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/industrial-commercial-biotechnology-msc/","Industrial and Commercial Biotechnology MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/innovation-creativity-entrepreneurship-msc/","Innovation, Creativity and Entrepreneurship MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/innovative-pedagogy-curriculum-pgcert/","Innovative Pedagogy and Curriculum PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-business-law-llm/","International Business Law LLM"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-business-management-msc/","International Business Management MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-business-management-london-msc/","International Business Management MSc (London campus)"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-development-education-ma/","International Development and Education MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/int-dev-edu-cross-cultural-comms-ma/","International Development and Education with Cross Cultural Communication MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-economics-finance-msc/","International Economics and Finance MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-financial-analysis-ma/","International Financial Analysis MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-human-resource-management-ma/","International Human Resource Management MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-legal-studies-llm/","International Legal Studies LLM"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/int-marine-enviro-consultancy-imec-msc-pgdip/","International Marine Environmental Consultancy (IMEC) MSc, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-marketing-msc/","International Marketing MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/int-marketing-london-msc/","International Marketing MSc (London campus)"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-multimedia-journalism-ma/","International Multimedia Journalism MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-political-economy-ma/","International Political Economy MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-politics-critical-geopolitics-ma/","International Politics (Critical Geopolitics) MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-politics-global-justice-ethics-ma/","International Politics (Global Justice and Ethics) MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/int-politics-globalisation-poverty-development-ma/","International Politics (Globalisation, Poverty and Development) MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-spatial-planning-msc/","International Spatial Planning MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/international-studies-ma/","International Studies MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/interpreting-ma/","Interpreting MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/japanese-studies-mlitt/","Japanese Studies MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/journalism-public-relations-phd/","Journalism and Public Relations PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/landscape-architecture-studies-ma/","Landscape Architecture Studies MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/language-pathology-msc/","Language Pathology MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/latin-american-interdisciplinary-studies-ma/","Latin American Interdisciplinary Studies MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/latin-american-studies-mlitt/","Latin American Studies MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/law-llm-by-research-mphil-phd/","Law LLM (by research), MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/linguistics-englishlang-langacq-eurolang-ma/","Linguistics (with specialist pathways in English Language, Language Acquisition, and European Languages) MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/linguistics-english-language-integrated-phd/","Linguistics and English Language Integrated PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/linguistics-applied-linguistics-mphil-phd/","Linguistics, Applied Linguistics MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/local-regional-development-research-ma/","Local and Regional Development (Research) MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/low-carbon-transport-engineering-msc/","Low Carbon Transport Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/low-intensity-psychological-therapies-pgcert/","Low Intensity Psychological Therapies PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/management-business-studies-research-ma-pgdip/","Management and Business Studies (Research) MA, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/marine-ecosystems-governance-mres/","Marine Ecosystems and Governance MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/marine-engineering-msc/","Marine Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/marine-sciences-mphil-phd/","Marine Sciences MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/marine-tech-int-singapore-msc-pgdip-pgcert/","Marine Technology (International) - Singapore MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/marine-tech-edu-consortium-mtec-msc-pgdip-pgcert/","Marine Technology Education Consortium (MTEC) MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/marine-technology-mphil-phd/","Marine Technology MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/marine-transport-with-management-msc/","Marine Transport with Management MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/marketing-mphil-phd/","Marketing MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/master-of-business-administration-mba/","Master of Business Administration MBA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/materials-design-engineering-msc/","Materials Design and Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/materials-engineering-mphil-phd/","Materials Engineering MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/mathematics-statistics-integrated-phd/","Mathematics and Statistics Integrated PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/mathematics-mphil-phd/","Mathematics MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/mechanical-systems-engineering-mphil-phd/","Mechanical and Systems Engineering MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/mechanical-engineering-msc/","Mechanical Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/mechatronics-msc/","Mechatronics MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/media-cultural-studies-mphil-phd/","Media and Cultural Studies MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/media-journalism-ma/","Media and Journalism MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/media-public-relations-ma/","Media and Public Relations MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/medical-molecular-biosciences-mres/","Medical and Molecular Biosciences MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/medical-education-mmeded-pgdip-pgcert/","Medical Education MMedEd, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/medical-genetics-mres/","Medical Genetics MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/medical-sciences-mres/","Medical Sciences MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/medical-sciences-msc/","Medical Sciences MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/medical-technology-innovation-mres/","Medical Technology Innovation MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/medicinal-plants-functional-foods-msc/","Medicinal Plants and Functional Foods MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/medicine-surgery-mphil-phd-md/","Medicine and Surgery MPhil, PhD, MD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/microbiology-mphil-phd-md/","Microbiology MPhil, PhD, MD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/microelectronics-msc/","Microelectronics MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/mitochondrial-biology-medicine-mres/","Mitochondrial Biology and Medicine MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/modern-contemporary-literature-ma/","Modern and Contemporary Literature MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/modern-languages-mlitt/","Modern Languages MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/modern-languages-mphil-phd/","Modern Languages MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/molecular-microbiology-mres/","Molecular Microbiology MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/musculoskeletal-ageing-cima-mres/","Musculoskeletal Ageing (CIMA) MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/museum-practice-mprac/","Museum Practice MPrac"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/museum-studies-ma-pgdip/","Museum Studies MA, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/museum-gallery-heritage-studies-mphil-phd/","Museum, Gallery and Heritage Studies MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/music-mlitt/","Music MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/music-mmus-pgdip/","Music MMus, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/music-mphil-phd/","Music MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/nanoscale-science-technology-mphil-phd/","Nanoscale Science and Technology MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/naval-architecture-msc/","Naval Architecture MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/neuromuscular-diseases-mres/","Neuromuscular Diseases MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/neuroscience-mphil-phd-md/","Neuroscience MPhil, PhD, MD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/neuroscience-mres/","Neuroscience MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/offshore-engineering-msc/","Offshore Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/oncology-pharmaceutical-industry-msc-pgdip/","Oncology for the Pharmaceutical Industry MSc, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/oncology-msc-pgdip/","Oncology MSc, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/operations-management-dual-award-msc-msc/","Operations Management (Dual Award) MSc/MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/operations-management-logistics-accounting-msc/","Operations Management, Logistics and Accounting MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/operations-logistics-supply-chain-management-msc/","Operations, Logistics and Supply Chain Management MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/organic-farming-food-production-systems-msc/","Organic Farming and Food Production Systems MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/orthodontics-msc/","Orthodontics MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/palliative-care-msc-pgdip/","Palliative Care MSc, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/petroleum-geochemistry-msc/","Petroleum Geochemistry MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/philosophical-studies-mphil-phd/","Philosophical Studies MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/phonetics-phonology-integrated-phd/","Phonetics and Phonology Integrated PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/physics-mphil-phd/","Physics MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/pipeline-engineering-msc-pgdip-pgcert/","Pipeline Engineering MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/planning-environment-research-ma/","Planning and Environment Research MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/planning-for-sustainability-climate-change-msc/","Planning for Sustainability and Climate Change MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/politics-research-ma/","Politics (Research) MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/politics-mphil-phd/","Politics MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/portuguese-mlitt/","Portuguese MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/pgce-schools-direct/","Postgraduate Certificate in Education (PGCE) - Schools Direct"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/postgraduate-certificate-in-education-pgce-primary/","Postgraduate Certificate in Education (PGCE) Primary (with Qualified Teacher Status QTS)"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/pgce-secondary/","Postgraduate Certificate in Education (PGCE) Secondary (with Qualified Teacher Status QTS)"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/power-distribution-engineering-msc-pgdip-pgcert/","Power Distribution Engineering MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/practitioner-enquiry-leadership-med/","Practitioner Enquiry Med, Practitioner Enquiry (Leadership), Master of (Med)"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/praxis-cog-behavioural-therapy-studies-pgcert/","Praxis Cognitive Behavioural Therapy Studies PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/professional-translating-for-european-languages-ma/","Professional Translating for European Languages MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/psychology-foundations-clinical-forensic-msc/","Psychology (Foundations in Clinical and Forensic Psychology) MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/psychology-foundations-in-clinical-health-msc/","Psychology (Foundations in Clinical and Health Psychology) MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/psychology-mphil-phd/","Psychology MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/public-health-hsresearch-msc-pgdip-pgcert/","Public Health and Health Services Research MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/public-health-mph/","Public Health MPH"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/public-health-epidemiology-hsresearch-mphil-phd-md/","Public Health, Epidemiology and Health Services Research MPhil, PhD, MD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/quantitative-finance-risk-management-msc/","Quantitative Finance and Risk Management MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/rail-logistics-msc-pgdip-pgcert/","Rail and Logistics MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/regional-development-spatial-planning-ma/","Regional Development and Spatial Planning MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/reflex-msc-pgdip-pgcert/","Renewable Energy Flexible Training Programme (REFLEX) MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/reem-msc-pgdip-pgcert/","Renewable Energy, Enterprise and Management (REEM) MSc, PGDip, PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/research-training-pgcert/","Research Training PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/restorative-dentistry-mclindent/","Restorative Dentistry MClinDent"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/roman-frontier-studies-ma/","Roman Frontier Studies MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/stream-engd/","Skills, Technology, Research and Management for the UK Water Sector (STREAM) EngD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/social-science-health-research-msc/","Social Science and Health Research MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/sociolinguistics-research-ma-pgdip/","Sociolinguistics (Research) MA, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/sociology-social-research-ma/","Sociology and Social Research MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/sociology-ma/","Sociology MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/sociology-mphil-phd/","Sociology MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/spanish-mlitt/","Spanish MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/spatial-planning-pgdip/","Spatial Planning PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/speech-language-sciences-mphil-phd/","Speech and Language Sciences MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/statistics-mphil-phd/","Statistics MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/stem-cells-regenerative-medicine-mres/","Stem Cells and Regenerative Medicine MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/strategic-planning-investment-msc/","Strategic Planning and Investment MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/structural-engineering-msc/","Structural Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/subsea-engineering-management-msc/","Subsea Engineering and Management MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/sustainable-agriculture-food-security-mres/","Sustainable Agriculture and Food Security MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/sustainable-agriculture-food-security-msc/","Sustainable Agriculture and Food Security MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/sustainable-buildings-environments-msc/","Sustainable Buildings and Environments MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/sustainable-chemical-engineering-msc-pgdip/","Sustainable Chemical Engineering MSc, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/synthetic-biology-msc/","Synthetic Biology MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/systems-biology-mres/","Systems Biology MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/technology-in-the-marine-environment-mres/","Technology in the Marine Environment MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/town-planning-diploma/","Town Planning Diploma"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/town-planning-msc/","Town Planning MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/toxicology-mres/","Toxicology MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/translating-interpreting-ma/","Translating and Interpreting MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/translating-interpreting-mphil-phd/","Translating and Interpreting MPhil, PhD"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/translating-ma/","Translating MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/translation-studies-ma/","Translation Studies MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/translation-studies-mlitt/","Translation Studies MLitt"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/translational-medicine-therapeutics-mres/","Translational Medicine and Therapeutics MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/transplantation-mres/","Transplantation MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/transplantation-pgcert/","Transplantation PGCert"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/transport-pgdip/","Transport PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/transport-planning-business-management-msc/","Transport Planning and Business Management MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/transport-planning-engineering-msc/","Transport Planning and Engineering MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/transport-planning-its-msc/","Transport Planning and Intelligent Transport Systems (ITS) MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/transport-planning-environment-msc/","Transport Planning and the Environment MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/urban-design-ma-pgdip/","Urban Design MA, PGDip"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/urban-energy-technology-policy-mres/","Urban Energy Technology and Policy MRes"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/urban-energy-technology-policy-msc/","Urban Energy Technology and Policy (with specialist pathways in Planning, Architecture and Engineering) MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/wildlife-management-msc/","Wildlife Management MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/wireless-embedded-systems-msc/","Wireless Embedded Systems MSc"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/world-politics-popular-culture-ma/","World Politics and Popular Culture MA"},
    	{"http://www.ncl.ac.uk/postgraduate/courses/degrees/writing-poetry-ma/","Writing Poetry MA"}
    };
}
