package no6.bournemouth;

import java.io.File;
import java.io.FileInputStream;

import org.htmlparser.Parser;
import org.htmlparser.filters.AndFilter;
import org.htmlparser.filters.HasAttributeFilter;
import org.htmlparser.filters.TagNameFilter;
import org.htmlparser.tags.LinkTag;
import org.htmlparser.util.NodeList;

public class getURL {

	/**
	 * @param args
	 */
	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub

		FileInputStream fis=new FileInputStream(new File("./bournemouthPost.html"));
		byte[] b=new byte[fis.available()];
        fis.read(b);
       fis.close();
        String htmls=new String(b);
       int count=1;
	    Parser	parser=Parser.createParser(htmls, "utf-8");
   	    AndFilter ProfessionNameFilter=new AndFilter(new TagNameFilter("a"),
                   new HasAttributeFilter("href"));
   	    NodeList nodes4=parser.extractAllNodesThatMatch(ProfessionNameFilter);
   	    for(int i=0;i<nodes4.size();i++)
   	    {
   	    	LinkTag link=(LinkTag)nodes4.elementAt(i);
   	    	if(!link.getAttribute("href").equals("#"))
   	    	{
   	    		System.out.println("{\""+count+"\",\"https://www1.bournemouth.ac.uk"+link.getAttribute("href")+"\",\""+html2Str(link.toHtml().replaceAll("<span[\\s\\S]*/span>",""))+"\",\"0\"},");
                count++;
   	    	}
   	    	
   	    }
	}
	public static String html2Str(String html) { 
		return html.replaceAll("<[^>]+>", "");
	}
	public static String HTMLFilter(String input) {
	    if (input == null) {
	        input = "";
	        return input;
	    }
	    input = input.trim().replaceAll("&amp;", "&");
	    input = input.trim().replaceAll("&lt;", "<");
	    input = input.trim().replaceAll("&gt;", ">");
	    input = input.trim().replaceAll("    ", " ");
	    input = input.trim().replaceAll("<br>", "\n");
	    input = input.trim().replaceAll("&nbsp;", "  ");
	    input = input.trim().replaceAll("&quot;", "\"");
	    input = input.trim().replaceAll("&#39;", "'");
	    input = input.trim().replaceAll("&#92;", "\\\\");
	    input = input.trim().replaceAll("&#...;", "");
	    input = input.trim().replaceAll("&#....;", "");
	    return input;
	}
	
	public static String[][] UnData={
		{"1","https://www1.bournemouth.ac.uk/study/courses/ba-hons-accounting-law","BA (Hons) Accounting and Law","0"},
		{"2","https://www1.bournemouth.ac.uk/study/courses/maccfin-hons-accounting-finance","MAccFin (Hons) Accounting and Finance","0"},
		{"3","https://www1.bournemouth.ac.uk/study/courses/ba-hons-finance-business","BA (Hons) Finance and Business","0"},
		{"4","https://www1.bournemouth.ac.uk/study/courses/ba-hons-accounting-taxation","BA (Hons) Accounting and Taxation","0"},
		{"5","https://www1.bournemouth.ac.uk/study/courses/ba-hons-finance-law-0","BA (Hons) Finance and Law","0"},
		{"6","https://www1.bournemouth.ac.uk/study/courses/ba-hons-finance-economics","BA (Hons) Finance and Economics","0"},
		{"7","https://www1.bournemouth.ac.uk/study/courses/ba-hons-economics","BA (Hons) Economics","0"},
		{"8","https://www1.bournemouth.ac.uk/study/courses/ba-hons-accounting-finance","BA (Hons) Accounting and Finance","0"},
		{"9","https://www1.bournemouth.ac.uk/study/courses/ba-hons-accounting-business","BA (Hons) Accounting and Business","0"},
		{"10","https://www1.bournemouth.ac.uk/study/courses/ba-hons-international-finance-0","BA (Hons) International Finance","0"},
		{"11","https://www1.bournemouth.ac.uk/study/courses/ba-hons-business-studies-economics","BA (Hons) Business Studies with Economics","0"},
		{"12","https://www1.bournemouth.ac.uk/study/courses/ba-hons-business-studies-enterprise","BA (Hons) Business Studies with Enterprise ","0"},
		{"13","https://www1.bournemouth.ac.uk/study/courses/ba-hons-business-studies-finance","BA (Hons) Business Studies with Finance","0"},
		{"14","https://www1.bournemouth.ac.uk/study/courses/ba-hons-marketing-communications","BA (Hons) Marketing Communications","0"},
		{"15","https://www1.bournemouth.ac.uk/study/courses/ba-hons-business-studies-human-resource-management","BA (Hons) Business Studies with Human Resource Management","0"},
		{"16","https://www1.bournemouth.ac.uk/study/courses/ba-hons-business-studies-law","BA (Hons) Business Studies with Law","0"},
		{"17","https://www1.bournemouth.ac.uk/study/courses/ba-hons-business-studies-operations-project-management","BA (Hons) Business Studies with Operations &amp; Project Management","0"},
		{"18","https://www1.bournemouth.ac.uk/study/courses/ba-hons-business-studies-marketing","BA (Hons) Business Studies with Marketing","0"},
		{"19","https://www1.bournemouth.ac.uk/study/courses/ba-hons-international-business-studies","BA (Hons) International Business Studies","0"},
		{"20","https://www1.bournemouth.ac.uk/study/courses/ba-hons-retail-management","BA (Hons) Retail Management","0"},
		{"21","https://www1.bournemouth.ac.uk/study/courses/ba-hons-international-management-0","BA (Hons) International Management","0"},
		{"22","https://www1.bournemouth.ac.uk/study/courses/ba-hons-business-management","BA (Hons) Business and Management","0"},
		{"23","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-marketing","BSc (Hons) Marketing","0"},
		{"24","https://www1.bournemouth.ac.uk/study/courses/ba-hons-international-business-management","BA (Hons) International Business &amp; Management","0"},
		{"25","https://www1.bournemouth.ac.uk/study/courses/ba-hons-business-studies","BA (Hons) Business Studies","0"},
		{"26","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-software-development-animation-games-effects","BSc (Hons) Software Development for Animation Games and Effects","0"},
		{"27","https://www1.bournemouth.ac.uk/study/courses/ba-hons-computer-visualisation-animation","BA (Hons) Computer Visualisation and Animation","0"},
		{"28","https://www1.bournemouth.ac.uk/study/courses/ba-hons-computer-animation-arts","BA (Hons) Computer Animation Arts","0"},
		{"29","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-cyber-security-management","BSc (Hons) Cyber Security Management","0"},
		{"30","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-business-information-technology","BSc (Hons) Business Information Technology","0"},
		{"31","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-information-technology-management","BSc (Hons) Information Technology Management","0"},
		{"32","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-computer-networks","BSc (Hons) Computer Networks","0"},
		{"33","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-software-engineering","BSc (Hons) Software Engineering","0"},
		{"34","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-computing","BSc (Hons) Computing","0"},
		{"35","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-forensic-computing-security","BSc (Hons) Forensic Computing and Security","0"},
		{"36","https://www1.bournemouth.ac.uk/study/courses/beng-honsmeng-hons-engineering-part-time","BEng (Hons)/MEng (Hons) Engineering (Part-time)","0"},
		{"37","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-design-engineering-3","BSc (Hons) Design Engineering","0"},
		{"38","https://www1.bournemouth.ac.uk/study/courses/ba-hons-product-design","BA (Hons) Product Design","0"},
		{"39","https://www1.bournemouth.ac.uk/study/courses/ba-hons-industrial-design","BA (Hons) Industrial Design","0"},
		{"40","https://www1.bournemouth.ac.uk/study/courses/mdes-hons-product-design","MDes (Hons) Product Design","0"},
		{"41","https://www1.bournemouth.ac.uk/study/courses/bengmeng-hons-mechanical-engineering","BEng/MEng (Hons) Mechanical Engineering","0"},
		{"42","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-product-design","BSc (Hons) Product Design","0"},
		{"43","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-games-programming","BSc (Hons) Games Programming","0"},
		{"44","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-games-technology","BSc (Hons) Games Technology","0"},
		{"45","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-music-audio-technology","BSc (Hons) Music and Audio Technology","0"},
		{"46","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-music-sound-production-technology","BSc (Hons) Music and Sound Production Technology","0"},
		{"47","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-paramedic-science","BSc (Hons) Paramedic Science","0"},
		{"48","https://www1.bournemouth.ac.uk/study/courses/diploma-higher-education-operating-department-practice-0","Diploma of Higher Education Operating Department Practice","0"},
		{"49","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-childrens-young-peoples-nursing","BSc (Hons) Children's and Young People's Nursing","0"},
		{"50","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-nutrition","BSc (Hons) Nutrition","0"},
		{"51","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-mental-health-nursing","BSc (Hons) Mental Health Nursing","0"},
		{"52","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-physiotherapy","BSc (Hons) Physiotherapy","0"},
		{"53","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-clinical-exercise-science","BSc (Hons) Clinical Exercise Science","0"},
		{"54","https://www1.bournemouth.ac.uk/study/courses/ba-hons-social-work","BA (Hons) Social Work","0"},
		{"55","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-midwifery","BSc (Hons) Midwifery","0"},
		{"56","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-occupational-therapy","BSc (Hons) Occupational Therapy","0"},
		{"57","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-adult-nursing","BSc (Hons) Adult Nursing","0"},
		{"58","https://www1.bournemouth.ac.uk/study/courses/ba-hons-sociology-anthropology","BA (Hons) Sociology and Anthropology","0"},
		{"59","https://www1.bournemouth.ac.uk/study/courses/ba-hons-politics","BA (Hons) Politics","0"},
		{"60","https://www1.bournemouth.ac.uk/study/courses/ba-hons-sociology","BA (Hons) Sociology","0"},
		{"61","https://www1.bournemouth.ac.uk/study/courses/ba-hons-sociology-criminology","BA (Hons) Sociology and Criminology","0"},
		{"62","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-anthropology","BSc (Hons) Anthropology","0"},
		{"63","https://www1.bournemouth.ac.uk/study/courses/ba-hons-history","BA (Hons) History","0"},
		{"64","https://www1.bournemouth.ac.uk/study/courses/ba-hons-accounting-law","BA (Hons) Accounting and Law","0"},
		{"65","https://www1.bournemouth.ac.uk/study/courses/llb-hons-law-economics","LLB (Hons) Law with Economics ","0"},
		{"66","https://www1.bournemouth.ac.uk/study/courses/ba-hons-finance-law-0","BA (Hons) Finance and Law","0"},
		{"67","https://www1.bournemouth.ac.uk/study/courses/ba-hons-business-studies-human-resource-management","BA (Hons) Business Studies with Human Resource Management","0"},
		{"68","https://www1.bournemouth.ac.uk/study/courses/ba-hons-business-studies-law","BA (Hons) Business Studies with Law","0"},
		{"69","https://www1.bournemouth.ac.uk/study/courses/llb-hons-business-law","LLB (Hons) Business Law ","0"},
		{"70","https://www1.bournemouth.ac.uk/study/courses/llb-hons-law","LLB (Hons) Law","0"},
		{"71","https://www1.bournemouth.ac.uk/study/courses/llb-hons-law-taxation","LLB (Hons) Law &amp; Taxation","0"},
		{"72","https://www1.bournemouth.ac.uk/study/courses/ba-hons-law","BA (Hons) Law","0"},
		{"73","https://www1.bournemouth.ac.uk/study/courses/llb-hons-entertainment-law","LLB (Hons) Entertainment Law","0"},
		{"74","https://www1.bournemouth.ac.uk/study/courses/ba-hons-multimedia-journalism","BA (Hons) Multimedia Journalism","0"},
		{"75","https://www1.bournemouth.ac.uk/study/courses/ba-hons-marketing-communications","BA (Hons) Marketing Communications","0"},
		{"76","https://www1.bournemouth.ac.uk/study/courses/ba-hons-advertising","BA (Hons) Advertising","0"},
		{"77","https://www1.bournemouth.ac.uk/study/courses/ba-hons-communication-media","BA (Hons) Communication and Media","0"},
		{"78","https://www1.bournemouth.ac.uk/study/courses/ba-hons-media-production","BA (Hons) Media Production","0"},
		{"79","https://www1.bournemouth.ac.uk/study/courses/ba-hons-film-production-cinematography","BA (Hons) Film Production and Cinematography","0"},
		{"80","https://www1.bournemouth.ac.uk/study/courses/ba-hons-photography","BA (Hons) Photography","0"},
		{"81","https://www1.bournemouth.ac.uk/study/courses/ba-hons-film","BA (Hons) Film","0"},
		{"82","https://www1.bournemouth.ac.uk/study/courses/ba-hons-public-relations","BA (Hons) Public Relations","0"},
		{"83","https://www1.bournemouth.ac.uk/study/courses/ba-hons-scriptwriting-film-television","BA (Hons) Scriptwriting for Film and Television","0"},
		{"84","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-marketing","BSc (Hons) Marketing","0"},
		{"85","https://www1.bournemouth.ac.uk/study/courses/mlit-hons-english","MLit (Hons) English","0"},
		{"86","https://www1.bournemouth.ac.uk/study/courses/ba-hons-english","BA (Hons) English","0"},
		{"87","https://www1.bournemouth.ac.uk/study/courses/ba-hons-television-production","BA (Hons) Television Production","0"},
		{"88","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-marine-ecology-conservation","BSc (Hons) Marine Ecology and Conservation","0"},
		{"89","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-archaeology","BSc (Hons) Archaeology","0"},
		{"90","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-psychology","BSc (Hons) Psychology","0"},
		{"91","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-archaeological-forensic-sciences","BSc (Hons) Archaeological and Forensic Sciences","0"},
		{"92","https://www1.bournemouth.ac.uk/study/courses/ba-hons-archaeology-anthropology","BA (Hons) Archaeology and Anthropology","0"},
		{"93","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-forensic-investigation","BSc (Hons) Forensic Investigation","0"},
		{"94","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-ecology-wildlife-conservation","BSc (Hons) Ecology &amp; Wildlife Conservation","0"},
		{"95","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-forensic-biology","BSc (Hons) Forensic Biology","0"},
		{"96","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-geography","BSc (Hons) Geography","0"},
		{"97","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-forensic-science","BSc (Hons) Forensic Science","0"},
		{"98","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-biological-sciences","BSc (Hons) Biological Sciences","0"},
		{"99","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-environmental-science","BSc (Hons) Environmental Science","0"},
		{"100","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-sports-psychology-coaching-sciences","BSc (Hons) Sports Psychology and Coaching Sciences","0"},
		{"101","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-sports-management","BSc (Hons) Sports Management","0"},
		{"102","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-sport-development-coaching-sciences-0","BSc (Hons) Sport Development &amp; Coaching Sciences","0"},
		{"103","https://www1.bournemouth.ac.uk/study/courses/bsc-hons-sports-management-golf","BSc (Hons) Sports Management (Golf)","0"},
		{"104","https://www1.bournemouth.ac.uk/study/courses/ba-hons-events-management","BA (Hons) Events Management","0"},
		{"105","https://www1.bournemouth.ac.uk/study/courses/ba-hons-international-hospitality-management","BA (Hons) International Hospitality Management","0"},
		{"106","https://www1.bournemouth.ac.uk/study/courses/ba-hons-tourism-management","BA (Hons) Tourism Management","0"},
		{"107","https://www1.bournemouth.ac.uk/study/courses/ba-hons-international-hospitality-tourism-management-0","BA (Hons) International Hospitality &amp; Tourism Management","0"},
		{"108","https://www1.bournemouth.ac.uk/study/courses/ba-hons-events-leisure-marketing","BA (Hons) Events and Leisure Marketing","0"}
	};

	public static String[][] PostData={
		{"1","https://www1.bournemouth.ac.uk/study/courses/ma-computer-games-art","MA Computer Games Art","0"},
		{"2","https://www1.bournemouth.ac.uk/study/courses/ma-3d-computer-animation","MA 3D Computer Animation","0"},
		{"3","https://www1.bournemouth.ac.uk/study/courses/ma-digital-effects","MA Digital Effects","0"},
		{"4","https://www1.bournemouth.ac.uk/study/courses/msc-computer-animation-visual-effects","MSc Computer Animation and Visual Effects","0"},
		{"5","https://www1.bournemouth.ac.uk/study/courses/msc-forensic-archaeology","MSc Forensic Archaeology","0"},
		{"6","https://www1.bournemouth.ac.uk/study/courses/msc-archaeology","MSc Archaeology","0"},
		{"7","https://www1.bournemouth.ac.uk/study/courses/msc-bioarchaeology","MSc Bioarchaeology","0"},
		{"8","https://www1.bournemouth.ac.uk/study/courses/msc-osteoarchaeology","MSc Osteoarchaeology","0"},
		{"9","https://www1.bournemouth.ac.uk/study/courses/msc-forensic-anthropology","MSc Forensic Anthropology","0"},
		{"10","https://www1.bournemouth.ac.uk/study/courses/msc-maritime-archaeology","MSc Maritime Archaeology","0"},
		{"11","https://www1.bournemouth.ac.uk/study/courses/msc-biological-anthropology","MSc Biological Anthropology","0"},
		{"12","https://www1.bournemouth.ac.uk/study/courses/msc-innovation-management-entrepreneurship-0","MSc Innovation Management and Entrepreneurship","0"},
		{"13","https://www1.bournemouth.ac.uk/study/courses/msc-international-management","MSc International Management","0"},
		{"14","https://www1.bournemouth.ac.uk/study/courses/msc-professional-development-human-resources-management","MSc Professional Development (Human Resources Management)","0"},
		{"15","https://www1.bournemouth.ac.uk/study/courses/msc-management-human-resources","MSc Management with Human Resources","0"},
		{"16","https://www1.bournemouth.ac.uk/study/courses/msc-professional-development-loss-adjusting","MSc Professional Development (Loss Adjusting)","0"},
		{"17","https://www1.bournemouth.ac.uk/study/courses/msc-green-economy","MSc Green Economy","0"},
		{"18","https://www1.bournemouth.ac.uk/study/courses/msc-management-project-management","MSc Management with Project Management","0"},
		{"19","https://www1.bournemouth.ac.uk/study/courses/msc-consumer-behaviour","MSc Consumer Behaviour","0"},
		{"20","https://www1.bournemouth.ac.uk/study/courses/msc-retail-management-marketing","MSc Retail Management and Marketing","0"},
		{"21","https://www1.bournemouth.ac.uk/study/courses/msc-events-marketing","MSc Events Marketing","0"},
		{"22","https://www1.bournemouth.ac.uk/study/courses/msc-marketing-management","MSc Marketing Management","0"},
		{"23","https://www1.bournemouth.ac.uk/study/courses/msc-hotel-food-services-management","MSc Hotel and Food Services Management","0"},
		{"24","https://www1.bournemouth.ac.uk/study/courses/master-business-administration","Master of Business Administration","0"},
		{"25","https://www1.bournemouth.ac.uk/study/courses/msc-sport-management","MSc Sport Management","0"},
		{"26","https://www1.bournemouth.ac.uk/study/courses/ma-multimedia-journalism","MA Multimedia Journalism","0"},
		{"27","https://www1.bournemouth.ac.uk/study/courses/ma-literary-media","MA Literary Media","0"},
		{"28","https://www1.bournemouth.ac.uk/study/courses/ma-journalism-studies","MA Journalism Studies","0"},
		{"29","https://www1.bournemouth.ac.uk/study/courses/ma-media-communication","MA Media and Communication","0"},
		{"30","https://www1.bournemouth.ac.uk/study/courses/ma-computer-games-art","MA Computer Games Art","0"},
		{"31","https://www1.bournemouth.ac.uk/study/courses/msc-computer-games-technology","MSc Computer Games Technology","0"},
		{"32","https://www1.bournemouth.ac.uk/study/courses/ma-digital-effects","MA Digital Effects","0"},
		{"33","https://www1.bournemouth.ac.uk/study/courses/msc-applied-data-analytics","MSc Applied Data Analytics","0"},
		{"34","https://www1.bournemouth.ac.uk/study/courses/msc-enterprise-information-systems","MSc Enterprise Information Systems","0"},
		{"35","https://www1.bournemouth.ac.uk/study/courses/msc-computer-animation-visual-effects","MSc Computer Animation and Visual Effects","0"},
		{"36","https://www1.bournemouth.ac.uk/study/courses/msc-mobile-app-development","MSc Mobile App Development","0"},
		{"37","https://www1.bournemouth.ac.uk/study/courses/msc-cyber-security-human-factors","MSc Cyber Security and Human Factors","0"},
		{"38","https://www1.bournemouth.ac.uk/study/courses/msc-information-technology","MSc Information Technology","0"},
		{"39","https://www1.bournemouth.ac.uk/study/courses/msc-biodiversity-conservation","MSc Biodiversity Conservation","0"},
		{"40","https://www1.bournemouth.ac.uk/study/courses/msc-green-economy","MSc Green Economy","0"},
		{"41","https://www1.bournemouth.ac.uk/study/courses/ma-political-psychology","MA Political Psychology","0"},
		{"42","https://www1.bournemouth.ac.uk/study/courses/ma-creative-media-education-online","MA Creative &amp; Media Education (Online) ","0"},
		{"43","https://www1.bournemouth.ac.uk/study/courses/ma-corporate-communication","MA Corporate Communication","0"},
		{"44","https://www1.bournemouth.ac.uk/study/courses/ma-advertising","MA Advertising","0"},
		{"45","https://www1.bournemouth.ac.uk/study/courses/ma-literary-media","MA Literary Media","0"},
		{"46","https://www1.bournemouth.ac.uk/study/courses/msc-consumer-behaviour","MSc Consumer Behaviour","0"},
		{"47","https://www1.bournemouth.ac.uk/study/courses/msc-events-marketing","MSc Events Marketing","0"},
		{"48","https://www1.bournemouth.ac.uk/study/courses/msc-tourism-management-marketing","MSc Tourism Management and Marketing","0"},
		{"49","https://www1.bournemouth.ac.uk/study/courses/master-business-administration","Master of Business Administration","0"},
		{"50","https://www1.bournemouth.ac.uk/study/courses/ma-international-political-communication","MA International Political Communication","0"},
		{"51","https://www1.bournemouth.ac.uk/study/courses/msc-product-design","MSc Product Design","0"},
		{"52","https://www1.bournemouth.ac.uk/study/courses/msc-mechanical-engineering-design","MSc Mechanical Engineering Design","0"},
		{"53","https://www1.bournemouth.ac.uk/study/courses/msc-engineering-project-management","MSc Engineering Project Management","0"},
		{"54","https://www1.bournemouth.ac.uk/study/courses/ma-industrial-design","MA Industrial Design","0"},
		{"55","https://www1.bournemouth.ac.uk/study/courses/msc-corporate-governance","MSc Corporate Governance","0"},
		{"56","https://www1.bournemouth.ac.uk/study/courses/msc-international-taxation-finance","MSc International Taxation and Finance","0"},
		{"57","https://www1.bournemouth.ac.uk/study/courses/msc-corporate-governance-0","MSc Corporate Governance","0"},
		{"58","https://www1.bournemouth.ac.uk/study/courses/msc-finance","MSc Finance","0"},
		{"59","https://www1.bournemouth.ac.uk/study/courses/msc-international-economics-finance-1","MSc International Economics and Finance","0"},
		{"60","https://www1.bournemouth.ac.uk/study/courses/pg-cert-intellectual-property","PG Cert Intellectual Property","0"},
		{"61","https://www1.bournemouth.ac.uk/study/courses/llm-intellectual-property","LLM Intellectual Property","0"},
		{"62","https://www1.bournemouth.ac.uk/study/courses/msc-international-finance","MSc International Finance","0"},
		{"63","https://www1.bournemouth.ac.uk/study/courses/msc-international-accounting-finance","MSc International Accounting and Finance","0"},
		{"64","https://www1.bournemouth.ac.uk/study/courses/msc-international-risk-management-finance-1","MSc International Risk Management and Finance","0"},
		{"65","https://www1.bournemouth.ac.uk/study/courses/llm-international-commercial-law","LLM International Commercial Law","0"},
		{"66","https://www1.bournemouth.ac.uk/study/courses/msc-international-investment-finance","MSc International Investment and Finance","0"},
		{"67","https://www1.bournemouth.ac.uk/study/courses/msc-forensic-toxicology-research","MSc Forensic Toxicology by Research","0"},
		{"68","https://www1.bournemouth.ac.uk/study/courses/msc-biodiversity-conservation","MSc Biodiversity Conservation","0"},
		{"69","https://www1.bournemouth.ac.uk/study/courses/msc-forensic-archaeology","MSc Forensic Archaeology","0"},
		{"70","https://www1.bournemouth.ac.uk/study/courses/msc-green-economy","MSc Green Economy","0"},
		{"71","https://www1.bournemouth.ac.uk/study/courses/msc-osteoarchaeology","MSc Osteoarchaeology","0"},
		{"72","https://www1.bournemouth.ac.uk/study/courses/msc-forensic-anthropology","MSc Forensic Anthropology","0"},
		{"73","https://www1.bournemouth.ac.uk/study/courses/msc-biological-anthropology","MSc Biological Anthropology","0"},
		{"74","https://www1.bournemouth.ac.uk/study/courses/msc-forensic-neuropsychological-perspectives-face-processing-0","MSc Forensic and Neuropsychological Perspectives in Face-Processing","0"},
		{"75","https://www1.bournemouth.ac.uk/study/courses/pgdip-mental-health-nursing-professional-registration","PGDip Mental Health Nursing (with professional registration)","0"},
		{"76","https://www1.bournemouth.ac.uk/study/courses/ma-advanced-practice","MA Advanced Practice ","0"},
		{"77","https://www1.bournemouth.ac.uk/study/courses/pgdip-midwifery","PGDip Midwifery","0"},
		{"78","https://www1.bournemouth.ac.uk/study/courses/pgdip-adult-nursing-professional-registration","PGDip Adult Nursing (with professional registration)","0"},
		{"79","https://www1.bournemouth.ac.uk/study/courses/msc-public-health","MSc Public Health","0"},
		{"80","https://www1.bournemouth.ac.uk/study/courses/msc-nutrition-behaviour","MSc Nutrition and Behaviour","0"},
		{"81","https://www1.bournemouth.ac.uk/study/courses/bscpg-dip-public-health-professional-registration-specialist-community-public-health-nurse-health-visiting","BSC/PG Dip Public Health with Professional Registration as a Specialist Community Public Health Nurse (Health Visiting) ","0"},
		{"82","https://www1.bournemouth.ac.uk/study/courses/pg-dipma-social-work-children-families","PG Dip/MA Social Work (Children and Families)","0"},
		{"83","https://www1.bournemouth.ac.uk/study/courses/mchiro-master-chiropractic","MChiro Master of Chiropractic","0"},
		{"84","https://www1.bournemouth.ac.uk/study/courses/bama-care-older-people","BA/MA Care of Older People","0"},
		{"85","https://www1.bournemouth.ac.uk/study/courses/ma-advanced-mental-health-practice","MA Advanced Mental Health Practice","0"},
		{"86","https://www1.bournemouth.ac.uk/study/courses/ma-advanced-practice-vulnerable-adults","MA Advanced Practice (Vulnerable Adults)","0"},
		{"87","https://www1.bournemouth.ac.uk/study/courses/ma-social-work","MA Social Work","0"},
		{"88","https://www1.bournemouth.ac.uk/study/courses/ma-social-care","MA Social Care","0"},
		{"89","https://www1.bournemouth.ac.uk/study/courses/pgdip-advanced-nurse-practitioner","PGDip Advanced Nurse Practitioner ","0"},
		{"90","https://www1.bournemouth.ac.uk/study/courses/pgdip-children-young-peoples-nursing-professional-registration","PGDip Children and Young People's Nursing (with professional registration)","0"},
		{"91","https://www1.bournemouth.ac.uk/study/courses/ma-leading-developing-services","MA Leading and Developing Services","0"},
		{"92","https://www1.bournemouth.ac.uk/study/courses/ma-multimedia-journalism","MA Multimedia Journalism","0"},
		{"93","https://www1.bournemouth.ac.uk/study/courses/ma-post-production-editing","MA Post Production Editing","0"},
		{"94","https://www1.bournemouth.ac.uk/study/courses/ma-literary-media","MA Literary Media","0"},
		{"95","https://www1.bournemouth.ac.uk/study/courses/ma-sports-media","MA Sports Media ","0"},
		{"96","https://www1.bournemouth.ac.uk/study/courses/ma-journalism-studies","MA Journalism Studies","0"},
		{"97","https://www1.bournemouth.ac.uk/study/courses/ma-producing-film-television","MA Producing Film and Television","0"},
		{"98","https://www1.bournemouth.ac.uk/study/courses/ma-media-communication","MA Media and Communication","0"},
		{"99","https://www1.bournemouth.ac.uk/study/courses/graduate-diploma-lawcpe","Graduate Diploma in Law/CPE","0"},
		{"100","https://www1.bournemouth.ac.uk/study/courses/msc-management-human-resources","MSc Management with Human Resources","0"},
		{"101","https://www1.bournemouth.ac.uk/study/courses/llm-public-international-law","LLM Public International Law","0"},
		{"102","https://www1.bournemouth.ac.uk/study/courses/pg-cert-intellectual-property","PG Cert Intellectual Property","0"},
		{"103","https://www1.bournemouth.ac.uk/study/courses/llm-intellectual-property","LLM Intellectual Property","0"},
		{"104","https://www1.bournemouth.ac.uk/study/courses/lpc-legal-practice-course","LPC Legal Practice Course","0"},
		{"105","https://www1.bournemouth.ac.uk/study/courses/llm-legal-practice","LLM Legal Practice","0"},
		{"106","https://www1.bournemouth.ac.uk/study/courses/llm-international-tax-law","LLM International Tax Law","0"},
		{"107","https://www1.bournemouth.ac.uk/study/courses/master-business-administration","Master of Business Administration","0"},
		{"108","https://www1.bournemouth.ac.uk/study/courses/llm-international-commercial-law","LLM International Commercial Law","0"},
		{"109","https://www1.bournemouth.ac.uk/study/courses/ma-multimedia-journalism","MA Multimedia Journalism","0"},
		{"110","https://www1.bournemouth.ac.uk/study/courses/ma-radio-production","MA Radio Production","0"},
		{"111","https://www1.bournemouth.ac.uk/study/courses/ma-production-design-film-television","MA Production Design for Film and Television","0"},
		{"112","https://www1.bournemouth.ac.uk/study/courses/ma-post-production-editing","MA Post Production Editing","0"},
		{"113","https://www1.bournemouth.ac.uk/study/courses/ma-creative-media-education-online","MA Creative &amp; Media Education (Online) ","0"},
		{"114","https://www1.bournemouth.ac.uk/study/courses/ma-creative-media-arts-data-innovation","MA Creative Media Arts: Data and Innovation","0"},
		{"115","https://www1.bournemouth.ac.uk/study/courses/ma-scriptwriting","MA Scriptwriting","0"},
		{"116","https://www1.bournemouth.ac.uk/study/courses/ma-sound-design-film-television","MA Sound Design for Film and Television","0"},
		{"117","https://www1.bournemouth.ac.uk/study/courses/msc-mobile-app-development","MSc Mobile App Development","0"},
		{"118","https://www1.bournemouth.ac.uk/study/courses/ma-cinematography-film-television","MA Cinematography for Film and Television","0"},
		{"119","https://www1.bournemouth.ac.uk/study/courses/msc-digital-music-audio-production","MSc Digital Music and Audio Production","0"},
		{"120","https://www1.bournemouth.ac.uk/study/courses/ma-producing-film-television","MA Producing Film and Television","0"},
		{"121","https://www1.bournemouth.ac.uk/study/courses/ma-directing-film-television","MA Directing Film and Television","0"},
		{"122","https://www1.bournemouth.ac.uk/study/courses/ma-political-psychology","MA Political Psychology","0"},
		{"123","https://www1.bournemouth.ac.uk/study/courses/msc-nutrition-behaviour","MSc Nutrition and Behaviour","0"},
		{"124","https://www1.bournemouth.ac.uk/study/courses/msc-foundations-clinical-psychology","MSc Foundations of Clinical Psychology","0"},
		{"125","https://www1.bournemouth.ac.uk/study/courses/msc-clinical-developmental-neuropsychology","MSc Clinical and Developmental Neuropsychology","0"},
		{"126","https://www1.bournemouth.ac.uk/study/courses/msc-forensic-neuropsychological-perspectives-face-processing-0","MSc Forensic and Neuropsychological Perspectives in Face-Processing","0"},
		{"127","https://www1.bournemouth.ac.uk/study/courses/msc-sport-management","MSc Sport Management","0"},
		{"128","https://www1.bournemouth.ac.uk/study/courses/ma-radio-production","MA Radio Production","0"},
		{"129","https://www1.bournemouth.ac.uk/study/courses/ma-computer-games-art","MA Computer Games Art","0"},
		{"130","https://www1.bournemouth.ac.uk/study/courses/msc-computer-games-technology","MSc Computer Games Technology","0"},
		{"131","https://www1.bournemouth.ac.uk/study/courses/ma-3d-computer-animation","MA 3D Computer Animation","0"},
		{"132","https://www1.bournemouth.ac.uk/study/courses/ma-digital-effects","MA Digital Effects","0"},
		{"133","https://www1.bournemouth.ac.uk/study/courses/msc-computer-animation-visual-effects","MSc Computer Animation and Visual Effects","0"},
		{"134","https://www1.bournemouth.ac.uk/study/courses/msc-digital-music-audio-production","MSc Digital Music and Audio Production","0"},
		{"135","https://www1.bournemouth.ac.uk/study/courses/msc-information-technology","MSc Information Technology","0"},
		{"136","https://www1.bournemouth.ac.uk/study/courses/msc-international-hospitality-tourism-management","MSc International Hospitality and Tourism Management","0"},
		{"137","https://www1.bournemouth.ac.uk/study/courses/msc-tourism-management","MSc Tourism Management","0"},
		{"138","https://www1.bournemouth.ac.uk/study/courses/msc-sustainable-tourism-planning","MSc Sustainable Tourism Planning","0"},
		{"139","https://www1.bournemouth.ac.uk/study/courses/msc-events-marketing","MSc Events Marketing","0"},
		{"140","https://www1.bournemouth.ac.uk/study/courses/msc-tourism-management-marketing","MSc Tourism Management and Marketing","0"},
		{"141","https://www1.bournemouth.ac.uk/study/courses/msc-hotel-food-services-management","MSc Hotel and Food Services Management","0"},
		{"142","https://www1.bournemouth.ac.uk/study/courses/msc-events-management","MSc Events Management","0"},
		{"143","https://www1.bournemouth.ac.uk/study/courses/mres-faculty-media-communication","MRes - Faculty of Media &amp; Communication","0"},
		{"144","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-media-communication","MPhil - Faculty of Media &amp; Communication","0"},
		{"145","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-media-communication","PhD - Faculty of Media &amp; Communication","0"},
		{"146","https://www1.bournemouth.ac.uk/study/courses/doctor-professional-practice-creative-industries","Doctor of Professional Practice Creative Industries","0"},
		{"147","https://www1.bournemouth.ac.uk/study/courses/doctor-engineering-digital-media","Doctor of Engineering Digital Media","0"},
		{"148","https://www1.bournemouth.ac.uk/study/courses/mres-department-archaeology-anthropology-forensic-sciences-life-environmental-sciences","MRes - Department of Archaeology, Anthropology &amp; Forensic Sciences and Life &amp; Environmental Sciences","0"},
		{"149","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-science-technology","MPhil - Faculty of Science &amp; Technology ","0"},
		{"150","https://www1.bournemouth.ac.uk/study/courses/mres-faculty-management","MRes - Faculty of Management ","0"},
		{"151","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-management","MPhil - Faculty of Management","0"},
		{"152","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-management","PhD - Faculty of Management","0"},
		{"153","https://www1.bournemouth.ac.uk/study/courses/mres-faculty-media-communication","MRes - Faculty of Media &amp; Communication","0"},
		{"154","https://www1.bournemouth.ac.uk/study/courses/doctor-professional-practice-creative-industries","Doctor of Professional Practice Creative Industries","0"},
		{"155","https://www1.bournemouth.ac.uk/study/courses/mres-faculty-media-communication","MRes - Faculty of Media &amp; Communication","0"},
		{"156","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-media-communication","MPhil - Faculty of Media &amp; Communication","0"},
		{"157","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-media-communication","PhD - Faculty of Media &amp; Communication","0"},
		{"158","https://www1.bournemouth.ac.uk/study/courses/doctor-engineering-digital-media","Doctor of Engineering Digital Media","0"},
		{"159","https://www1.bournemouth.ac.uk/study/courses/mres-department-archaeology-anthropology-forensic-sciences-life-environmental-sciences","MRes - Department of Archaeology, Anthropology &amp; Forensic Sciences and Life &amp; Environmental Sciences","0"},
		{"160","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-science-technology","MPhil - Faculty of Science &amp; Technology ","0"},
		{"161","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-science-technology","PhD - Faculty of Science &amp; Technology","0"},
		{"162","https://www1.bournemouth.ac.uk/study/courses/mres-faculty-media-communication","MRes - Faculty of Media &amp; Communication","0"},
		{"163","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-media-communication","MPhil - Faculty of Media &amp; Communication","0"},
		{"164","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-media-communication","PhD - Faculty of Media &amp; Communication","0"},
		{"165","https://www1.bournemouth.ac.uk/study/courses/doctor-professional-practice-creative-industries","Doctor of Professional Practice Creative Industries","0"},
		{"166","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-science-technology","PhD - Faculty of Science &amp; Technology","0"},
		{"167","https://www1.bournemouth.ac.uk/study/courses/doctor-engineering-digital-media","Doctor of Engineering Digital Media","0"},
		{"168","https://www1.bournemouth.ac.uk/study/courses/mres-computing-creative-technology-design-engineering","MRes - Computing, Creative Technology, Design &amp; Engineering","0"},
		{"169","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-science-technology","MPhil - Faculty of Science &amp; Technology ","0"},
		{"170","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-management","MPhil - Faculty of Management","0"},
		{"171","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-management","PhD - Faculty of Management","0"},
		{"172","https://www1.bournemouth.ac.uk/study/courses/mres-faculty-management","MRes - Faculty of Management ","0"},
		{"173","https://www1.bournemouth.ac.uk/study/courses/mres-department-archaeology-anthropology-forensic-sciences-life-environmental-sciences","MRes - Department of Archaeology, Anthropology &amp; Forensic Sciences and Life &amp; Environmental Sciences","0"},
		{"174","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-science-technology","MPhil - Faculty of Science &amp; Technology ","0"},
		{"175","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-science-technology","PhD - Faculty of Science &amp; Technology","0"},
		{"176","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-health-social-sciences","MPhil - Faculty of Health &amp; Social Sciences","0"},
		{"177","https://www1.bournemouth.ac.uk/study/courses/mres-faculty-health-social-sciences","MRes - Faculty of Health &amp; Social Sciences","0"},
		{"178","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-health-social-sciences","PhD - Faculty of Health &amp; Social Sciences","0"},
		{"179","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-media-communication","PhD - Faculty of Media &amp; Communication","0"},
		{"180","https://www1.bournemouth.ac.uk/study/courses/doctor-professional-practice-creative-industries","Doctor of Professional Practice Creative Industries","0"},
		{"181","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-media-communication","MPhil - Faculty of Media &amp; Communication","0"},
		{"182","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-media-communication","PhD - Faculty of Media &amp; Communication","0"},
		{"183","https://www1.bournemouth.ac.uk/study/courses/doctor-education-creative-media-2","Doctor of Education Creative and Media","0"},
		{"184","https://www1.bournemouth.ac.uk/study/courses/doctor-engineering-digital-media","Doctor of Engineering Digital Media","0"},
		{"185","https://www1.bournemouth.ac.uk/study/courses/mres-faculty-media-communication","MRes - Faculty of Media &amp; Communication","0"},
		{"186","https://www1.bournemouth.ac.uk/study/courses/mres-faculty-media-communication","MRes - Faculty of Media &amp; Communication","0"},
		{"187","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-media-communication","MPhil - Faculty of Media &amp; Communication","0"},
		{"188","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-management","PhD - Faculty of Management","0"},
		{"189","https://www1.bournemouth.ac.uk/study/courses/mres-faculty-media-communication","MRes - Faculty of Media &amp; Communication","0"},
		{"190","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-media-communication","MPhil - Faculty of Media &amp; Communication","0"},
		{"191","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-media-communication","PhD - Faculty of Media &amp; Communication","0"},
		{"192","https://www1.bournemouth.ac.uk/study/courses/doctor-engineering-digital-media","Doctor of Engineering Digital Media","0"},
		{"193","https://www1.bournemouth.ac.uk/study/courses/mres-faculty-management","MRes - Faculty of Management ","0"},
		{"194","https://www1.bournemouth.ac.uk/study/courses/mphil-faculty-management","MPhil - Faculty of Management","0"},
		{"195","https://www1.bournemouth.ac.uk/study/courses/phd-faculty-management","PhD - Faculty of Management","0"},
		{"196","https://www1.bournemouth.ac.uk/study/courses/rendering-shading","Rendering &amp; Shading","0"},
		{"197","https://www1.bournemouth.ac.uk/study/courses/rigging-animation","Rigging for Animation","0"},
		{"198","https://www1.bournemouth.ac.uk/study/courses/scripting-computer-generated-imagery-cgi","Scripting for Computer Generated Imagery (CGI)","0"},
		{"199","https://www1.bournemouth.ac.uk/study/courses/visual-contextual-studies-animation","Visual &amp; Contextual Studies for Animation","0"},
		{"200","https://www1.bournemouth.ac.uk/study/courses/fundamentals-computer-graphics","Fundamentals of Computer Graphics ","0"},
		{"201","https://www1.bournemouth.ac.uk/study/courses/character-design","Character Design","0"},
		{"202","https://www1.bournemouth.ac.uk/study/courses/fundamentals-sonar","Fundamentals of Sonar ","0"},
		{"203","https://www1.bournemouth.ac.uk/study/courses/introduction-sonar","Introduction to Sonar","0"},
		{"204","https://www1.bournemouth.ac.uk/study/courses/fundamentals-sonar","Fundamentals of Sonar ","0"},
		{"205","https://www1.bournemouth.ac.uk/study/courses/introduction-sonar","Introduction to Sonar","0"},
		{"206","https://www1.bournemouth.ac.uk/study/courses/international-disaster-management","International Disaster Management","0"},
		{"207","https://www1.bournemouth.ac.uk/study/courses/emergency-management-tourism-professionals","Emergency Management for Tourism Professionals","0"},
		{"208","https://www1.bournemouth.ac.uk/study/courses/durotriges-big-dig","The Durotriges Big Dig","0"},
		{"209","https://www1.bournemouth.ac.uk/study/courses/durotriges-big-dig","The Durotriges Big Dig","0"},
		{"210","https://www1.bournemouth.ac.uk/study/courses/fundamentals-sonar","Fundamentals of Sonar ","0"},
		{"211","https://www1.bournemouth.ac.uk/study/courses/emergency-management-tourism-professionals","Emergency Management for Tourism Professionals","0"},
		{"212","https://www1.bournemouth.ac.uk/study/courses/biodiversity-ecosystem-services","Biodiversity &amp; Ecosystem Services","0"},
		{"213","https://www1.bournemouth.ac.uk/study/courses/introduction-sonar","Introduction to Sonar","0"},
		{"214","https://www1.bournemouth.ac.uk/study/courses/sustainable-development-practice","Sustainable Development in Practice","0"},
		{"215","https://www1.bournemouth.ac.uk/study/courses/carbon-management","Carbon Management","0"},
		{"216","https://www1.bournemouth.ac.uk/study/courses/environmental-law-social-justice","Environmental Law &amp; Social Justice ","0"},
		{"217","https://www1.bournemouth.ac.uk/study/courses/green-technology-renewable-energy","Green Technology &amp; Renewable Energy","0"},
		{"218","https://www1.bournemouth.ac.uk/study/courses/frontiers-sustainability-science","Frontiers of Sustainability Science","0"},
		{"219","https://www1.bournemouth.ac.uk/study/courses/hospitality-cpd-corporate-clients","Hospitality CPD for Corporate Clients","0"},
		{"220","https://www1.bournemouth.ac.uk/study/courses/next-generation-web-design","Next Generation Web Design","0"},
		{"221","https://www1.bournemouth.ac.uk/study/courses/intellectual-property-emerging-business-models","Intellectual Property &amp; Emerging Business Models","0"},
		{"222","https://www1.bournemouth.ac.uk/study/courses/critical-design-experimental-interaction-prototyping","Critical Design for Experimental Interaction Prototyping","0"},
		{"223","https://www1.bournemouth.ac.uk/study/courses/producing-multiplatform-video-graphics","Producing Multiplatform Video &amp; Graphics","0"},
		{"224","https://www1.bournemouth.ac.uk/study/courses/environmental-law-social-justice","Environmental Law &amp; Social Justice ","0"},
		{"225","https://www1.bournemouth.ac.uk/study/courses/fundamentals-sonar","Fundamentals of Sonar ","0"},
		{"226","https://www1.bournemouth.ac.uk/study/courses/introduction-sonar","Introduction to Sonar","0"},
		{"227","https://www1.bournemouth.ac.uk/study/courses/advertising-society","Advertising &amp; Society","0"},
		{"228","https://www1.bournemouth.ac.uk/study/courses/global-journalism","Global Journalism","0"},
		{"229","https://www1.bournemouth.ac.uk/study/courses/ethical-journalist","The Ethical Journalist","0"},
		{"230","https://www1.bournemouth.ac.uk/study/courses/digital-storytelling-journalists","Digital Storytelling for Journalists","0"},
		{"231","https://www1.bournemouth.ac.uk/study/courses/applied-creativity-marketing-communications","Applied Creativity (Marketing Communications)","0"},
		{"232","https://www1.bournemouth.ac.uk/study/courses/film-production-management-digital-environment","Film Production Management for the Digital Environment","0"},
		{"233","https://www1.bournemouth.ac.uk/study/courses/intellectual-property-emerging-business-models","Intellectual Property &amp; Emerging Business Models","0"},
		{"234","https://www1.bournemouth.ac.uk/study/courses/editorial-leadership","Editorial Leadership","0"},
		{"235","https://www1.bournemouth.ac.uk/study/courses/entrepreneurial-journalism","Entrepreneurial Journalism","0"},
		{"236","https://www1.bournemouth.ac.uk/study/courses/corporate-strategy-media","Corporate Strategy in Media","0"},
		{"237","https://www1.bournemouth.ac.uk/study/courses/exploring-word-mouth-communication","Exploring Word of Mouth Communication","0"},
		{"238","https://www1.bournemouth.ac.uk/study/courses/strategic-marketing-media","Strategic Marketing in the Media","0"},
		{"239","https://www1.bournemouth.ac.uk/study/courses/creative-non-fiction","Creative Non-Fiction ","0"},
		{"240","https://www1.bournemouth.ac.uk/study/courses/change-organisation-culture","Change &amp; Organisation Culture","0"},
		{"241","https://www1.bournemouth.ac.uk/study/courses/writing-editing-publishing-short-course","Writing, Editing and Publishing (Short Course)","0"},
		{"242","https://www1.bournemouth.ac.uk/study/courses/integrated-marketing-communications-explored","Integrated Marketing Communications Explored","0"},
		{"243","https://www1.bournemouth.ac.uk/study/courses/communicating-across-cultures","Communicating Across Cultures","0"},
		{"244","https://www1.bournemouth.ac.uk/study/courses/digital-film-distribution-marketing","Digital Film Distribution &amp; Marketing","0"},
		{"245","https://www1.bournemouth.ac.uk/study/courses/public-relations-planning-evaluation","Public Relations Planning &amp; Evaluation","0"},
		{"246","https://www1.bournemouth.ac.uk/study/courses/branding-brand-management","Branding &amp; Brand Management","0"},
		{"247","https://www1.bournemouth.ac.uk/study/courses/relationship-marketing","Relationship Marketing","0"},
		{"248","https://www1.bournemouth.ac.uk/study/courses/social-media-classroom","Social Media in the Classroom","0"},
		{"249","https://www1.bournemouth.ac.uk/study/courses/science-journalism","Science Journalism ","0"},
		{"250","https://www1.bournemouth.ac.uk/study/courses/global-journalism","Global Journalism","0"},
		{"251","https://www1.bournemouth.ac.uk/study/courses/creative-coding-education","Creative Coding for Education","0"},
		{"252","https://www1.bournemouth.ac.uk/study/courses/media-education-theory","Media Education (Theory)","0"},
		{"253","https://www1.bournemouth.ac.uk/study/courses/ethical-journalist","The Ethical Journalist","0"},
		{"254","https://www1.bournemouth.ac.uk/study/courses/digital-storytelling-journalists","Digital Storytelling for Journalists","0"},
		{"255","https://www1.bournemouth.ac.uk/study/courses/creative-educator","The Creative Educator","0"},
		{"256","https://www1.bournemouth.ac.uk/study/courses/impact-news","The Impact of News","0"},
		{"257","https://www1.bournemouth.ac.uk/study/courses/writing-feature-film-treatment","Writing the Feature Film Treatment ","0"},
		{"258","https://www1.bournemouth.ac.uk/study/courses/next-generation-web-design","Next Generation Web Design","0"},
		{"259","https://www1.bournemouth.ac.uk/study/courses/writing-location-based-short-drama-script","Writing a Location-Based Short Drama Script","0"},
		{"260","https://www1.bournemouth.ac.uk/study/courses/documentary-practice","Documentary Practice","0"},
		{"261","https://www1.bournemouth.ac.uk/study/courses/future-media-platforms-environments-experiences","Future Media Platforms, Environments &amp; Experiences","0"},
		{"262","https://www1.bournemouth.ac.uk/study/courses/film-production-management-digital-environment","Film Production Management for the Digital Environment","0"},
		{"263","https://www1.bournemouth.ac.uk/study/courses/intellectual-property-emerging-business-models","Intellectual Property &amp; Emerging Business Models","0"},
		{"264","https://www1.bournemouth.ac.uk/study/courses/leadership-management","Leadership &amp; Management","0"},
		{"265","https://www1.bournemouth.ac.uk/study/courses/assessing-creativity","Assessing Creativity","0"},
		{"266","https://www1.bournemouth.ac.uk/study/courses/editorial-leadership","Editorial Leadership","0"},
		{"267","https://www1.bournemouth.ac.uk/study/courses/socialtv-social-media-broadcasting","#SocialTV: Social Media &amp; Broadcasting","0"},
		{"268","https://www1.bournemouth.ac.uk/study/courses/entrepreneurial-journalism","Entrepreneurial Journalism","0"},
		{"269","https://www1.bournemouth.ac.uk/study/courses/international-film-business","International Film Business ","0"},
		{"270","https://www1.bournemouth.ac.uk/study/courses/iptv-video-internet-streaming","IPTV &amp; Video Internet Streaming","0"},
		{"271","https://www1.bournemouth.ac.uk/study/courses/developing-short-form-film-digital-platforms","Developing Short-form Film for Digital Platforms","0"},
		{"272","https://www1.bournemouth.ac.uk/study/courses/corporate-strategy-media","Corporate Strategy in Media","0"},
		{"273","https://www1.bournemouth.ac.uk/study/courses/strategic-marketing-media","Strategic Marketing in the Media","0"},
		{"274","https://www1.bournemouth.ac.uk/study/courses/critical-design-experimental-interaction-prototyping","Critical Design for Experimental Interaction Prototyping","0"},
		{"275","https://www1.bournemouth.ac.uk/study/courses/creative-non-fiction","Creative Non-Fiction ","0"},
		{"276","https://www1.bournemouth.ac.uk/study/courses/writing-editing-publishing-short-course","Writing, Editing and Publishing (Short Course)","0"},
		{"277","https://www1.bournemouth.ac.uk/study/courses/digital-film-distribution-marketing","Digital Film Distribution &amp; Marketing","0"},
		{"278","https://www1.bournemouth.ac.uk/study/courses/cross-platform-radio-production-management","Cross Platform Radio Production &amp; Management","0"},
		{"279","https://www1.bournemouth.ac.uk/study/courses/managing-creativity-innovation","Managing Creativity &amp; Innovation","0"},
		{"280","https://www1.bournemouth.ac.uk/study/courses/professional-enquiry-creative-media-contexts","Professional Enquiry in Creative and Media Contexts","0"},
		{"281","https://www1.bournemouth.ac.uk/study/courses/developing-digital-feature-film-projects","Developing Digital Feature Film Projects","0"},
		{"282","https://www1.bournemouth.ac.uk/study/courses/public-relations-planning-evaluation","Public Relations Planning &amp; Evaluation","0"},
		{"283","https://www1.bournemouth.ac.uk/study/courses/remediating-teaching-english-foreign-language","Remediating Teaching English as a Foreign Language","0"},
		{"284","https://www1.bournemouth.ac.uk/study/courses/protocols-e-learning","The Protocols of E-Learning ","0"},
		{"285","https://www1.bournemouth.ac.uk/study/courses/digital-learning-futures","Digital Learning Futures","0"},
		{"286","https://www1.bournemouth.ac.uk/study/courses/media-coverage-extremism-risks-responsibilities","Media Coverage of Extremism: Risks and Responsibilities","0"},
		{"287","https://www1.bournemouth.ac.uk/study/courses/media-education-practice","Media Education (Practice) ","0"},
		{"288","https://www1.bournemouth.ac.uk/study/courses/relationship-marketing","Relationship Marketing","0"},
		{"289","https://www1.bournemouth.ac.uk/study/courses/durotriges-big-dig","The Durotriges Big Dig","0"},
		{"290","https://www1.bournemouth.ac.uk/study/courses/active-iq-level-3-certificate-personal-training","Active IQ Level 3 Certificate in Personal Training","0"},
		{"291","https://www1.bournemouth.ac.uk/study/courses/active-iq-level-2-certificate-fitness-instructing-gym","Active IQ Level 2 Certificate in Fitness Instructing (Gym)","0"},
		{"292","https://www1.bournemouth.ac.uk/study/courses/active-iq-level-3-certificate-sports-massage-soft-tissue-therapy-qcf","Active IQ Level 3 Certificate in Sports Massage (Soft Tissue Therapy) (QCF)","0"},
		{"293","https://www1.bournemouth.ac.uk/study/courses/retail-cpd-corporate-clients-short-course","Retail CPD for Corporate Clients (Short Course)","0"},
		{"294","https://www1.bournemouth.ac.uk/study/courses/active-iq-level-3-certificate-personal-training","Active IQ Level 3 Certificate in Personal Training","0"},
		{"295","https://www1.bournemouth.ac.uk/study/courses/active-iq-level-2-certificate-fitness-instructing-gym","Active IQ Level 2 Certificate in Fitness Instructing (Gym)","0"},
		{"296","https://www1.bournemouth.ac.uk/study/courses/active-iq-level-3-certificate-sports-massage-soft-tissue-therapy-qcf","Active IQ Level 3 Certificate in Sports Massage (Soft Tissue Therapy) (QCF)","0"},
		{"297","https://www1.bournemouth.ac.uk/study/courses/tourism-cpd-corporate-clients-short-course","Tourism CPD for Corporate Clients (Short Course)","0"},
		{"298","https://www1.bournemouth.ac.uk/study/courses/emergency-management-tourism-professionals","Emergency Management for Tourism Professionals","0"},
		{"299","https://www1.bournemouth.ac.uk/study/courses/maritime-archaeology","Maritime Archaeology","0"},
		{"300","https://www1.bournemouth.ac.uk/study/courses/management-archaeological-material","Management of Archaeological Material","0"},
		{"301","https://www1.bournemouth.ac.uk/study/courses/durotriges-big-dig","The Durotriges Big Dig","0"},
		{"302","https://www1.bournemouth.ac.uk/study/courses/active-iq-level-3-certificate-personal-training","Active IQ Level 3 Certificate in Personal Training","0"},
		{"303","https://www1.bournemouth.ac.uk/study/courses/active-iq-level-2-certificate-fitness-instructing-gym","Active IQ Level 2 Certificate in Fitness Instructing (Gym)","0"},
		{"304","https://www1.bournemouth.ac.uk/study/courses/active-iq-level-3-certificate-sports-massage-soft-tissue-therapy-qcf","Active IQ Level 3 Certificate in Sports Massage (Soft Tissue Therapy) (QCF)","0"},
		{"305","https://www1.bournemouth.ac.uk/study/courses/intellectual-property-emerging-business-models","Intellectual Property &amp; Emerging Business Models","0"},
		{"306","https://www1.bournemouth.ac.uk/study/courses/rendering-shading","Rendering &amp; Shading","0"},
		{"307","https://www1.bournemouth.ac.uk/study/courses/rigging-animation","Rigging for Animation","0"},
		{"308","https://www1.bournemouth.ac.uk/study/courses/scripting-computer-generated-imagery-cgi","Scripting for Computer Generated Imagery (CGI)","0"},
		{"309","https://www1.bournemouth.ac.uk/study/courses/visual-contextual-studies-animation","Visual &amp; Contextual Studies for Animation","0"},
		{"310","https://www1.bournemouth.ac.uk/study/courses/fundamentals-computer-graphics","Fundamentals of Computer Graphics ","0"},
		{"311","https://www1.bournemouth.ac.uk/study/courses/character-design","Character Design","0"},
		{"312","https://www1.bournemouth.ac.uk/study/courses/managing-creativity-innovation","Managing Creativity &amp; Innovation","0"},
		{"313","https://www1.bournemouth.ac.uk/study/courses/international-disaster-management","International Disaster Management","0"},
		{"314","https://www1.bournemouth.ac.uk/study/courses/durotriges-big-dig","The Durotriges Big Dig","0"},
		{"315","https://www1.bournemouth.ac.uk/study/courses/maritime-archaeology","Maritime Archaeology","0"},
		{"316","https://www1.bournemouth.ac.uk/study/courses/international-disaster-management","International Disaster Management","0"},
		{"317","https://www1.bournemouth.ac.uk/study/courses/biodiversity-ecosystem-services","Biodiversity &amp; Ecosystem Services","0"},
		{"318","https://www1.bournemouth.ac.uk/study/courses/sustainable-development-practice","Sustainable Development in Practice","0"},
		{"319","https://www1.bournemouth.ac.uk/study/courses/carbon-management","Carbon Management","0"},
		{"320","https://www1.bournemouth.ac.uk/study/courses/environmental-law-social-justice","Environmental Law &amp; Social Justice ","0"},
		{"321","https://www1.bournemouth.ac.uk/study/courses/green-technology-renewable-energy","Green Technology &amp; Renewable Energy","0"},
		{"322","https://www1.bournemouth.ac.uk/study/courses/frontiers-sustainability-science","Frontiers of Sustainability Science","0"},
		{"323","https://www1.bournemouth.ac.uk/study/courses/durotriges-big-dig","The Durotriges Big Dig","0"},
		{"324","https://www1.bournemouth.ac.uk/study/courses/fundamentals-sonar","Fundamentals of Sonar ","0"},
		{"325","https://www1.bournemouth.ac.uk/study/courses/introduction-sonar","Introduction to Sonar","0"},
		{"326","https://www1.bournemouth.ac.uk/study/courses/developing-leadership-skills","Developing Leadership Skills","0"},
		{"327","https://www1.bournemouth.ac.uk/study/courses/leading-people-teams","Leading People &amp; Teams","0"},
		{"328","https://www1.bournemouth.ac.uk/study/courses/durotriges-big-dig","The Durotriges Big Dig","0"},
		{"329","https://www1.bournemouth.ac.uk/study/courses/fundamentals-sonar","Fundamentals of Sonar ","0"},
		{"330","https://www1.bournemouth.ac.uk/study/courses/emergency-management-tourism-professionals","Emergency Management for Tourism Professionals","0"},
		{"331","https://www1.bournemouth.ac.uk/study/courses/introduction-sonar","Introduction to Sonar","0"},
		{"332","https://www1.bournemouth.ac.uk/study/courses/sustainable-development-practice","Sustainable Development in Practice","0"},
		{"333","https://www1.bournemouth.ac.uk/study/courses/carbon-management","Carbon Management","0"},
		{"334","https://www1.bournemouth.ac.uk/study/courses/environmental-law-social-justice","Environmental Law &amp; Social Justice ","0"},
		{"335","https://www1.bournemouth.ac.uk/study/courses/green-technology-renewable-energy","Green Technology &amp; Renewable Energy","0"},
		{"336","https://www1.bournemouth.ac.uk/study/courses/frontiers-sustainability-science","Frontiers of Sustainability Science","0"},
		{"337","https://www1.bournemouth.ac.uk/study/courses/events-leisure-cpd-corporate-clients-short-course","Events &amp; Leisure CPD for Corporate Clients (Short Course)","0"},
		{"338","https://www1.bournemouth.ac.uk/study/courses/developing-leadership-skills","Developing Leadership Skills","0"},
		{"339","https://www1.bournemouth.ac.uk/study/courses/leading-people-teams","Leading People &amp; Teams","0"},
		{"340","https://www1.bournemouth.ac.uk/study/courses/science-journalism","Science Journalism ","0"},
		{"341","https://www1.bournemouth.ac.uk/study/courses/global-journalism","Global Journalism","0"},
		{"342","https://www1.bournemouth.ac.uk/study/courses/ethical-journalist","The Ethical Journalist","0"},
		{"343","https://www1.bournemouth.ac.uk/study/courses/digital-storytelling-journalists","Digital Storytelling for Journalists","0"},
		{"344","https://www1.bournemouth.ac.uk/study/courses/impact-news","The Impact of News","0"},
		{"345","https://www1.bournemouth.ac.uk/study/courses/intellectual-property-emerging-business-models","Intellectual Property &amp; Emerging Business Models","0"},
		{"346","https://www1.bournemouth.ac.uk/study/courses/editorial-leadership","Editorial Leadership","0"},
		{"347","https://www1.bournemouth.ac.uk/study/courses/entrepreneurial-journalism","Entrepreneurial Journalism","0"},
		{"348","https://www1.bournemouth.ac.uk/study/courses/corporate-strategy-media","Corporate Strategy in Media","0"},
		{"349","https://www1.bournemouth.ac.uk/study/courses/exploring-word-mouth-communication","Exploring Word of Mouth Communication","0"},
		{"350","https://www1.bournemouth.ac.uk/study/courses/strategic-marketing-media","Strategic Marketing in the Media","0"},
		{"351","https://www1.bournemouth.ac.uk/study/courses/change-organisation-culture","Change &amp; Organisation Culture","0"},
		{"352","https://www1.bournemouth.ac.uk/study/courses/cross-platform-radio-production-management","Cross Platform Radio Production &amp; Management","0"},
		{"353","https://www1.bournemouth.ac.uk/study/courses/managing-creativity-innovation","Managing Creativity &amp; Innovation","0"},
		{"354","https://www1.bournemouth.ac.uk/study/courses/public-relations-planning-evaluation","Public Relations Planning &amp; Evaluation","0"},
		{"355","https://www1.bournemouth.ac.uk/study/courses/media-coverage-extremism-risks-responsibilities","Media Coverage of Extremism: Risks and Responsibilities","0"},
		{"356","https://www1.bournemouth.ac.uk/study/courses/environmental-law-social-justice","Environmental Law &amp; Social Justice ","0"},
		{"357","https://www1.bournemouth.ac.uk/study/courses/advertising-society","Advertising &amp; Society","0"},
		{"358","https://www1.bournemouth.ac.uk/study/courses/applied-creativity-marketing-communications","Applied Creativity (Marketing Communications)","0"},
		{"359","https://www1.bournemouth.ac.uk/study/courses/developing-leadership-skills","Developing Leadership Skills","0"},
		{"360","https://www1.bournemouth.ac.uk/study/courses/leading-people-teams","Leading People &amp; Teams","0"},
		{"361","https://www1.bournemouth.ac.uk/study/courses/intellectual-property-emerging-business-models","Intellectual Property &amp; Emerging Business Models","0"},
		{"362","https://www1.bournemouth.ac.uk/study/courses/leadership-management","Leadership &amp; Management","0"},
		{"363","https://www1.bournemouth.ac.uk/study/courses/corporate-strategy-media","Corporate Strategy in Media","0"},
		{"364","https://www1.bournemouth.ac.uk/study/courses/exploring-word-mouth-communication","Exploring Word of Mouth Communication","0"},
		{"365","https://www1.bournemouth.ac.uk/study/courses/change-organisation-culture","Change &amp; Organisation Culture","0"},
		{"366","https://www1.bournemouth.ac.uk/study/courses/integrated-marketing-communications-explored","Integrated Marketing Communications Explored","0"},
		{"367","https://www1.bournemouth.ac.uk/study/courses/communicating-across-cultures","Communicating Across Cultures","0"},
		{"368","https://www1.bournemouth.ac.uk/study/courses/managing-creativity-innovation","Managing Creativity &amp; Innovation","0"},
		{"369","https://www1.bournemouth.ac.uk/study/courses/public-relations-planning-evaluation","Public Relations Planning &amp; Evaluation","0"},
		{"370","https://www1.bournemouth.ac.uk/study/courses/branding-brand-management","Branding &amp; Brand Management","0"},
		{"371","https://www1.bournemouth.ac.uk/study/courses/writing-feature-film-treatment","Writing the Feature Film Treatment ","0"},
		{"372","https://www1.bournemouth.ac.uk/study/courses/managing-production-workflows-across-platforms","Managing Production Workflows Across Platforms","0"},
		{"373","https://www1.bournemouth.ac.uk/study/courses/writing-location-based-short-drama-script","Writing a Location-Based Short Drama Script","0"},
		{"374","https://www1.bournemouth.ac.uk/study/courses/documentary-practice","Documentary Practice","0"},
		{"375","https://www1.bournemouth.ac.uk/study/courses/future-media-platforms-environments-experiences","Future Media Platforms, Environments &amp; Experiences","0"},
		{"376","https://www1.bournemouth.ac.uk/study/courses/film-production-management-digital-environment","Film Production Management for the Digital Environment","0"},
		{"377","https://www1.bournemouth.ac.uk/study/courses/intellectual-property-emerging-business-models","Intellectual Property &amp; Emerging Business Models","0"},
		{"378","https://www1.bournemouth.ac.uk/study/courses/socialtv-social-media-broadcasting","#SocialTV: Social Media &amp; Broadcasting","0"},
		{"379","https://www1.bournemouth.ac.uk/study/courses/international-film-business","International Film Business ","0"},
		{"380","https://www1.bournemouth.ac.uk/study/courses/iptv-video-internet-streaming","IPTV &amp; Video Internet Streaming","0"},
		{"381","https://www1.bournemouth.ac.uk/study/courses/developing-short-form-film-digital-platforms","Developing Short-form Film for Digital Platforms","0"},
		{"382","https://www1.bournemouth.ac.uk/study/courses/project-management-media-professionals","Project Management for Media Professionals","0"},
		{"383","https://www1.bournemouth.ac.uk/study/courses/digital-film-distribution-marketing","Digital Film Distribution &amp; Marketing","0"},
		{"384","https://www1.bournemouth.ac.uk/study/courses/cross-platform-radio-production-management","Cross Platform Radio Production &amp; Management","0"},
		{"385","https://www1.bournemouth.ac.uk/study/courses/developing-digital-feature-film-projects","Developing Digital Feature Film Projects","0"},
		{"386","https://www1.bournemouth.ac.uk/study/courses/digital-learning-futures","Digital Learning Futures","0"},
		{"387","https://www1.bournemouth.ac.uk/study/courses/relationship-marketing","Relationship Marketing","0"},
		{"388","https://www1.bournemouth.ac.uk/study/courses/active-iq-level-3-certificate-personal-training","Active IQ Level 3 Certificate in Personal Training","0"},
		{"389","https://www1.bournemouth.ac.uk/study/courses/active-iq-level-2-certificate-fitness-instructing-gym","Active IQ Level 2 Certificate in Fitness Instructing (Gym)","0"},
		{"390","https://www1.bournemouth.ac.uk/study/courses/active-iq-level-3-certificate-sports-massage-soft-tissue-therapy-qcf","Active IQ Level 3 Certificate in Sports Massage (Soft Tissue Therapy) (QCF)","0"},
		{"391","https://www1.bournemouth.ac.uk/study/courses/international-disaster-management","International Disaster Management","0"},
		{"392","https://www1.bournemouth.ac.uk/study/courses/environmental-law-social-justice","Environmental Law &amp; Social Justice ","0"},
		{"393","https://www1.bournemouth.ac.uk/study/courses/developing-leadership-skills","Developing Leadership Skills","0"},
		{"394","https://www1.bournemouth.ac.uk/study/courses/leading-people-teams","Leading People &amp; Teams","0"},
		{"395","https://www1.bournemouth.ac.uk/study/courses/retail-cpd-corporate-clients-short-course","Retail CPD for Corporate Clients (Short Course)","0"},
		{"396","https://www1.bournemouth.ac.uk/study/courses/science-journalism","Science Journalism ","0"},
		{"397","https://www1.bournemouth.ac.uk/study/courses/impact-news","The Impact of News","0"},
		{"398","https://www1.bournemouth.ac.uk/study/courses/writing-feature-film-treatment","Writing the Feature Film Treatment ","0"},
		{"399","https://www1.bournemouth.ac.uk/study/courses/creative-non-fiction","Creative Non-Fiction ","0"},
		{"400","https://www1.bournemouth.ac.uk/study/courses/writing-editing-publishing-short-course","Writing, Editing and Publishing (Short Course)","0"},
		{"401","https://www1.bournemouth.ac.uk/study/courses/media-coverage-extremism-risks-responsibilities","Media Coverage of Extremism: Risks and Responsibilities","0"},
		{"402","https://www1.bournemouth.ac.uk/study/courses/developing-leadership-skills","Developing Leadership Skills","0"},
		{"403","https://www1.bournemouth.ac.uk/study/courses/leading-people-teams","Leading People &amp; Teams","0"},
		{"404","https://www1.bournemouth.ac.uk/study/courses/intellectual-property-emerging-business-models","Intellectual Property &amp; Emerging Business Models","0"},
		{"405","https://www1.bournemouth.ac.uk/study/courses/leadership-management","Leadership &amp; Management","0"},
		{"406","https://www1.bournemouth.ac.uk/study/courses/corporate-strategy-media","Corporate Strategy in Media","0"},
		{"407","https://www1.bournemouth.ac.uk/study/courses/strategic-marketing-media","Strategic Marketing in the Media","0"},
		{"408","https://www1.bournemouth.ac.uk/study/courses/change-organisation-culture","Change &amp; Organisation Culture","0"},
		{"409","https://www1.bournemouth.ac.uk/study/courses/managing-creativity-innovation","Managing Creativity &amp; Innovation","0"},
		{"410","https://www1.bournemouth.ac.uk/study/courses/social-media-classroom","Social Media in the Classroom","0"},
		{"411","https://www1.bournemouth.ac.uk/study/courses/creative-coding-education","Creative Coding for Education","0"},
		{"412","https://www1.bournemouth.ac.uk/study/courses/media-education-theory","Media Education (Theory)","0"},
		{"413","https://www1.bournemouth.ac.uk/study/courses/creative-educator","The Creative Educator","0"},
		{"414","https://www1.bournemouth.ac.uk/study/courses/assessing-creativity","Assessing Creativity","0"},
		{"415","https://www1.bournemouth.ac.uk/study/courses/professional-enquiry-creative-media-contexts","Professional Enquiry in Creative and Media Contexts","0"},
		{"416","https://www1.bournemouth.ac.uk/study/courses/remediating-teaching-english-foreign-language","Remediating Teaching English as a Foreign Language","0"},
		{"417","https://www1.bournemouth.ac.uk/study/courses/protocols-e-learning","The Protocols of E-Learning ","0"},
		{"418","https://www1.bournemouth.ac.uk/study/courses/digital-learning-futures","Digital Learning Futures","0"},
		{"419","https://www1.bournemouth.ac.uk/study/courses/media-education-practice","Media Education (Practice) ","0"},
		{"420","https://www1.bournemouth.ac.uk/study/courses/tourism-cpd-corporate-clients-short-course","Tourism CPD for Corporate Clients (Short Course)","0"},
		{"421","https://www1.bournemouth.ac.uk/study/courses/emergency-management-tourism-professionals","Emergency Management for Tourism Professionals","0"}
	};
}
