package no7.Brighton;

import java.io.File;
import java.io.FileInputStream;
import java.util.ArrayList;

import org.htmlparser.Parser;
import org.htmlparser.filters.AndFilter;
import org.htmlparser.filters.HasAttributeFilter;
import org.htmlparser.filters.TagNameFilter;
import org.htmlparser.tags.LinkTag;
import org.htmlparser.util.NodeList;

public class getURL {

	/**
	 * @param args
	 */
	public static void main(String[] args) throws Exception {
			// TODO Auto-generated method stub

			FileInputStream fis=new FileInputStream(new File("./BrightonPost.html"));
			byte[] b=new byte[fis.available()];
	        fis.read(b);
	       fis.close();
	        String htmls=new String(b);
	       int count=1;
	       ArrayList<String> list=new ArrayList<String>();
		    Parser	parser=Parser.createParser(htmls, "utf-8");
	   	    AndFilter ProfessionNameFilter=new AndFilter(new TagNameFilter("a"),
	                   new HasAttributeFilter("href"));
	   	    NodeList nodes4=parser.extractAllNodesThatMatch(ProfessionNameFilter);
	   	    for(int i=0;i<nodes4.size();i++)
	   	    {
	   	    	LinkTag link=(LinkTag)nodes4.elementAt(i);
	   	    	//if(!link.getAttribute("href").equals("")&&!html2Str(link.toHtml()).contains("View this course"))
	   	    	{
	   	    		if(!list.contains(link.getAttribute("href")))
	   	    		{
	   	    			list.add(link.getAttribute("href"));
	   	    			/*System.out.println(HTMLFilter(html2Str(link.toHtml()))
	   	   	    				.replace("\r\n", "").split(" – ").length);*/
	   	    			System.out.println("{\""+count+"\",\"https://www.brighton.ac.uk"
	   	   	    				+link.getAttribute("href")+"\",\""+HTMLFilter(html2Str(link.toHtml()))
	   	   	    				.replace("\r\n", "")+"\",\"0\"},");
	   	                count++;
	   	    		}
	   	    		
	   	    	}
	   	    	
	   	    }
		}
		public static String html2Str(String html) { 
			return html.replaceAll("<[^>]+>", "");
		}
		public static String HTMLFilter(String input) {
		    if (input == null) {
		        input = "";
		        return input;
		    }
		    input = input.trim().replaceAll("&amp;", "&");
		    input = input.trim().replaceAll("&lt;", "<");
		    input = input.trim().replaceAll("&gt;", ">");
		    input = input.trim().replaceAll("    ", " ");
		    input = input.trim().replaceAll("<br>", "\n");
		    input = input.trim().replaceAll("&nbsp;", "  ");
		    input = input.trim().replaceAll("&quot;", "\"");
		    input = input.trim().replaceAll("&#39;", "'");
		    input = input.trim().replaceAll("&#92;", "\\\\");
		    input = input.trim().replaceAll("&#...;", "");
		    input = input.trim().replaceAll("&#....;", "");
		    return input;
		}
		public static String[][] UnData={
			{"1","https://www.brighton.ac.uk/courses/study/3d-design-and-craft-ba-hons.aspx","3D Design and Craft BA(Hons)","0"},
			{"2","https://www.brighton.ac.uk/courses/study/3d-design-and-craft-mdes.aspx","3D Design and Craft MDes","0"},
			{"3","https://www.brighton.ac.uk/courses/study/acca-professional-accountancy-acca-prof.aspx","ACCA Professional Accountancy ACCA PROF","0"},
			{"4","https://www.brighton.ac.uk/courses/study/accounting-and-finance-bsc-hons.aspx","Accounting and Finance BSc(Hons)","0"},
			{"5","https://www.brighton.ac.uk/courses/study/acute-clinical-practice-acute-care-gradcert.aspx","Acute Clinical Practice (Acute Care) GradCert","0"},
			{"6","https://www.brighton.ac.uk/courses/study/acute-clinical-practice-burn-and-reconstructive-surgery-gradcert.aspx","Acute Clinical Practice (Burn and Reconstructive Surgery) GradCert","0"},
			{"7","https://www.brighton.ac.uk/courses/study/acute-clinical-practice-cancer-care-gradcert.aspx","Acute Clinical Practice (Cancer Care) GradCert","0"},
			{"8","https://www.brighton.ac.uk/courses/study/acute-clinical-practice-cardiac-care-gradcert.aspx","Acute Clinical Practice (Cardiac Care) GradCert","0"},
			{"9","https://www.brighton.ac.uk/courses/study/acute-clinical-practice-child-health-gradcert.aspx","Acute Clinical Practice (Child Health) GradCert","0"},
			{"10","https://www.brighton.ac.uk/courses/study/acute-clinical-practice-emergency-care-gradcert.aspx","Acute Clinical Practice (Emergency Care) GradCert","0"},
			{"11","https://www.brighton.ac.uk/courses/study/acute-clinical-practice-intensive-care-gradcert.aspx","Acute Clinical Practice (Intensive Care) GradCert","0"},
			{"12","https://www.brighton.ac.uk/courses/study/acute-clinical-practice-neonatal-care-gradcert.aspx","Acute Clinical Practice (Neonatal Care) GradCert","0"},
			{"13","https://www.brighton.ac.uk/courses/study/acute-clinical-practice-ophthalmic-care-gradcert.aspx","Acute Clinical Practice (Ophthalmic Care) GradCert","0"},
			{"14","https://www.brighton.ac.uk/courses/study/acute-clinical-practice-renal-care-gradcert.aspx","Acute Clinical Practice (Renal Care) GradCert","0"},
			{"15","https://www.brighton.ac.uk/courses/study/acute-clinical-practice-bsc-hons-top-up-degree.aspx","Acute Clinical Practice BSc(Hons) top-up degree","0"},
			{"16","https://www.brighton.ac.uk/courses/study/advanced-french-cert.aspx","Advanced French Certificate","0"},
			{"17","https://www.brighton.ac.uk/courses/study/advanced-german-cert.aspx","Advanced German Cert","0"},
			{"18","https://www.brighton.ac.uk/courses/study/advanced-spanish-cert.aspx","Advanced Spanish Cert","0"},
			{"19","https://www.brighton.ac.uk/courses/study/aeronautical-engineering-beng-hons.aspx","Aeronautical Engineering BEng(Hons)","0"},
			{"20","https://www.brighton.ac.uk/courses/study/aeronautical-engineering-beng-hons-with-integrated-foundation-year.aspx","Aeronautical Engineering BEng(Hons) (with integrated foundation year)","0"},
			{"21","https://www.brighton.ac.uk/courses/study/aeronautical-engineering-bsc-hons-top-up-degree.aspx","Aeronautical Engineering BSc(Hons) top-up degree","0"},
			{"22","https://www.brighton.ac.uk/courses/study/aeronautical-engineering-meng.aspx","Aeronautical Engineering MEng","0"},
			{"23","https://www.brighton.ac.uk/courses/study/applied-psychology-and-criminology-ba-hons.aspx","Applied Psychology and Criminology BA(Hons)","0"},
			{"24","https://www.brighton.ac.uk/courses/study/applied-psychology-and-sociology-ba-hons.aspx","Applied Psychology and Sociology BA(Hons)","0"},
			{"25","https://www.brighton.ac.uk/courses/study/applied-psychology-bsc-hons.aspx","Applied Psychology BSc(Hons)","0"},
			{"26","https://www.brighton.ac.uk/courses/study/applied-social-science-ba-hons.aspx","Applied Social Science BA(Hons)","0"},
			{"27","https://www.brighton.ac.uk/courses/study/archaeology-and-geography-bsc-hons.aspx","Archaeology and Geography BSc(Hons)","0"},
			{"28","https://www.brighton.ac.uk/courses/study/architectural-technology-bsc-hons.aspx","Architectural Technology BSc(Hons)","0"},
			{"29","https://www.brighton.ac.uk/courses/study/architecture-and-urban-planning-ba-hons.aspx","Architecture and Urban Planning BA(Hons)","0"},
			{"30","https://www.brighton.ac.uk/courses/study/architecture-ba-hons.aspx","Architecture BA(Hons)","0"},
			{"31","https://www.brighton.ac.uk/courses/study/automotive-engineering-beng-hons.aspx","Automotive Engineering BEng(Hons)","0"},
			{"32","https://www.brighton.ac.uk/courses/study/automotive-engineering-beng-hons-with-integrated-foundation-year.aspx","Automotive Engineering BEng(Hons) (with integrated foundation year)","0"},
			{"33","https://www.brighton.ac.uk/courses/study/automotive-engineering-bsc-hons-top-up-degree.aspx","Automotive Engineering BSc(Hons) top-up degree","0"},
			{"34","https://www.brighton.ac.uk/courses/study/automotive-engineering-meng.aspx","Automotive Engineering MEng","0"},
			{"35","https://www.brighton.ac.uk/courses/study/biological-sciences-bsc-hons.aspx","Biological Sciences BSc(Hons)","0"},
			{"36","https://www.brighton.ac.uk/courses/study/biology-bsc-hons.aspx","Biology BSc(Hons)","0"},
			{"37","https://www.brighton.ac.uk/courses/study/biomedical-science-bsc-hons.aspx","Biomedical Science BSc(Hons)","0"},
			{"38","https://www.brighton.ac.uk/courses/study/broadcast-media-ba-hons-top-up-degree.aspx","Broadcast Media BA(Hons) top-up-degree","0"},
			{"39","https://www.brighton.ac.uk/courses/study/broadcast-media-foundation-degree.aspx","Broadcast Media foundation degree","0"},
			{"40","https://www.brighton.ac.uk/courses/study/building-surveying-bsc-hons.aspx","Building Surveying BSc(Hons)","0"},
			{"41","https://www.brighton.ac.uk/courses/study/business-bsc-hons.aspx","Business BSc(Hons)","0"},
			{"42","https://www.brighton.ac.uk/courses/study/business-bsc-hons-top-up-degree.aspx","Business BSc(Hons) top-up degree","0"},
			{"43","https://www.brighton.ac.uk/courses/study/business-computer-systems-bsc-hons.aspx","Business Computer Systems BSc(Hons)","0"},
			{"44","https://www.brighton.ac.uk/courses/study/business-computer-systems-mcomp.aspx","Business Computer Systems MComp","0"},
			{"45","https://www.brighton.ac.uk/courses/study/business-information-systems-ba-hons.aspx","Business Information Systems BA(Hons)","0"},
			{"46","https://www.brighton.ac.uk/courses/study/business-management-bsc-hons.aspx","Business Management BSc(Hons)","0"},
			{"47","https://www.brighton.ac.uk/courses/study/business-management-with-economics-bsc-hons.aspx","Business Management with Economics BSc(Hons)","0"},
			{"48","https://www.brighton.ac.uk/courses/study/business-management-with-finance-bsc-hons.aspx","Business Management with Finance BSc(Hons)","0"},
			{"49","https://www.brighton.ac.uk/courses/study/business-management-with-human-resource-management-bsc-hons.aspx","Business Management with Human Resource Management BSc(Hons)","0"},
			{"50","https://www.brighton.ac.uk/courses/study/business-management-with-marketing-bsc-hons.aspx","Business Management with Marketing BSc(Hons)","0"},
			{"51","https://www.brighton.ac.uk/courses/study/business-with-economics-bsc-hons.aspx","Business with Economics BSc(Hons)","0"},
			{"52","https://www.brighton.ac.uk/courses/study/business-with-finance-bsc-hons.aspx","Business with Finance BSc(Hons)","0"},
			{"53","https://www.brighton.ac.uk/courses/study/business-with-human-resource-management-bsc-hons.aspx","Business with Human Resource Management BSc(Hons)","0"},
			{"54","https://www.brighton.ac.uk/courses/study/business-with-marketing-bsc-hons.aspx","Business with Marketing BSc(Hons)","0"},
			{"55","https://www.brighton.ac.uk/courses/study/chemistry-bsc-hons.aspx","Chemistry BSc(Hons)","0"},
			{"56","https://www.brighton.ac.uk/courses/study/chemistry-mchem.aspx","Chemistry MChem","0"},
			{"57","https://www.brighton.ac.uk/courses/study/civil-engineering-with-integrated-foundation-year-beng-hons.aspx","Civil Engineering (with integrated foundation year) BEng(Hons)","0"},
			{"58","https://www.brighton.ac.uk/courses/study/civil-engineering-beng-hons.aspx","Civil Engineering BEng(Hons)","0"},
			{"59","https://www.brighton.ac.uk/courses/study/civil-engineering-meng.aspx","Civil Engineering MEng","0"},
			{"60","https://www.brighton.ac.uk/courses/study/civil-engineering-with-construction-management-beng-hons.aspx","Civil Engineering with Construction Management BEng(Hons)","0"},
			{"61","https://www.brighton.ac.uk/courses/study/civil-engineering-with-construction-management-meng.aspx","Civil Engineering with Construction Management MEng","0"},
			{"62","https://www.brighton.ac.uk/courses/study/civil-with-environmental-engineering-beng-hons.aspx","Civil with Environmental Engineering BEng(Hons)","0"},
			{"63","https://www.brighton.ac.uk/courses/study/civil-with-environmental-engineering-meng.aspx","Civil with Environmental Engineering MEng","0"},
			{"64","https://www.brighton.ac.uk/courses/study/community-specialist-practice-bsc-hons.aspx","Community Specialist Practice BSc(Hons)","0"},
			{"65","https://www.brighton.ac.uk/courses/study/computer-science-games-bsc-hons.aspx","Computer Science (Games) BSc(Hons)","0"},
			{"66","https://www.brighton.ac.uk/courses/study/computer-science-bsc-hons.aspx","Computer Science BSc(Hons)","0"},
			{"67","https://www.brighton.ac.uk/courses/study/computer-science-mcomp.aspx","Computer Science MComp","0"},
			{"68","https://www.brighton.ac.uk/courses/study/computer-systems-and-communications-beng-hons.aspx","Computer Systems and Communications BEng(Hons)","0"},
			{"69","https://www.brighton.ac.uk/courses/study/computer-systems-and-communications-meng.aspx","Computer Systems and Communications MEng","0"},
			{"70","https://www.brighton.ac.uk/courses/study/computer-systems-with-networking-bsc-hons.aspx","Computer Systems with Networking BSc(Hons)","0"},
			{"71","https://www.brighton.ac.uk/courses/study/computing-and-business-bsc-hons.aspx","Computing and Business BSc(Hons)","0"},
			{"72","https://www.brighton.ac.uk/courses/study/computing-and-education-bsc-hons.aspx","Computing and Education BSc(Hons)","0"},
			{"73","https://www.brighton.ac.uk/courses/study/construction-management-bsc-hons.aspx","Construction Management BSc(Hons)","0"},
			{"74","https://www.brighton.ac.uk/courses/study/creative-music-production-ba-hons-top-up-degree.aspx","Creative Music Production BA(Hons) top-up degree","0"},
			{"75","https://www.brighton.ac.uk/courses/study/criminology-and-sociology-ba-hons.aspx","Criminology and Sociology BA(Hons)","0"},
			{"76","https://www.brighton.ac.uk/courses/study/criminology-ba-hons.aspx","Criminology BA(Hons)","0"},
			{"77","https://www.brighton.ac.uk/courses/study/digital-film-ba-hons.aspx","Digital Film BA(Hons)","0"},
			{"78","https://www.brighton.ac.uk/courses/study/digital-games-production-bsc-hons.aspx","Digital Games Production BSc(Hons)","0"},
			{"79","https://www.brighton.ac.uk/courses/study/digital-media-bsc-hons.aspx","Digital Media BSc(Hons)","0"},
			{"80","https://www.brighton.ac.uk/courses/study/digital-media-development-bsc-hons.aspx","Digital Media Development BSc(Hons)","0"},
			{"81","https://www.brighton.ac.uk/courses/study/digital-music-and-sound-arts-ba-hons.aspx","Digital Music and Sound Arts BA(Hons)","0"},
			{"82","https://www.brighton.ac.uk/courses/study/diploma-in-professional-studies-in-accounting-acca.aspx","Diploma in Professional Studies in Accounting (ACCA)","0"},
			{"83","https://www.brighton.ac.uk/courses/study/early-childhood-education-and-care-ba-hons.aspx","Early Childhood Education and Care BA(Hons)","0"},
			{"84","https://www.brighton.ac.uk/courses/study/early-childhood-practice-ba-hons.aspx","Early Childhood Practice BA(Hons)","0"},
			{"85","https://www.brighton.ac.uk/courses/study/earth-and-ocean-science-bsc-hons.aspx","Earth and Ocean Science BSc(Hons)","0"},
			{"86","https://www.brighton.ac.uk/courses/study/ecology-bsc-hons.aspx","Ecology BSc(Hons)","0"},
			{"87","https://www.brighton.ac.uk/courses/study/economics-ba-hons.aspx","Economics BA(Hons)","0"},
			{"88","https://www.brighton.ac.uk/courses/study/economics-bsc-hons.aspx","Economics BSc(Hons)","0"},
			{"89","https://www.brighton.ac.uk/courses/study/education-and-english-literature-ba-hons.aspx","Education and English Literature BA(Hons)","0"},
			{"90","https://www.brighton.ac.uk/courses/study/education-and-sociology-ba-hons.aspx","Education and Sociology BA(Hons)","0"},
			{"91","https://www.brighton.ac.uk/courses/study/education-ba-hons.aspx","Education BA(Hons)","0"},
			{"92","https://www.brighton.ac.uk/courses/study/electrical-and-electronic-engineering-beng-hons.aspx","Electrical and Electronic Engineering BEng(Hons)","0"},
			{"93","https://www.brighton.ac.uk/courses/study/electrical-and-electronic-engineering-beng-hons-with-integrated-foundation-year.aspx","Electrical and Electronic Engineering BEng(Hons) (with integrated foundation year)","0"},
			{"94","https://www.brighton.ac.uk/courses/study/electrical-and-electronic-engineering-meng.aspx","Electrical and Electronic Engineering MEng","0"},
			{"95","https://www.brighton.ac.uk/courses/study/electronic-and-computer-engineering-beng-hons.aspx","Electronic and Computer Engineering BEng(Hons)","0"},
			{"96","https://www.brighton.ac.uk/courses/study/electronic-and-computer-engineering-beng-hons-with-integrated-foundation-year.aspx","Electronic and Computer Engineering BEng(Hons) (with integrated foundation year)","0"},
			{"97","https://www.brighton.ac.uk/courses/study/electronic-and-computer-engineering-meng.aspx","Electronic and Computer Engineering MEng","0"},
			{"98","https://www.brighton.ac.uk/courses/study/electronic-engineering-bsc-hons-top-up-degree.aspx","Electronic Engineering BSc(Hons) top-up degree","0"},
			{"99","https://www.brighton.ac.uk/courses/study/engineering-integrated-foundation-year.aspx","Engineering integrated foundation year","0"},
			{"100","https://www.brighton.ac.uk/courses/study/english-for-academic-study-ug.aspx","English for Academic Study","0"},
			{"101","https://www.brighton.ac.uk/courses/study/english-language-and-creative-writing-ba-hons.aspx","English Language and Creative Writing BA(Hons)","0"},
			{"102","https://www.brighton.ac.uk/courses/study/english-language-and-english-literature-ba-hons.aspx","English Language and English Literature BA(Hons)","0"},
			{"103","https://www.brighton.ac.uk/courses/study/english-language-and-linguistics-ba-hons.aspx","English Language and Linguistics BA(Hons)","0"},
			{"104","https://www.brighton.ac.uk/courses/study/english-language-and-media-ba-hons.aspx","English Language and Media BA(Hons)","0"},
			{"105","https://www.brighton.ac.uk/courses/study/english-language-ba-hons.aspx","English Language BA(Hons)","0"},
			{"106","https://www.brighton.ac.uk/courses/study/english-literature-and-creative-writing-ba-hons.aspx","English Literature and Creative Writing BA(Hons)","0"},
			{"107","https://www.brighton.ac.uk/courses/study/english-literature-and-linguistics-ba-hons.aspx","English Literature and Linguistics BA(Hons)","0"},
			{"108","https://www.brighton.ac.uk/courses/study/english-literature-and-media-studies-ba-hons.aspx","English Literature and Media Studies BA(Hons)","0"},
			{"109","https://www.brighton.ac.uk/courses/study/english-literature-and-social-history-ba-hons.aspx","English Literature and Social History BA(Hons)","0"},
			{"110","https://www.brighton.ac.uk/courses/study/english-literature-ba-hons.aspx","English Literature BA(Hons)","0"},
			{"111","https://www.brighton.ac.uk/courses/study/environment-and-media-studies-ba-hons.aspx","Environment and Media Studies BA(Hons)","0"},
			{"112","https://www.brighton.ac.uk/courses/study/environmental-biology-and-education-bsc-hons.aspx","Environmental Biology and Education BSc(Hons)","0"},
			{"113","https://www.brighton.ac.uk/courses/study/environmental-sciences-bsc-hons.aspx","Environmental Sciences BSc(Hons)","0"},
			{"114","https://www.brighton.ac.uk/courses/study/euro-ba-in-international-hospitality-management.aspx","Euro BA in International Hospitality Management","0"},
			{"115","https://www.brighton.ac.uk/courses/study/european-computing-dest-informatique-bsc-hons.aspx","European Computing/DEST Informatique BSc(Hons)","0"},
			{"116","https://www.brighton.ac.uk/courses/study/fashion-and-dress-history-ba-hons.aspx","Fashion and Dress History BA(Hons)","0"},
			{"117","https://www.brighton.ac.uk/courses/study/fashion-communication-with-business-studies-ba-hons.aspx","Fashion Communication with Business Studies BA(Hons)","0"},
			{"118","https://www.brighton.ac.uk/courses/study/fashion-with-business-studies-ba-hons.aspx","Fashion with Business Studies BA(Hons)","0"},
			{"119","https://www.brighton.ac.uk/courses/study/fashion-with-business-studies-mdes.aspx","Fashion with Business Studies MDes","0"},
			{"120","https://www.brighton.ac.uk/courses/study/film-and-screen-studies-ba-hons.aspx","Film and Screen Studies BA(Hons)","0"},
			{"121","https://www.brighton.ac.uk/courses/study/finance-and-investment-bsc-hons.aspx","Finance and Investment BSc(Hons)","0"},
			{"122","https://www.brighton.ac.uk/courses/study/fine-art-painting-ba-hons.aspx","Fine Art Painting BA(Hons)","0"},
			{"123","https://www.brighton.ac.uk/courses/study/fine-art-sculpture-ba-hons.aspx","Fine Art Sculpture BA(Hons)","0"},
			{"124","https://www.brighton.ac.uk/courses/study/fine-art-critical-practice-ba-hons.aspx","Fine Art: Critical Practice BA(Hons)","0"},
			{"125","https://www.brighton.ac.uk/courses/study/fine-art-printmaking-ba-hons.aspx","Fine Art: Printmaking BA(Hons)","0"},
			{"126","https://www.brighton.ac.uk/courses/study/geography-ba-hons.aspx","Geography BA(Hons)","0"},
			{"127","https://www.brighton.ac.uk/courses/study/geography-bsc-hons.aspx","Geography BSc(Hons)","0"},
			{"128","https://www.brighton.ac.uk/courses/study/geography-mgeog.aspx","Geography MGeog","0"},
			{"129","https://www.brighton.ac.uk/courses/study/geography-with-geoinformatics-bsc-hons.aspx","Geography with Geoinformatics BSc(Hons)","0"},
			{"130","https://www.brighton.ac.uk/courses/study/geology-bsc-hons.aspx","Geology BSc(Hons)","0"},
			{"131","https://www.brighton.ac.uk/courses/study/geology-mgeol.aspx","Geology MGeol","0"},
			{"132","https://www.brighton.ac.uk/courses/study/globalisation-history-politics-culture-ba-hons.aspx","Globalisation: History, Politics, Culture BA(Hons)","0"},
			{"133","https://www.brighton.ac.uk/courses/study/graphic-design-ba-hons.aspx","Graphic Design BA(Hons)","0"},
			{"134","https://www.brighton.ac.uk/courses/study/graphic-design-for-digital-media-ba-hons.aspx","Graphic Design for Digital Media BA(Hons)","0"},
			{"135","https://www.brighton.ac.uk/courses/study/health-and-social-care-practice-foundation-degree.aspx","Health and Social Care Practice foundation degree","0"},
			{"136","https://www.brighton.ac.uk/courses/study/health-studies-bsc-hons-top-up-degree.aspx","Health Studies BSc(Hons) top-up degree","0"},
			{"137","https://www.brighton.ac.uk/courses/study/history-of-art-and-design-ba-hons.aspx","History of Art and Design BA(Hons)","0"},
			{"138","https://www.brighton.ac.uk/courses/study/history-literature-and-culture-ba-hons.aspx","History, Literature and Culture BA(Hons)","0"},
			{"139","https://www.brighton.ac.uk/courses/study/human-biology-and-education-bsc-hons.aspx","Human Biology and Education BSc(Hons)","0"},
			{"140","https://www.brighton.ac.uk/courses/study/humanities-ba-hons.aspx","Humanities BA(Hons)","0"},
			{"141","https://www.brighton.ac.uk/courses/study/humanities-war-conflict-and-modernity-ba-hons.aspx","Humanities: War, Conflict and Modernity BA(Hons)","0"},
			{"142","https://www.brighton.ac.uk/courses/study/illustration-ba-hons.aspx","Illustration BA(Hons)","0"},
			{"143","https://www.brighton.ac.uk/courses/study/illustration-for-screen-arts-ba-hons.aspx","Illustration for Screen Arts BA(Hons)","0"},
			{"144","https://www.brighton.ac.uk/courses/study/interior-architecture-ba-hons.aspx","Interior Architecture BA(Hons)","0"},
			{"145","https://www.brighton.ac.uk/courses/study/interior-design-ba-hons-top-up-degree.aspx","Interior Design BA(Hons) top-up degree","0"},
			{"146","https://www.brighton.ac.uk/courses/study/interior-design-diploma.aspx","Interior Design Diploma","0"},
			{"147","https://www.brighton.ac.uk/courses/study/interior-design-foundation-degree.aspx","Interior Design foundation degree","0"},
			{"148","https://www.brighton.ac.uk/courses/study/intermediate-french-cert.aspx","Intermediate French Cert","0"},
			{"149","https://www.brighton.ac.uk/courses/study/intermediate-german-cert.aspx","Intermediate German Cert","0"},
			{"150","https://www.brighton.ac.uk/courses/study/intermediate-spanish-cert.aspx","Intermediate Spanish Cert","0"},
			{"151","https://www.brighton.ac.uk/courses/study/international-business-bsc-hons.aspx","International Business BSc(Hons)","0"},
			{"152","https://www.brighton.ac.uk/courses/study/international-event-management-ba-hons.aspx","International Event Management BA(Hons)","0"},
			{"153","https://www.brighton.ac.uk/courses/study/international-event-management-ba-hons-top-up-degree.aspx","International Event Management BA(Hons) top-up degree","0"},
			{"154","https://www.brighton.ac.uk/courses/study/international-hospitality-management-ba-hons.aspx","International Hospitality Management BA(Hons)","0"},
			{"155","https://www.brighton.ac.uk/courses/study/international-hospitality-management-ba-hons-top-up-degree.aspx","International Hospitality Management BA(Hons) top-up degree","0"},
			{"156","https://www.brighton.ac.uk/courses/study/international-tourism-management-ba-hons.aspx","International Tourism Management BA(Hons)","0"},
			{"157","https://www.brighton.ac.uk/courses/study/international-tourism-management-ba-hons-top-up-degree.aspx","International Tourism Management BA(Hons) top-up degree","0"},
			{"158","https://www.brighton.ac.uk/courses/study/international-travel-management-ba-hons-top-up-degree.aspx","International Travel Management BA(Hons) top-up degree","0"},
			{"159","https://www.brighton.ac.uk/courses/study/journalism-ba-hons.aspx","Journalism BA(Hons)","0"},
			{"160","https://www.brighton.ac.uk/courses/study/law-with-business-llb-hons.aspx","Law with Business LLB(Hons)","0"},
			{"161","https://www.brighton.ac.uk/courses/study/law-with-criminology-llb-hons.aspx","Law with Criminology LLB(Hons)","0"},
			{"162","https://www.brighton.ac.uk/courses/study/linguistics-ba-hons.aspx","Linguistics BA(Hons)","0"},
			{"163","https://www.brighton.ac.uk/courses/study/marketing-bsc-hons.aspx","Marketing BSc(Hons)","0"},
			{"164","https://www.brighton.ac.uk/courses/study/marketing-management-bsc-hons.aspx","Marketing Management BSc(Hons)","0"},
			{"165","https://www.brighton.ac.uk/courses/study/mathematics-and-business-bsc-hons.aspx","Mathematics and Business BSc(Hons)","0"},
			{"166","https://www.brighton.ac.uk/courses/study/mathematics-and-computing-bsc-hons.aspx","Mathematics and Computing BSc(Hons)","0"},
			{"167","https://www.brighton.ac.uk/courses/study/mathematics-and-education-bsc-hons.aspx","Mathematics and Education BSc(Hons)","0"},
			{"168","https://www.brighton.ac.uk/courses/study/mathematics-bsc-hons.aspx","Mathematics BSc(Hons)","0"},
			{"169","https://www.brighton.ac.uk/courses/study/mathematics-with-business-bsc-hons.aspx","Mathematics with Business BSc(Hons)","0"},
			{"170","https://www.brighton.ac.uk/courses/study/mathematics-with-economics-bsc-hons.aspx","Mathematics with Economics BSc(Hons)","0"},
			{"171","https://www.brighton.ac.uk/courses/study/mathematics-with-finance-bsc-hons.aspx","Mathematics with Finance BSc(Hons)","0"},
			{"172","https://www.brighton.ac.uk/courses/study/mechanical-and-manufacturing-engineering-bsc-hons-top-up-degree.aspx","Mechanical and Manufacturing Engineering BSc(Hons) top-up degree","0"},
			{"173","https://www.brighton.ac.uk/courses/study/mechanical-engineering-beng-hons.aspx","Mechanical Engineering BEng(Hons)","0"},
			{"174","https://www.brighton.ac.uk/courses/study/mechanical-engineering-beng-hons-with-integrated-foundation-year.aspx","Mechanical Engineering BEng(Hons) (with integrated foundation year)","0"},
			{"175","https://www.brighton.ac.uk/courses/study/mechanical-engineering-meng.aspx","Mechanical Engineering MEng","0"},
			{"176","https://www.brighton.ac.uk/courses/study/media-and-english-literature-ba-hons.aspx","Media and English Literature BA(Hons)","0"},
			{"177","https://www.brighton.ac.uk/courses/study/media-studies-and-education-ba-hons.aspx","Media Studies and Education BA(Hons)","0"},
			{"178","https://www.brighton.ac.uk/courses/study/media-studies-and-sociology-ba-hons.aspx","Media Studies and Sociology BA(Hons)","0"},
			{"179","https://www.brighton.ac.uk/courses/study/media-studies-ba-hons.aspx","Media Studies BA(Hons)","0"},
			{"180","https://www.brighton.ac.uk/courses/study/media-industry-and-innovation-ba-hons.aspx","Media, Industry and Innovation BA(Hons)","0"},
			{"181","https://www.brighton.ac.uk/courses/study/medicine-bm-bs.aspx","Medicine BM BS","0"},
			{"182","https://www.brighton.ac.uk/courses/study/midwifery-3-years-bsc-hons.aspx","Midwifery (3 years) BSc(Hons)","0"},
			{"183","https://www.brighton.ac.uk/courses/study/moving-image-ba-hons.aspx","Moving Image BA(Hons)","0"},
			{"184","https://www.brighton.ac.uk/courses/study/multimedia-broadcast-journalism-ba-hons.aspx","Multimedia Broadcast Journalism BA(Hons)","0"},
			{"185","https://www.brighton.ac.uk/courses/study/nurse-practitioner-bsc-hons-top-up-degree.aspx","Nurse Practitioner BSc(Hons) top-up degree","0"},
			{"186","https://www.brighton.ac.uk/courses/study/nursing-adult-bsc-hons.aspx","Nursing (Adult) BSc(Hons)","0"},
			{"187","https://www.brighton.ac.uk/courses/study/nursing-child-bsc-hons.aspx","Nursing (Child) BSc(Hons)","0"},
			{"188","https://www.brighton.ac.uk/courses/study/nursing-mental-health-bsc-hons.aspx","Nursing (Mental Health) BSc(Hons)","0"},
			{"189","https://www.brighton.ac.uk/courses/study/occupational-therapy-bsc-hons.aspx","Occupational Therapy BSc(Hons)","0"},
			{"190","https://www.brighton.ac.uk/courses/study/paramedic-practice-bsc-hons.aspx","Paramedic Practice BSc(Hons)","0"},
			{"191","https://www.brighton.ac.uk/courses/study/pharmaceutical-and-chemical-sciences-bsc-hons.aspx","Pharmaceutical and Chemical Sciences BSc(Hons)","0"},
			{"192","https://www.brighton.ac.uk/courses/study/pharmacy-mpharm.aspx","Pharmacy MPharm","0"},
			{"193","https://www.brighton.ac.uk/courses/study/philosophy-politics-and-art-ba-hons.aspx","Philosophy, Politics and Art BA(Hons)","0"},
			{"194","https://www.brighton.ac.uk/courses/study/philosophy-politics-and-ethics-ba-hons.aspx","Philosophy, Politics and Ethics BA(Hons)","0"},
			{"195","https://www.brighton.ac.uk/courses/study/photography-ba-hons.aspx","Photography BA(Hons)","0"},
			{"196","https://www.brighton.ac.uk/courses/study/physical-education-ba-hons.aspx","Physical Education BA(Hons)","0"},
			{"197","https://www.brighton.ac.uk/courses/study/physical-education-ba-hons-with-qts.aspx","Physical Education BA(Hons) with QTS","0"},
			{"198","https://www.brighton.ac.uk/courses/study/physical-geography-and-geology-bsc-hons.aspx","Physical Geography and Geology BSc(Hons)","0"},
			{"199","https://www.brighton.ac.uk/courses/study/physiotherapy-bsc-hons.aspx","Physiotherapy BSc(Hons)","0"},
			{"200","https://www.brighton.ac.uk/courses/study/podiatry-bsc-hons.aspx","Podiatry BSc(Hons)","0"},
			{"201","https://www.brighton.ac.uk/courses/study/politics-ba-hons.aspx","Politics BA(Hons)","0"},
			{"202","https://www.brighton.ac.uk/courses/study/primary-education-3-7-years-ba-hons-with-qts.aspx","Primary Education (3–7 years) BA(Hons) with QTS","0"},
			{"203","https://www.brighton.ac.uk/courses/study/primary-education-5-11-years-ba-hons-with-qts.aspx","Primary Education (5–11 years) BA(Hons) with QTS","0"},
			{"204","https://www.brighton.ac.uk/courses/study/primary-english-education-ba-hons-with-qts.aspx","Primary English Education BA(Hons) with QTS","0"},
			{"205","https://www.brighton.ac.uk/courses/study/primary-mathematics-education-ba-hons-with-qts.aspx","Primary Mathematics Education BA(Hons) with QTS","0"},
			{"206","https://www.brighton.ac.uk/courses/study/product-design-technology-with-professional-experience-bsc-hons.aspx","Product Design Technology with Professional Experience BSc(Hons)","0"},
			{"207","https://www.brighton.ac.uk/courses/study/product-design-with-professional-experience-bsc-hons.aspx","Product Design with Professional Experience BSc(Hons)","0"},
			{"208","https://www.brighton.ac.uk/courses/study/professional-practice-bsc-hons-top-up-degree.aspx","Professional Practice BSc(Hons) top-up degree","0"},
			{"209","https://www.brighton.ac.uk/courses/study/professional-studies-in-learning-and-development-ba-hons.aspx","Professional Studies in Learning and Development BA(Hons)","0"},
			{"210","https://www.brighton.ac.uk/courses/study/project-management-for-construction-bsc-hons.aspx","Project Management for Construction BSc(Hons)","0"},
			{"211","https://www.brighton.ac.uk/courses/study/public-health-bsc-hons.aspx","Public Health BSc(Hons)","0"},
			{"212","https://www.brighton.ac.uk/courses/study/retail-management-ba-hons.aspx","Retail Management BA(Hons)","0"},
			{"213","https://www.brighton.ac.uk/courses/study/retail-management-ba-hons-top-up-degree.aspx","Retail Management BA(Hons) top-up degree","0"},
			{"214","https://www.brighton.ac.uk/courses/study/retail-marketing-ba-hons.aspx","Retail Marketing BA(Hons)","0"},
			{"215","https://www.brighton.ac.uk/courses/study/retail-marketing-ba-hons-top-up-degree.aspx","Retail Marketing BA(Hons) top-up degree","0"},
			{"216","https://www.brighton.ac.uk/courses/study/secondary-mathematics-education-ba-hons-with-qts.aspx","Secondary Mathematics Education BA(Hons) with QTS","0"},
			{"217","https://www.brighton.ac.uk/courses/study/social-policy-and-practice-bsc-hons.aspx","Social Policy and Practice BSc(Hons)","0"},
			{"218","https://www.brighton.ac.uk/courses/study/social-science-ba-hons.aspx","Social Science BA(Hons)","0"},
			{"219","https://www.brighton.ac.uk/courses/study/social-work-bsc-hons.aspx","Social Work BSc(Hons)","0"},
			{"220","https://www.brighton.ac.uk/courses/study/sociology-and-english-literature-ba-hons.aspx","Sociology and English Literature BA(Hons)","0"},
			{"221","https://www.brighton.ac.uk/courses/study/sociology-and-social-history-ba-hons.aspx","Sociology and Social History BA(Hons)","0"},
			{"222","https://www.brighton.ac.uk/courses/study/sociology-ba-hons.aspx","Sociology BA(Hons)","0"},
			{"223","https://www.brighton.ac.uk/courses/study/software-engineering-bsc-hons.aspx","Software Engineering BSc(Hons)","0"},
			{"224","https://www.brighton.ac.uk/courses/study/software-engineering-mcomp.aspx","Software Engineering MComp","0"},
			{"225","https://www.brighton.ac.uk/courses/study/specialist-community-public-health-nursing-bsc-hons.aspx","Specialist Community Public Health Nursing BSc(Hons)","0"},
			{"226","https://www.brighton.ac.uk/courses/study/sport-and-exercise-science-bsc-hons.aspx","Sport and Exercise Science BSc(Hons)","0"},
			{"227","https://www.brighton.ac.uk/courses/study/sport-and-fitness-bsc-hons-top-up-degree.aspx","Sport and Fitness BSc(Hons) top-up degree","0"},
			{"228","https://www.brighton.ac.uk/courses/study/sport-business-management-bsc-hons.aspx","Sport Business Management BSc(Hons)","0"},
			{"229","https://www.brighton.ac.uk/courses/study/sport-coaching-and-development-ba-hons-top-up-degree.aspx","Sport Coaching and Development BA(Hons) top-up degree","0"},
			{"230","https://www.brighton.ac.uk/courses/study/sport-coaching-bsc-hons.aspx","Sport Coaching BSc(Hons)","0"},
			{"231","https://www.brighton.ac.uk/courses/study/sport-journalism-ba-hons.aspx","Sport Journalism BA(Hons)","0"},
			{"232","https://www.brighton.ac.uk/courses/study/sport-studies-ba-hons.aspx","Sport Studies BA(Hons)","0"},
			{"233","https://www.brighton.ac.uk/courses/study/sports-product-design-with-professional-experience-bsc-hons.aspx","Sports Product Design with Professional Experience BSc(Hons)","0"},
			{"234","https://www.brighton.ac.uk/courses/study/summer-pre-sessional-ug.aspx","Summer Pre-sessional","0"},
			{"235","https://www.brighton.ac.uk/courses/study/supporting-learning-11-19-years-ba-hons.aspx","Supporting Learning 11-19 Years BA(Hons)","0"},
			{"236","https://www.brighton.ac.uk/courses/study/supporting-learning-5-11-years-ba-hons.aspx","Supporting Learning 5-11 Years BA(Hons)","0"},
			{"237","https://www.brighton.ac.uk/courses/study/television-and-digital-media-production-ba-hons.aspx","Television and Digital Media Production BA(Hons)","0"},
			{"238","https://www.brighton.ac.uk/courses/study/television-production-foundation-degree.aspx","Television Production foundation degree","0"},
			{"239","https://www.brighton.ac.uk/courses/study/textiles-with-business-studies-ba-hons.aspx","Textiles with Business Studies BA(Hons)","0"},
			{"240","https://www.brighton.ac.uk/courses/study/textiles-with-business-studies-mdes.aspx","Textiles with Business Studies MDes","0"},
			{"241","https://www.brighton.ac.uk/courses/study/troops-to-teachers-non-graduate-programme.aspx","Troops to Teachers non-graduate programme","0"},
			{"242","https://www.brighton.ac.uk/courses/study/visual-culture-ba-hons.aspx","Visual Culture BA(Hons)","0"},
			{"243","https://www.brighton.ac.uk/courses/study/working-with-children-and-young-people-ba-hons.aspx","Working with Children and Young People BA(Hons)","0"},
			{"244","https://www.brighton.ac.uk/courses/study/youth-work-ba-hons.aspx","Youth Work BA(Hons)","0"}
		};
		public static String[][] PostData={
			{"1","https://www.brighton.ac.uk/courses/study/secondary-biology-pgce-profgce.aspx","(Secondary) Biology PGCE PROFGCE","0"},
			{"2","https://www.brighton.ac.uk/courses/study/secondary-chemistry-pgce-profgce.aspx","(Secondary) Chemistry PGCE PROFGCE","0"},
			{"3","https://www.brighton.ac.uk/courses/study/secondary-physics-pgce-profgce.aspx","(Secondary) Physics PGCE PROFGCE","0"},
			{"4","https://www.brighton.ac.uk/courses/study/secondary-physics-with-mathematics-pgce-profgce.aspx","(Secondary) Physics with Mathematics PGCE (PROFGCE)","0"},
			{"5","https://www.brighton.ac.uk/courses/study/accounting-acca-msc-pgcert-pgdip.aspx","Accounting (ACCA) MSc (PGCert PGDip)","0"},
			{"6","https://www.brighton.ac.uk/courses/study/advanced-practice-health-msc-pgdip.aspx","Advanced Practice (Health) MSc (PGDip)","0"},
			{"7","https://www.brighton.ac.uk/courses/study/advanced-social-work-and-management-msc.aspx","Advanced Social Work and Management MSc","0"},
			{"8","https://www.brighton.ac.uk/courses/study/advanced-social-work-msc.aspx","Advanced Social Work MSc","0"},
			{"9","https://www.brighton.ac.uk/courses/study/anaesthesia-and-perioperative-medicine-msc-pgcert-pgdip.aspx","Anaesthesia and Perioperative Medicine MSc, PGCert, PGDip","0"},
			{"10","https://www.brighton.ac.uk/courses/study/applied-ethics-ma-pgcert-pgdip.aspx","Applied Ethics MA (PGCert PGDip)","0"},
			{"11","https://www.brighton.ac.uk/courses/study/applied-exercise-physiology-msc-pgcert-pgdip.aspx","Applied Exercise Physiology MSc (PGCert PGDip)","0"},
			{"12","https://www.brighton.ac.uk/courses/study/applied-sport-physiology-msc-pgcert-pgdip.aspx","Applied Sport Physiology MSc (PGCert PGDip)","0"},
			{"13","https://www.brighton.ac.uk/courses/study/approved-mental-health-practice-pgdip.aspx","Approved Mental Health Practice PGDip","0"},
			{"14","https://www.brighton.ac.uk/courses/study/architectural-and-urban-design-ma-pgcert-pgdip.aspx","Architectural and Urban Design MA (PGCert PGDip)","0"},
			{"15","https://www.brighton.ac.uk/courses/study/architecture-post-part-2-professional-experience.aspx","Architecture Post Part 2 Professional Experience","0"},
			{"16","https://www.brighton.ac.uk/courses/study/architecture-professional-practice-pre-diploma.aspx","Architecture Professional Practice Pre-Diploma","0"},
			{"17","https://www.brighton.ac.uk/courses/study/architecture-riba-part-2-march.aspx","Architecture RIBA Part 2 MArch","0"},
			{"18","https://www.brighton.ac.uk/courses/study/architecture-riba-part-3-pgdip.aspx","Architecture RIBA Part 3 PGDip","0"},
			{"19","https://www.brighton.ac.uk/courses/study/art-and-design-secondary-pgce-profgce.aspx","Art and Design (Secondary) PGCE (PROFGCE)","0"},
			{"20","https://www.brighton.ac.uk/courses/study/arts-and-cultural-research-mres-pgcert-pgdip.aspx","Arts and Cultural Research MRes (PGCert PGDip)","0"},
			{"21","https://www.brighton.ac.uk/courses/study/arts-and-design-by-independent-project-ma.aspx","Arts and Design by Independent Project MA","0"},
			{"22","https://www.brighton.ac.uk/courses/study/automotive-electronic-engineering-msc-pgcert-pgdip.aspx","Automotive Electronic Engineering MSc (PGCert PGDip)","0"},
			{"23","https://www.brighton.ac.uk/courses/study/biomedical-sciences-msc-pgcert-pgdip.aspx","Biomedical Sciences MSc (PGCert PGDip)","0"},
			{"24","https://www.brighton.ac.uk/courses/study/bioscience-mres.aspx","Bioscience MRes","0"},
			{"25","https://www.brighton.ac.uk/courses/study/blood-sciences-msc-pgcert-pgdip.aspx","Blood Sciences MSc (PGCert PGDip)","0"},
			{"26","https://www.brighton.ac.uk/courses/study/by-learning-objectives-msc-pgcert-pgdip.aspx","By Learning Objectives MSc (PGCert PGDip)","0"},
			{"27","https://www.brighton.ac.uk/courses/study/cardiology-msc-pgcert-pgdip.aspx","Cardiology MSc (PGCert PGDip)","0"},
			{"28","https://www.brighton.ac.uk/courses/study/cellular-sciences-msc-pgcert-pgdip.aspx","Cellular Sciences MSc (PGCert PGDip)","0"},
			{"29","https://www.brighton.ac.uk/courses/study/change-management-pgcert.aspx","Change Management PGCert","0"},
			{"30","https://www.brighton.ac.uk/courses/study/chemistry-mres-pgcert-pgdip.aspx","Chemistry MRes (PGCert PGDip)","0"},
			{"31","https://www.brighton.ac.uk/courses/study/civil-engineering-msc-pgcert-pgdip.aspx","Civil Engineering MSc (PGCert PGDip)","0"},
			{"32","https://www.brighton.ac.uk/courses/study/clinical-pharmacy-msc.aspx","Clinical Pharmacy MSc","0"},
			{"33","https://www.brighton.ac.uk/courses/study/clinical-pharmacy-practice-msc.aspx","Clinical Pharmacy Practice MSc","0"},
			{"34","https://www.brighton.ac.uk/courses/study/clinical-radiology-msc-pgcert-pgdip.aspx","Clinical Radiology MSc (PGCert, PGDip)","0"},
			{"35","https://www.brighton.ac.uk/courses/study/clinical-research-mres-pgcert-pgdip.aspx","Clinical Research MRes (PGCert PGDip)","0"},
			{"36","https://www.brighton.ac.uk/courses/study/community-health-and-education-msc-pgcert-pgdip.aspx","Community Health and Education MSc (PGCert PGDip)","0"},
			{"37","https://www.brighton.ac.uk/courses/study/community-health-and-management-msc-pgcert-pgdip.aspx","Community Health and Management MSc (PGCert PGDip)","0"},
			{"38","https://www.brighton.ac.uk/courses/study/community-health-msc-pgcert-pgdip.aspx","Community Health MSc (PGCert PGDip)","0"},
			{"39","https://www.brighton.ac.uk/courses/study/community-psychology-ma.aspx","Community Psychology MA","0"},
			{"40","https://www.brighton.ac.uk/courses/study/community-specialist-practice-msc-pgdip.aspx","Community Specialist Practice MSc PGDip","0"},
			{"41","https://www.brighton.ac.uk/courses/study/computer-science-msc-pgcert-pgdip.aspx","Computer Science MSc (PGCert PGDip)","0"},
			{"42","https://www.brighton.ac.uk/courses/study/computing-msc-pgcert-pgdip.aspx","Computing MSc (PGCert PGDip)","0"},
			{"43","https://www.brighton.ac.uk/courses/study/construction-management-msc-pgcert-pgdip.aspx","Construction Management MSc (PGCert PGDip)","0"},
			{"44","https://www.brighton.ac.uk/courses/study/craft-ma-pgdip.aspx","Craft MA (PGDip)","0"},
			{"45","https://www.brighton.ac.uk/courses/study/creative-media-ma.aspx","Creative Media MA","0"},
			{"46","https://www.brighton.ac.uk/courses/study/creative-writing-ma-pgcert-pgdip.aspx","Creative Writing MA (PGCert PGDip)","0"},
			{"47","https://www.brighton.ac.uk/courses/study/cultural-and-critical-theory-ma-pgcert-pgdip.aspx","Cultural and Critical Theory MA (PGCert PGDip)","0"},
			{"48","https://www.brighton.ac.uk/courses/study/cultural-history-memory-and-identity-ma-pgcert-pgdip.aspx","Cultural History, Memory and Identity MA (PGCert PGDip)","0"},
			{"49","https://www.brighton.ac.uk/courses/study/dance-secondary-pgce-profgce.aspx","Dance (Secondary) PGCE (PROFGCE)","0"},
			{"50","https://www.brighton.ac.uk/courses/study/data-analytics-msc-pgcert-pgdip.aspx","Data Analytics MSc (PGCert PGDip)","0"},
			{"51","https://www.brighton.ac.uk/courses/study/dementia-studies-msc-pgcert-pgdip.aspx","Dementia Studies MSc (PGCert PGDip)","0"},
			{"52","https://www.brighton.ac.uk/courses/study/design-and-technology-secondary-pgce-profgce.aspx","Design and Technology (Secondary) PGCE (PROFGCE)","0"},
			{"53","https://www.brighton.ac.uk/courses/study/diabetes-in-primary-care-pgcert.aspx","Diabetes in Primary Care PGCert","0"},
			{"54","https://www.brighton.ac.uk/courses/study/digital-media-arts-ma.aspx","Digital Media Arts MA","0"},
			{"55","https://www.brighton.ac.uk/courses/study/digital-media-production-msc.aspx","Digital Media Production MSc","0"},
			{"56","https://www.brighton.ac.uk/courses/study/early-years-initial-teacher-training.aspx","Early Years Initial Teacher Training","0"},
			{"57","https://www.brighton.ac.uk/courses/study/ecology-mres-pgcert-pgdip.aspx","Ecology MRes (PGCert PGDip)","0"},
			{"58","https://www.brighton.ac.uk/courses/study/economics-and-finance-msc-pgcert-pgdip.aspx","Economics and Finance MSc (PGCert PGDIP)","0"},
			{"59","https://www.brighton.ac.uk/courses/study/education-early-childhood-ma-pgcert-pgdip.aspx","Education (Early Childhood) MA (PGCert PGDip)","0"},
			{"60","https://www.brighton.ac.uk/courses/study/education-higher-education-ma-pgcert-pgdip.aspx","Education (Higher Education) MA (PGCert PGDip)","0"},
			{"61","https://www.brighton.ac.uk/courses/study/education-international-education-ma-pgcert-pgdip.aspx","Education (International Education) MA (PGCert PGDip)","0"},
			{"62","https://www.brighton.ac.uk/courses/study/education-leadership-and-management-ma-pgcert-pgdip.aspx","Education (Leadership and Management) MA (PGCert PGDip)","0"},
			{"63","https://www.brighton.ac.uk/courses/study/education-mathematics-education-ma-pgcert-pgdip.aspx","Education (Mathematics Education) MA (PGCert PGDip)","0"},
			{"64","https://www.brighton.ac.uk/courses/study/education-ma-pgcert-pgdip.aspx","Education MA (PGCert PGDip)","0"},
			{"65","https://www.brighton.ac.uk/courses/study/english-secondary-pgce-profgce.aspx","English (Secondary) PGCE (PROFGCE)","0"},
			{"66","https://www.brighton.ac.uk/courses/study/english-for-academic-study-pg.aspx","English for Academic Study","0"},
			{"67","https://www.brighton.ac.uk/courses/study/english-language-ma.aspx","English Language MA","0"},
			{"68","https://www.brighton.ac.uk/courses/study/environmental-assessment-and-management-msc-pgcert-pgdip.aspx","Environmental Assessment and Management MSc (PGCert PGDip)","0"},
			{"69","https://www.brighton.ac.uk/courses/study/ethics-of-art-and-design-ma-pgcert-pgdip.aspx","Ethics of Art and Design MA PGCert PGDip","0"},
			{"70","https://www.brighton.ac.uk/courses/study/ethics-of-education-ma-pgcert-pgdip.aspx","Ethics of Education MA PGCert PGDip","0"},
			{"71","https://www.brighton.ac.uk/courses/study/evidence-informed-practice-pgce.aspx","Evidence Informed Practice PGCE","0"},
			{"72","https://www.brighton.ac.uk/courses/study/extended-masters.aspx","Extended Masters","0"},
			{"73","https://www.brighton.ac.uk/courses/study/fashion-ma.aspx","Fashion MA","0"},
			{"74","https://www.brighton.ac.uk/courses/study/finance-and-accounting-msc.aspx","Finance and Accounting MSc","0"},
			{"75","https://www.brighton.ac.uk/courses/study/finance-and-banking-msc.aspx","Finance and Banking MSc","0"},
			{"76","https://www.brighton.ac.uk/courses/study/finance-and-investment-msc-pgcert-pgdip.aspx","Finance and Investment MSc (PGCert PGDip)","0"},
			{"77","https://www.brighton.ac.uk/courses/study/finance-and-risk-management-msc.aspx","Finance and Risk Management MSc","0"},
			{"78","https://www.brighton.ac.uk/courses/study/fine-art-ma.aspx","Fine Art MA","0"},
			{"79","https://www.brighton.ac.uk/courses/study/further-education-and-training-pgce-cert-certed-profgce.aspx","Further Education and Training PGCE (Cert CertEd PROFGCE)","0"},
			{"80","https://www.brighton.ac.uk/courses/study/general-management-full-time-mba-pgcert-pgdip.aspx","General Management (Full-time) MBA (PGCert PGDip)","0"},
			{"81","https://www.brighton.ac.uk/courses/study/general-management-part-time-mba-pgcert-pgdip.aspx","General Management (Part-time) MBA (PGCert PGDip)","0"},
			{"82","https://www.brighton.ac.uk/courses/study/general-pharmacy-practice-pgdip-pgcert.aspx","General Pharmacy Practice PGDip (PGCert)","0"},
			{"83","https://www.brighton.ac.uk/courses/study/geographical-information-systems-and-environmental-management-msc-pgdip.aspx","Geographical Information Systems and Environmental Management MSc (PGDip)","0"},
			{"84","https://www.brighton.ac.uk/courses/study/geography-secondary-pgce-profgce.aspx","Geography (Secondary) PGCE (PROFGCE)","0"},
			{"85","https://www.brighton.ac.uk/courses/study/global-health-msc-pgcert-pgdip.aspx","Global Health MSc (PGCert PGDip)","0"},
			{"86","https://www.brighton.ac.uk/courses/study/globalisation-politics-conflict-and-human-rights-ma-pgcert-pgdip.aspx","Globalisation: Politics, Conflict and Human Rights MA (PGCert PGDip)","0"},
			{"87","https://www.brighton.ac.uk/courses/study/health-and-education-msc-pgcert-pgdip.aspx","Health and Education MSc (PGCert PGDip)","0"},
			{"88","https://www.brighton.ac.uk/courses/study/health-and-management-msc-pgcert-pgdip.aspx","Health and Management MSc (PGCert PGDip)","0"},
			{"89","https://www.brighton.ac.uk/courses/study/health-and-social-care-education-pgcert.aspx","Health and Social Care Education PGCert","0"},
			{"90","https://www.brighton.ac.uk/courses/study/health-msc-pgcert-pgdip.aspx","Health MSc (PGCert PGDip)","0"},
			{"91","https://www.brighton.ac.uk/courses/study/health-promotion-and-education-ma-pgcert-pgdip.aspx","Health Promotion and Education MA (PGCert PGDip)","0"},
			{"92","https://www.brighton.ac.uk/courses/study/health-promotion-and-management-ma-pgcert-pgdip.aspx","Health Promotion and Management MA (PGCert PGDip)","0"},
			{"93","https://www.brighton.ac.uk/courses/study/health-promotion-ma-pgcert-pgdip.aspx","Health Promotion MA (PGCert PGDip)","0"},
			{"94","https://www.brighton.ac.uk/courses/study/healthcare-ethics-ma-pgcert-pgdip.aspx","Healthcare Ethics MA PGCert PGDip","0"},
			{"95","https://www.brighton.ac.uk/courses/study/highway-engineering-management-msc-pgdip-pgcert.aspx","Highway Engineering Management MSc","0"},
			{"96","https://www.brighton.ac.uk/courses/study/history-of-design-and-material-culture-ma.aspx","History of Design and Material Culture MA","0"},
			{"97","https://www.brighton.ac.uk/courses/study/human-resource-management-msc-pgcert-pgdip.aspx","Human Resource Management MSc (PGCert PGDip)","0"},
			{"98","https://www.brighton.ac.uk/courses/study/human-resource-management-pgdip.aspx","Human Resource Management PGDip","0"},
			{"99","https://www.brighton.ac.uk/courses/study/humanistic-psychotherapeutic-counselling-pgdip.aspx","Humanistic Psychotherapeutic Counselling PGDip","0"},
			{"100","https://www.brighton.ac.uk/courses/study/inclusive-arts-practice-ma-pgcert-pgdip.aspx","Inclusive Arts Practice MA (PGCert PGDip)","0"},
			{"101","https://www.brighton.ac.uk/courses/study/industrial-pharmaceutical-sciences-msc-pgcert-pgdip.aspx","Industrial Pharmaceutical Sciences MSc (PGCert PGDip)","0"},
			{"102","https://www.brighton.ac.uk/courses/study/industrial-pharmaceutical-studies-msc-pgcert-pgdip.aspx","Industrial Pharmaceutical Studies MSc (PGCert PGDip)","0"},
			{"103","https://www.brighton.ac.uk/courses/study/infection-sciences-msc-pgcert-pgdip.aspx","Infection Sciences MSc (PGCert PGDip)","0"},
			{"104","https://www.brighton.ac.uk/courses/study/information-security-msc.aspx","Information Security MSc (PGDip PGCert)","0"},
			{"105","https://www.brighton.ac.uk/courses/study/information-systems-msc-pgcert-pgdip.aspx","Information Systems MSc (PGCert PGDip)","0"},
			{"106","https://www.brighton.ac.uk/courses/study/interior-design-ma-pgcert-pgdip.aspx","Interior Design MA (PGCert PGDip)","0"},
			{"107","https://www.brighton.ac.uk/courses/study/international-event-management-msc-pgcert-pgdip.aspx","International Event Management MSc (PGCert PGDip)","0"},
			{"108","https://www.brighton.ac.uk/courses/study/international-health-promotion-ma-pgdip.aspx","International Health Promotion MA (PGDip)","0"},
			{"109","https://www.brighton.ac.uk/courses/study/international-hospitality-management-msc-pgcert-pgdip.aspx","International Hospitality Management MSc (PGCert PGDip)","0"},
			{"110","https://www.brighton.ac.uk/courses/study/international-management-mba-pgcert-pgdip.aspx","International Management MBA (PGCert PGDip)","0"},
			{"111","https://www.brighton.ac.uk/courses/study/international-management-msc-pgcert-pgdip.aspx","International Management MSc (PGCert PGDip)","0"},
			{"112","https://www.brighton.ac.uk/courses/study/international-retail-management-msc-pgcert-pgdip.aspx","International Retail Management MSc (PGCert PGDIP)","0"},
			{"113","https://www.brighton.ac.uk/courses/study/international-tourism-management-msc-pgcert-pgdip.aspx","International Tourism Management MSc (PGCert PGDip)","0"},
			{"114","https://www.brighton.ac.uk/courses/study/internet-and-distributed-systems-msc-pgcert-pgdip.aspx","Internet and Distributed Systems MSc (PGCert PGDip)","0"},
			{"115","https://www.brighton.ac.uk/courses/study/knowledge-and-innovation-management-mba-pgcert-pgdip.aspx","Knowledge and Innovation Management MBA (PGCert PGDip)","0"},
			{"116","https://www.brighton.ac.uk/courses/study/law-cpe-pgdip.aspx","Law CPE PGDip","0"},
			{"117","https://www.brighton.ac.uk/courses/study/leadership-and-commissioning-msc-pgcert-pgdip.aspx","Leadership and Commissioning MSc (PGCert PGDip)","0"},
			{"118","https://www.brighton.ac.uk/courses/study/leadership-mba-pgcert-pgdip.aspx","Leadership MBA (PGCert PGDip)","0"},
			{"119","https://www.brighton.ac.uk/courses/study/linguistics-ma-mres.aspx","Linguistics MA MRes","0"},
			{"120","https://www.brighton.ac.uk/courses/study/literature-ma-pgcert-pgdip.aspx","Literature MA (PGCert PGDip)","0"},
			{"121","https://www.brighton.ac.uk/courses/study/logistics-and-supply-chain-management-msc-pgcert-pgdip.aspx","Logistics and Supply Chain Management MSc (PGCert PGDip)","0"},
			{"122","https://www.brighton.ac.uk/courses/study/making-of-histories-pgcert.aspx","Making of Histories PGCert","0"},
			{"123","https://www.brighton.ac.uk/courses/study/making-of-histories-pgdip.aspx","Making of Histories PGDip","0"},
			{"124","https://www.brighton.ac.uk/courses/study/management-entrepreneurship-msc-pgcert-pgdip.aspx","Management (Entrepreneurship) MSc (PGCert PGDip)","0"},
			{"125","https://www.brighton.ac.uk/courses/study/management-human-resources-msc-pgcert-pgdip.aspx","Management (Human Resources) MSc (PGCert PGDip)","0"},
			{"126","https://www.brighton.ac.uk/courses/study/management-innovation-msc-pgcert-pgdip.aspx","Management (Innovation) MSc (PGCert PGDip)","0"},
			{"127","https://www.brighton.ac.uk/courses/study/management-and-leadership-cmi-extended-diploma.aspx","Management and Leadership CMI Extended Diploma","0"},
			{"128","https://www.brighton.ac.uk/courses/study/management-gradcert.aspx","Management GradCert","0"},
			{"129","https://www.brighton.ac.uk/courses/study/management-msc-pgcert-pgdip.aspx","Management MSc (PGCert PGDip)","0"},
			{"130","https://www.brighton.ac.uk/courses/study/management-practice-and-law-in-architecture-pgdip.aspx","Management, Practice and Law in Architecture PGDip","0"},
			{"131","https://www.brighton.ac.uk/courses/study/managing-change-and-innovation-msc-pgcert-pgdip.aspx","Managing Change and Innovation MSc (PGCert PGDip)","0"},
			{"132","https://www.brighton.ac.uk/courses/study/marketing-branding-and-communications-msc-pgcert-pgdip.aspx","Marketing (Branding and Communications) MSc (PGCert PGDip)","0"},
			{"133","https://www.brighton.ac.uk/courses/study/marketing-digital-marketing-msc-pgcert-pgdip.aspx","Marketing (Digital Marketing) MSc (PGCert PGDip)","0"},
			{"134","https://www.brighton.ac.uk/courses/study/marketing-international-marketing-msc-pgcert-pgdip.aspx","Marketing (International Marketing) MSc (PGCert PGDip)","0"},
			{"135","https://www.brighton.ac.uk/courses/study/marketing-social-marketing-msc-pgcert-pgdip.aspx","Marketing (Social Marketing) MSc (PGCert PGDip)","0"},
			{"136","https://www.brighton.ac.uk/courses/study/marketing-msc-pgcert-pgdip.aspx","Marketing MSc (PGCert PGDip)","0"},
			{"137","https://www.brighton.ac.uk/courses/study/mathematics-secondary-pgce-profgce.aspx","Mathematics (Secondary) PGCE (PROFGCE)","0"},
			{"138","https://www.brighton.ac.uk/courses/study/media-ethics-ma-pgcert-pgdip.aspx","Media Ethics MA PGCert PGDip","0"},
			{"139","https://www.brighton.ac.uk/courses/study/medical-education-pgcert.aspx","Medical Education PGCert","0"},
			{"140","https://www.brighton.ac.uk/courses/study/medical-ethics-ma-pgcert-pgdip.aspx","Medical Ethics MA PGCert PGDip","0"},
			{"141","https://www.brighton.ac.uk/courses/study/medical-research-mres-pgcert.aspx","Medical Research MRes (PGCert)","0"},
			{"142","https://www.brighton.ac.uk/courses/study/modern-foreign-languages-secondary-pgce-profgce.aspx","Modern Foreign Languages (Secondary)  PGCE (PROFGCE)","0"},
			{"143","https://www.brighton.ac.uk/courses/study/neuromusculoskeletal-physiotherapy-msc-pgcert-pgdip.aspx","Neuromusculoskeletal Physiotherapy MSc (PGCert PGDip)","0"},
			{"144","https://www.brighton.ac.uk/courses/study/non-medical-prescribing-for-pharmacists.aspx","Non-Medical Prescribing for Pharmacists","0"},
			{"145","https://www.brighton.ac.uk/courses/study/occupational-therapy-post-reg-msc-pgcert-pgdip.aspx","Occupational Therapy (Post-registration) MSc (PGCert PGDip)","0"},
			{"146","https://www.brighton.ac.uk/courses/study/occupational-therapy-pre-reg-msc-pgcert-pgdip.aspx","Occupational Therapy (Pre-Registration) MSc (PGCert PGDip)","0"},
			{"147","https://www.brighton.ac.uk/courses/study/occupational-therapy-and-education-post-reg-msc-pgcert-pgdip.aspx","Occupational Therapy and Education (Post-registration) MSc (PGCert PGDip)","0"},
			{"148","https://www.brighton.ac.uk/courses/study/occupational-therapy-and-management-post-reg-msc-pgcert-pgdip.aspx","Occupational Therapy and Management (Post-registration) MSc (PGCert PGDip)","0"},
			{"149","https://www.brighton.ac.uk/courses/study/paediatrics-and-child-health-msc-pgcert-pgdip.aspx","Paediatrics and Child Health MSc (PGCert, PGDip)","0"},
			{"150","https://www.brighton.ac.uk/courses/study/performance-and-visual-practices-ma-pgcert-pgdip.aspx","Performance and Visual Practices MA (PGCert PGDip)","0"},
			{"151","https://www.brighton.ac.uk/courses/study/pharmaceutical-and-biomedical-sciences-mres-pgcert-pgdip.aspx","Pharmaceutical and Biomedical Sciences MRes (PGCert PGDip)","0"},
			{"152","https://www.brighton.ac.uk/courses/study/pharmacology-msc-pgcert-pgdip.aspx","Pharmacology MSc (PGCert PGDip)","0"},
			{"153","https://www.brighton.ac.uk/courses/study/pharmacy-ospap-msc-pgdip.aspx","Pharmacy (OSPAP) MSc (PGDip)","0"},
			{"154","https://www.brighton.ac.uk/courses/study/pharmacy-ospap-pgdip.aspx","Pharmacy (OSPAP) PGDip","0"},
			{"155","https://www.brighton.ac.uk/courses/study/philosophy-of-language-ma-pgcert-pgdip.aspx","Philosophy of Language MA (PGCert PGDip)","0"},
			{"156","https://www.brighton.ac.uk/courses/study/photography-ma.aspx","Photography MA","0"},
			{"157","https://www.brighton.ac.uk/courses/study/physical-education-secondary-pgce-profgce.aspx","Physical Education (Secondary) PGCE (PROFGCE)","0"},
			{"158","https://www.brighton.ac.uk/courses/study/physician-associate-studies-pgdip.aspx","Physician Associate Studies PGDip","0"},
			{"159","https://www.brighton.ac.uk/courses/study/physiotherapy-and-education-msc-pgcert-pgdip.aspx","Physiotherapy and Education MSc (PGCert PGDip)","0"},
			{"160","https://www.brighton.ac.uk/courses/study/physiotherapy-and-management-msc-pgcert-pgdip.aspx","Physiotherapy and Management MSc (PGCert PGDip)","0"},
			{"161","https://www.brighton.ac.uk/courses/study/physiotherapy-msc-pgcert-pgdip.aspx","Physiotherapy MSc (PGCert PGDip)","0"},
			{"162","https://www.brighton.ac.uk/courses/study/physiotherapy-with-independent-prescribing-msc-pgcert-pgdip.aspx","Physiotherapy with Independent Prescribing MSc (PGCert PGDip)","0"},
			{"163","https://www.brighton.ac.uk/courses/study/podiatry-and-education-msc-pgcert-pgdip.aspx","Podiatry and Education MSc (PGCert PGDip)","0"},
			{"164","https://www.brighton.ac.uk/courses/study/podiatry-and-management-msc-pgcert-pgdip.aspx","Podiatry and Management MSc (PGCert PGDip)","0"},
			{"165","https://www.brighton.ac.uk/courses/study/podiatry-msc-pgcert-pgdip.aspx","Podiatry MSc (PGCert PGDip)","0"},
			{"166","https://www.brighton.ac.uk/courses/study/podiatry-with-clinical-biomechanics-msc-pgcert-pgdip.aspx","Podiatry with Clinical Biomechanics MSc (PGCert PGDip)","0"},
			{"167","https://www.brighton.ac.uk/courses/study/podiatry-with-diabetes-msc-pgcert-pgdip.aspx","Podiatry with Diabetes MSc (PGCert PGDip)","0"},
			{"168","https://www.brighton.ac.uk/courses/study/podiatry-with-independent-prescribing-msc-pgcert-pgdip.aspx","Podiatry with Independent Prescribing MSc (PGCert PGDip)","0"},
			{"169","https://www.brighton.ac.uk/courses/study/podiatry-with-rheumatology-msc-pgcert-pgdip.aspx","Podiatry with Rheumatology MSc (PGCert PGDip)","0"},
			{"170","https://www.brighton.ac.uk/courses/study/politics-and-ethics-ma-pgcert-pgdip.aspx","Politics and Ethics MA PGCert PGDip","0"},
			{"171","https://www.brighton.ac.uk/courses/study/prescribing-gradcert-pgcert.aspx","Prescribing (GradCert PGCert)","0"},
			{"172","https://www.brighton.ac.uk/courses/study/primary-education-3-7-years-pgce-profgce.aspx","Primary Education (3-7 years) PGCE (PROFGCE)","0"},
			{"173","https://www.brighton.ac.uk/courses/study/primary-education-pgce-profgce.aspx","Primary Education PGCE (PROFGCE)","0"},
			{"174","https://www.brighton.ac.uk/courses/study/principles-of-podiatric-surgery-msc-pgcert-pgdip.aspx","Principles of Podiatric Surgery MSc (PGCert PGDip)","0"},
			{"175","https://www.brighton.ac.uk/courses/study/professional-education-studies-pgcert.aspx","Professional Education Studies PGCert","0"},
			{"176","https://www.brighton.ac.uk/courses/study/professional-health-and-social-care-practice-msc-pgcert-pgdip.aspx","Professional Health and Social Care Practice MSc (PGCert PGDip)","0"},
			{"177","https://www.brighton.ac.uk/courses/study/professional-social-work-practice-pgcert.aspx","Professional Social Work Practice PGCert","0"},
			{"178","https://www.brighton.ac.uk/courses/study/professional-social-work-practice-pgdip.aspx","Professional Social Work Practice PGDip","0"},
			{"179","https://www.brighton.ac.uk/courses/study/project-management-for-construction-msc-pgcert-pgdip.aspx","Project Management for Construction MSc (PGCert PGDip)","0"},
			{"180","https://www.brighton.ac.uk/courses/study/psychiatry-msc-pgcert-pgdip.aspx","Psychiatry MSc (PGCert PGDip)","0"},
			{"181","https://www.brighton.ac.uk/courses/study/psychodynamic-psychotherapeutic-counselling-pgdip.aspx","Psychodynamic Psychotherapeutic Counselling PGDip","0"},
			{"182","https://www.brighton.ac.uk/courses/study/psychotherapy-msc.aspx","Psychotherapy MSc","0"},
			{"183","https://www.brighton.ac.uk/courses/study/public-health-msc-pgcert-pgdip.aspx","Public Health MSc (PGCert PGDip)","0"},
			{"184","https://www.brighton.ac.uk/courses/study/public-service-management-mba-pgcert-pgdip.aspx","Public Service Management MBA (PGCert PGDip)","0"},
			{"185","https://www.brighton.ac.uk/courses/study/rehabilitation-science-physiotherapy-msc-pgcert-pgdip.aspx","Rehabilitation Science (Physiotherapy) MSc (PGCert PGDip)","0"},
			{"186","https://www.brighton.ac.uk/courses/study/religious-studies-secondary-pgce-profgce.aspx","Religious Studies (Secondary) PGCE (PROFGCE)","0"},
			{"187","https://www.brighton.ac.uk/courses/study/retail-management-msc-pgcert-pgdip.aspx","Retail Management MSc (PGCert PGDip)","0"},
			{"188","https://www.brighton.ac.uk/courses/study/school-direct-tuition-and-school-direct-salaried.aspx","School Direct Tuition and School Direct Salaried","0"},
			{"189","https://www.brighton.ac.uk/courses/study/sequential-design-illustration-ma.aspx","Sequential Design/Illustration MA","0"},
			{"190","https://www.brighton.ac.uk/courses/study/simulation-in-clinical-practice-pgcert.aspx","Simulation in Clinical Practice PGCert","0"},
			{"191","https://www.brighton.ac.uk/courses/study/social-marketing-pgcert.aspx","Social Marketing PGCert","0"},
			{"192","https://www.brighton.ac.uk/courses/study/social-science-mres-pgcert.aspx","Social Science MRes (PGCert)","0"},
			{"193","https://www.brighton.ac.uk/courses/study/social-work-msc.aspx","Social Work MSc","0"},
			{"194","https://www.brighton.ac.uk/courses/study/specialist-community-public-health-nursing-msc-pgcert-pgdip.aspx","Specialist Community Public Health Nursing MSc (PGCert PGDip)","0"},
			{"195","https://www.brighton.ac.uk/courses/study/specific-learning-difficulties-dyslexia-pgcert.aspx","Specific Learning Difficulties (Dyslexia) PGCert","0"},
			{"196","https://www.brighton.ac.uk/courses/study/sport-and-international-development-ma.aspx","Sport and International Development MA","0"},
			{"197","https://www.brighton.ac.uk/courses/study/sport-business-management-msc.aspx","Sport Business Management MSc","0"},
			{"198","https://www.brighton.ac.uk/courses/study/sports-injury-management-msc-pgcert-pgdip.aspx","Sports Injury Management MSc (PGCert PGDip)","0"},
			{"199","https://www.brighton.ac.uk/courses/study/subject-knowledge-enhancement-for-teacher-training.aspx","Subject Knowledge Enhancement for teacher training","0"},
			{"200","https://www.brighton.ac.uk/courses/study/summer-pre-sessional-pg.aspx","Summer Pre-sessional","0"},
			{"201","https://www.brighton.ac.uk/courses/study/sustainable-design-ma.aspx","Sustainable Design MA","0"},
			{"202","https://www.brighton.ac.uk/courses/study/tesol-diploma.aspx","TESOL Diploma","0"},
			{"203","https://www.brighton.ac.uk/courses/study/tesol-ma.aspx","TESOL MA","0"},
			{"204","https://www.brighton.ac.uk/courses/study/tesol-with-ict-ma.aspx","TESOL with ICT MA","0"},
			{"205","https://www.brighton.ac.uk/courses/study/textiles-ma.aspx","Textiles MA","0"},
			{"206","https://www.brighton.ac.uk/courses/study/tourism-and-international-development-msc-pgcert-pgdip.aspx","Tourism and International Development MSc (PGCert PGDip)","0"},
			{"207","https://www.brighton.ac.uk/courses/study/town-planning-msc-pgcert-pgdip.aspx","Town Planning MSc (PGCert PGDip)","0"},
			{"208","https://www.brighton.ac.uk/courses/study/user-experience-design-msc-pgcert-pgdip.aspx","User Experience Design MSc (PGCert PGDip)","0"},
			{"209","https://www.brighton.ac.uk/courses/study/war-history-and-politics-ma-pgcert-pgdip.aspx","War: History and Politics MA (PGCert PGDip)","0"},
			{"210","https://www.brighton.ac.uk/courses/study/water-and-environmental-management-msc-pgdip.aspx","Water and Environmental Management MSc (PGDip)","0"},
			{"211","https://www.brighton.ac.uk/courses/study/agriculture-foundation-degree-partner-college.aspx","Agriculture foundation degree (partner college)","0"},
			{"212","https://www.brighton.ac.uk/courses/study/animal-behaviour-and-welfare-bsc-hons-top-up-degree-partner-college.aspx","Animal Behaviour and Welfare BSc(Hons) top-up degree (partner college)","0"},
			{"213","https://www.brighton.ac.uk/courses/study/animal-science-foundation-degree-partner-college.aspx","Animal Science foundation degree (partner college)","0"},
			{"214","https://www.brighton.ac.uk/courses/study/arboriculture-foundation-degree-partner-college.aspx","Arboriculture foundation degree (partner college)","0"},
			{"215","https://www.brighton.ac.uk/courses/study/art-and-design-top-up-ba-hons.aspx","Art and Design (top-up) BA(Hons) (partner college)","0"},
			{"216","https://www.brighton.ac.uk/courses/study/art-and-design-ba-hons-top-up-degree-partner-college.aspx","Art and Design BA(Hons) top-up degree (partner college)","0"},
			{"217","https://www.brighton.ac.uk/courses/study/aviation-operations-management-bsc-hons-top-up-degree-partner-college.aspx","Aviation Operations Management BSc(Hons) top-up (partner college)","0"},
			{"218","https://www.brighton.ac.uk/courses/study/aviation-operations-management-foundation-degree-partner-college.aspx","Aviation Operations Management foundation degree (partner college)","0"},
			{"219","https://www.brighton.ac.uk/courses/study/biological-sciences-foundation-degree-partner-college.aspx","Biological Sciences foundation degree (partner college)","0"},
			{"220","https://www.brighton.ac.uk/courses/study/business-foundation-degree-partner-college.aspx","Business foundation degree (partner college)","0"},
			{"221","https://www.brighton.ac.uk/courses/study/complementary-healthcare-foundation-degree-partner-college.aspx","Complementary Healthcare foundation degree (partner college)","0"},
			{"222","https://www.brighton.ac.uk/courses/study/computing-computer-games-development-foundation-degree-partner-college.aspx","Computing (Computer Games Development) foundation degree (partner college)","0"},
			{"223","https://www.brighton.ac.uk/courses/study/countryside-management-foundation-degree-partner-college.aspx","Countryside Management foundation degree (partner college)","0"},
			{"224","https://www.brighton.ac.uk/courses/study/creative-metalworking-foundation-degree-partner-college.aspx","Creative Metalworking foundation degree (partner college)","0"},
			{"225","https://www.brighton.ac.uk/courses/study/creative-music-production-ba-hons-top-up-degree-partner-college.aspx","Creative Music Production BA(Hons) top-up degree (partner college)","0"},
			{"226","https://www.brighton.ac.uk/courses/study/creative-music-production-foundation-degree-partner-college.aspx","Creative Music Production foundation degree (partner college)","0"},
			{"227","https://www.brighton.ac.uk/courses/study/digital-media-design-ba-hons-top-up-degree-partner-college.aspx","Digital Media Design BA(Hons) top-up degree (partner college)","0"},
			{"228","https://www.brighton.ac.uk/courses/study/digital-media-design-foundation-degree-partner-college.aspx","Digital Media Design foundation degree (partner college)","0"},
			{"229","https://www.brighton.ac.uk/courses/study/early-years-care-and-education-foundation-degree-partner-college.aspx","Early Years Care and Education foundation degree (partner college)","0"},
			{"230","https://www.brighton.ac.uk/courses/study/equine-dentistry-foundation-degree-partner-college.aspx","Equine Dentistry foundation degree (partner college)","0"},
			{"231","https://www.brighton.ac.uk/courses/study/equine-sports-coaching-foundation-diploma-partner-college.aspx","Equine Sports Coaching foundation diploma (partner college)","0"},
			{"232","https://www.brighton.ac.uk/courses/study/equine-sports-performance-bsc-hons-partner-college.aspx","Equine Sports Performance BSc(Hons) (partner college)","0"},
			{"233","https://www.brighton.ac.uk/courses/study/equine-studies-foundation-degree-partner-college.aspx","Equine Studies foundation degree (partner college)","0"},
			{"234","https://www.brighton.ac.uk/courses/study/event-and-tourism-management-foundation-degree-partner-college.aspx","Event and Tourism Management foundation degree (partner college)","0"},
			{"235","https://www.brighton.ac.uk/courses/study/film-production-ba-hons-top-up-degree-partner-college.aspx","Film Production BA(Hons) top-up degree (partner college)","0"},
			{"236","https://www.brighton.ac.uk/courses/study/fine-art-contemporary-practice-foundation-degree-partner-college.aspx","Fine Art Contemporary Practice foundation degree (partner college)","0"},
			{"237","https://www.brighton.ac.uk/courses/study/fine-art-foundation-degree-partner-college.aspx","Fine Art foundation degree (partner college)","0"},
			{"238","https://www.brighton.ac.uk/courses/study/forestry-and-woodland-management-foundation-degree-partner-college.aspx","Forestry and Woodland Management foundation degree (partner college)","0"},
			{"239","https://www.brighton.ac.uk/courses/study/further-education-and-training-pgcecert-ed-partner-college.aspx","Further Education and Training PGCE/Cert-Ed (partner college)","0"},
			{"240","https://www.brighton.ac.uk/courses/study/graphic-communication-foundation-degree-partner-college.aspx","Graphic Communication foundation degree (partner college)","0"},
			{"241","https://www.brighton.ac.uk/courses/study/hospitality-and-event-management-foundation-degree-partner-college.aspx","Hospitality and Event Management foundation degree (partner college)","0"},
			{"242","https://www.brighton.ac.uk/courses/study/hospitality-and-tourism-management-foundation-degree-partner-college.aspx","Hospitality and Tourism Management foundation degree (partner college)","0"},
			{"243","https://www.brighton.ac.uk/courses/study/human-resource-management-pgdip-partner-college.aspx","Human Resource Management PGDip (Partner College)","0"},
			{"244","https://www.brighton.ac.uk/courses/study/illustration-foundation-degree-partner-college.aspx","Illustration foundation degree (partner college)","0"},
			{"245","https://www.brighton.ac.uk/courses/study/internet-software-development-fdsc-partner-college.aspx","Internet Software Development FdSc (partner college)","0"},
			{"246","https://www.brighton.ac.uk/courses/study/music-and-sound-production-fda-partner-college.aspx","Music and Sound Production FdA (partner college)","0"},
			{"247","https://www.brighton.ac.uk/courses/study/music-production-and-creative-recording-ba-hons-top-up-partner-college.aspx","Music Production and Creative Recording BA(Hons) top-up (partner college)","0"},
			{"248","https://www.brighton.ac.uk/courses/study/music-production-and-creative-recording-foundation-degree-partner-college.aspx","Music Production and Creative Recording foundation degree (partner college)","0"},
			{"249","https://www.brighton.ac.uk/courses/study/outdoor-adventurous-activities-foundation-degree-partner-college.aspx","Outdoor Adventurous Activities foundation degree (partner college)","0"},
			{"250","https://www.brighton.ac.uk/courses/study/outdoor-adventurous-facilitation-bahons-top-up-degree-partner-college.aspx","Outdoor Adventurous Facilitation BA(Hons) top-up degree (partner college)","0"},
			{"251","https://www.brighton.ac.uk/courses/study/person-centred-counselling-bsc-hons-top-up-degree-partner-college.aspx","Person-centred Counselling BSc(Hons) top-up degree (partner college)","0"},
			{"252","https://www.brighton.ac.uk/courses/study/person-centred-counselling-foundation-degree-partner-college.aspx","Person-centred Counselling foundation degree (partner college)","0"},
			{"253","https://www.brighton.ac.uk/courses/study/photography-foundation-degree-partner-college.aspx","Photography foundation degree (partner college)","0"},
			{"254","https://www.brighton.ac.uk/courses/study/public-and-emergency-services-management-foundation-degree-partner-college.aspx","Public and Emergency Services Management foundation degree (partner college)","0"},
			{"255","https://www.brighton.ac.uk/courses/study/sport-coaching-and-development-foundation-degree-partner-college.aspx","Sport Coaching and Development foundation degree (partner college)","0"},
			{"256","https://www.brighton.ac.uk/courses/study/travel-and-tourism-management-foundation-degree-partner-college.aspx","Travel and Tourism Management foundation degree (partner college)","0"},
			{"257","https://www.brighton.ac.uk/courses/study/veterinary-nursing-foundation-degree-partner-college.aspx","Veterinary Nursing foundation degree (partner college)","0"},
			{"258","https://www.brighton.ac.uk/courses/study/visual-arts-practice-ba-hons-top-up-degree-partner-college.aspx","Visual Arts Practice BA(Hons) top-up degree (partner college)","0"},
			{"259","https://www.brighton.ac.uk/courses/study/viticulture-and-oenology-bsc-hons-partner-college.aspx","Viticulture and Oenology BSc(Hons) (partner college)","0"},
			{"260","https://www.brighton.ac.uk/courses/study/viticulture-and-oenology-msc-partner-college.aspx","Viticulture and Oenology MSc (partner college)","0"},
			{"261","https://www.brighton.ac.uk/courses/study/wine-business-ba-hons-partner-college.aspx","Wine Business BA(Hons) (partner college)","0"},
			{"262","https://www.brighton.ac.uk/courses/study/wine-business-ba-hons-top-up-degree-partner-college.aspx","Wine Business BA(Hons) top-up degree (partner college)","0"},
			{"263","https://www.brighton.ac.uk/courses/study/wine-business-foundation-degree-and-diploma-partner-college.aspx","Wine Business foundation degree and diploma (partner college)","0"},
			{"264","https://www.brighton.ac.uk/courses/study/wine-production-foundation-degree-and-diploma-partner-college.aspx","Wine Production foundation degree and diploma (partner college)","0"}
		};
	

}
