package no5.melbourne;

import java.io.File;
import java.io.FileInputStream;

import org.htmlparser.NodeFilter;
import org.htmlparser.Parser;
import org.htmlparser.filters.AndFilter;
import org.htmlparser.filters.HasAttributeFilter;
import org.htmlparser.filters.TagNameFilter;
import org.htmlparser.tags.LinkTag;
import org.htmlparser.util.NodeList;
import org.htmlparser.visitors.HtmlPage;

public class getURL {

	/**
	 * @param args
	 */
	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub

		for(int i=0;i<UnData.length;i++){
			System.out.println(UnData[i][1].split("/")[UnData[i][1].split("/").length-1]);
		}
		FileInputStream fis=new FileInputStream(new File("./melbourneUn.html"));
        byte[] b=new byte[fis.available()];
        fis.read(b);
       fis.close();
        String htmls=new String(b);
       int count=1;
	    Parser	parser=Parser.createParser(htmls, "utf-8");
   	    AndFilter ProfessionNameFilter=new AndFilter(new TagNameFilter("a"),
                   new HasAttributeFilter("href"));
   	    NodeList nodes4=parser.extractAllNodesThatMatch(ProfessionNameFilter);
   	    for(int i=0;i<nodes4.size();i++)
   	    {
   	    	LinkTag link=(LinkTag)nodes4.elementAt(i);
   	    	if(!link.getAttribute("href").equals("#"))
   	    	{
   	    		System.out.println("{\""+count+"\",\"https://handbook.unimelb.edu.au"+link.getAttribute("href")+"\",\""+html2Str(link.toHtml().replaceAll("<span[\\s\\S]*/span>",""))+"\",\"0\"},");
                count++;
   	    	}
   	    	
   	    }

	}
	public static String html2Str(String html) { 
		return html.replaceAll("<[^>]+>", "");
	}

	public static String[][] UnData={
		{"1","https://handbook.unimelb.edu.au/view/2016/A-URBHORT","Associate Degree in Urban Horticulture","0"},
		{"2","https://handbook.unimelb.edu.au/view/2016/B-AGR","Bachelor of Agriculture","0"},
		{"3","https://handbook.unimelb.edu.au/view/2016/BH-AGR","Bachelor of Agriculture (Degree with Honours)","0"},
		{"4","https://handbook.unimelb.edu.au/view/2016/B-ARTS","Bachelor of Arts","0"},
		{"5","https://handbook.unimelb.edu.au/view/2016/104AA","Bachelor of Arts (Degree with Honours)","0"},
		{"6","https://handbook.unimelb.edu.au/view/2016/BH-ARTS","Bachelor of Arts (Degree with Honours)","0"},
		{"7","https://handbook.unimelb.edu.au/view/2016/B-ARTSEXT","Bachelor of Arts (Extended)","0"},
		{"8","https://handbook.unimelb.edu.au/view/2016/B-BMED","Bachelor of Biomedicine","0"},
		{"9","https://handbook.unimelb.edu.au/view/2016/BH-BMED","Bachelor of Biomedicine (Degree with Honours)","0"},
		{"10","https://handbook.unimelb.edu.au/view/2016/B-COM","Bachelor of Commerce","0"},
		{"11","https://handbook.unimelb.edu.au/view/2016/BH-COM","Bachelor of Commerce (Degree with Honours)","0"},
		{"12","https://handbook.unimelb.edu.au/view/2016/084AA","Bachelor of Dance (Degree with Honours)","0"},
		{"13","https://handbook.unimelb.edu.au/view/2016/B-ENG","Bachelor of Engineering","0"},
		{"14","https://handbook.unimelb.edu.au/view/2016/B-ENVS","Bachelor of Environments","0"},
		{"15","https://handbook.unimelb.edu.au/view/2016/BH-ENVS","Bachelor of Environments (Degree with Honours)","0"},
		{"16","https://handbook.unimelb.edu.au/view/2016/919AA","Bachelor of Film and Television (Degree with Honours)","0"},
		{"17","https://handbook.unimelb.edu.au/view/2016/B-FAANIM","Bachelor of Fine Arts (Animation)","0"},
		{"18","https://handbook.unimelb.edu.au/view/2016/B-FADANCE","Bachelor of Fine Arts (Dance)","0"},
		{"19","https://handbook.unimelb.edu.au/view/2016/BH-FA","Bachelor of Fine Arts (Degree with Honours)","0"},
		{"20","https://handbook.unimelb.edu.au/view/2016/B-FAFILMTV","Bachelor of Fine Arts (Film and Television)","0"},
		{"21","https://handbook.unimelb.edu.au/view/2016/B-FAMUSTH","Bachelor of Fine Arts (Music Theatre)","0"},
		{"22","https://handbook.unimelb.edu.au/view/2016/B-FAPROD","Bachelor of Fine Arts (Production)","0"},
		{"23","https://handbook.unimelb.edu.au/view/2016/B-FASCWRI","Bachelor of Fine Arts (Screenwriting)","0"},
		{"24","https://handbook.unimelb.edu.au/view/2016/B-FATHPRAC","Bachelor of Fine Arts (Theatre Practice)","0"},
		{"25","https://handbook.unimelb.edu.au/view/2016/B-FAVISART","Bachelor of Fine Arts (Visual Art)","0"},
		{"26","https://handbook.unimelb.edu.au/view/2016/565IN","Bachelor of Medical Science","0"},
		{"27","https://handbook.unimelb.edu.au/view/2016/B-MUS","Bachelor of Music","0"},
		{"28","https://handbook.unimelb.edu.au/view/2016/BH-MUS","Bachelor of Music (Degree with Honours)","0"},
		{"29","https://handbook.unimelb.edu.au/view/2016/734AA","Bachelor of Music Performance (Degree with Honours)","0"},
		{"30","https://handbook.unimelb.edu.au/view/2016/841AC","Bachelor of Oral Health","0"},
		{"31","https://handbook.unimelb.edu.au/view/2016/BH-ORHLTH","Bachelor of Oral Health (Degree with Honours)","0"},
		{"32","https://handbook.unimelb.edu.au/view/2016/065PC","Bachelor of Property and Construction","0"},
		{"33","https://handbook.unimelb.edu.au/view/2016/B-SCI","Bachelor of Science","0"},
		{"34","https://handbook.unimelb.edu.au/view/2016/BH-SCI","Bachelor of Science (Degree with Honours)","0"},
		{"35","https://handbook.unimelb.edu.au/view/2016/B-SCIEXT","Bachelor of Science (Extended)","0"},
		{"36","https://handbook.unimelb.edu.au/view/2016/D-GENST","Diploma in General Studies","0"},
		{"37","https://handbook.unimelb.edu.au/view/2016/D-INFO","Diploma in Informatics","0"},
		{"38","https://handbook.unimelb.edu.au/view/2016/D-LANG","Diploma in Languages","0"},
		{"39","https://handbook.unimelb.edu.au/view/2016/D-MATHSC","Diploma in Mathematical Sciences","0"},
		{"40","https://handbook.unimelb.edu.au/view/2016/888CH","Diploma in Modern Languages (Chinese)","0"},
		{"41","https://handbook.unimelb.edu.au/view/2016/D-MUS","Diploma in Music (Practical)","0"},
		{"42","https://handbook.unimelb.edu.au/view/2016/777CC","U21 Certificate in Global Issues","0"},
		{"43","https://handbook.unimelb.edu.au/view/2016/D-GLOBISS","U21 Diploma in Global Issues","0"}
	};
	public static String[][] PostData={
		{"1","https://handbook.unimelb.edu.au/view/2016/DH-AGRSC","Doctor of Agricultural Science","0"},
		{"2","https://handbook.unimelb.edu.au/view/2016/661AA","Doctor of Clinical Dentistry","0"},
		{"3","https://handbook.unimelb.edu.au/view/2016/J02AA","Doctor of Clinical Physiotherapy","0"},
		{"4","https://handbook.unimelb.edu.au/view/2016/DH-DSC","Doctor of Dental Science","0"},
		{"5","https://handbook.unimelb.edu.au/view/2016/MC-DDENSUR","Doctor of Dental Surgery","0"},
		{"6","https://handbook.unimelb.edu.au/view/2016/300BB","Doctor of Education","0"},
		{"7","https://handbook.unimelb.edu.au/view/2016/DH-FORSC","Doctor of Forest Science","0"},
		{"8","https://handbook.unimelb.edu.au/view/2016/DH-LLD","Doctor of Laws","0"},
		{"9","https://handbook.unimelb.edu.au/view/2016/J15AA","Doctor of Medical Science","0"},
		{"10","https://handbook.unimelb.edu.au/view/2016/J15TC","Doctor of Medical Science","0"},
		{"11","https://handbook.unimelb.edu.au/view/2016/MC-DMED","Doctor of Medicine","0"},
		{"12","https://handbook.unimelb.edu.au/view/2016/DH-MUS","Doctor of Music","0"},
		{"13","https://handbook.unimelb.edu.au/view/2016/MC-DOPTOM","Doctor of Optometry","0"},
		{"14","https://handbook.unimelb.edu.au/view/2016/DR-PHILAGR","Doctor of Philosophy - Agricultural Sciences","0"},
		{"15","https://handbook.unimelb.edu.au/view/2016/DR-PHILABP","Doctor of Philosophy - Architecture, Building and Planning","0"},
		{"16","https://handbook.unimelb.edu.au/view/2016/DR-PHILART","Doctor of Philosophy - Arts","0"},
		{"17","https://handbook.unimelb.edu.au/view/2016/DR-PHILBE","Doctor of Philosophy - Business and Economics","0"},
		{"18","https://handbook.unimelb.edu.au/view/2016/DR-PHILEDU","Doctor of Philosophy - Education","0"},
		{"19","https://handbook.unimelb.edu.au/view/2016/DR-PHILENG","Doctor of Philosophy - Engineering","0"},
		{"20","https://handbook.unimelb.edu.au/view/2016/DR-PHILLAW","Doctor of Philosophy - Law","0"},
		{"21","https://handbook.unimelb.edu.au/view/2016/DR-PHILMDH","Doctor of Philosophy - Medicine, Dentistry and Health Sciences","0"},
		{"22","https://handbook.unimelb.edu.au/view/2016/DR-PHILMUS","Doctor of Philosophy - Music","0"},
		{"23","https://handbook.unimelb.edu.au/view/2016/DR-PHILSCI","Doctor of Philosophy - Science","0"},
		{"24","https://handbook.unimelb.edu.au/view/2016/DR-PHILVET","Doctor of Philosophy - Veterinary Science","0"},
		{"25","https://handbook.unimelb.edu.au/view/2016/DR-PHILVCA","Doctor of Philosophy - Victorian College of the Arts","0"},
		{"26","https://handbook.unimelb.edu.au/view/2016/MC-DPHYSIO","Doctor of Physiotherapy","0"},
		{"27","https://handbook.unimelb.edu.au/view/2016/330CN","Doctor of Psychology (Clinical Neuropsychology)","0"},
		{"28","https://handbook.unimelb.edu.au/view/2016/DH-SC","Doctor of Science","0"},
		{"29","https://handbook.unimelb.edu.au/view/2016/MC-DVETMED","Doctor of Veterinary Medicine","0"},
		{"30","https://handbook.unimelb.edu.au/view/2016/DH-VSC","Doctor of Veterinary Science","0"},
		{"31","https://handbook.unimelb.edu.au/view/2016/DH-VPA","Doctor of Visual and Performing Arts","0"},
		{"32","https://handbook.unimelb.edu.au/view/2016/MC-EMA","Executive Master of Arts","0"},
		{"33","https://handbook.unimelb.edu.au/view/2016/GC-ADOLHW","Graduate Certificate in Adolescent Health and Wellbeing","0"},
		{"34","https://handbook.unimelb.edu.au/view/2016/GC-ALL","Graduate Certificate in Advanced Learning and Leadership","0"},
		{"35","https://handbook.unimelb.edu.au/view/2016/GC-AGEING","Graduate Certificate in Ageing","0"},
		{"36","https://handbook.unimelb.edu.au/view/2016/GC-AGSC","Graduate Certificate in Agricultural Sciences","0"},
		{"37","https://handbook.unimelb.edu.au/view/2016/GC-ARBCULT","Graduate Certificate in Arboriculture","0"},
		{"38","https://handbook.unimelb.edu.au/view/2016/GC-ARTS","Graduate Certificate in Arts","0"},
		{"39","https://handbook.unimelb.edu.au/view/2016/GCA-ARTS","Graduate Certificate in Arts (Advanced)","0"},
		{"40","https://handbook.unimelb.edu.au/view/2016/GC-ARTSCE","Graduate Certificate in Arts and Community Engagement","0"},
		{"41","https://handbook.unimelb.edu.au/view/2016/GC-AVHLTH","Graduate Certificate in Avian Health","0"},
		{"42","https://handbook.unimelb.edu.au/view/2016/GC-AVHLTHG","Graduate Certificate in Avian Health - Uni Georgia","0"},
		{"43","https://handbook.unimelb.edu.au/view/2016/GC-BFIREPM","Graduate Certificate in Bushfire Planning and Management","0"},
		{"44","https://handbook.unimelb.edu.au/view/2016/F02AA","Graduate Certificate in Business Forensics","0"},
		{"45","https://handbook.unimelb.edu.au/view/2016/GC-CANCRSC","Graduate Certificate in Cancer Sciences","0"},
		{"46","https://handbook.unimelb.edu.au/view/2016/GC-CWMGT","Graduate Certificate in Catchment and Waterway Management","0"},
		{"47","https://handbook.unimelb.edu.au/view/2016/GC-CCFPI","Graduate Certificate in Climate Change for Primary Industries","0"},
		{"48","https://handbook.unimelb.edu.au/view/2016/N12AA","Graduate Certificate in Clinical Research","0"},
		{"49","https://handbook.unimelb.edu.au/view/2016/GC-CLINTCH","Graduate Certificate in Clinical Teaching","0"},
		{"50","https://handbook.unimelb.edu.au/view/2016/GC-CLINUS","Graduate Certificate in Clinical Ultrasound","0"},
		{"51","https://handbook.unimelb.edu.au/view/2016/GC-COMCUST","Graduate Certificate in Communication and Customer Strategy","0"},
		{"52","https://handbook.unimelb.edu.au/view/2016/GC-DTACP","Graduate Certificate in Dental Therapy (Advanced Clinical Practice)","0"},
		{"53","https://handbook.unimelb.edu.au/view/2016/GC-ELI","Graduate Certificate in Early Literacy Intervention","0"},
		{"54","https://handbook.unimelb.edu.au/view/2016/GC-EDGEN","Graduate Certificate in Education","0"},
		{"55","https://handbook.unimelb.edu.au/view/2016/GC-EDUCLIL","Graduate Certificate in Education (CLIL)","0"},
		{"56","https://handbook.unimelb.edu.au/view/2016/GC-EDIBMCP","Graduate Certificate in Education (International Baccalaureate)","0"},
		{"57","https://handbook.unimelb.edu.au/view/2016/GC-EDIBDP","Graduate Certificate in Education (International Baccalaureate) DP","0"},
		{"58","https://handbook.unimelb.edu.au/view/2016/GC-EDIBPY","Graduate Certificate in Education (International Baccalaureate) PYP","0"},
		{"59","https://handbook.unimelb.edu.au/view/2016/GC-EDMYL","Graduate Certificate in Education (Middle Years Literacies)","0"},
		{"60","https://handbook.unimelb.edu.au/view/2016/GC-EDSLD","Graduate Certificate in Education (Specific Learning Difficulties)","0"},
		{"61","https://handbook.unimelb.edu.au/view/2016/GC-EDRES","Graduate Certificate in Educational Research","0"},
		{"62","https://handbook.unimelb.edu.au/view/2016/GC-ENV","Graduate Certificate in Environment","0"},
		{"63","https://handbook.unimelb.edu.au/view/2016/GC-EVAL","Graduate Certificate in Evaluation","0"},
		{"64","https://handbook.unimelb.edu.au/view/2016/GC-EVALO","Graduate Certificate in Evaluation","0"},
		{"65","https://handbook.unimelb.edu.au/view/2016/GC-FOODSC","Graduate Certificate in Food Science","0"},
		{"66","https://handbook.unimelb.edu.au/view/2016/GC-FORSMGT","Graduate Certificate in Forest Systems Management","0"},
		{"67","https://handbook.unimelb.edu.au/view/2016/GC-GARDES","Graduate Certificate in Garden Design","0"},
		{"68","https://handbook.unimelb.edu.au/view/2016/GC-GWINEST","Graduate Certificate in Global Wine Studies","0"},
		{"69","https://handbook.unimelb.edu.au/view/2016/687AA","Graduate Certificate in Indigenous Arts Management","0"},
		{"70","https://handbook.unimelb.edu.au/view/2016/GC-IRL","Graduate Certificate in Indigenous Research and Leadership","0"},
		{"71","https://handbook.unimelb.edu.au/view/2016/GCA-JOURN","Graduate Certificate in Journalism (Advanced)","0"},
		{"72","https://handbook.unimelb.edu.au/view/2016/GC-LI","Graduate Certificate in Learning Intervention","0"},
		{"73","https://handbook.unimelb.edu.au/view/2016/423AA","Graduate Certificate in Marketing","0"},
		{"74","https://handbook.unimelb.edu.au/view/2016/GC-MKTMGT","Graduate Certificate in Marketing Management","0"},
		{"75","https://handbook.unimelb.edu.au/view/2016/GC-MHSC","Graduate Certificate in Mental Health Science","0"},
		{"76","https://handbook.unimelb.edu.au/view/2016/GC-MLEA","Graduate Certificate in Modern Languages Education (Stream A)","0"},
		{"77","https://handbook.unimelb.edu.au/view/2016/GC-MLEB","Graduate Certificate in Modern Languages Education (Stream B)","0"},
		{"78","https://handbook.unimelb.edu.au/view/2016/M02MU","Graduate Certificate in Music (Musicology/Ethnomusicology)","0"},
		{"79","https://handbook.unimelb.edu.au/view/2016/M02PM","Graduate Certificate in Music (Practical Music)","0"},
		{"80","https://handbook.unimelb.edu.au/view/2016/GC-NP","Graduate Certificate in Nursing Practice","0"},
		{"81","https://handbook.unimelb.edu.au/view/2016/GC-NPCPC","Graduate Certificate in Nursing Practice (Cancer and Palliative Care)","0"},
		{"82","https://handbook.unimelb.edu.au/view/2016/GC-NPCC","Graduate Certificate in Nursing Practice (Critical Care)","0"},
		{"83","https://handbook.unimelb.edu.au/view/2016/GC-NPEMERG","Graduate Certificate in Nursing Practice (Emergency)","0"},
		{"84","https://handbook.unimelb.edu.au/view/2016/GC-NPNICU","Graduate Certificate in Nursing Practice (Neonatal Intensive Care)","0"},
		{"85","https://handbook.unimelb.edu.au/view/2016/GC-NPPIC","Graduate Certificate in Nursing Practice (Paediatric Intensive Care)","0"},
		{"86","https://handbook.unimelb.edu.au/view/2016/GC-NPPAED","Graduate Certificate in Nursing Practice (Paediatrics)","0"},
		{"87","https://handbook.unimelb.edu.au/view/2016/GC-NPRCC","Graduate Certificate in Nursing Practice (Rural Critical Care)","0"},
		{"88","https://handbook.unimelb.edu.au/view/2016/GC-PALCARE","Graduate Certificate in Palliative Care","0"},
		{"89","https://handbook.unimelb.edu.au/view/2016/GC-PHTYEWH","Graduate Certificate in Physiotherapy (Exercise and Women's Health)","0"},
		{"90","https://handbook.unimelb.edu.au/view/2016/GC-PHTYPAE","Graduate Certificate in Physiotherapy (Paediatrics)","0"},
		{"91","https://handbook.unimelb.edu.au/view/2016/GC-PHTYPFP","Graduate Certificate in Physiotherapy (Pelvic Floor Physiotherapy)","0"},
		{"92","https://handbook.unimelb.edu.au/view/2016/GC-PCN","Graduate Certificate in Primary Care Nursing","0"},
		{"93","https://handbook.unimelb.edu.au/view/2016/GCA-PUBCOM","Graduate Certificate in Publishing and Communications (Advanced)","0"},
		{"94","https://handbook.unimelb.edu.au/view/2016/GC-QA","Graduate Certificate in Quality Assurance","0"},
		{"95","https://handbook.unimelb.edu.au/view/2016/GC-REHABSC","Graduate Certificate in Rehabilitation Science","0"},
		{"96","https://handbook.unimelb.edu.au/view/2016/GC-RESMGPL","Graduate Certificate in Research Management and Policy","0"},
		{"97","https://handbook.unimelb.edu.au/view/2016/GC-SC","Graduate Certificate in Science","0"},
		{"98","https://handbook.unimelb.edu.au/view/2016/GC-SEXHLTH","Graduate Certificate in Sexual Health","0"},
		{"99","https://handbook.unimelb.edu.au/view/2016/GC-SAECC","Graduate Certificate in Small Animal Emergency and Critical Care","0"},
		{"100","https://handbook.unimelb.edu.au/view/2016/GC-SAUA","Graduate Certificate in Small Animal Ultrasound Abdominal","0"},
		{"101","https://handbook.unimelb.edu.au/view/2016/GC-SOCIMP","Graduate Certificate in Social Impact","0"},
		{"102","https://handbook.unimelb.edu.au/view/2016/GC-SURGED","Graduate Certificate in Surgical Education","0"},
		{"103","https://handbook.unimelb.edu.au/view/2016/GC-TESOLA","Graduate Certificate in TESOL (Stream A)","0"},
		{"104","https://handbook.unimelb.edu.au/view/2016/GC-TESOLB","Graduate Certificate in TESOL (Stream B)","0"},
		{"105","https://handbook.unimelb.edu.au/view/2016/GC-TEM","Graduate Certificate in Tertiary Education Management","0"},
		{"106","https://handbook.unimelb.edu.au/view/2016/GC-TERTCH","Graduate Certificate in Tertiary Teaching","0"},
		{"107","https://handbook.unimelb.edu.au/view/2016/GC-TRNSPRC","Graduate Certificate in Transfusion Practice","0"},
		{"108","https://handbook.unimelb.edu.au/view/2016/622AA","Graduate Certificate in University Management","0"},
		{"109","https://handbook.unimelb.edu.au/view/2016/697AA","Graduate Certificate in University Teaching","0"},
		{"110","https://handbook.unimelb.edu.au/view/2016/GC-UCH","Graduate Certificate in Urban and Cultural Heritage","0"},
		{"111","https://handbook.unimelb.edu.au/view/2016/842AA","Graduate Certificate in Visual Art","0"},
		{"112","https://handbook.unimelb.edu.au/view/2016/GC-VOICEST","Graduate Certificate in Voice Studies","0"},
		{"113","https://handbook.unimelb.edu.au/view/2016/449AA","Graduate Certificate in Wine Technology and Viticulture","0"},
		{"114","https://handbook.unimelb.edu.au/view/2016/GC-YMH","Graduate Certificate in Youth Mental Health","0"},
		{"115","https://handbook.unimelb.edu.au/view/2016/GC-TSS","Graduate Certificate in the Teaching of Shakespeare","0"},
		{"116","https://handbook.unimelb.edu.au/view/2016/GD-ACTSC","Graduate Diploma in Actuarial Science","0"},
		{"117","https://handbook.unimelb.edu.au/view/2016/GD-ADOLHW","Graduate Diploma in Adolescent Health and Wellbeing","0"},
		{"118","https://handbook.unimelb.edu.au/view/2016/GD-AGEING","Graduate Diploma in Ageing","0"},
		{"119","https://handbook.unimelb.edu.au/view/2016/GD-AGRBUSV","Graduate Diploma in Agribusiness for Veterinarians","0"},
		{"120","https://handbook.unimelb.edu.au/view/2016/GD-AGSC","Graduate Diploma in Agricultural Sciences","0"},
		{"121","https://handbook.unimelb.edu.au/view/2016/GD-ANIMSC","Graduate Diploma in Animal Science","0"},
		{"122","https://handbook.unimelb.edu.au/view/2016/GD-ARTS","Graduate Diploma in Arts","0"},
		{"123","https://handbook.unimelb.edu.au/view/2016/GDA-ARTS","Graduate Diploma in Arts (Advanced)","0"},
		{"124","https://handbook.unimelb.edu.au/view/2016/GDA-ACM","Graduate Diploma in Arts and Cultural Management (Advanced)","0"},
		{"125","https://handbook.unimelb.edu.au/view/2016/726AA","Graduate Diploma in Asian Law","0"},
		{"126","https://handbook.unimelb.edu.au/view/2016/968AB","Graduate Diploma in Banking and Finance Law","0"},
		{"127","https://handbook.unimelb.edu.au/view/2016/GD-BIOSTAT","Graduate Diploma in Biostatistics","0"},
		{"128","https://handbook.unimelb.edu.au/view/2016/GD-BLTENV","Graduate Diploma in Built Environments","0"},
		{"129","https://handbook.unimelb.edu.au/view/2016/GDA-BLTENV","Graduate Diploma in Built Environments (Advanced)","0"},
		{"130","https://handbook.unimelb.edu.au/view/2016/GD-BFIREPM","Graduate Diploma in Bushfire Planning and Management","0"},
		{"131","https://handbook.unimelb.edu.au/view/2016/GD-BA","Graduate Diploma in Business Administration","0"},
		{"132","https://handbook.unimelb.edu.au/view/2016/031AA","Graduate Diploma in Clinical Dentistry","0"},
		{"133","https://handbook.unimelb.edu.au/view/2016/GD-CLINED","Graduate Diploma in Clinical Education","0"},
		{"134","https://handbook.unimelb.edu.au/view/2016/N34AA","Graduate Diploma in Clinical Research","0"},
		{"135","https://handbook.unimelb.edu.au/view/2016/GD-CLINUS","Graduate Diploma in Clinical Ultrasound","0"},
		{"136","https://handbook.unimelb.edu.au/view/2016/518AB","Graduate Diploma in Communications Law","0"},
		{"137","https://handbook.unimelb.edu.au/view/2016/GD-CCLAW","Graduate Diploma in Competition and Consumer Law","0"},
		{"138","https://handbook.unimelb.edu.au/view/2016/189AA","Graduate Diploma in Construction Law","0"},
		{"139","https://handbook.unimelb.edu.au/view/2016/538AA","Graduate Diploma in Corporations and Securities Law","0"},
		{"140","https://handbook.unimelb.edu.au/view/2016/498AB","Graduate Diploma in Dispute Resolution","0"},
		{"141","https://handbook.unimelb.edu.au/view/2016/GD-ECO","Graduate Diploma in Economics","0"},
		{"142","https://handbook.unimelb.edu.au/view/2016/188AA","Graduate Diploma in Employment and Labour Relations Law","0"},
		{"143","https://handbook.unimelb.edu.au/view/2016/GD-ENRSLAW","Graduate Diploma in Energy and Resources Law","0"},
		{"144","https://handbook.unimelb.edu.au/view/2016/GD-ENV","Graduate Diploma in Environment","0"},
		{"145","https://handbook.unimelb.edu.au/view/2016/GD-ENVLAW","Graduate Diploma in Environmental Law","0"},
		{"146","https://handbook.unimelb.edu.au/view/2016/GD-FIN","Graduate Diploma in Finance","0"},
		{"147","https://handbook.unimelb.edu.au/view/2016/GD-FOODSC","Graduate Diploma in Food Science","0"},
		{"148","https://handbook.unimelb.edu.au/view/2016/GD-FORSMGT","Graduate Diploma in Forest Systems Management","0"},
		{"149","https://handbook.unimelb.edu.au/view/2016/583AA","Graduate Diploma in Genetic Counselling","0"},
		{"150","https://handbook.unimelb.edu.au/view/2016/178AA","Graduate Diploma in Government Law","0"},
		{"151","https://handbook.unimelb.edu.au/view/2016/428AA","Graduate Diploma in Guided Imagery and Music","0"},
		{"152","https://handbook.unimelb.edu.au/view/2016/343AA","Graduate Diploma in Health and Medical Law","0"},
		{"153","https://handbook.unimelb.edu.au/view/2016/636AA","Graduate Diploma in Human Rights Law","0"},
		{"154","https://handbook.unimelb.edu.au/view/2016/276AA","Graduate Diploma in Intellectual Property Law","0"},
		{"155","https://handbook.unimelb.edu.au/view/2016/891AA","Graduate Diploma in International Economic Law","0"},
		{"156","https://handbook.unimelb.edu.au/view/2016/323AA","Graduate Diploma in International Law","0"},
		{"157","https://handbook.unimelb.edu.au/view/2016/191AA","Graduate Diploma in International Tax","0"},
		{"158","https://handbook.unimelb.edu.au/view/2016/GDA-JOURN","Graduate Diploma in Journalism (Advanced)","0"},
		{"159","https://handbook.unimelb.edu.au/view/2016/GD-LEGSTU","Graduate Diploma in Legal Studies","0"},
		{"160","https://handbook.unimelb.edu.au/view/2016/GD-MKTG","Graduate Diploma in Marketing","0"},
		{"161","https://handbook.unimelb.edu.au/view/2016/GD-MHSC","Graduate Diploma in Mental Health Science","0"},
		{"162","https://handbook.unimelb.edu.au/view/2016/M01CO","Graduate Diploma in Music (Composition)","0"},
		{"163","https://handbook.unimelb.edu.au/view/2016/M01MU","Graduate Diploma in Music (Musicology/Ethnomusicology)","0"},
		{"164","https://handbook.unimelb.edu.au/view/2016/M01PM","Graduate Diploma in Music (Practical Music)","0"},
		{"165","https://handbook.unimelb.edu.au/view/2016/GD-NP","Graduate Diploma in Nursing Practice","0"},
		{"166","https://handbook.unimelb.edu.au/view/2016/GD-NPMH","Graduate Diploma in Nursing Practice (Mental Health)","0"},
		{"167","https://handbook.unimelb.edu.au/view/2016/GD-PERFCR","Graduate Diploma in Performance Creation","0"},
		{"168","https://handbook.unimelb.edu.au/view/2016/GD-PCN","Graduate Diploma in Primary Care Nursing","0"},
		{"169","https://handbook.unimelb.edu.au/view/2016/702PA","Graduate Diploma in Property Valuation","0"},
		{"170","https://handbook.unimelb.edu.au/view/2016/340AA","Graduate Diploma in Psychology","0"},
		{"171","https://handbook.unimelb.edu.au/view/2016/GDA-PSYCH","Graduate Diploma in Psychology (Advanced)","0"},
		{"172","https://handbook.unimelb.edu.au/view/2016/GDA-PUBCOM","Graduate Diploma in Publishing and Communications (Advanced)","0"},
		{"173","https://handbook.unimelb.edu.au/view/2016/GD-REHABSC","Graduate Diploma in Rehabilitation Science","0"},
		{"174","https://handbook.unimelb.edu.au/view/2016/GD-SC","Graduate Diploma in Science","0"},
		{"175","https://handbook.unimelb.edu.au/view/2016/GDA-SCI","Graduate Diploma in Science (Advanced)","0"},
		{"176","https://handbook.unimelb.edu.au/view/2016/893AA","Graduate Diploma in Sports Law","0"},
		{"177","https://handbook.unimelb.edu.au/view/2016/GD-SURGANT","Graduate Diploma in Surgical Anatomy","0"},
		{"178","https://handbook.unimelb.edu.au/view/2016/GD-SURGED","Graduate Diploma in Surgical Education","0"},
		{"179","https://handbook.unimelb.edu.au/view/2016/187AA","Graduate Diploma in Tax","0"},
		{"180","https://handbook.unimelb.edu.au/view/2016/GD-TROPMH","Graduate Diploma in Tropical Medicine and Hygiene","0"},
		{"181","https://handbook.unimelb.edu.au/view/2016/GD-URBHORT","Graduate Diploma in Urban Horticulture","0"},
		{"182","https://handbook.unimelb.edu.au/view/2016/GD-VPLMGT","Graduate Diploma in Veterinary Professional Leadership and Management","0"},
		{"183","https://handbook.unimelb.edu.au/view/2016/GD-VOICEST","Graduate Diploma in Voice Studies","0"},
		{"184","https://handbook.unimelb.edu.au/view/2016/GD-YMH","Graduate Diploma in Youth Mental Health","0"},
		{"185","https://handbook.unimelb.edu.au/view/2016/MC-JURISD","Juris Doctor","0"},
		{"186","https://handbook.unimelb.edu.au/view/2016/794NF","Juris Doctor/Master of Business Administration","0"},
		{"187","https://handbook.unimelb.edu.au/view/2016/MC-ACTSCI","Master of Actuarial Science","0"},
		{"188","https://handbook.unimelb.edu.au/view/2016/MC-ADOLHW","Master of Adolescent Health &amp; Wellbeing","0"},
		{"189","https://handbook.unimelb.edu.au/view/2016/MC-AN","Master of Advanced Nursing","0"},
		{"190","https://handbook.unimelb.edu.au/view/2016/MC-ANP","Master of Advanced Nursing Practice","0"},
		{"191","https://handbook.unimelb.edu.au/view/2016/J01AL","Master of Advanced Nursing Practice (Cancer Nursing)","0"},
		{"192","https://handbook.unimelb.edu.au/view/2016/J01AR","Master of Advanced Nursing Practice (Critical Care)","0"},
		{"193","https://handbook.unimelb.edu.au/view/2016/J01AS","Master of Advanced Nursing Practice (Emergency Care)","0"},
		{"194","https://handbook.unimelb.edu.au/view/2016/MC-ANPMH","Master of Advanced Nursing Practice (Mental Health)","0"},
		{"195","https://handbook.unimelb.edu.au/view/2016/MC-ANPNICU","Master of Advanced Nursing Practice (Neonatal Intensive Care)","0"},
		{"196","https://handbook.unimelb.edu.au/view/2016/MC-ANPNP","Master of Advanced Nursing Practice (Nurse Practitioner)","0"},
		{"197","https://handbook.unimelb.edu.au/view/2016/J01AP","Master of Advanced Nursing Practice (Paediatrics)","0"},
		{"198","https://handbook.unimelb.edu.au/view/2016/J01AF","Master of Advanced Nursing Practice (Palliative Care)","0"},
		{"199","https://handbook.unimelb.edu.au/view/2016/J01AY","Master of Advanced Nursing Practice (Rural Critical Care)","0"},
		{"200","https://handbook.unimelb.edu.au/view/2016/J17RE","Master of Advanced Social Work","0"},
		{"201","https://handbook.unimelb.edu.au/view/2016/MC-AGEING","Master of Ageing","0"},
		{"202","https://handbook.unimelb.edu.au/view/2016/704CC","Master of Agribusiness","0"},
		{"203","https://handbook.unimelb.edu.au/view/2016/MC-AGSC","Master of Agricultural Sciences","0"},
		{"204","https://handbook.unimelb.edu.au/view/2016/837AA","Master of Applied Finance","0"},
		{"205","https://handbook.unimelb.edu.au/view/2016/MC-APLING","Master of Applied Linguistics","0"},
		{"206","https://handbook.unimelb.edu.au/view/2016/MC-APP","Master of Applied Positive Psychology","0"},
		{"207","https://handbook.unimelb.edu.au/view/2016/MC-ARCH","Master of Architecture","0"},
		{"208","https://handbook.unimelb.edu.au/view/2016/038AB","Master of Art Curatorship","0"},
		{"209","https://handbook.unimelb.edu.au/view/2016/MR-ARTSAST","Master of Arts (Advanced Seminar &amp; Shorter Thesis)","0"},
		{"210","https://handbook.unimelb.edu.au/view/2016/MC-ARTPAE","Master of Arts (Professional and Applied Ethics)","0"},
		{"211","https://handbook.unimelb.edu.au/view/2016/MR-ARTSTHS","Master of Arts (Thesis only)","0"},
		{"212","https://handbook.unimelb.edu.au/view/2016/MC-ACP","Master of Arts and Community Practice","0"},
		{"213","https://handbook.unimelb.edu.au/view/2016/175AA","Master of Arts and Cultural Management","0"},
		{"214","https://handbook.unimelb.edu.au/view/2016/526AA","Master of Banking and Finance Law","0"},
		{"215","https://handbook.unimelb.edu.au/view/2016/MC-BMEDSC","Master of Biomedical Science","0"},
		{"216","https://handbook.unimelb.edu.au/view/2016/991AA","Master of Biostatistics","0"},
		{"217","https://handbook.unimelb.edu.au/view/2016/MC-SCIBIT","Master of Biotechnology","0"},
		{"218","https://handbook.unimelb.edu.au/view/2016/MC-BA","Master of Business Administration","0"},
		{"219","https://handbook.unimelb.edu.au/view/2016/MC-BAEV","Master of Business Administration","0"},
		{"220","https://handbook.unimelb.edu.au/view/2016/MC-BAPT","Master of Business Administration","0"},
		{"221","https://handbook.unimelb.edu.au/view/2016/MC-BAPTME","Master of Business Administration","0"},
		{"222","https://handbook.unimelb.edu.au/view/2016/MC-BUSAIS","Master of Business Administration/Master of Information Systems","0"},
		{"223","https://handbook.unimelb.edu.au/view/2016/MC-BAMKTG","Master of Business Administration/Master of Marketing","0"},
		{"224","https://handbook.unimelb.edu.au/view/2016/MC-BUSANA","Master of Business Analytics","0"},
		{"225","https://handbook.unimelb.edu.au/view/2016/305BB","Master of Clinical Audiology","0"},
		{"226","https://handbook.unimelb.edu.au/view/2016/MC-CLINED","Master of Clinical Education","0"},
		{"227","https://handbook.unimelb.edu.au/view/2016/MC-CLINOPT","Master of Clinical Optometry","0"},
		{"228","https://handbook.unimelb.edu.au/view/2016/N01AA","Master of Clinical Research","0"},
		{"229","https://handbook.unimelb.edu.au/view/2016/MC-CLINTCH","Master of Clinical Teaching","0"},
		{"230","https://handbook.unimelb.edu.au/view/2016/MC-CU","Master of Clinical Ultrasound","0"},
		{"231","https://handbook.unimelb.edu.au/view/2016/202AT","Master of Commerce","0"},
		{"232","https://handbook.unimelb.edu.au/view/2016/MC-COMACCT","Master of Commerce (Accounting)","0"},
		{"233","https://handbook.unimelb.edu.au/view/2016/MC-COMACTS","Master of Commerce (Actuarial Science)","0"},
		{"234","https://handbook.unimelb.edu.au/view/2016/202AF","Master of Commerce (Finance)","0"},
		{"235","https://handbook.unimelb.edu.au/view/2016/MC-COMMGT","Master of Commerce (Management)","0"},
		{"236","https://handbook.unimelb.edu.au/view/2016/MC-COMMKT","Master of Commerce (Marketing)","0"},
		{"237","https://handbook.unimelb.edu.au/view/2016/504AA","Master of Commercial Law","0"},
		{"238","https://handbook.unimelb.edu.au/view/2016/MC-CMCNLAW","Master of Competition and Consumer Law","0"},
		{"239","https://handbook.unimelb.edu.au/view/2016/195AA","Master of Construction Law","0"},
		{"240","https://handbook.unimelb.edu.au/view/2016/MC-CM","Master of Construction Management","0"},
		{"241","https://handbook.unimelb.edu.au/view/2016/MC-CTPYART","Master of Contemporary Art","0"},
		{"242","https://handbook.unimelb.edu.au/view/2016/D01LF","Master of Creative Writing, Publishing and Editing","0"},
		{"243","https://handbook.unimelb.edu.au/view/2016/274AB","Master of Criminology","0"},
		{"244","https://handbook.unimelb.edu.au/view/2016/MC-CULMC","Master of Cultural Materials Conservation","0"},
		{"245","https://handbook.unimelb.edu.au/view/2016/MC-DANCE","Master of Dance","0"},
		{"246","https://handbook.unimelb.edu.au/view/2016/234AA","Master of Design","0"},
		{"247","https://handbook.unimelb.edu.au/view/2016/MC-DSNPERF","Master of Design for Performance","0"},
		{"248","https://handbook.unimelb.edu.au/view/2016/097AB","Master of Development Studies","0"},
		{"249","https://handbook.unimelb.edu.au/view/2016/MC-DIRPERF","Master of Directing for Performance","0"},
		{"250","https://handbook.unimelb.edu.au/view/2016/MC-DRAMAT","Master of Dramaturgy","0"},
		{"251","https://handbook.unimelb.edu.au/view/2016/MC-ECO","Master of Economics","0"},
		{"252","https://handbook.unimelb.edu.au/view/2016/960AC","Master of Education","0"},
		{"253","https://handbook.unimelb.edu.au/view/2016/960BA","Master of Education","0"},
		{"254","https://handbook.unimelb.edu.au/view/2016/MC-EDCLIL","Master of Education (CLIL)","0"},
		{"255","https://handbook.unimelb.edu.au/view/2016/960EB","Master of Education (Educational Management)","0"},
		{"256","https://handbook.unimelb.edu.au/view/2016/MC-EDEDMGT","Master of Education (Educational Management)","0"},
		{"257","https://handbook.unimelb.edu.au/view/2016/960ID","Master of Education (International Baccalaureate)","0"},
		{"258","https://handbook.unimelb.edu.au/view/2016/MC-EDIBDP","Master of Education (International Baccalaureate) DP","0"},
		{"259","https://handbook.unimelb.edu.au/view/2016/MC-EDIBPY","Master of Education (International Baccalaureate) PYP","0"},
		{"260","https://handbook.unimelb.edu.au/view/2016/960LH","Master of Education (Language Intervention and Hearing Impairment)","0"},
		{"261","https://handbook.unimelb.edu.au/view/2016/960SE","Master of Education (Special Education Inclusion and Early Intervention)","0"},
		{"262","https://handbook.unimelb.edu.au/view/2016/960NL","Master of Education (Specific Learning Difficulties)","0"},
		{"263","https://handbook.unimelb.edu.au/view/2016/960SL","Master of Education (Specific Learning Difficulties)","0"},
		{"264","https://handbook.unimelb.edu.au/view/2016/G01SW","Master of Education (Student Wellbeing)","0"},
		{"265","https://handbook.unimelb.edu.au/view/2016/695AA","Master of Education Policy (International)","0"},
		{"266","https://handbook.unimelb.edu.au/view/2016/312AA","Master of Educational Psychology","0"},
		{"267","https://handbook.unimelb.edu.au/view/2016/G02AA","Master of Educational Psychology/Doctor of Philosophy","0"},
		{"268","https://handbook.unimelb.edu.au/view/2016/510AA","Master of Employment and Labour Relations Law","0"},
		{"269","https://handbook.unimelb.edu.au/view/2016/MC-ENGYSYS","Master of Energy Systems","0"},
		{"270","https://handbook.unimelb.edu.au/view/2016/MC-ENRSLAW","Master of Energy and Resources Law","0"},
		{"271","https://handbook.unimelb.edu.au/view/2016/MC-ENG","Master of Engineering","0"},
		{"272","https://handbook.unimelb.edu.au/view/2016/761EM","Master of Engineering Management","0"},
		{"273","https://handbook.unimelb.edu.au/view/2016/746ST","Master of Engineering Structures","0"},
		{"274","https://handbook.unimelb.edu.au/view/2016/MC-ENGGC","Master of English in a Global Context","0"},
		{"275","https://handbook.unimelb.edu.au/view/2016/MC-ENT","Master of Enterprise","0"},
		{"276","https://handbook.unimelb.edu.au/view/2016/MC-ENTSC","Master of Enterprise (Science)","0"},
		{"277","https://handbook.unimelb.edu.au/view/2016/MC-ENTR","Master of Entrepreneurship","0"},
		{"278","https://handbook.unimelb.edu.au/view/2016/MC-ENV","Master of Environment","0"},
		{"279","https://handbook.unimelb.edu.au/view/2016/206EC","Master of Environmental Engineering","0"},
		{"280","https://handbook.unimelb.edu.au/view/2016/MC-ENVLAW","Master of Environmental Law","0"},
		{"281","https://handbook.unimelb.edu.au/view/2016/570AA","Master of Epidemiology","0"},
		{"282","https://handbook.unimelb.edu.au/view/2016/MC-EVAL","Master of Evaluation","0"},
		{"283","https://handbook.unimelb.edu.au/view/2016/MC-EVALO","Master of Evaluation","0"},
		{"284","https://handbook.unimelb.edu.au/view/2016/MR-EVAL","Master of Evaluation","0"},
		{"285","https://handbook.unimelb.edu.au/view/2016/MC-FILMTV","Master of Film and Television","0"},
		{"286","https://handbook.unimelb.edu.au/view/2016/MC-FIN","Master of Finance","0"},
		{"287","https://handbook.unimelb.edu.au/view/2016/MR-FACCD","Master of Fine Arts (Community Cultural Development)","0"},
		{"288","https://handbook.unimelb.edu.au/view/2016/MR-FACMUS","Master of Fine Arts (Contemporary Music)","0"},
		{"289","https://handbook.unimelb.edu.au/view/2016/MR-FADANCE","Master of Fine Arts (Dance)","0"},
		{"290","https://handbook.unimelb.edu.au/view/2016/MR-FAFTV","Master of Fine Arts (Film and Television)","0"},
		{"291","https://handbook.unimelb.edu.au/view/2016/MR-FAIAP","Master of Fine Arts (Interdisciplinary Arts Practice)","0"},
		{"292","https://handbook.unimelb.edu.au/view/2016/MR-FAMUSTH","Master of Fine Arts (Music Theatre)","0"},
		{"293","https://handbook.unimelb.edu.au/view/2016/MR-FAPROD","Master of Fine Arts (Production)","0"},
		{"294","https://handbook.unimelb.edu.au/view/2016/MR-FATHTR","Master of Fine Arts (Theatre)","0"},
		{"295","https://handbook.unimelb.edu.au/view/2016/MR-FAVISAR","Master of Fine Arts (Visual Art)","0"},
		{"296","https://handbook.unimelb.edu.au/view/2016/439FS","Master of Food Science","0"},
		{"297","https://handbook.unimelb.edu.au/view/2016/MC-FOODPI","Master of Food and Packaging Innovation","0"},
		{"298","https://handbook.unimelb.edu.au/view/2016/MC-FRSTES","Master of Forest Ecosystem Science","0"},
		{"299","https://handbook.unimelb.edu.au/view/2016/MC-GENCOUN","Master of Genetic Counselling","0"},
		{"300","https://handbook.unimelb.edu.au/view/2016/MC-GEOSC","Master of Geoscience","0"},
		{"301","https://handbook.unimelb.edu.au/view/2016/MC-GMCOM","Master of Global Media Communication","0"},
		{"302","https://handbook.unimelb.edu.au/view/2016/MC-GLBSTED","Master of Global Studies in Education","0"},
		{"303","https://handbook.unimelb.edu.au/view/2016/507AA","Master of Health and Medical Law","0"},
		{"304","https://handbook.unimelb.edu.au/view/2016/MC-HUMRLAW","Master of Human Rights Law","0"},
		{"305","https://handbook.unimelb.edu.au/view/2016/MC-IS","Master of Information Systems","0"},
		{"306","https://handbook.unimelb.edu.au/view/2016/ML-ISBA","Master of Information Systems/Graduate Diploma in Business Admin","0"},
		{"307","https://handbook.unimelb.edu.au/view/2016/MC-IT","Master of Information Technology","0"},
		{"308","https://handbook.unimelb.edu.au/view/2016/MC-INSLEAD","Master of Instructional Leadership","0"},
		{"309","https://handbook.unimelb.edu.au/view/2016/277AA","Master of Intellectual Property Law","0"},
		{"310","https://handbook.unimelb.edu.au/view/2016/MC-IB","Master of International Business","0"},
		{"311","https://handbook.unimelb.edu.au/view/2016/MC-IR","Master of International Relations","0"},
		{"312","https://handbook.unimelb.edu.au/view/2016/192AA","Master of International Tax","0"},
		{"313","https://handbook.unimelb.edu.au/view/2016/MC-JOURN","Master of Journalism","0"},
		{"314","https://handbook.unimelb.edu.au/view/2016/MC-LARCH","Master of Landscape Architecture","0"},
		{"315","https://handbook.unimelb.edu.au/view/2016/635AA","Master of Law and Development","0"},
		{"316","https://handbook.unimelb.edu.au/view/2016/502CW","Master of Laws","0"},
		{"317","https://handbook.unimelb.edu.au/view/2016/502NT","Master of Laws","0"},
		{"318","https://handbook.unimelb.edu.au/view/2016/MC-LI","Master of Learning Intervention","0"},
		{"319","https://handbook.unimelb.edu.au/view/2016/MC-LIT","Master of Literacy","0"},
		{"320","https://handbook.unimelb.edu.au/view/2016/MC-MGMT","Master of Management","0"},
		{"321","https://handbook.unimelb.edu.au/view/2016/MC-MGMTAFN","Master of Management (Accounting and Finance)","0"},
		{"322","https://handbook.unimelb.edu.au/view/2016/MC-MGMTACT","Master of Management (Accounting)","0"},
		{"323","https://handbook.unimelb.edu.au/view/2016/MC-MGMTFIN","Master of Management (Finance)","0"},
		{"324","https://handbook.unimelb.edu.au/view/2016/MC-MGMTHRE","Master of Management (Human Resources)","0"},
		{"325","https://handbook.unimelb.edu.au/view/2016/MC-MGMTMKT","Master of Management (Marketing)","0"},
		{"326","https://handbook.unimelb.edu.au/view/2016/294BE","Master of Marketing","0"},
		{"327","https://handbook.unimelb.edu.au/view/2016/294FN","Master of Marketing","0"},
		{"328","https://handbook.unimelb.edu.au/view/2016/294PN","Master of Marketing","0"},
		{"329","https://handbook.unimelb.edu.au/view/2016/MC-MKTCOMM","Master of Marketing Communications","0"},
		{"330","https://handbook.unimelb.edu.au/view/2016/572AT","Master of Medicine","0"},
		{"331","https://handbook.unimelb.edu.au/view/2016/572RC","Master of Medicine (Radiology)","0"},
		{"332","https://handbook.unimelb.edu.au/view/2016/MC-MHSC","Master of Mental Health Science","0"},
		{"333","https://handbook.unimelb.edu.au/view/2016/MC-MLEA","Master of Modern Languages Education (Stream A)","0"},
		{"334","https://handbook.unimelb.edu.au/view/2016/MC-MLEB","Master of Modern Languages Education (Stream B)","0"},
		{"335","https://handbook.unimelb.edu.au/view/2016/652AB","Master of Music","0"},
		{"336","https://handbook.unimelb.edu.au/view/2016/652CO","Master of Music (Composition)","0"},
		{"337","https://handbook.unimelb.edu.au/view/2016/MR-MUSINCO","Master of Music (Interactive Composition)","0"},
		{"338","https://handbook.unimelb.edu.au/view/2016/MR-MUSJI","Master of Music (Jazz &amp; Improvisation)","0"},
		{"339","https://handbook.unimelb.edu.au/view/2016/652MP","Master of Music (Music Performance)","0"},
		{"340","https://handbook.unimelb.edu.au/view/2016/MR-MUSMPPS","Master of Music (Music Psychology &amp; Performance Science)","0"},
		{"341","https://handbook.unimelb.edu.au/view/2016/652MT","Master of Music (Music Therapy)","0"},
		{"342","https://handbook.unimelb.edu.au/view/2016/652MU","Master of Music (Musicology/Ethnomusicology)","0"},
		{"343","https://handbook.unimelb.edu.au/view/2016/MC-MUSOP","Master of Music (Opera Performance)","0"},
		{"344","https://handbook.unimelb.edu.au/view/2016/MC-MUSPT","Master of Music (Performance Teaching)","0"},
		{"345","https://handbook.unimelb.edu.au/view/2016/161IN","Master of Music Studies","0"},
		{"346","https://handbook.unimelb.edu.au/view/2016/M04AA","Master of Music Therapy","0"},
		{"347","https://handbook.unimelb.edu.au/view/2016/MC-NTCW","Master of Narrative Therapy and Community Work","0"},
		{"348","https://handbook.unimelb.edu.au/view/2016/MC-NURSC","Master of Nursing Science","0"},
		{"349","https://handbook.unimelb.edu.au/view/2016/MR-PHILAGR","Master of Philosophy - Agricultural Sciences","0"},
		{"350","https://handbook.unimelb.edu.au/view/2016/MR-PHILABP","Master of Philosophy - Architecture, Building and Planning","0"},
		{"351","https://handbook.unimelb.edu.au/view/2016/MR-PHILART","Master of Philosophy - Arts","0"},
		{"352","https://handbook.unimelb.edu.au/view/2016/MR-PHILEDU","Master of Philosophy - Education","0"},
		{"353","https://handbook.unimelb.edu.au/view/2016/MR-PHILENG","Master of Philosophy - Engineering","0"},
		{"354","https://handbook.unimelb.edu.au/view/2016/MR-PHILLAW","Master of Philosophy - Law","0"},
		{"355","https://handbook.unimelb.edu.au/view/2016/MR-PHILBMS","Master of Philosophy - MDHS (Biomedical Science)","0"},
		{"356","https://handbook.unimelb.edu.au/view/2016/MR-PHILDSC","Master of Philosophy - MDHS (Dental Science)","0"},
		{"357","https://handbook.unimelb.edu.au/view/2016/MR-PHILHLT","Master of Philosophy - MDHS (Health Sciences)","0"},
		{"358","https://handbook.unimelb.edu.au/view/2016/MR-PHILMED","Master of Philosophy - MDHS (Medicine)","0"},
		{"359","https://handbook.unimelb.edu.au/view/2016/MR-PHILPGH","Master of Philosophy - MDHS (Population and Global Health)","0"},
		{"360","https://handbook.unimelb.edu.au/view/2016/MR-PHILPSY","Master of Philosophy - MDHS (Psychological Sciences)","0"},
		{"361","https://handbook.unimelb.edu.au/view/2016/MR-PHILMUS","Master of Philosophy - Music","0"},
		{"362","https://handbook.unimelb.edu.au/view/2016/MR-PHILSCI","Master of Philosophy - Science","0"},
		{"363","https://handbook.unimelb.edu.au/view/2016/MR-PHILVET","Master of Philosophy - Veterinary Science","0"},
		{"364","https://handbook.unimelb.edu.au/view/2016/MR-PHILVCA","Master of Philosophy - Victorian College of the Arts","0"},
		{"365","https://handbook.unimelb.edu.au/view/2016/546AA","Master of Primary Health Care","0"},
		{"366","https://handbook.unimelb.edu.au/view/2016/MC-PRIVLAW","Master of Private Law","0"},
		{"367","https://handbook.unimelb.edu.au/view/2016/MC-PROD","Master of Producing","0"},
		{"368","https://handbook.unimelb.edu.au/view/2016/MC-PRODDFS","Master of Production Design for Screen","0"},
		{"369","https://handbook.unimelb.edu.au/view/2016/MC-PROP","Master of Property","0"},
		{"370","https://handbook.unimelb.edu.au/view/2016/342AA","Master of Psychiatry","0"},
		{"371","https://handbook.unimelb.edu.au/view/2016/MC-PO","Master of Psychiatry","0"},
		{"372","https://handbook.unimelb.edu.au/view/2016/MC-PSYCHCS","Master of Psychology (Clinical - Singapore)","0"},
		{"373","https://handbook.unimelb.edu.au/view/2016/080CC","Master of Psychology (Clinical Child Psychology)/Doctor of Philosophy","0"},
		{"374","https://handbook.unimelb.edu.au/view/2016/527CN","Master of Psychology (Clinical Neuropsychology)","0"},
		{"375","https://handbook.unimelb.edu.au/view/2016/080CN","Master of Psychology (Clinical Neuropsychology)/Doctor of Philosophy","0"},
		{"376","https://handbook.unimelb.edu.au/view/2016/527CL","Master of Psychology (Clinical Psychology)","0"},
		{"377","https://handbook.unimelb.edu.au/view/2016/080CL","Master of Psychology (Clinical Psychology)/Doctor of Philosophy","0"},
		{"378","https://handbook.unimelb.edu.au/view/2016/MC-PA","Master of Public Administration","0"},
		{"379","https://handbook.unimelb.edu.au/view/2016/MC-PAENH","Master of Public Administration (Enhanced)","0"},
		{"380","https://handbook.unimelb.edu.au/view/2016/244CW","Master of Public Health","0"},
		{"381","https://handbook.unimelb.edu.au/view/2016/344AB","Master of Public Policy and Management","0"},
		{"382","https://handbook.unimelb.edu.au/view/2016/511AA","Master of Public and International Law","0"},
		{"383","https://handbook.unimelb.edu.au/view/2016/MC-PUBCOM","Master of Publishing and Communications","0"},
		{"384","https://handbook.unimelb.edu.au/view/2016/MC-REHABSC","Master of Rehabilitation Science","0"},
		{"385","https://handbook.unimelb.edu.au/view/2016/MR-RESABP","Master of Research","0"},
		{"386","https://handbook.unimelb.edu.au/view/2016/MR-RESMED","Master of Research","0"},
		{"387","https://handbook.unimelb.edu.au/view/2016/MC-SCIBIO","Master of Science (BioSciences)","0"},
		{"388","https://handbook.unimelb.edu.au/view/2016/MC-SCIBIF","Master of Science (Bioinformatics)","0"},
		{"389","https://handbook.unimelb.edu.au/view/2016/MC-SCICHE","Master of Science (Chemistry)","0"},
		{"390","https://handbook.unimelb.edu.au/view/2016/MC-SCICMP","Master of Science (Computer Science)","0"},
		{"391","https://handbook.unimelb.edu.au/view/2016/MC-SCIEAR","Master of Science (Earth Sciences)","0"},
		{"392","https://handbook.unimelb.edu.au/view/2016/MC-SCIECO","Master of Science (Ecosystem Science)","0"},
		{"393","https://handbook.unimelb.edu.au/view/2016/MC-SCIEPI","Master of Science (Epidemiology)","0"},
		{"394","https://handbook.unimelb.edu.au/view/2016/MC-SCIGEO","Master of Science (Geography)","0"},
		{"395","https://handbook.unimelb.edu.au/view/2016/MC-SCIMAT","Master of Science (Mathematics and Statistics)","0"},
		{"396","https://handbook.unimelb.edu.au/view/2016/MC-SCIPHY","Master of Science (Physics)","0"},
		{"397","https://handbook.unimelb.edu.au/view/2016/MC-SCIVIS","Master of Science (Vision Science)","0"},
		{"398","https://handbook.unimelb.edu.au/view/2016/MC-SCWR","Master of Screenwriting","0"},
		{"399","https://handbook.unimelb.edu.au/view/2016/706AA","Master of Social Policy","0"},
		{"400","https://handbook.unimelb.edu.au/view/2016/MC-SOCW","Master of Social Work","0"},
		{"401","https://handbook.unimelb.edu.au/view/2016/MC-SPCHPTH","Master of Speech Pathology","0"},
		{"402","https://handbook.unimelb.edu.au/view/2016/MC-SCM150","Master of Supply Chain Management","0"},
		{"403","https://handbook.unimelb.edu.au/view/2016/552AA","Master of Surgery","0"},
		{"404","https://handbook.unimelb.edu.au/view/2016/MC-SURGED","Master of Surgical Education","0"},
		{"405","https://handbook.unimelb.edu.au/view/2016/MC-TESOLA","Master of TESOL (Stream A)","0"},
		{"406","https://handbook.unimelb.edu.au/view/2016/MC-TESOLB","Master of TESOL (Stream B)","0"},
		{"407","https://handbook.unimelb.edu.au/view/2016/742AB","Master of Tax","0"},
		{"408","https://handbook.unimelb.edu.au/view/2016/MC-TEACHEC","Master of Teaching (Early Childhood)","0"},
		{"409","https://handbook.unimelb.edu.au/view/2016/MC-TEACHYA","Master of Teaching (Early Years)","0"},
		{"410","https://handbook.unimelb.edu.au/view/2016/MC-TEACHPR","Master of Teaching (Primary)","0"},
		{"411","https://handbook.unimelb.edu.au/view/2016/MC-TEACHSA","Master of Teaching (Secondary)","0"},
		{"412","https://handbook.unimelb.edu.au/view/2016/MC-TEACHSI","Master of Teaching (Secondary) Internship","0"},
		{"413","https://handbook.unimelb.edu.au/view/2016/364AA","Master of Telecommunications Engineering","0"},
		{"414","https://handbook.unimelb.edu.au/view/2016/MC-TEM","Master of Tertiary Education Management","0"},
		{"415","https://handbook.unimelb.edu.au/view/2016/MC-TRANS","Master of Translation","0"},
		{"416","https://handbook.unimelb.edu.au/view/2016/MC-TRANEXT","Master of Translation (Extended)","0"},
		{"417","https://handbook.unimelb.edu.au/view/2016/MC-TRANART","Master of Transnational Arts","0"},
		{"418","https://handbook.unimelb.edu.au/view/2016/MC-URBDES","Master of Urban Design","0"},
		{"419","https://handbook.unimelb.edu.au/view/2016/MC-URBHORT","Master of Urban Horticulture","0"},
		{"420","https://handbook.unimelb.edu.au/view/2016/MC-URPL","Master of Urban Planning","0"},
		{"421","https://handbook.unimelb.edu.au/view/2016/MC-UCH","Master of Urban and Cultural Heritage","0"},
		{"422","https://handbook.unimelb.edu.au/view/2016/MC-VPHEAD","Master of Veterinary Public Health (Emergency Animal Diseases)","0"},
		{"423","https://handbook.unimelb.edu.au/view/2016/872AA","Master of Veterinary Science","0"},
		{"424","https://handbook.unimelb.edu.au/view/2016/872BB","Master of Veterinary Science","0"},
		{"425","https://handbook.unimelb.edu.au/view/2016/MC-VETSTDR","Master of Veterinary Studies","0"},
		{"426","https://handbook.unimelb.edu.au/view/2016/MC-WRIPERF","Master of Writing for Performance","0"},
		{"427","https://handbook.unimelb.edu.au/view/2016/MC-YMH","Master of Youth Mental Health","0"},
		{"428","https://handbook.unimelb.edu.au/view/2016/PR-ARTSED","Professional Certificate in Arts Education","0"},
		{"429","https://handbook.unimelb.edu.au/view/2016/N28AA","Professional Certificate in Clinical Research","0"},
		{"430","https://handbook.unimelb.edu.au/view/2016/PR-EDASC","Professional Certificate in Education (Autism Spectrum Conditions)","0"},
		{"431","https://handbook.unimelb.edu.au/view/2016/GC-EDCLIL","Professional Certificate in Education (CLIL)","0"},
		{"432","https://handbook.unimelb.edu.au/view/2016/GC-PEDPBL","Professional Certificate in Education (Positive Behaviour and Learning)","0"},
		{"433","https://handbook.unimelb.edu.au/view/2016/PR-EDPOSED","Professional Certificate in Education (Positive Education)","0"},
		{"434","https://handbook.unimelb.edu.au/view/2016/GC-EDTFA","Professional Certificate in Education (TFA Mentoring)","0"},
		{"435","https://handbook.unimelb.edu.au/view/2016/PR-GWINEST","Professional Certificate in Global Wine Studies","0"},
		{"436","https://handbook.unimelb.edu.au/view/2016/GC-HISTED","Professional Certificate in History Education","0"},
		{"437","https://handbook.unimelb.edu.au/view/2016/GC-IRPRO","Professional Certificate in Indigenous Research","0"},
		{"438","https://handbook.unimelb.edu.au/view/2016/GC-INSLEAD","Professional Certificate in Instructional Leadership","0"},
		{"439","https://handbook.unimelb.edu.au/view/2016/PR-MTHEDPR","Professional Certificate in Mathematics Education (Primary)","0"},
		{"440","https://handbook.unimelb.edu.au/view/2016/PR-MTHED12","Professional Certificate in Mathematics Education (Years 11-12)","0"},
		{"441","https://handbook.unimelb.edu.au/view/2016/PR-MTHED10","Professional Certificate in Mathematics Education (Years 7-10)","0"},
		{"442","https://handbook.unimelb.edu.au/view/2016/PR-MHPRAC","Professional Certificate in Mental Health Practice","0"},
		{"443","https://handbook.unimelb.edu.au/view/2016/PR-POSPSYC","Professional Certificate in Positive Psychology","0"},
		{"444","https://handbook.unimelb.edu.au/view/2016/PR-TCHCLIN","Professional Certificate in Teaching (Clinical)","0"},
		{"445","https://handbook.unimelb.edu.au/view/2016/SC-AGEING","Specialist Certificate in Ageing","0"},
		{"446","https://handbook.unimelb.edu.au/view/2016/SC-ADED","Specialist Certificate in Anterior and Dry Eye Disorders","0"},
		{"447","https://handbook.unimelb.edu.au/view/2016/N05BR","Specialist Certificate in Clinical Research (Biomedical Research Mgmt)","0"},
		{"448","https://handbook.unimelb.edu.au/view/2016/N05NS","Specialist Certificate in Clinical Research (Neuroscience)","0"},
		{"449","https://handbook.unimelb.edu.au/view/2016/N05ON","Specialist Certificate in Clinical Research (Oncology)","0"},
		{"450","https://handbook.unimelb.edu.au/view/2016/GC-CRCOORD","Specialist Certificate in Clinical Research-Clinical Trials Coordination","0"},
		{"451","https://handbook.unimelb.edu.au/view/2016/GC-CRMONIT","Specialist Certificate in Clinical Research-Clinical Trials Monitoring","0"},
		{"452","https://handbook.unimelb.edu.au/view/2016/GC-CRIMFD","Specialist Certificate in Criminology (Forensic Disability)","0"},
		{"453","https://handbook.unimelb.edu.au/view/2016/GC-CRIMSOM","Specialist Certificate in Criminology (Sexual Offender Management)","0"},
		{"454","https://handbook.unimelb.edu.au/view/2016/SC-CCCONS","Specialist Certificate in Cross-Cultural Conservation and Heritage","0"},
		{"455","https://handbook.unimelb.edu.au/view/2016/SC-ECODES","Specialist Certificate in Economic Design","0"},
		{"456","https://handbook.unimelb.edu.au/view/2016/GC-EXECLDS","Specialist Certificate in Executive Leadership","0"},
		{"457","https://handbook.unimelb.edu.au/view/2016/SC-GARD","Specialist Certificate in Glaucoma and Retinal Disease","0"},
		{"458","https://handbook.unimelb.edu.au/view/2016/SC-GREEN","Specialist Certificate in Green Roofs and Walls","0"},
		{"459","https://handbook.unimelb.edu.au/view/2016/SC-HEARSC","Specialist Certificate in Hearing Science","0"},
		{"460","https://handbook.unimelb.edu.au/view/2016/GC-PAEDOP","Specialist Certificate in Paediatric Orthopaedic Physiotherapy","0"},
		{"461","https://handbook.unimelb.edu.au/view/2016/GC-PALLC","Specialist Certificate in Palliative Care","0"},
		{"462","https://handbook.unimelb.edu.au/view/2016/SC-PRACTMH","Specialist Certificate in Practice of Tropical Medicine and Hygiene","0"},
		{"463","https://handbook.unimelb.edu.au/view/2016/SC-REHABSC","Specialist Certificate in Rehabilitation Science","0"},
		{"464","https://handbook.unimelb.edu.au/view/2016/GC-RPP","Specialist Certificate in Rural Paediatric Practice","0"},
		{"465","https://handbook.unimelb.edu.au/view/2016/SC-SCE","Specialist Certificate in Strategic Communications and Engagement","0"},
		{"466","https://handbook.unimelb.edu.au/view/2016/GC-STRATMK","Specialist Certificate in Strategic Marketing","0"},
		{"467","https://handbook.unimelb.edu.au/view/2016/SC-TGR","Specialist Certificate in Teaching for Graduate Researchers","0"},
		{"468","https://handbook.unimelb.edu.au/view/2016/SC-TRAVMED","Specialist Certificate in Travel Medicine","0"},
		{"469","https://handbook.unimelb.edu.au/view/2016/SC-UCH","Specialist Certificate in Urban and Cultural Heritage","0"},
		{"470","https://handbook.unimelb.edu.au/view/2016/GC-MCLP","Specialist Certificate in the Management of Contact Lens Patients","0"},
		{"471","https://handbook.unimelb.edu.au/view/2016/GC-MLVP","Specialist Certificate in the Management of Low Vision Patients","0"},
		{"472","https://handbook.unimelb.edu.au/view/2016/SC-MNOD","Specialist Certificate in the Management of Neural-Ophthalmic Disorders","0"},
		{"473","https://handbook.unimelb.edu.au/view/2016/GC-MPP","Specialist Certificate in the Management of Paediatric Patients","0"}
		
	};
}

