package birmingham;

import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.config.CookieSpecs;
import org.apache.http.client.config.RequestConfig;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;
import org.htmlparser.Node;
import org.htmlparser.Parser;
import org.htmlparser.filters.AndFilter;
import org.htmlparser.filters.HasAttributeFilter;
import org.htmlparser.filters.TagNameFilter;
import org.htmlparser.tags.LinkTag;
import org.htmlparser.util.NodeList;

public class getPostURL {

	/**
	 * @param args
	 */
	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub
		RequestConfig requestConfig = RequestConfig.custom().setCookieSpec(CookieSpecs.STANDARD_STRICT).build();  
		CloseableHttpClient httpclient = HttpClients.custom().setDefaultRequestConfig(requestConfig).build();  
		
		String searchpage1="http://www.birmingham.ac.uk/postgraduate/courses/taught/search.aspx?CourseComplete_AtoZ_header_AtoZLetter=";
		String searchpage2="&CourseComplete_atozlisting_goto=";
		for(int i=0;i<26;i++)
		{
			int a=Integer.parseInt(LetterPages[i][1]);
			for(int j=1;j<=a;j++)
			{
				int index=j;
				//System.out.println(index);
				HttpGet httpGet = new HttpGet(searchpage1+LetterPages[i][0]+searchpage2+index); 
				HttpResponse response = httpclient.execute(httpGet);  
				HttpEntity entity = response.getEntity();
				String htmls=null;
				if (entity != null) { 
				    htmls=EntityUtils.toString(entity).replace("\t", " ");
				}
				Parser parser=Parser.createParser(htmls, "utf-8");
			    AndFilter ProfessionNameFilter=new AndFilter(new TagNameFilter("table"),
		                new HasAttributeFilter("class","sys_uob-listing"));
		        NodeList nodes1 = parser.extractAllNodesThatMatch(ProfessionNameFilter);
		        parser=Parser.createParser(nodes1.elementAt(0).toHtml(), "utf-8");
		        TagNameFilter TF=new TagNameFilter("tr");
		        NodeList nodes2 = parser.extractAllNodesThatMatch(TF);
		        //System.out.println("Size:"+nodes2.size());
		        if(nodes2.size()>0)
		        {
		        	for(int k=1;k<nodes2.size();k++)
		        	{
		        		
		        		//***************get links;name;type;time
		        		Node node=(Node)nodes2.elementAt(k);
		        		//System.out.println(node.toHtml());
		        		AndFilter linkFilter=new AndFilter(new TagNameFilter("a"),
		                        new HasAttributeFilter("title"));
		        		parser=Parser.createParser(node.toHtml(), "utf-8");
		                NodeList nodes3 = parser.extractAllNodesThatMatch(linkFilter);
		                //System.out.println(nodes3.size());
		                Node aNode=nodes3.elementAt(0);
		                //System.out.println(aNode.toHtml());
		                LinkTag l=(LinkTag)aNode;
		                System.out.print("{\"http://www.birmingham.ac.uk"+l.getAttribute("href")+"\",\""+html2Str(aNode.toHtml().replace(" <br />", "\",\"")).trim()+"\",\"");
		                //html2Str(aNode.toHtml().replace("<br />", ";"));
		                System.out.print(GetType(html2Str(aNode.toHtml().replace(" <br />", "\",\"")).trim()));
		                
		               
		                System.out.println("\"},");
		                
		        	}
		        	
			
		        }
		        }
			}
		
	}
	public static String GetType(String input)//BA BEng Bsc Msc MEng 
	{
		String types="BA;BEng;BSc;BDS;BN;BVSc;MOSci;MESci;MEcol;MPhys;MMath;MMarBiol;MBChB;MChem;MSc;MEng;Double MA;Joint MA;MA;MArich;MBA;PG;Pg;EdD;MEd;Postgraduate Diploma;Postgraduate Certificate;Doctorate;Graduate Certificate;LLM;LLB;GradDip;MTh;MRes";
		
		String[] array=types.split(";");
		for(int i=0;i<array.length;i++)
		{
			if(input.contains(array[i]))
			{
				return array[i];
			}
		}
		//String result=array[array.length-1].replace(")", "");
		return "";
	}
		public static String html2Str(String html) { 
			return html.replaceAll("<[^>]+>", "");
		}
		public static String[][] PostData={
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/international-acct-finance.aspx","Accounting and Finance, International MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/sport-exercise/golf-coaching.aspx","Advanced Certificate in Golf Coaching",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/chemical-engineering/advanced-chemical-engineering.aspx","Advanced Chemical Engineering Masters/MSc/Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/advanced-clinical-practice.aspx","Advanced Clinical Practice MSc/PGCert/PGDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/computer-science/advanced-computer-science.aspx","Advanced Computer Science Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/dent/advanced-general-dental-practice-distance.aspx","Advanced General Dental Practice MSc (Distance Learning)","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/sport-exercise/advanced-manipulative-physio.aspx","Advanced Manipulative Physiotherapy MSc/Postgraduate Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/mechanical-engineering/advanced-mechanical-engineering.aspx","Advanced Mechanical Engineering Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/sport-exercise/advancing-practice.aspx","Advancing Practice MSc/Diploma/PG Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/dasa/africa-and-development.aspx","Africa and Development MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/dasa/african-studies.aspx","African Studies MA/Diploma","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/cwas/african-studies.aspx","African Studies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/air-pollution-mgt-ctrl.aspx","Air Pollution Management and Control MSc/Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/gees/atmospheric-sciences-air-pollution.aspx","Air Pollution, Atmospheric Sciences and, PhD with Integrated Study",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/air-power.aspx","Air Power: History, Theory and Practice MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/caha/ancient-history.aspx","Ancient History MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/caha/cuneiform-ancient-near-eastern-studies.aspx","Ancient Near Eastern Studies, Cuneiform MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/bomgs/antiquity-byzantine.aspx","Antiquity MA: Byzantine Studies pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/caha/antiquity-classical-archaeology.aspx","Antiquity MA: Classical Archaeology pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/caha/antiquity-classics.aspx","Antiquity MA: Classics and Ancient History pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/caha/antiquity-egyptology.aspx","Antiquity MA: Egyptology pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/micropalaeontology.aspx","Applied and Petroleum Micropalaeontology MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/english/applied-corpus-linguistics.aspx","Applied Corpus Linguistics MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/edu/applied-edu-child-psychology.aspx","Applied Educational and Child Psychology Doctorate (App Ed and Child Psy D)","Doctorate"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/english/applied-linguistics.aspx","Applied Linguistics MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/maths/applied-mathematics-mres.aspx","Applied Mathematics MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/applied-met-climatology.aspx","Applied Meteorology and Climatology MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/caha/cultural-archaeology.aspx","Archaeology MA / Diploma / Certificate Cultural Archaeology pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/caha/landscape-archaeology.aspx","Archaeology MA / Diploma / Certificate Landscape Archaeology pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/caha/archaeology.aspx","Archaeology MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/caha/archaeology.aspx","Archaeology MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/caha/antiquity-classical-archaeology.aspx","Archaeology, Classical pathway: Antiquity MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/caha/greek-archaeology.aspx","Archaeology, Greek MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/histart/history-art-curating.aspx","Art History and Curating MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/histart/history-art-curating.aspx","Art, History of, Curating, MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/histart/history-art.aspx","Art, History of, MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/histart/history-art.aspx","Art, History of, MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/gees/atmospheric-sciences-air-pollution.aspx","Atmospheric Sciences and Air Pollution PhD with Integrated Study",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/autism-children.aspx","Autism - Children",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/autism-children.aspx","Autism (Children) MEd/BPhil/Postgraduate Diploma/Postgraduate Certificate/Advanced Certificate","MEd"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/chemical-engineering/biochemical-engineering.aspx","Biochemical Engineering Masters/MSc/Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-science-biology.aspx","Biology - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/metallurgy-materials/biomaterials-mres.aspx","Biomaterials MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/med/biomedical-research-in-vivo.aspx","Biomedical Research: Integrative and Translational MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/biosciences/molecular-biotechnology.aspx","Biotechnology, Molecular MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/guangzhou-mba.aspx","Birmingham-Jinan MBA","BA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/psych/brain-imaging-cognitive-neuro.aspx","Brain Imaging and Cognitive Neuroscience MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/british-ww1-studies.aspx","British First World War Studies MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/history/C20th-british-history.aspx","British History, Twentieth Century MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/business-admin-grad-diploma.aspx","Business Administration Graduate Diploma",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/business/integrated-study-business-and-management.aspx","Business Management PhD with Integrated Study",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/international-business.aspx","Business, International MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/international-business-singapore.aspx","Business, International MSc (Singapore)","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/bomgs/byzantine-studies.aspx","Byzantine Studies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/med/cancer-sciences.aspx","Cancer Sciences MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/med/cardiovascular-science.aspx","Cardiovascular Science MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/cwas/caribbean-literature.aspx","Caribbean Literature MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/cpd/psych/cognitive-behaviour-therapy-hi.aspx","CBT High Intensity Postgraduate Diploma","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/cpd/psych/cognitive-behaviour-therapy.aspx","CBT Postgraduate Diploma","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/biosciences/molecular-cellular-bio.aspx","Cellular Biology, Molecular and, MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/chemistry/chemistry-biology-biomedical-imaging-masters.aspx","Chemical Biology and Biomedical Imaging Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/chemical-engineering/chemical-engineering-integrated.aspx","Chemical Engineering PhD with Integrated Study",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/chemical-engineering/chemical-engineering-science-mres.aspx","Chemical Engineering Science MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/chemical-engineering/efficient-fossil-energy-technologies-msc.aspx","Chemical Engineering, Advanced Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/chemical-engineering/advanced-chemical-engineering.aspx","Chemical Engineering, Advanced Masters/MSc/Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-science-chemistry.aspx","Chemistry - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/chemistry/chemistry-biomedical-imaging-mres.aspx","Chemistry for Biomedical Research MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/civil-engineering/civil-engineering-management.aspx","Civil Engineering and Management Masters/MSc/Diploma/Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/civil-engineering/civil-engineering.aspx","Civil Engineering Masters/MSc/Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/caha/antiquity-classics.aspx","Classics and Ancient History pathway, Antiquity MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/caha/classics.aspx","Classics MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/applied-met-climatology.aspx","Climatology, Applied Meteorology and, MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/med/clinical-health-research.aspx","Clinical Health Research MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/clinical-neuropsychiatry.aspx","Clinical Neuropsychiatry MSc/PG Diploma/PG Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/clinical-oncology-full-time.aspx","Clinical Oncology MSc/Postgraduate Diploma - Full-time","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/clinical-oncology-part-time.aspx","Clinical Oncology MSc/Postgraduate Diploma - Part-time","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/clinical-primary-comm-care.aspx","Clinical Primary and Community Care MSc/PG Diploma/PG Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/psychology/clinical-psychology.aspx","Clinical Psychology MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/med/ClinicalResearch-AcademicClinicalFellows(ACF)FrameworkMResPGDipPGCert.aspx","Clinical Research - Academic Clinical Fellows (ACF) Framework MRes/PG Dip/PG Cert","PG"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/cpd/psych/cognitive-behaviour-therapy-hi.aspx","Cognitive Behaviour Therapy High Intensity Postgraduate Diploma","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/cpd/psych/cognitive-behaviour-therapy.aspx","Cognitive Behaviour Therapy Postgraduate Diploma","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/psych/computation-neuro-cognitive-robotics.aspx","Cognitive Robotics, Computational Neuroscience and, MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/phil/phil-mind-cognitive-sci.aspx","Cognitive Science, Philosophy of Mind and, MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/arts-law-inter/colonial-postcolonial-studies.aspx","Colonial and Postcolonial Studies MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/law/commercial-law.aspx","Commercial Law LLM","LLM"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/communications-engineering-networks.aspx","Communications Engineering and Networks Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/communications-engineering-networks-industry.aspx","Communications Engineering and Networks Masters/MSc with Industrial Studies","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/psych/computation-neuro-cognitive-robotics.aspx","Computational Neuroscience and Cognitive Robotics MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/computer-science/advanced-computer-science.aspx","Computer Science Advanced MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/computer-science/computer-science.aspx","Computer Science Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/computer-science/computer-security.aspx","Computer Security Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/civil-engineering/construction-management.aspx","Construction Management Masters/MSc/Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/contemporary-history.aspx","Contemporary History MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/english/corpus-linguistics.aspx","Corpus Linguistics MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/fcw/creative-writing.aspx","Creative Writing MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/law/criminal-law.aspx","Criminal Law and Criminal Justice LLM","LLM"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/english/critical-discourse-culture-comm.aspx","Critical Discourse, Culture and Communication MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/caha/cuneiform-ancient-near-eastern-studies.aspx","Cuneiform and Ancient Near Eastern Studies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/computer-science/cyber-security.aspx","Cyber Security Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/econ/development-economics.aspx","Development Economics MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/development-management-aid.aspx","Development Management (Aid Management) MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/development-management-human-resources.aspx","Development Management (Human Resources and Development Management) MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/development-management-public-economic-finance.aspx","Development Management (Public Economic Management and Finance) MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/development-management.aspx","Development Management (with specialist pathways) MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/drama/directing.aspx","Directing MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/distance/govsoc/public-administration.aspx","Distance Learning Masters in Public Administration (MPA)",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/online-mba.aspx","Distance Learning MBA","BA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/online-msc-international-business.aspx","Distance Learning MSc in International Business","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/social-policy/doctorate-social-work.aspx","Doctor of Social Work",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/chemistry/drug-discovery-medicinal-chemistry.aspx","Drug Discovery and Medicinal Chemistry Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/language-literacies-dyslexia.aspx","Dyslexia - Language and Literacies",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/history/early-modern-history.aspx","Early Modern History MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/bomgs/mod-east-med-history.aspx","East Mediterranean History, Modern MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/econ/economics.aspx","Economics MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/edu/edd-education.aspx","EdD - Education","EdD"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/edu/edd-education.aspx","EdD Education","EdD"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/international-studies-education.aspx","Education - International Studies",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/school-direct.aspx","Education - School Direct",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/school-improvement.aspx","Education - School Improvement",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/edu/education-learning.aspx","Education and Learning PhD with Integrated Study",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/cpd/edu/edu-health-professionals.aspx","Education for Health Professionals MEd/ Postgraduate Diploma/ Postgraduate Certificate","MEd"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/edu/educational-studies.aspx","Educational Studies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/chemical-engineering/efficient-fossil-energy-technologies-msc.aspx","Efficient Fossil Energy Technologies Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/caha/egyptology.aspx","Egyptology MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/caha/antiquity-egyptology.aspx","Egyptology pathway, Antiquity MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/electrical-power-systems.aspx","Electrical Power Systems Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/electrical-power-systems-advanced-research.aspx","Electrical Power Systems with Advanced Research Masters/MSc (Two Year)","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/electrical-transportation.aspx","Electrical Transportation Systems and Infrastructure Masters/MSc/PG Diploma/PG Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/electromagnetic-sensor-networks.aspx","Electromagnetic Sensor Networks Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/electromagnetic-sensor-networks-industry.aspx","Electromagnetic Sensor Networks Masters/MSc with Industrial Studies","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/electronic-computer-engineering.aspx","Electronic and Computer Engineering Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/electronic-computer-engineering-industry.aspx","Electronic and Computer Engineering Masters/MSc with Industrial Studies","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/eese/electronic-electrical-computer-engineering.aspx","Electronic, Electrical and Computer Engineering MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/embedded-systems.aspx","Embedded Systems Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/embedded-systems-industry.aspx","Embedded Systems Masters/MSc with Industrial Studies","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/mechanical-engineering/engineering-management.aspx","Engineering Management Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-english.aspx","English - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/english/language-applied-linguistics.aspx","English Language and Applied Linguistics MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/econ/environment-natural-resource-econ.aspx","Environmental and Natural Resource Economics MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/environmental-health.aspx","Environmental Health MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/executive-mba.aspx","Executive MBA","BA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/sport-exercise/exercise-sport-sciences.aspx","Exercise and Sport Sciences MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/sport-exercise/exercise-sport-sciences.aspx","Exercise and Sport Sciences MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/sport-exercise/exercise-sports-medicine-football.aspx","Exercise and Sports Medicine (Football) MSc/Postgraduate Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/fcw/film-tv-research-prod.aspx","Film and Television: Research and Production MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/fcw/film-studies.aspx","Film Studies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/investments.aspx","Finance",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/econ/financial-economics.aspx","Financial Economics MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/maths/financial-engineering.aspx","Financial Engineering Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/financial-management.aspx","Financial Management MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/chemical-engineering/food-quality-health-msc.aspx","Food Quality and Health Masters/MSc/PGDip/PGCert","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/chemical-engineering/food-safety-hygiene.aspx","Food Safety, Hygiene and Management Masters/MSc/PG Diploma/PG Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/chemical-engineering/formulation-engineering-engd.aspx","Formulation Engineering EngD",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-french.aspx","French - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-french-spanish.aspx","French and Spanish - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/functional-clinical-anatomy.aspx","Functional and Clinical Anatomy MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/genomic-medicine.aspx","Genomic Medicine MSc/PGDip/PGCert","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-geography.aspx","Geography - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/civil-engineering/geotechnical-engineering-management.aspx","Geotechnical Engineering and Management Masters/MSc/Diploma/Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/civil-engineering/geotechnical-engineering.aspx","Geotechnical Engineering Masters/MSc/Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-german.aspx","German - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-german-french.aspx","German and French - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/global-banking-finance-mba.aspx","Global Banking and Finance MBA","BA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/global-cooperation-security.aspx","Global Cooperation and Security MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/phil/global-ethics.aspx","Global Ethics MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/global-history.aspx","Global History MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/singapore-mba.aspx","Global MBA - Singapore","BA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-development-governance-state-building-internship.aspx","Governance and Statebuilding (International Development) with Internship MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/business-admin-grad-diploma.aspx","Graduate Diploma in Business Administration",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/caha/greek-archaeology.aspx","Greek Archaeology MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/bomgs/modern-greek-studies.aspx","Greek Studies, Modern MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/phil/phil-health-happiness.aspx","Health and Happiness, Philosophy of, MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/pg-modules/health-care-evaluation-and-commissioning--.aspx","Health Care Evaluation and Commissioning",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/social-policy/health-care-policy-management.aspx","Health Care Policy and Management MSc/PGDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/health-econometrics.aspx","Health Economics and Econometrics MSc/PGDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/health-economics-policy.aspx","Health Economics and Health Policy MSc/Postgraduate Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/health-research-methods.aspx","Health Research Methods - MSc/PGDip/PGCert","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/sport-exercise/health-studies.aspx","Health Studies MSc/PG Diploma/PG Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/law/health-bioethics-law.aspx","Health, Bioethics and Law LLM","LLM"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/phil/health-bioethics-law.aspx","Health, Bioethics and Law MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/social-policy/healthcare-commissioning.aspx","Healthcare Commissioning MSc/PGCert/PGDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-history-citizenship.aspx","History & Citizenship - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/histart/history-art.aspx","History of Art MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/histart/history-art.aspx","History of Art MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/history-of-warfare.aspx","History of Warfare MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/caha/ancient-history.aspx","History, Ancient MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/history/early-modern-history.aspx","History, Early Modern, MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/history/medieval-history.aspx","History, Medieval MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/history/mod-european-history.aspx","History, Modern European MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/west-midlands-history.aspx","History, West Midlands MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/contemporary-history.aspx","History. Contemporary MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/history-of-warfare.aspx","History. warfare MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/arts-law-inter/holocaust-genocide.aspx","Holocaust and Genocide MA/Diploma/Certificate","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/computer-science/human-computer-interaction.aspx","Human Computer Interaction Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/human-resource-management.aspx","Human Resource Management MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/human-resource-management-cipd.aspx","Human Resource Management with CIPD Pathway",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/phil/human-rights-human-values.aspx","Human Values and Human Rights MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/arts-law-inter/humanities.aspx","Humanities MA/Diploma/Certificate","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/chemical-engineering/hydrogen-fuel-cells-mres.aspx","Hydrogen, Fuel Cells and their Applications MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/chemical-engineering/hydrogen-fuel-cells-integrated-phd.aspx","Hydrogen, Fuel Cells and their Applications PhD with Integrated Study",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/hydrogeology.aspx","Hydrogeology MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/immunology-and-immunotherapy.aspx","Immunology and Immunotherapy MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/chemical-engineering/industrial-project-management.aspx","Industrial Project Management Masters/MSc/Diploma/Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/international-acct-finance.aspx","International Accounting and Finance MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/international-business.aspx","International Business MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/international-business-singapore.aspx","International Business MSc (Singapore)","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/online-msc-international-business.aspx","International Business MSc by Distance Learning","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/law/international-commercial-law.aspx","International Commercial Law LLM","LLM"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/distance/govsoc/international-development-conflict-security.aspx","International Development (Conflict, Security and Development) by distance learning MSc/PGDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-development-conflict-security.aspx","International Development (Conflict, Security and Development) MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-development-environment-sustainability-politics.aspx","International Development (Environment, Sustainability and Politics) MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-development-governance-state-building.aspx","International Development (Governance and Statebuilding) MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-development-governance-state-building-internship.aspx","International Development (Governance and Statebuilding) with Internship MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-development-political-economy.aspx","International Development (International Political Economy and Development) MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/distance/govsoc/international-development-poverty-inequality.aspx","International Development (Poverty, Inequality and Development) by distance learning MSc/PGDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-development-poverty-inequality.aspx","International Development (Poverty, Inequality and Development) MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-development-urban.aspx","International Development (Urban Development) MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-development.aspx","International Development (with specialist pathways) MSc/GDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/distance/govsoc/international-development.aspx","International Development by distance learning MSc/PGDip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/govsoc/international-development.aspx","International Development PhD with Integrated Study",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/econ/international-economics.aspx","International Economics MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/ironbridge/heritage-management.aspx","International Heritage Management MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/law/international-law.aspx","International Law LLM: Crime, Justice and Human Rights","LLM"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/phil/international-law-ethics-politics.aspx","International Law, Ethics and Politics MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/law/international-law.aspx","International Law: Crime, Justice and Human Rights LLM","LLM"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/international-marketing.aspx","International Marketing MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/econ/international-money-banking.aspx","International Money and Banking MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-relations-contemporary-asia-pacific.aspx","International Relations (Contemporary Asia Pacific) MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-relations-diplomacy.aspx","International Relations (Diplomacy) MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-relations-gender.aspx","International Relations (Gender) MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-relations-peacekeeping.aspx","International Relations (International Peacekeeping) MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-relations-political-economy.aspx","International Relations (International Political Economy) MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-relations-research-methods.aspx","International Relations (Research Methods) MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-relations-security.aspx","International Relations (Security) MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-relations-terrorism-political-violence.aspx","International Relations (Terrorism and Political Violence) MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/international-relations.aspx","International Relations (with specialist pathways) MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/international-studies-education.aspx","International Studies in Education MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/thr/inter-religious-relations.aspx","Inter-religious Relations MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/investments.aspx","Investments MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/thr/islamic-studies.aspx","Islamic Studies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/language-literacies-dyslexia.aspx","Language, Literacies and Dyslexia MEd/Postgraduate Diploma/Postgraduate Certificate","MEd"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/caha/late-antiquity.aspx","Late Antiquity MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/law/commercial-law.aspx","Law, Commercial LLM","LLM"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/law/LLM-general.aspx","Law, LLM (General)","LLM"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/cpd/social-policy/leader-manage-social-care.aspx","Leadership and Management for Social Care MA/Postgraduate Diploma","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/cpd/social-policy/leader-manage-social-work.aspx","Leadership and Management for Social Work MA/Postgraduate Diploma/Post-qualifying (Higher Specialist) Award","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/social-policy/leadership-health-services-improve.aspx","Leadership for Health Services Improvement MSc/PGDip/PGCert","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/severe-profound-multiple-learning-difficulties.aspx","Learning Difficulties - Severe, Profound and Multiple",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/english/literary-linguistics.aspx","Literary Linguistics MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/english/english-literature.aspx","Literature and Culture MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/fcw/literature-film.aspx","Literature and Film MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/law/llb-graduates.aspx","LLB for Graduates","LLB"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/law/LLM-general.aspx","LLM (General)","LLM"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/law/health-bioethics-law.aspx","LLM Health, Bioethics and Law","LLM"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/law/international-commercial-law.aspx","LLM in International Commercial Law","LLM"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/govsoc/local-government-public-policy.aspx","Local Government and Public Policy PhD with Integrated Study",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/bfa-pre-masters/ma-music-with-intergrated-pre-masters.aspx","MA Music with Integrated Pre-Masters","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/psych/psychology-ma.aspx","MA Psychology","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/maths/management-mathematics-mres.aspx","Management Mathematics MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/management.aspx","Management MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/management.aspx","Management MSc (with Specialist Pathways in Strategy and Entrepreneurship & Innovation)","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/management-special-education.aspx","Management of Special Education in Developing Countries MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/management-entrepreneurship-innovation.aspx","Management: Entrepreneurship & Innovation Pathway MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/management-operations.aspx","Management: Operations Pathway MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/management-organisational-leadership-and-change.aspx","Management: Organisational Leadership and Change Pathway MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/management-strategy.aspx","Management: Strategy Pathway MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/marketing-communications.aspx","Marketing Communications MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/marketing.aspx","Marketing MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/public-administration.aspx","Masters in Public Administration (MPA)",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/distance/govsoc/public-administration.aspx","Masters in Public Administration (MPA) by Distance Learning",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/metallurgy-materials/materials-sustainable-energy-technology-mres.aspx","Materials for Sustainable Energy Technologies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/econ/mathematical-finance.aspx","Mathematical Finance MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/maths/mathematical-modelling.aspx","Mathematical Modelling MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-primary-mathematics.aspx","Mathematics - Postgraduate Diploma Primary Education (SSPIP)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-mathematics.aspx","Mathematics - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/secondary-mathematics-ske.aspx","Mathematics - Subject Knowledge Enhancement (SKE)",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/maths/mathematics-morse.aspx","Mathematics, Operational Research, Statistics and Econometrics (MORSE) Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/guangzhou-mba.aspx","MBA - Guangzhou","BA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/mba.aspx","MBA (full-time)","BA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/mba-strategy-procure-management.aspx","MBA (Strategy and Procurement Management)","BA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/online-mba.aspx","MBA by Distance Learning","BA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/mba-public-service.aspx","MBA Public Service","BA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/history/medieval-history.aspx","Medieval History MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/medieval-studies.aspx","Medieval Studies MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/english/medieval-studies.aspx","Medieval Studies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/biosciences/microbiology-infection.aspx","Microbiology and Infection MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/social-policy/migration-superdiversity-policy.aspx","Migration, Superdiversity and Policy MA/Diploma/Certificate","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/modern-british-studies.aspx","Modern British Studies MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/bomgs/mod-east-med-history.aspx","Modern East Mediterranean History MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/history/mod-european-history.aspx","Modern European History MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/bomgs/modern-greek-studies.aspx","Modern Greek Studies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-mfl.aspx","Modern Languages - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/lang/modern-languages.aspx","Modern Languages MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/biosciences/molecular-cellular-bio.aspx","Molecular and Cellular Biology MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/biosciences/molecular-biotechnology.aspx","Molecular Biotechnology MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/biosciences/molecular-mech-toxicology.aspx","Molecular Mechanistic Toxicology MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/econ/money-banking-finance.aspx","Money, Banking and Finance MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/gees/environmental-biological-nanoscience.aspx","MRes Environmental and Biological Nanoscience*","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/chemical-engineering/agricultural-food-industry-research-mres.aspx","MRes in Agriculture and Food","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/metallurgy-materials/advanced-materials-modelling-icme.aspx","MSc Advanced Materials Modelling (ICME)","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/psych/brain-imaging-cognitive-neuro.aspx","MSc Brain Imaging and Cognitive Neuroscience","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/bfa-pre-masters/msc-development-economics-with-integrated-pre-masters.aspx","MSc Development Economics with Integrated pre-Masters","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/bfa-pre-masters/MSc-Economics-with-Integrated-pre-Masters.aspx","MSc Economics with Integrated Pre-Masters","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/bfa-pre-masters/msc-environmental-and-natural-resource-economics-with-integrated-pre-masters.aspx","MSc Environmental and Natural Resource Economics with Integrated pre-Masters","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/bfa-pre-masters/msc-international-economics-with-integrated-pre-masters.aspx","MSc International Economics with Integrated pre-Masters","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/bfa-pre-masters/msc-international-money-and-banking-with-integrated-pre-masters.aspx","MSc International Money and Banking with Integrated pre-Masters","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/metallurgy-materials/materials-science-engineering.aspx","MSc Materials Science and Engineering","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/bfa-pre-masters/msc-money-banking-and-finance-with-integrated-pre-masters.aspx","MSc Money Banking and Finance with Integrated pre-Masters","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/msc-flexible-programme.aspx","MSc programmes ¨C flexible route","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/multidisciplinary-healthcare-simulation.aspx","Multidisciplinary Healthcare Simulation - PGCert","PG"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/computer-science/computer-multidisciplinary-optimisation.aspx","Multidisciplinary Optimisation Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/musculoskeletal-ageing.aspx","Musculoskeletal Ageing and Health - MSc/PG Dip","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/pg-modules/musculoskeletal-anatomy-and-analytical-methods.aspx","Musculoskeletal Anatomy and Analytical Methods",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/music/british-music-studies.aspx","Music MA: British Music Studies pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/music/choral-conducting.aspx","Music MA: Choral Conducting pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/music/critical-musicology.aspx","Music MA: Critical Musicology pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/music/early-music-dissertation.aspx","Music MA: Early Music pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/music/electroacoustic.aspx","Music MA: Electroacoustic composition/sonic art pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/music/instrumental.aspx","Music MA: Instrumental/Vocal Composition pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/music/mixed-composition.aspx","Music MA: Mixed Composition pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/music/musicology.aspx","Music MA: Musicology pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/music/open-with.aspx","Music MA: Open Pathway with Performance","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/music/open-without.aspx","Music MA: Open Pathway without Performance","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/music/performance.aspx","Music MA: Performance pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/music/performance-practice.aspx","Music MA: Performance Practice pathway","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/gees/environmental-biological-nanoscience.aspx","Nanoscience and Nanotechnology, Human and Environmental Health Impacts of, MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/research/computer-science/natural-computation-mres.aspx","Natural Computation MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/nuclear-decommissioning.aspx","Nuclear Decommissioning and Waste Management MSc/PG Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/occupational-health.aspx","Occupational Health MSc/PGDip/PGCert","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/science-occupational-health-safety-environ.aspx","Occupational Health, Safety and the Environment , Science of, MSc/Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/mechanical-engineering/operations-management.aspx","Operations Management Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/thr/pentecostal-charismatic-studies.aspx","Pentecostal and Charismatic Studies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgdip-teaching-studies.aspx","PGDip Teaching Studies","PG"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/pharmaceutical-enterprise.aspx","Pharmaceutical Enterprise MSc/PG Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/metallurgy-materials/PhD-integrated-studies-structural-metallic-systems-gas-turbine-systems.aspx","PhD with Integrated Studies Structural Metallic Systems for Gas Turbine Applications",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/phil/philosophy.aspx","Philosophy MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/phil/philosophy.aspx","Philosophy MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/phil/phil-health-happiness.aspx","Philosophy of Health and Happiness MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/phil/phil-mind-cognitive-sci.aspx","Philosophy of Mind and Cognitive Science MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/phil/phil-religion-ethics.aspx","Philosophy of Religion and Ethics MA/Diploma","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-physical-education.aspx","Physical Education - Secondary Education (QTS)",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/sport-exercise/sport-physical-education-sport-pedagogy.aspx","Physical Education and Sport Pedagogy MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/research/chemistry/physical-sciences-health-phd.aspx","Physical Sciences for Health (Sci-Phy-4-Health) PhD/Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/physician-associate-msc.aspx","Physician Associate Studies MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/physician-associate.aspx","Physician Associate Studies Postgraduate Diploma","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/physicians-assistant-anaesthesia.aspx","Physicians Assistant (Anaesthesia) Postgraduate Diploma","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-science-physics.aspx","Physics - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/secondary-physics-ske.aspx","Physics - Postgraduate Diploma Secondary Education (QTS) Subject Knowledge Enhancement (SKE) route","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/physics/physics-technology-nuclear-reactors.aspx","Pysics and Technology of Nuclear Reactors Masters\\MSC","MSc"},//Physics and Technology of Nuclear Reactors Masters\MSc
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/physics-radio-engineering.aspx","Physics for Radio Engineering Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-physics-mathematics.aspx","Physics with Mathematics - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/sport-exercise/physio-pre-reg.aspx","Physiotherapy (pre-registration) MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/drama/playwriting-studies.aspx","Playwriting Studies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/social-policy/policy-practice-integrated.aspx","Policy into Practice (with Integrated Placement) MA/PG Diploma","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/social-policy/policy-practice.aspx","Policy into Practice MA/Diploma/Certificate","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/political-science-british-politics-state.aspx","Political Science (British Politics and the State) MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/political-science-research-methods.aspx","Political Science (Research Methods) MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/political-science.aspx","Political Science (with specialist pathways) MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/political-theory.aspx","Political Theory MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/cpd/psych/compassion-focused-therapy.aspx","Postgraduate Diploma in Compassion Focused Therapy","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgdip-teaching-studies.aspx","Postgraduate Diploma in Teaching Studies","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-primary.aspx","Postgraduate Diploma Primary Education (PGCE Advanced) General Primary or Early Years","PG"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-primary-mathematics.aspx","Postgraduate Diploma Primary Education (SSPIP) Mathematics","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary.aspx","Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-english.aspx","Postgraduate Diploma Secondary Education (QTS) - English","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-geography.aspx","Postgraduate Diploma Secondary Education (QTS) - Geography","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-history-citizenship.aspx","Postgraduate Diploma Secondary Education (QTS) - History and History & Citizenship","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-mathematics.aspx","Postgraduate Diploma Secondary Education (QTS) - Mathematics","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/secondary-mathematics-ske.aspx","Postgraduate Diploma Secondary Education (QTS) - Mathematics Subject Knowledge Enhancement route for non-specialists","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-french.aspx","Postgraduate Diploma Secondary Education (QTS) - Modern Languages: French","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-french-spanish.aspx","Postgraduate Diploma Secondary Education (QTS) - Modern Languages: French and Spanish","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-german.aspx","Postgraduate Diploma Secondary Education (QTS) - Modern Languages: German","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-german-french.aspx","Postgraduate Diploma Secondary Education (QTS) - Modern Languages: German and French","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-spanish.aspx","Postgraduate Diploma Secondary Education (QTS) - Modern Languages: Spanish","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-physical-education.aspx","Postgraduate Diploma Secondary Education (QTS) - Physical Education","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/secondary-physics-ske.aspx","Postgraduate Diploma Secondary Education (QTS) - Physics Subject Knowledge Enhancement route","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-physics-mathematics.aspx","Postgraduate Diploma Secondary Education (QTS) - Physics with Mathematics","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-religious-education.aspx","Postgraduate Diploma Secondary Education (QTS) - Religious Education","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-science-biology.aspx","Postgraduate Diploma Secondary Education (QTS) - Science: Biology","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-science-chemistry.aspx","Postgraduate Diploma Secondary Education (QTS) - Science: Chemistry","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-science-physics.aspx","Postgraduate Diploma Secondary Education (QTS) - Science: Physics","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-mfl.aspx","Postgraduate Diploma Secondary Education (QTS) ¨CModern Languages (French/Spanish/German)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/research/thr/practical-theology-doctorate.aspx","Practical Theology Doctorate (DPT)","Doctorate"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/maths/pre-masters-certificate-in-mathematics.aspx","Pre-Masters Certificate in Mathematics",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/clinical-primary-comm-care.aspx","Primary and Community Care, Clinical MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/med/dpharm.aspx","Professional Doctorate in Pharmacy (DPharm)","Doctorate"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/mechanical-engineering/project-management.aspx","Project Management Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/psych/psychology-ma.aspx","Psychology MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/psych/psychology.aspx","Psychology MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/pg-modules/psychology-of-physical-activity-promotion.aspx","Psychology of physical activity promotion",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/psychology/clinical-psychology.aspx","Psychology, Clinical MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/public-environ-health-science.aspx","Public and Environmental Health Sciences MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/public-health-tech-assessment.aspx","Public Health (Health Technology Assessment) MPH/PG Diploma/PG Certificate","PG"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/public-health-international.aspx","Public Health (International) MPH/PG Diploma/PG Certificate","PG"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/public-health-seal.aspx","Public Health (SEAL) MPH",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/public-health.aspx","Public Health MPH/PG Diploma/PG Certificate","PG"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/public-management-health-social-care.aspx","Public Management (Health and Social Care) MSc/PGDip/PGCert","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/public-management-local-policy-leadership.aspx","Public Management (Local Policy and Leadership) MSc/PGDip/PGCert","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/public-management.aspx","Public Management MSc/PGDip/PGCert","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/public-service-commissioning.aspx","Public Service Commissioning MSc/PGDip/GDip/PGCert/GCert","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/maths/pure-mathematics-mres.aspx","Pure Mathematics MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/civil-engineering/railway-risk-safety.aspx","Railway Risk and Safety Management /MSc/Diploma/Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/civil-engineering/railway-systems-engineering.aspx","Railway Systems Engineering and Integration Masters/MSc/Diploma/Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/civil-engineering/railway-systems-mres.aspx","Railway Systems Integration MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/thr/religion-culture.aspx","Religion and Culture MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/phil/phil-religion-ethics.aspx","Religion and Ethics, Philosophy of, MA/Diploma","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/thr/religion-politics-society.aspx","Religion, Politics and Society",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-religious-education.aspx","Religious Education - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/reformation-early-mod-studies.aspx","Renaissance, Reformation and Early Modern Studies MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/gees/research-human-geography.aspx","Research in Human Geography MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/research-human-geography.aspx","Research in Human Geography MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/pg-modules/research-project-musculoskeletal-ageing-and-health.aspx","Research project - Musculoskeletal Ageing and Health",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/rf-microwave-engineering.aspx","RF and Microwave Engineering Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/eese/rf-microwave-engineering-industry.aspx","RF and Microwave Engineering Masters/MSc with Industrial Studies","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/river-environ-mgt.aspx","River Environments and their Management MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/civil-engineering/road-management-engineering.aspx","Road Management and Engineering Masters/MSc/Diploma/Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/computer-science/robotics.aspx","Robotics Masters/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/school-direct.aspx","School Direct",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/school-improvement.aspx","School Improvement and Educational Leadership MA/Postgraduate Diploma/ Postgraduate Certificate","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/metallurgy-materials/science-engineering-materials.aspx","Science and Engineering of Materials MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/science-occupational-health-safety-environ.aspx","Science of Occupational Health, Safety and the Environment MSc/Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/special-educational-needs-coordination.aspx","SENCO",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/special-educational-needs-disabilities.aspx","SEND - Special Educational Needs and Disabilities",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/severe-profound-multiple-learning-difficulties.aspx","Severe, Profound and Multiple Learning Difficulties MEd/Postgraduate Diploma/Postgraduate Certificate/Advanced Certificate","MEd"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/arts-law-inter/gender-studies.aspx","Sexuality and Gender Studies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/english/shakespeare-and-creativity.aspx","Shakespeare and Creativity MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/research/english/shakespeare-and-creativity.aspx","Shakespeare and Creativity PhD with integrated study",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/english/shakespeare-education.aspx","Shakespeare and Education MA (on campus or by distance learning)","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/english/shakespeare-theatre.aspx","Shakespeare and Theatre MA/Diploma/Distance learning","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/english/shakespeare-studies.aspx","Shakespeare Studies MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/thr/sikh-studies.aspx","Sikh Studies MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/social-political-theory.aspx","Social and Political Theory MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/social-policy/social-policy.aspx","Social Policy MA/Diploma/Certificate","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/dasa/social-research-african.aspx","Social Research (African Studies) MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/social-research-business.aspx","Social Research (Business) MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/social-research-econ.aspx","Social Research (Economic and Social History) MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/social-research-education.aspx","Social Research (Education) MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/govsoc/social-research-local-government-public-policy.aspx","Social Research (Local Government and Public Policy) MA/PGDip/PGCert","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/social-policy/social-research-soc-policy.aspx","Social Research (Social Policy) MA/Diploma","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/social-policy/social-research-soc-work.aspx","Social Research (Social Work and Professional Practice) MA/PGDip","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/socsci/social-research.aspx","Social Research MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/social-policy/social-work.aspx","Social Work MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary-spanish.aspx","Spanish - Postgraduate Diploma Secondary Education (QTS)","Postgraduate Diploma"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/special-educational-needs-disabilities.aspx","Special Educational Needs and Disabilities",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/special-educational-needs-coordination.aspx","Special Educational Needs Coordination (National Award for Special Educational Needs Coordination)",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/sport-exercise/sport-coaching.aspx","Sport Coaching PGDip/MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/sport-exercise/sport-policy-business-management.aspx","Sport Policy, Business and Management MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/maths/statistics-mres.aspx","Statistics MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/business/strategic-marketing-consult.aspx","Strategic Marketing and Consulting MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/civil-engineering/structural-engineering.aspx","Structural Engineering and Practice Masters/MSc/Diploma","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/pgce-secondary.aspx","Teacher Training - Secondary Education",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/teaching-english-foreign-language.aspx","Teaching English as a Foreign Language (TEFL) MA/ Postgraduate Diploma/ Postgraduate Certificate (School of Education)","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/english/english-foreign-second-lang.aspx","Teaching English to Speakers of Other Languages (TESOL) MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/edu/teaching-english-foreign-language.aspx","TEFL Education",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/english/english-foreign-second-lang.aspx","TESOL, Teaching English to Speakers of Other Languages MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/pg-modules/biology-of-ageing.aspx","The Biology of Ageing",""},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/thr/theology-and-religion.aspx","Theology and Religion MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/thr/theology.aspx","Theology and Religion MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/biosciences/toxicology.aspx","Toxicology MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/biosciences/molecular-mech-toxicology.aspx","Toxicology, Molecular Mechanistic MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/arts-law-inter/translation-studies.aspx","Translation Studies MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/med/trauma-science.aspx","Trauma Science MSc","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/combined/history/C20th-british-history.aspx","Twentieth Century British History MRes","MRes"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/gees/urban-regional-planning.aspx","Urban and Regional Planning (with RTPI accreditation) MSc/PG Diploma/Certificate","MSc"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/history/west-midlands-history.aspx","West Midlands History MA","MA"},
			{"http://www.birmingham.ac.uk/postgraduate/courses/taught/ironbridge/world-heritage-studies.aspx","World Heritage Studies MA","MA"}
		};
	public static String[][] LetterPages=
		{
		{"A","4"},
		{"B","2"},
		{"C","5"},
		{"D","2"},
		{"E","4"},
		{"F","2"},
		{"G","2"},
		{"H","3"},
		{"I","4"},
		{"J","0"},
		{"K","0"},
		{"L","2"},
		{"M","7"},
		{"N","1"},
		{"O","1"},
		{"P","7"},
		{"Q","0"},
		{"R","2"},
		{"S","4"},
		{"T","2"},
		{"U","1"},
		{"V","0"},
		{"W","1"},
		{"X","0"},
		{"Y","0"},
		{"Z","0"}};

}
